### ISSUE TITLE
Load More than one?

### ISSUE THREAD

**Issue by brandondeweese** [putyourlightson/craft-sprig#10]
This seems like it should be pretty straightforward, but when using your Load more recipe, how you load more than one entry? Say a range of entries? Or would I need to use a different receipt for that?

**Comment by bencroker** [comment]
Have you changed the default limit value?

```twig
{{ sprig('_components/load-more', {limit: 5}) }}
```

https://putyourlightson.com/sprig-cookbook#load-more

**Comment by brandondeweese** [comment]
Sorry I should clarify. Load more than one entry when the button is clicked? For instance, I want to load increments of 5 on the click..

**Comment by bencroker** [comment]
Have you tried my code above?

**Comment by brandondeweese** [comment]
Yes. I got that to work, but what if I only want to load one initially, then load increments of 5?

**Comment by bencroker** [comment]
In that case something like this in your component should work, which specifies to set it to 5 on Sprig (AJAX) requests, otherwise 1.

```twig
{% set limit = sprig.request ? 5 : 1 %}
```

**Comment by brandondeweese** [comment]
Perfect. Thanks for the quick responses.

**Comment by bencroker** [comment]
Sure thing!

**Comment by brandondeweese** [comment]
One more thing...is there a way to apply css classes to components?

**Comment by bencroker** [comment]
Just as you usually would, please open a new issue with some code samples if you'd like me to take a closer look.
