### ISSUE TITLE
Contact Form Sprig Component and Form Validation

### ISSUE THREAD

**Issue by pacoNew** [putyourlightson/craft-sprig#100]
### Question
Hallo Ben, ich benutze das contact form Sprig component und es funktioniert perfekt. Obendrauf benutze ich noch eine Javascript Form Validierung. Soweit so gut. 

Wenn das Formular nun erfolgreich validiert und versendet wird, kommt ganz kurz die Success Meldung von Sprig, danach springt die Seite wieder zurück zum Formular. 

In der Url wird folgenden Parameter mitgegeben: fromName=Name&message%5Bfirma%5D=Name&fromEmail=mail%40gmail.com&message%5Bbody%5D=sdf

Hast du evtl. eine Idee was hier passiert, kommt evtl. htmx noch in Konflikt mit dem Validation Plugin? Ich benutze folgende Libary: https://via-profit.github.io/js-form-validator/

Danke für deine Rückmeldung
Pascal Ujak

**Comment by bencroker** [comment]
Hi Pascal, responding here in English for the benefit of others. 

In general, JavaScript validation will not work with out of the box with Sprig, which really only relies on back-end validation. It is possible to add front-end validation to Sprig, but for that you would have to look into using [validation in htmx](https://htmx.org/docs/#validation). My advice would be choosing to use either front-end validation or Sprig, but not both.

**Comment by pacoNew** [comment]
Hi Ben, 

vielen Dank für deine Antwort. Und sorry, dass ich auf Github nicht auf Englisch geschrieben habe.

Alles klar, das macht absolut Sinn. Ich habe mich entschieden Sprig zu nehmen und eine Backend Validation 
zu machen.

Ich wünsche dir noch ein schönes Wochenende

Liebe Grüsse Pascal

**Comment by bencroker** [comment]
Alles klar, dir auch!
