### ISSUE TITLE
Get querystrings from a component that is being refreshed

### ISSUE THREAD

**Issue by billmn** [putyourlightson/craft-sprig#102]
### Introduction
I have a component that allow to switch between commerce variants and update the url with `s-push-url`.

```twig
<a
    href="{{ variant.url }}"
    sprig
    s-ext="refreshSiteSwitch"
    s-push-url="?variant={{ variant.id }}"
    s-val:variant="{{ variant.id }}"
>
    <img src="{{ variant.image.url }}">
</a>
```

I would retrieve the current querystring from another Sprig component in the navbar (called `siteSwitch`) and refresh it using the `refreshSiteSwitch` extension.

Navbar:
```twig
{{ sprig('_components/siteSwitch', [], {
    class: 'site-switch-component',
}) }}
```

`siteSwitch` component:
```twig
{{ craft.app.request.queryStringWithoutPath }}
```

`refreshSiteSwitch` extension:
```js
htmx.defineExtension('refreshSiteSwitch', {
    onEvent: (name, e) => {
        if (name == 'htmx:afterRequest') {
            document.querySelectorAll('.site-switch-component').forEach(el => {
                el.dispatchEvent(new Event('refresh'))
            })
        }
    }
})
```

---

### Problem
Assuming you have a url like this: `https://domain.test/en/93-pot-26-cm?variant=94`

On first load the component show `variant=64`, but if I switch to another variant the URL was `https://domain.test/en/93-pot-26-cm?variant=99` and the component show:

```
sprig%3AsiteId=4bf72e2973fa86a6bcef599b4ef3d308e4ec6bdaee5097d8389198f6c11c90a43&sprig%3Atemplate=4f8863a1ab3a72fb5be0850c319e9456f588f5244fa163552558da0d24af27b9_components%2FsiteSwitch
```

Instead of `variant=99`.

I think this is normal because it retrieve querystrings from the AJAX Sprig request, but I don't know how can I retrieve the main URL that I have in the browser.

https://user-images.githubusercontent.com/779534/107239196-e8afbf00-6a28-11eb-82f1-72e26d3a43f5.mov

Some idea on how to accomplish this?

**Comment by bencroker** [comment]
It sounds like you're trying to get the query string of the page but you are outputting the query string of the component, which is obviously different.

Have you tested using `sprig.url`? See https://putyourlightson.com/plugins/sprig#sprig.url

Or just outputting the variable in the component yourself, if that's what you want?

```twig
variant={{ variant }}
```

**Comment by billmn** [comment]
> Have you tested using sprig.url?

Yes but it returns the previous url. If I switch from variant 94 to variant 99, I have the url of the variant 94 while I would like the current one.


> Or just outputting the variable in the component yourself, if that's what you want?

The variant variable exists on first load but not on sprig ajax requests.


It would be useful to have a function like `sprig.url` that returns the current url instead of the previous request's url.

**Comment by bencroker** [comment]
> It would be useful to have a function like sprig.url that returns the current url instead of the previous request's url.

Since you create the URL with `s-push-url="?variant={{ variant.id }}"`, it is trivial to put that in a variable and use it as you wish. I showed how to do something similar in the last Sprigboard video at https://putyourlightson.com/sprig/videos#7.-pushing-url-updates

**Comment by billmn** [comment]
Yeah, the problem is two different Sprig components and I haven't found another way to communicate between components than using the `refresh` method. I will try another solution. Thank you!
