### ISSUE TITLE
Help with category filtering

### ISSUE THREAD

**Issue by E2design** [putyourlightson/craft-sprig#103]
### Question
This question is related to my question #98 from a couple of days back. I'm extending the filter with a category filter. The category dropdown (categoryOption) shows the correct categories and when selected sprig refreshes the page and the selected category is pushed to the url. However no single entry is shown in the result list?

the howtodoCategory is the name of the related category field in the entry. 

Breaking my head about this can't find the solution.

    {# sets a default value if not defined by `s-val:*` on the clicked element #}
    {% set page = page ?? 1 %}
    {# sets the number of articles per page #}
    {% set limit = limit ?? 16 %} 
    {# set the available options for the limit selection on the front-end #}
    {% set limitOptions = [12, 24, 48, 96 ] %}
    {# set a variable querying all tags #}
    {# sets the services category to all #}
    {% set category = category ?? '' %}
    {# set the available options for the categories selection on the front-end #}
    {% set categoryOptions = craft.categories().group('services').level(1).all() %}
    {% set search = search ?? '' %}
  
    {# Query the entries from the comefare blog using a filter to create a set of reusable criteria #}
    {% set filters = {
	    search: search,
	    section: 'comefare',
	    limit: limit,
	   howtodoCategory: category,
    } %}	

    {% set entryQuery = craft.entries(filters|merge({
	    with: ['howtodoImage'],
    })) %}	

    {# Paginates the entry query given the current page #}
    {% set pageInfo = sprig.paginate(entryQuery, page) %}

    {# sets the entryQuery to the entries variable #}
    {% set entries = pageInfo.pageResults %}	

    {# pushes the criteria (filters) into the url string #}
    {% do sprig.pushUrl('?' ~ filters|merge({page: page})|url_encode) %}
    
    {# navbar to search and filter #}
    <section class="uk-section uk-padding-small background-grey-less-medium">
	<div class="uk-container">		
		<div class="uk-margin-bottom" s-replace="#results">
			
			<div class="uk-grid-small uk-flex" uk-grid>
				<div class="uk-inline uk-width-1-4@m uk-width-1-1@s">
					<a class="fix-form-icon-flip" href="#" uk-icon="icon: search"></a>
					{# Replaces only the `#results` div on keyup or when the value is changed #}
					<input class="uk-search-input" sprig s-trigger="keyup changed delay:300ms" type="search" name="search" value="{{ search }}" placeholder="Ricerca">
				</div>
				<div class="uk-width-1-4@m uk-width-1-1@s" uk-form-custom="target: > * > span:first-child">
					<select sprig class="uk-select" id="category" name="category">
						<option>Seleziona categoria </option>
						{% for categoryOption in categoryOptions %}
							<option value="{{ categoryOption}}" {{ categoryOption == category ? 'selected' }}>{{ categoryOption }}</option>
						{% endfor %}
					</select>
					<button class="fix-button fix-button-default uk-width-1-1@s" " type="button" tabindex="-1">
						<span></span>
						<span uk-icon="icon: chevron-down"></span>
					</button>
				</div>
				<div class="uk-visible@m uk-width-1-4@m uk-width-1-1@s" uk-form-custom="target: > * > span:first-child">
					<select class="uk-select" id="form-stacked-select" name="" >
						<option>Seleziona tag </option>
						{% for tag in tags %}
						<option>{{ tag }}</option>
						{% endfor %}
					</select>
					<button class="fix-button fix-button-default uk-width-1-1@s" type="button" tabindex="-1">
						<span></span>
						<span uk-icon="icon: chevron-down"></span>
					</button>
				</div>
				<div class="uk-visible@m uk-width-1-4@m uk-width-1-1@s" uk-form-custom="target: > * > span:first-child">
					<select sprig class="uk-select" id="limit" name="limit" value="">
						{% for limitOption in limitOptions %}
							<option value="{{ limitOption}}" {{ limitOption == limit ? 'selected' }}>{{ limitOption}}</option>
						{% endfor %}
					</select>
					<button class="fix-button fix-button-default uk-width-1-1@s" type="button" tabindex="-1">
						<span></span>
						<span uk-icon="icon: chevron-down"></span>
					</button>
				</div>
			</div>	
					
		</div>
	</div>
</section>

**Comment by bencroker** [comment]
Instead of `howtodoCategory: category`, you should probably be using the `relatedTo` parameter as explained in https://craftcms.com/knowledge-base/displaying-entries-related-to-a-category

**Comment by bencroker** [comment]
Also related: https://github.com/putyourlightson/craft-sprig/issues/74#issuecomment-748045109
