### ISSUE TITLE
Sprig rendering has gotten very slow since I made site live.

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#104]
I launched a site today with Sprig. An eCommerce one and while the sprig components were quite fast rendering on staging site now that there is traffic on the site they are a show stopper

https://share.johnhenry.ie/qGuXKPx8

Up to 50 secs while the page loads in under a second. One of these components is just a svg with a conditional in it

Using Blitz on the site also.

Craft Craft CMS 3.5.19.1
Sprig 1.3.3

**Comment by john-henry** [comment]
Note I am also using Cloudflare set up as per Blitz docs.

**Comment by bencroker** [comment]
Yup, that doesn't look right at all. There's a `token` fetch being initialised by a `calculator.js` script that is also taking close to 50s to load, so seems like it may be a server issue.

**Comment by john-henry** [comment]
Ok I think I sorted it. I added a sprig rule to Cloudflare to bypass and turn off anything it doesn't need and also add it to exclude it in Blitz. It was showing tampered message for an age with components but once I cleared Blitz cache it all seemed to work again.

**Comment by john-henry** [comment]
Will look at calcualtror.js thanks. that should not be on every page

**Comment by john-henry** [comment]
Ok I think we are good now. Closing out.
