### ISSUE TITLE
Using sprig contact-form component with server side caching?

### ISSUE THREAD

**Issue by pacoNew** [putyourlightson/craft-sprig#106]
Hi Ben, i just wonder if it's possible to use the sprig contact-form component while the site is server side cached? I work with a Hosting, which offers liteSpeed cache. 

I've tried so far to to load new data for the CSRF-Token by ajax. (I know, spirg will do that normally). This worked just fine with normal contact form offered by Craft. But I really want to use the sprig method.

Thanks for you reply and your time.

Cheers, Pascal

**Comment by bencroker** [comment]
It should be possible, see the dynamic content recipe at https://putyourlightson.com/sprig/cookbook#dynamic-content

**Comment by pacoNew** [comment]
Lieber Ben,

vielen Dank dir wieder mal :-)

Es läuft wie geschmiert. Habe mega Freude daran.

Ehrlich gesagt habe ich vor einigen Tagen schon versucht, das Kontaktformular via dynamic content einzubetten. 
Bin allerdings kläglich gescheitert. Habe anscheinend den ersten Parameter {'limit': }  nicht mitgegeben, weil
ich dachte, den brauch ich ja eh nicht, ich möchte ja schliesslich keine Entries ausgeben.

Dieser wird aber trotzdem gebraucht, sowie ich es jetzt verstanden habe. Bin gewillt das Konzept noch besser verstehen zu lernen.

Danke dir für deine Geduld und dein fantastisches Plugin.

Liebe Grüsse aus der zugefrorenen Schweiz

Pascal

**Comment by bencroker** [comment]
Gut zu hören Pascal, bleib warm!
