### ISSUE TITLE
pageInfo.total decreasing on each page

### ISSUE THREAD

**Issue by peteeveleigh** [putyourlightson/craft-sprig#108]
When using pageInfo.total to display the total number of results in a paginated set, the number decreases as one progresses through the pages. It looks like the total is being calculated from the number of pages including and *after* the current one and omits to include any entries from pages *before* the current page.

### To reproduce
Create a paginated result set and use `sprig.paginate`
Output the total results using `pageInfo.total` and move through the pages
`pageInfo.total` decreases by the number of entries being displayed per-page.

### Expected behaviour
`total` should remain consistent as the total number of entries being returned in the entire paginated set.

### Screenshots
Three screenshots added showing how the total decreases as we advance through the pages.

<img width="1153" alt="Screenshot 2021-02-21 at 17 10 37" src="https://user-images.githubusercontent.com/827065/108632671-0d178c80-7468-11eb-862b-79a6764c3d5a.png">
<img width="1210" alt="Screenshot 2021-02-21 at 17 10 47" src="https://user-images.githubusercontent.com/827065/108632674-0e48b980-7468-11eb-95e7-005645c813f4.png">
<img width="1186" alt="Screenshot 2021-02-21 at 17 10 55" src="https://user-images.githubusercontent.com/827065/108632675-0e48b980-7468-11eb-95eb-29f104a540eb.png">

### Versions
- Plugin version: Sprig 1.3.3
- Craft version: Pro 3.6.3

--

**Comment by bencroker** [comment]
Can you show the code that you use to generate the query and output the total results?

**Comment by peteeveleigh** [comment]
Yeah sure. This is extracted from the template to make it a bit clearer.
This is an example of the query being made. FYI `searchFilter` is an array of category IDs. 

```
{% set cats = ['and'] %}
	{% set cats = cats|merge(searchFilter) %}

	{% set entries = craft.entries().section('publications').publicationKeywords(cats).search(query).with(withFields).orderBy('publicationDate desc').offset(offset).limit(limit) %}
	{% set pageInfo = sprig.paginate(entries, page) %}
```

And then the total results (pageInfo.total) is being passed into a "hero" component as

```
{% include '_includes/hero' with {
	'heading' : 'Publications',
	'copy' : databasePages.publicationsPageIntroText,
	'total' : 'Total results: ' ~ pageInfo.total
}%}
```

As mentioned it "works" but as I advance through the pages the total is reduced by the amount of results per page.

and just in case, here's the pagination markup

```
<div class="pagination">
	{% if entries and pageInfo.totalPages > 1 %}

			{% if pageInfo.currentPage > 1 %}
				<button class="button button--pagination pagination__previous" sprig s-val:page="{{ page - 1 }}">
					Previous
				</button>
			{% endif %}


			<div class="pagination__numbers">

				{% for i in pageInfo.dynamicRange(5) %}
					{% if i == pageInfo.currentPage %}
						<span class="pagination__number pagination__number--active">{{ i }}</span>
					{% else %}
					{# Refreshes the component and pushes the new value into the URL #}
						<a class="pagination__number" href="?page={{ i }}" sprig s-val:page="{{ i }}">{{ i }}</a>
					{% endif %}
				{% endfor %}

			</div>

			{% if pageInfo.currentPage < pageInfo.totalPages %}
				<button class="button button--pagination pagination__next" sprig s-val:page="{{ page + 1 }}">
					Next
				</button>
			{% endif %}
	{% endif %}
</div>

```

**Comment by peteeveleigh** [comment]
Ahhh is it the offset query param that I'm applying?

**Comment by peteeveleigh** [comment]
Yep, I can see what I did wrong now! Should have known it wouldn't be a bug

**Comment by bencroker** [comment]
Yup, you got it, the offset should not be applied to the query.
