### ISSUE TITLE
Counting the number of filtered entries that contains a custom field

### ISSUE THREAD

**Issue by ConversioniaDev** [putyourlightson/craft-sprig#109]
### Question
I'm having trouble counting the entries after a filter is applied. I have three different counts that I'm needing to display along with the results. Each of the counts has a new set variable. The entries are not showing the defined query, instead it shows the results of the last set variable. Here is an example.

```
{# Results of the query #}
{% set entryQuery = craft.entries()
    .section('jobs')
    .search(search)
    .driverType(driverType)
    .truckType(truckType)
%}

{# count of the above query #}
{{ entryQuery|length }}

{# count of the above entryQuery that was posted within the last 14 days #}
{% set start = now|date_modify('-14 days')|atom %}
{% set end = now|atom %}

{% set countNew = entryQuery
    .postdate(['and', ">= #{start}", "< #{end}"])
%}
{{ countNew|length }}

{# count of the above entryQuery that has a custom field of .highNeeds(true) within the entry #}
{% set highNeeds = craft.app.fields.getFieldByHandle('highNeeds') %}
{% set countHighNeeds = entryQuery
    .highNeeds(true)
%}
{{ countHighNeeds|length }}

{# List of queried entries #}
{% for entry in entryQuery %}
This is showing only the entries with a custom field of .highNeeds(true).
{% endfor %}
```

The last set is overriding the original entryQuery and not showing all the results. It's only displaying the ones marked with `.highNeeds(true)` in the entry even through I'm calling `entryQuery` in the for statement in the template for the listings. I'm not calling any of the variables associated with the counts.

Why is the last defined variable set overriding the original `entryQuery` when it's called?

### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
Each time you add parameters to `entryQuery`, it is applied further down the template. To avoid this you can use the `clone` tag as explained in the Craft docs at https://craftcms.com/docs/3.x/entries-fields.html#working-with-entries-field-data

You should also use `entryQuery.count()` instead of `entryQuery|length`.

**Comment by ConversioniaDev** [comment]
Well, a 10 second fix for a 3 hour problem. Thanks, @bencroker. Works like a champ.

**Comment by bencroker** [comment]
Glad to hear it!
