### ISSUE TITLE
Styling Component on "Load More" recipe

### ISSUE THREAD

**Issue by brandondeweese** [putyourlightson/craft-sprig#11]
Is there a way to style the component wrapper? Perhaps add classes?

Currently, the div looks like this.

`<div id="component-IVuSg0" hx-target="this" hx-include="#component-IVuSg0 *" hx-trigger="refresh" hx-get="http://langrand.build/index.php?p=actions/sprig/components/render" hx-vars="'sprig:template':'fad2b3c8804bdcb333998c714aec09eadb8ebc53be023c7dfcfce5cfbe8dda95scripts/load-more','sprig:variables[limit]':'fc2fd9e7d41cb14aaead9532e973d77b77de8dbc5785ced0bf18273ce0e9c7ef2'">`

**Comment by bencroker** [comment]
You can add attributes in the third parameter when creating a component, so for example:

```twig
{{ sprig('load-more', [], {class: 'custom-class'}) }}
```
