### ISSUE TITLE
Amount of Sprig components on a page vs. AJAX speed/delays

### ISSUE THREAD

**Issue by uaextension** [putyourlightson/craft-sprig#110]
### Question
It's my first foray into Sprig and AJAX in general, so this is likely a very naive question:
In my test I am experiencing that very long wait time for the spring request (wait time for the modal window to pop up when one of the 20 cards is clicked) to complete:
https://ext.ualberta.ca/twigsandbox-program-tiles-only?program=management-development

whereas a a page with just a few sprig components (the blue tiles) has a good response time:
https://ext.ualberta.ca/twigsandbox-program-tiles-only?program=social-media 

I've stripped out the actual "reading of the API and filling in the modal window with data" part to make sure that wasn't causing the delays.

I'm using the following spring directive on each blue tile (and caching the tile content):

`<div class='card  h-100'`
`      sprig s-trigger="click"`
`      s-vars="clickedcardnoc: '{{noc}}', clickedcardregion: '{{region}}'"`
`      s-replace="#careerModalContent" >`
` `
`       {% cache globally using key cacheKey for 10 minutes %}`
`       …`
` `

Any pointers to help me debug the slow loading time would be very appreciated

**Comment by bencroker** [comment]
Loading the page at https://ext.ualberta.ca/twigsandbox-program-tiles-only?program=management-development takes 8 seconds for me. The modal loads in 6 seconds. So either your server is very slow or your code is extremely unperformant.

Please also note that `s-vars` is deprecated and should _not_ be used:
https://putyourlightson.com/plugins/sprig#s-vars

**Comment by uaextension** [comment]
Thanks. So it's not Sprig itself, right? Asking because [a 2-tile page](https://ext.ualberta.ca/twigsandbox-program-tiles-only?program=visual-arts) and [a 5-tile page](https://ext.ualberta.ca/twigsandbox-program-tiles-only?program=social-media)  have a much much lower delay/wait time.

> Please also note that s-vars is deprecated and should not be used:

Right! I really tried to get _s-vals_ working but even my 'console.log(evt.detail.xhr)' wasn't showing the values as being passed. I actually have this commented out at the moment (wasn't working): 
`{# s-vals="{'clickedcardnoc': {{noc}}, 'clickedcardregion': {{region}} }" #} ` 
response URL: 
`https://ext.ualberta.ca/index.php?p=actions/sprig/components/render&sprig%3AsiteId=32834119f9b46a208d28284e0550abfd1f9d8d9ea08591a6216e3b8a4aa7d24b1&sprig%3Atemplate=7b0c941377d281628a47cf9e0e37b973c9d80ed413f01a826353e6bd4f97ffe9_components%2Fcareer-carousel&sprig%3Avariables%5BentryID%5D=3a0321921dbf38ed61a61b01b6320f62b4a3ca2e8003585354dde68566cd7d9c135&sprig%3Avariables%5Bregion%5D=bd17a8668dd12fa4d3c4402c81993f9757b748cb678a64b101d9e85a88aa1e95Edmonton%20metro`

whereas `s-vars="clickedcardnoc: '{{noc}}', clickedcardregion: '{{region}}'"` 
works and its response URL is:
`https://ext.ualberta.ca/index.php?p=actions/sprig/components/render&clickedcardnoc=5136&clickedcardregion=Edmonton%20metro&sprig%3AsiteId=32834119f9b46a208d28284e0550abfd1f9d8d9ea08591a6216e3b8a4aa7d24b1&sprig%3Atemplate=7b0c941377d281628a47cf9e0e37b973c9d80ed413f01a826353e6bd4f97ffe9_components%2Fcareer-carousel&sprig%3Avariables%5BentryID%5D=3a0321921dbf38ed61a61b01b6320f62b4a3ca2e8003585354dde68566cd7d9c135&sprig%3Avariables%5Bregion%5D=bd17a8668dd12fa4d3c4402c81993f9757b748cb678a64b101d9e85a88aa1e95Edmonton%20metro`

**Comment by bencroker** [comment]
> Thanks. So it's not Sprig itself, right? Asking because a 2-tile page and a 5-tile page have a much much lower delay/wait time.

My guess is that your queries could use some eager-loading, see https://craftcms.com/docs/3.x/extend/element-types.html#eager-loading

Try using [s-val](https://putyourlightson.com/plugins/sprig#s-val) instead, it's a lot easier to work with.

```
s-val:clickedcardnoc="{{noc}}" s-val:clickedcardregion="{{region}}"
```

**Comment by uaextension** [comment]
Much appreciated

1. using s-val now because your markup worked - thanks so much
2. hunted the culprit down: each card is making a 'lite' call to the api to get the two fields that need to appear on the card itself: the 'career title', and the 'number of openings', so I will need to come up with something different. Craft caching of the card itself – that's the element that has the s-trigger on it – wouldn't make sense, would it? If Craft had let me cached variables, the obvious solution would be to cache the returned api dataset, but from what I can tell using {% cache %} in a template  will only cache the HTML output (I think?)

**Comment by bencroker** [comment]
> hunted the culprit down: each card is making a 'lite' call to the api to get the two fields that need to appear on the card itself: the 'career title', and the 'number of openings', so I will need to come up with something different.

Not sure what you mean by "API" here, but it sounds like eager-loading might help. Either way, it sounds like your Sprig issue is resolved.

> If Craft had let me cached variables, the obvious solution would be to cache the returned api dataset, but from what I can tell using {% cache %} in a template will only cache the HTML output (I think?)

Correct.

**Comment by uaextension** [comment]
Thanks for your help with this (my Sprig issue is definitely resolved now), and also for making this plugin available.
