### ISSUE TITLE
Update multiple components simultaneously

### ISSUE THREAD

**Issue by piotrpog** [putyourlightson/craft-sprig#112]
Is it possible? I know that we can update one component and then automatically trigger updating other components, using events. But this requires at least two requests. Is it possible to update multiple components at once, when one component triggers it?

**Comment by bencroker** [comment]
Yes, just trigger the refresh event on all components you want to refresh.

**Comment by piotrpog** [comment]
@bencroker 
Yes, but this takes two requests as i mentioned in first post. Is it possible to update multiple components with just one request?

**Comment by bencroker** [comment]
Do you mean 1 line of code instead of 2, or am I missing something?

**Comment by piotrpog** [comment]
@bencroker 
Hi,
sorry for lack of reply :)
What i meant is when one component triggers another, first needs to refresh and it triggers second request to server. Which means that visuallu for user, second component refresh will be delayed. 
Can we refresh both components at the same time? With one request to server, which would return html for both components, which would later be somehow divided and passed to specific components.

**Comment by bencroker** [comment]
You can trigger the refresh on multiple components at once, but this will trigger multiple requests and you cannot time the returned responses. If possible, using a single component simplifies things and makes multiple refreshes a non-issue.
