### ISSUE TITLE
Using Sprig in the control panel

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-sprig#113]
### Question

Hey Ben (and apologies for stalking you from plugin to plugin!)...

I would really like to try using Sprig, but for a back end control panel thing.  Basically we need to pull and display/filter some data from our ERP/Inventory system.  Integrating this into the Craft CP makes for a really nice, consistent interface for our operators.

So, I have download and installed Sprig, but pretty quickly hit a stumbling block...I can't get Sprig to load a template `{{sprig(test) }} from...well, anywhere, it seems, in this context. No issue doing the same in a front end template.

Maybe I am am doing something wrong but am guessing Sprig is only set up for front end template requests? Is that right?

I saw the Component Classes, which looks an alternative, but with (a quick) code check I can't see anything that different about how the template is loaded in that case.  So I am thinking that will run in to the same issue and that this might take some changes in Sprig to achieve?

What do you think - I think Sprig could be very handy for CP work as well.  But I haven't really used it yet, and there may me all sorts of considerations I am not...considering.  

Would love to get your thoughts on this.

**Comment by bencroker** [comment]
Using Sprig in the control panel is possible, you probably just need to take care of the template path. Are you seeing any errors in the browser console network tab?

**Comment by bossanova808** [comment]
Hmm, well I thought that it would just be a path issue too, but I tried a simple test - created a template in 

`mymodule/templates/main.twig`

```
{% extends '_layouts/cp' %}
{% set title = 'The Bridge - Supplier Purchases' %}
{% block content %}
    {{ sprig('test') }}
    {{ sprig.script }}
{% endblock %}
```

And then I created a test.twig which just has `Test` in it.  I tried placing that in all sorts of spots and using all sorts of paths (that exist!) - both in my front end templates folder and in the templates folder under my module...

All I see is 

`HTTP 400 – Bad Request – yii\web\BadRequestHttpException Unable to find the component or template “test”.`

Thinking about it, I only tried relative paths (`_components/test.html` - both under the module and under the front end templates folder - along with `{{ sprig('_components/test') }}` and so on - before simplifying back to just `test` and then placing the test template everywhere I could think of...to really make for the simplest test.

I'm feeling very rusty, having not poked around in modules for quite a while and I must be doing something stupid or forgetting something basic.  (I have no issue doing the same test all in the front end of things, of course...but from my module I jsut can't get the `sprig(test}` to load that template...

**Comment by bossanova808** [comment]
God damn it, I am rusty.  With a module you have to put the module name in front don't you?

`{{ sprig('mymodulename/test') }}`

**Comment by bencroker** [comment]
Yup, that's it!

**Comment by bossanova808** [comment]
Yep...for anyone reading this in the future, this is because of a bit of Craft magic...documented here:

https://craftcms.com/docs/3.x/extend/template-roots.html#plugin-control-panel-templates

Craft automatically creates a template root that points to `moduleName/templates` for you in the context of your module.

This breaks what seems to be the logical approach, which is one of the many things I tried...

i.e. with your template physically on the disk as: 
 `/modules/moduleName/templates/test.twig`

Giving Sprig:
`moduleName/templates/test` -> **will not load** as this actually gets translated to `moduleName/templates/templates/test`
`moduleName/test` -> will load

(Personally, I don't love this, as I'd prefer the given path to match the actual path, but, that's how it is...)
