### ISSUE TITLE
Filtering news entries by multiple checkboxes

### ISSUE THREAD

**Issue by MisterMike** [putyourlightson/craft-sprig#114]
### Question
I have not been able to figure this out yet, but I think it might be a nice usecase. 

Having a news page which lists news entries as thumbs with a bunch of checkboxes to filter by their categories. This works basically by using this code:

```{% set page = page ?? 1 %}
{% set newsCat = craft.app.request.getParam('newsCat') ?? '' %}

{% set relatedTo = [] %}
{% set relatedTo = newsCat ? relatedTo|merge([newsCat]) : relatedTo %}

{% set entryQuery = craft.entries
    .section('news')
    .limit(5)
    .relatedTo(relatedTo)
    ]) %}

{# Paginates the entry query given the current page #}
{% set pageInfo = sprig.paginate(entryQuery, page) %}
{% set newsEntries = pageInfo.pageResults %}
```

and then the checkboxes:
```
<ul>
    {% for category in craft.categories().group('news').all() %}
        <li class="filter--content--item{% if category.id in newsCat %} selected {% endif %}">
            <input sprig type="checkbox" class="filter_checkbox" name="newsCat" id="checkbox_{{ category.id }}" value="{{ category.id }}" {% if category.id in newsCat %} checked {% endif %}>
            <label id="label_{{ category.id }}" class="firstLabel" for="checkbox_{{ category.id }}">
                {{ category.title }}
            </label>
        </li>
    {% endfor %}
</ul>
```

After that, the news are looped:

```
{% for entry in newsEntries %}
...
{% endfor %}

{% do sprig.pushUrl('?' ~ {page: page, newsCat: newsCat}|url_encode) %}
```

### Additional context
Before Sprig, I have used javascript to implement this filtering and pushing the selections to the url. I was wondering if this can be done with Sprig more easily.

**Comment by bencroker** [comment]
Not sure what you mean by "more easily"? It only takes that one `sprig.pushUrl` command.

**Comment by MisterMike** [comment]
Ben, thanks for looking at it! Say I have three checkboxes to filter by "sports", "outdoor" and "public". Filter by "sports" : works. Additionally filter by "outdoor": works, but removes previously selected "sports" since reload happens when checkbox is selected. 

How can I filter using more than one checkbox? Can I "group" them using s-vals so value of already checked checkbox is preserved when clicking on another?

_"more easily" referred to quite some amount of vanilla JavaScript in comparison to very few lines of lean code using sprig._

**Comment by bencroker** [comment]
I think your checkbox input field's name just needs to be set to an array:

```twig
<input sprig type="checkbox" class="filter_checkbox" name="newsCat[]" id="checkbox_{{ category.id }}" value="{{ category.id }}" {% if category.id in newsCat %} checked {% endif %}>
```

**Comment by MisterMike** [comment]
Got it working as simple as I expected once I realized how to populate the name values for each checkbox.

```
{% set newsCat = newsCat ?? '' %}
{% set relatedTo = newsCat|join(',') %}

{% set entryQuery = craft.entries
    .section('news')
    .limit(5)
    .relatedTo(relatedTo)
%}


{% for category in craft.categories().group('news').all() %}
    <li>
        <input sprig type="checkbox" name="newsCat[{{ loop.index}}]" value="{{ category.id }}" {{ category.id in newsCat ? 'checked' :'' }}>
        <label for="checkbox_{{ category.id }}">
            {{ category.title }}
        </label>
    </li>
{% endfor %}

{% do sprig.pushUrl('?' ~ {page:page, newsCat:relatedTo}|url_encode) %}
```
