### ISSUE TITLE
Date field is throwing error Array to string

### ISSUE THREAD

**Issue by yeboJoseph** [putyourlightson/craft-sprig#116]
I'm pulling in a date field that should be passing in as an object but is throwing an Array to string error. I've been unable to figure it out. Any help would be much appreciated. 
Dump: array(0) { }

{% for entry in pageInfo.pageResults %}
            	{{entry.articleDate|date('medium')}}
		{{dump(entry.articleDate) }}
{% endfor %}

**Comment by bencroker** [comment]
Is the date field required? Is this specific to Sprig or does the same thing happen in a regular Twig template?

**Comment by yeboJoseph** [comment]
It's not required and is specific to Sprig. it works just fine in a regular Twig template.

**Comment by bencroker** [comment]
It sounds like the entry field has not been saved correctly. Does this work?

```twig
{{ entry.dateCreated|date('medium') }}
```

**Comment by yeboJoseph** [comment]
Hi Ben,
Thanks for your help. I had the field in the `with` part of my criteria.
