### ISSUE TITLE
FR: Please allow data- prefixing of s- and sprig- attributes

### ISSUE THREAD

**Issue by adrienne** [putyourlightson/craft-sprig#117]
### Is your feature request related to a problem? Please describe.
Fundamentally, the problem is that I want my HTML to validate, and custom attributes don't. 

### Describe the solution you would like
HTMX, which you use under the hood, has custom `hx-whatever` attributes, but they also work if you prefix them with `data-` (so `data-hx-whatever`). I would like to see the same solution for sprig, so that i could use `data-sprig` and `data-s-whatever` and have valid HTML while still having those attributes interact properly with Sprig.

**Comment by bencroker** [comment]
I'll consider this, thanks.

**Comment by leevigraham** [comment]
I think this should be the default. Given all the htmx attributes are either created from the `s-` or `sprig` attributes I don't see this as a breaking change.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-sprig/commit/ceb8b9e005e7ff1870910027dc2918bee6c4cf03 for the next release. Note that you'll likely also want to set the new config setting `hxDataPrefix` to `true`, to force `hx-` attributes to be prefixed with `data-`.
https://github.com/putyourlightson/craft-sprig/blob/ceb8b9e005e7ff1870910027dc2918bee6c4cf03/src/config.php#L25-L26

**Comment by bencroker** [comment]
Released in version 1.5.0.
