### ISSUE TITLE
Load currentUser using Sprig with Blitz

### ISSUE THREAD

**Issue by JMKelley** [putyourlightson/craft-sprig#118]
### Question
I'm having an issue with Sprig + Blitz Caching. I'm trying to load a user image if currentUser exists, though I'm having an issue with the caching. Sprig is loading in the unregistered user photo when logged in. I'm unsure if it's setup right.

      {{ sprig('components/_componentUser', {}, {
        's-trigger': 'refresh, load'
      }) }}

Then in my `_componentUser`

```
  {% if currentUser %}
            <li class="nav-item position-relative">
                <a class="nav-link py-3" href="/account" data-toggle="tooltip" data-placement="bottom" title="My Account">
                  <div class="account-circle">
                        <img src="{{ craft.gravatar.url(currentUser.email) }}" width="34" class="rounded-circle"/>
                  </div>
                </a>
            </li>
            {% else %}
            <li class="nav-item position-relative">
                <a class="nav-link" href="/account" data-toggle="tooltip" data-placement="bottom" title="My Account">
                  <div class="account-circle">
                        <span class="material-icons" data-icon="account_circle"></span>
                  </div>
                </a>
            </li>
  {% endif %}
```

### Additional context
Latest Blitz & Sprig versions.

**Comment by bencroker** [comment]
The code looks fine and if an image is being output then the `{% if currentUser %}` conditional must be truthy. Can you double check by outputting `currentUser.email` in the component?

**Comment by JMKelley** [comment]
Thanks for getting back to me. It works locally with Blitz caching enabled, could it be something with Cloudflare static caching? The email is returning OK.


- Clearing Cloudflare Reverse Proxy Cache causes it to work for a second, loading up an incognito tab and going to the site then makes it return false for all logged in users.

- I've tried impersonating another user in prod just to test, also returns false.

**Comment by bencroker** [comment]
If only reproducible in production then it could well be as issue with Cloudflare, but purging the cache should solve that.

**Comment by JMKelley** [comment]
Would wrapping the user portrait in a `{% if sprig.isRequest %}` tag force it to reload on each page load, would this fix the issue with Cloudflare caching it?

**Comment by bencroker** [comment]
Cloudflare should not cache the component. I suspect it was caching the parent template.

**Comment by JMKelley** [comment]
The bug is currently in production if you want to test with a fake account. [Here](https://www.vouchertoday.uk)

**Comment by bencroker** [comment]
Signing up doesn't seem to be working either.

![Screenshot 2021-03-24 at 17 39 12](https://user-images.githubusercontent.com/57572400/112348205-e5fee580-8cc7-11eb-9329-67428dce872f.png)

**Comment by JMKelley** [comment]
Apologies. Should be working now.

**Comment by bencroker** [comment]
Seems to be working, it recognises that I'm logged in.

![Screenshot 2021-03-24 at 18 38 22](https://user-images.githubusercontent.com/57572400/112357962-2c584280-8cd0-11eb-86dd-4cafc4d67095.png)

**Comment by JMKelley** [comment]
Thanks for testing it. If you refresh or come back to the page it will
revert to false.

**Comment by bencroker** [comment]
It keeps working as I navigate the site. Perhaps your browser is caching the result?
