### ISSUE TITLE
Asset upload from within front-end entry form

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-sprig#119]
### Question
Hi @bencroker , as per the [other issue](https://github.com/putyourlightson/craft-sprig/issues/9), I'm trying to get a front end entry form that contains a file input working with Sprig. 

Stripped down code is here...

```twig
{% set entry = entry ?? create('craft\\elements\\Entry') %}

{% if success is defined and success %}
    <p>The entry was successfully created!</p>
{% else %}

<form sprig s-method="post" s-action="entries/save-entry" enctype="multipart/form-data">

    {{ hiddenInput('sectionId', 7) }}
    {{ hiddenInput('entryId', entry.id ?? '') }}

    <label class="mb-2 inline-block" for="fullName">Full name</label>
    {{ input('text', 'fields[fullName]', fields.fullName ?? false, {
        id: 'fullName',
        placeholder: 'Name',
        class: ['input', entry.hasErrors('fullName') ? 'mb-2' : 'mb-6']|filter,
    }) }}

    {% if entry.hasErrors('fullName') %}
        <p class="mb-6">{{ entry.getFirstError('fullName') }}</p>
    {% endif %}

    <label class="mb-2 inline-block" for="document">Document</label>

    {{ input('file', 'fields[document]', fields.document ?? false, {
        id: 'document',
        class: [ 'input', entry.hasErrors('document') ? 'mb-2' : 'mb-6']|filter,
    }) }}

    {% if entry.hasErrors('document') %}
        <p>{{ entry.getFirstError('document') }}</p>
    {% endif %}
    
    <input type="submit" value="Create Entry">

</form>

{% endif %}

```

Sure I'm missing something, but `fullName` field works as expected, but the file input always errors with 'Cannot be blank',

**Comment by bencroker** [comment]
You should be using `s-encoding`, see https://putyourlightson.com/plugins/sprig#s-encoding

**Comment by shornuk** [comment]
> You should be using s-encoding, see https://putyourlightson.com/plugins/sprig#s-encoding

Nice! That's got it working now and submitting through 👍

The only issue I'm left with is that if the form doesn't validate, (for reasons other than the file input), it doesn't retain the file that was added. Currently adding `fields.document ?? false` as the value. Should that work?

**Comment by bencroker** [comment]
No, it will not, since `fields.document` will be the file object rather than the file path. You'll have to look for a workaround, perhaps putting `s-preserve` on the file input field to preserve its value or something similar.
https://putyourlightson.com/plugins/sprig#s-preserve

**Comment by shornuk** [comment]
`s-preserve` does the job 👍 Many thanks for your help and such a useful plugin.

**Comment by bencroker** [comment]
Glad to hear it!
