### ISSUE TITLE
Trying to bypass CORS Issue

### ISSUE THREAD

**Issue by bphippen** [putyourlightson/craft-sprig#120]
Hi Ben, not sure if Sprig supports this, but I am trying to submit a post request from a different front end url and getting a CORS policy error.

I have created a custom Sprig component with a save method where I am setting this response header:

`Craft::$app->response->headers->set('Access-Control-Allow-Origin', Craft::getAlias('@front'));`

@front is a specific url where the form lives.

However this does not work, there is still a CORS issue as if it was never set. I've also tried '*' wildcard CORS without luck as well.

Should I be doing something different here?

Thanks so much!

**Comment by bphippen** [comment]
Alright well after some testing, here is a solution that works for my specific scenario regarding two different urls that serve the same craft instance.

I am putting this in the init method of my custom Sprig component

`Craft::setAlias('@web', Craft::getAlias('@front'));`

**Comment by bencroker** [comment]
It's working when I test in a Sprig component locally.

```php

public function render(): string
{
    Craft::$app->response->headers->set('Access-Control-Allow-Origin', '*');

    return parent::render();
}
```

**Comment by bphippen** [comment]
Works locally if the domains are the same, but if you try two different urls, which I can really only reproduce on staging or production servers, is where it fails.

I think it has something to do with calling the actionRender controller and the `Access-Control-Allow-Origin', '*'` header from the render method is not being set yet.

In any case, updating the @web alias to the url where my sprig form lives worked for my needs.

**Comment by bencroker** [comment]
Ok great!
