### ISSUE TITLE
Redirect to newly created entry

### ISSUE THREAD

**Issue by fredrik-sogaard** [putyourlightson/craft-sprig#122]
I have a form to create an entry. Is is possible to redirect to the saved entry upon successfully saving it?

**Comment by bencroker** [comment]
It should be, using the [sprig.redirect](https://putyourlightson.com/plugins/sprig#sprig.redirecturl) template variable. On success, the saved entry ID will be available in the template as `id`.

```twig
{% if success is defined and success %}
    {% do sprig.redirect('/entry/' ~ id) %}
{% endif %}
```

**Comment by fredrik-sogaard** [comment]
Thanks! Works!
