### ISSUE TITLE
option for including query params of original page on refresh events

### ISSUE THREAD

**Issue by aloco** [putyourlightson/craft-sprig#123]
Hi, 

thank you for this great free plugin and your amazing work on other plugins too! I have a FR, but I am not sure if this is feasible or have any side effects.

### Is your feature request related to a problem? Please describe.
Imagine a website where you have some filter dropdowns and a sprig component which is showing results based on the filter selection. The filter selection is a very complex UI and therefore built in react / angular / vue whatever. The user should be able to share the filter selection via url, so therefore we store the selection of filters as query params. When loading the page initially, the query params are exposed to the sprig component. However, when changing the filters, we are setting the query params and then we are dispatching a `refresh` event to the result sprig component. The query params are not included anymore (I think because they are not included as form fields or `s-vals` within the sprig component) but they are available in `sprig.url`

In the docs https://putyourlightson.com/plugins/sprig#component-variables there is this
`Request parameters (query string and body parameters) are automatically available in your components, provided they do not begin with an underscore.` which is not working for us on `refresh` - so maybe we got something different wrong as well ..

### Describe the solution you would like
It would be nice if we could get an option to always include the current query params of the page when refreshing the sprig component without setting any values to the sprig component directly.

### Describe alternatives you have considered

There are already issues like this one https://github.com/putyourlightson/craft-sprig/issues/63 where you indicate to set values directly via input fields. I think we could also directly set `s-vals` data attributes from javascript to the sprig component. 

Within the sprig component, we could also use `sprig.url` to receive the current query params of the original page. However, `sprig.url` doesn´t contain the query params initially on page load. So we need to check if the query params are exposed to the template (initial page load) and for subsequent `refresh`, we need to check `sprig.url` instead. 

I hope I summarized this clearly - Curious about your opinion!

**Comment by bencroker** [comment]
Hi Andreas! 

The URL query params are passed into the Sprig component on initialisation only, not each time a component is refreshed.

Have you considered passing the values into the [htmx.trigger](https://htmx.org/api/#trigger) command?

```js
htmx.trigger('#component', 'refresh', {param1: 'value1', param2: 'value2'});
```

**Comment by aloco** [comment]
Hi Ben!,

thank you for the fast response! We are also using the built in pagination feature within the component so I assume when setting the params directly we are loosing the `page` param which is contained in the component. So we might need to get all current values with `htmx.values` and then setting the new merged values with `htmx.trigger` ?

**Comment by bencroker** [comment]
Yes, for example. If it's just that one parameter then you could also put it into an input field that you can then fetch the value of. 

```js
htmx.find('#page').value
```

**Comment by aloco** [comment]
Hi, alright thanks for the support, we will try this the next time we are running into this use case

**Comment by twosixcode** [comment]
@bencroker This issue described here the exact situation I am tackling at the moment. I wanted to follow up for clarification on the suggested solution:

> Have you considered passing the values into the htmx.trigger command?
> 
> `htmx.trigger('#component', 'refresh', {param1: 'value1', param2: 'value2'});`

I've verified my component is refreshing just fine via `htmx.trigger` but how would I access those pass params in the refreshed component template?

Thanks!

**Comment by bencroker** [comment]
You need to first pass them into the component from the parent template.

```twig
{{ sprig('_components/component', {
    param1: craft.app.request.getParam('param1'),
    param2: craft.app.request.getParam('param2'),
}) }}
```

You can then output them as normal.

```twig
param1: {{ param1 }}
param2: {{ param2 }}
```

**Comment by twosixcode** [comment]
@bencroker Thanks. I am passing from the parent template and it is there correctly in the component initially.
```
{{ sprig('_components/hero', {_entryid: entry.id, param1: 'testing'}, {
    'id': 'hero',
}) }}

```
Then, in a separate sprig component that is getting updated I have this in place to trigger a refresh on the `#hero` component:

```
{% if sprig.isRequest %}
	<script>
	  console.log('request');
	  htmx.trigger('#hero', 'refresh', {param1: 'updated param value'});
	</script>
{% endif %}
```

I can see the #hero component being triggered and updated (I output a timestamp in that component and can see that change, plus the console logging shows up). But the value of `param1` remains unaltered.

Any tips you have on what's amiss here would be appreciated. My goal here is very similar if not identical to the challenge described originally here by aloco.

**Comment by bencroker** [comment]
Oh I see. You are assuming that `htmx.trigger` will pass the value of `param1` into the template, but it does not. Using [htmx.trigger](https://htmx.org/api/#trigger) means you are in JS land, therefore those parameters become available on the event detail. You'd have to listen for the event in the refreshed component and then get the parameters from the event details, but keep in mind that you're no longer in Twig land.

**Comment by twosixcode** [comment]
Thanks, I did inspect the HTMX event some but wasn't sure how to access (are there methods for this?). The HTMX docs seem a bit lacking in examples. If you have any tips I would sure appreciate it!

**Comment by bencroker** [comment]
The [htmx.on()](https://htmx.org/api/#on) event listener can be used for this. Untested, but something along the lines of what's below.

```js
htmx.on('refresh', function(event) { 
    console.log(event.detail.param1);
});
```

**Comment by twosixcode** [comment]
Thanks. Decided just to make one gigantic sprig component for now, instead of trying to keep separate fragment components up to date manually.

**Comment by bencroker** [comment]
Sounds smart!
