### ISSUE TITLE
Odd behavior using sprig.pushUrl and clicking the browser back button

### ISSUE THREAD

**Issue by strandofgenius** [putyourlightson/craft-sprig#124]
### Describe the bug
When using `{% do sprig.pushUrl('?' ~ filters|url_encode) %}` there was some intial weirdness in Safari. I made some checkbox selections and then I navigated to another page and then clicked the back button the main navigation was being hidden since, as if it were trying to still apply a class to the body tag which only needs to be there if the main menu dialog was open.

I also found that when in Firefox and Chrome if I make some selections and then clicked the back button while remaining on the gallery page I was no longer able to toggle the main navigation.

### Screenshots
Here is a video of the menu disappearing in Safari: 
https://www.dropbox.com/s/6whjh5ztomd7qxz/Screen%20Recording%202021-04-15%20at%209.06.23%20AM.mov?dl=0

Here is a video of the menu as expected in Chrome:
https://www.dropbox.com/s/aa2x7tumesa2555/Screen%20Recording%202021-04-15%20at%209.09.39%20AM.mov?dl=0

### Versions
- Plugin version: 1.4.0
- Craft version: 3.6.7

**Comment by bencroker** [comment]
I believe this might be due to how htmx handles history events. See https://github.com/putyourlightson/craft-sprig/issues/92 for a recent discussion in case it is of any use to you.

**Comment by strandofgenius** [comment]
@bencroker yes, as I keep digging it looks like it's related to history. I was looking at their [docs](https://htmx.org/docs/#history) and found `hx-history-elt` but don't think this will solve my issue. It needs to refresh the whole page so that the js on the page is re-initalized.

**Comment by strandofgenius** [comment]
I see you had a support ticket here https://github.com/bigskysoftware/htmx/issues/370. Do you have an idea of how to remedy my issue?

**Comment by strandofgenius** [comment]
I'm not sure if this is the most ideal thing to do but I did do this to reload the page and I can now click my main nav button.
```js
htmx.on('htmx:historyRestore', function(event) {
    (function () {
        window.location.reload();
    })();
});
```

**Comment by bencroker** [comment]
So one idea might be to reset the checkboxes on page load. Another is to refresh the Sprig component on page load similar to the Dynamic Content recipe at https://putyourlightson.com/sprig/cookbook#dynamic-content.
