### ISSUE TITLE
Sprig / Load More + Htmx

### ISSUE THREAD

**Issue by thefubon** [putyourlightson/craft-sprig#126]
### Description
Please tell me. How can I do the same using the Sprig + HTMX plugin (Load More)? the page address is added. when you look at the news and come back, everything is displayed as it was downloaded.

### Demo
 http://www.thisismirador.com/page/4/

**Comment by bencroker** [comment]
Just set the limit to the page number times the number of results per page. For example:

```twig
{% set page = page ?? 1 %}
{% set perPage = 10 %}
{% set limit = page * perPage %}
{% set entries = craft.entries.limit(page * perPage).all() %}
```

Be sure to pass the page into the URL as a query string such as `?page=4`.

**Comment by thefubon** [comment]
Sorry, I cannot integrate into this format
```
{% set offset = offset ?? 0 %}
{% do sprig.pushUrl('?offset=' ~ offset) %}

{% set entryQuery = craft.entries
		.section(section)
		.offset(offset)
		.limit(limit)
%}
{% set entries = entryQuery.all() %}

{% for entry in entries %}
	
{% endfor %}

{% if entryQuery.count() > (offset + entries|length) %}
	<button class="uk-button uk-button-default uk-button-large uk-border-rounded uk-align-center"
		sprig
		s-val:offset="{{ offset + limit }}"
		s-target="this"
		s-swap="outerHTML">
		{{ 'Load More'|t }}
	</button>
{% endif %}

```

**Comment by bencroker** [comment]
Use the same idea as the code I provided, you'll just need to add a page count to your code and URL.

**Comment by thefubon** [comment]
Thanks
