### ISSUE TITLE
When should I be using nested components or triggering another component to refresh?

### ISSUE THREAD

**Issue by strandofgenius** [putyourlightson/craft-sprig#127]
### Question
Before you released the sprig board videos I ended up making something very similar with a little more of a complex layout with some columns. Originally I had it rerendering the whole component and started thinking that it seemed like a pretty big load especially as the number of lead results continues to grow.

I've added a screenshot to show the new layout that includes search, filters, a quick overview of total leads and then a table of lead results. You'll see there is a button that is meant to export the results based on what was queried not necessarily just the results that are viewable by page. However, I was finding that eventually it was throwing a `413 error` which was caused by too long of URL because it was returning all of the IDs that needed to be exported in the AJAX response.

This led me to try and see where it would be ideal or if it is necessary to break out the one component into multiple to handle the filters to refresh the data so that the responses could be handled better since the total leads will likely grow into the thousands of records.

### Additional context
<img width="1408" alt="Screen Shot 2021-04-27 at 11 34 08 AM" src="https://user-images.githubusercontent.com/11370639/116280082-f0d8ea00-a74d-11eb-8b67-a34bbdfae73f.png">

**Comment by bencroker** [comment]
> However, I was finding that eventually it was throwing a 413 error which was caused by too long of URL because it was returning all of the IDs that needed to be exported in the AJAX response.

Rather than sending all entry IDs, why not create the exported results directly from the filters? That seems like a much more scalable way to implement it.

**Comment by strandofgenius** [comment]
It is based on the filters, when the page first loads or when the filters change it rebuilds an array that is used to send to a controller that can export the entries into an excel doc using the Beam plugin. So right off the bat when that page loads with 1000 results the URL is too long.

```twig
{% set leadsarray = [] %}

{% for lead in totalLeads %}
    {% set leadsarray = leadsarray|merge([lead.id]) %}
{% endfor %}

<form method="post" accept-charset="UTF-8" action="/actions/export-to-excel-module/default/export-excel/">
    {{ csrfInput() }}
    <input id="leadList" type="hidden" name="leadlist" value="{{ leadsarray|json_encode() }}">
    <input type="submit" value="Export {{ pageInfo.total }} Results to Excel">
</form>
```

I'm wondering If it would be beneficial to break my one component apart into multiple components that talk to each other like you did the sprig cart? Would it help with how the requests are made?

**Comment by bencroker** [comment]
The issue is likely that the post request to the Beam plugin is too large. I don't see how multiple Sprig components can help with this.

**Comment by strandofgenius** [comment]
The issue seems to be even before I click export. When the page initial loaded I couldn't even get the filters to do anything. I kept giving me a `414 error` in the console. So I then removed this line `<input id="leadList" type="hidden" name="leadlist" value="{{ leadsarray|json_encode() }}">` which at least let me run the filters. Clearly this isn't very helpful since I want to export those entries.

 >I don't see how multiple Sprig components can help with this.

That's why I'm asking since I wasn't sure if you'd think there might be a use case for multiple components for how the filtering and data output should be handled in my situation.

**Comment by bencroker** [comment]
Ok, I see the issue now and understand your question better. The input field `leadlist` is submitted as part of the Sprig request, even though it has no reason to be. What I'd suggest is that you move the export form out of the component entirely (into the parent template, for example), and use JavaScript to populate the field value.

Then in your Sprig component you'd do something along the lines of:
```js
<script>
    htmx.find('#leadList').value = '{{ leadsarray|json_encode() }}';
</script>
```

**Comment by strandofgenius** [comment]
When I added that within the component htmx is not defined. I'm using sprig version `1.3.3`.

**Comment by bencroker** [comment]
Well you'd have to load htmx before outputting the script. Here's an alternative using vanilla JS:

```js
<script>
    document.getElementById('#leadList').value = '{{ leadsarray|json_encode() }}';
</script>
```

**Comment by strandofgenius** [comment]
I did try putting the sprig script inside the component but then it told me that `htmx.find` was null so then I was really confused. I kind of imagined that because the sprig script was already on the page because of the parent file then it should have been initiated. 

The thing is your example script worked but was giving me the console error.

**Comment by strandofgenius** [comment]
I see it's because it doesn't find the input until after the component has updated after a filter selection. It would also need to be when it's initially loaded as well.

**Comment by bencroker** [comment]
The Sprig script (htmx.js) must be loaded before `htmx.find` is executed, for obvious reasons. It should always be loaded outside of a Sprig component though.
