### ISSUE TITLE
Variable "entry" does not exist.

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#128]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

### Additional context
Add any other context or screenshots about the support request here.
Craft 3.6.12
Sprig 1.5.2

I've got a template that works if instead of sprig I use a regular include. The page loads correctly. However when I try to use sprig I get a template error:

`Variable "entry" does not exist.`

it appears that the "entry" is not being passed to the component. Not sure how to resolve this.

main template:

```twig
{% extends '_layout' %}

{% block content %}

  {% include '_includes/pageHeader' %}

  {{ sprig('_components/product-page') }}
  {% include "_components/product-page" %}

{% endblock %}
```

and inside the _components/product-page template I have this

```twig
{#
  Sprig component for product filters
 #}

	{% set entries = craft.entries.section('products').relatedTo(entry.productListingTypes) %}

	<div class="container mt-6">
		<div class="row">
			<div class="col-lg-3">
				<div class="bg-light p-3 mb-3">

          <form sprig>
            <input
              sprig
              s-trigger="keyup changed delay:300ms"
              type="search"
              name="q"
              aria-label="Search"
              placeholder="Search"
              autocomplete="off"
              value="{{ search ?? null }}"
              class="form-control">

              <h4>
                Filters
              </h4>

              <select
                sprig
                name="productType"
                id="productType"
                class="form-select" aria-label="Choose a product type">
                <option value="">-Choose-</option>
                {% for item in entry.productListingTypes.all() %}
                  <option value="{{ item.slug }}">{{ item.title }}</option>
                {% endfor %}
              </select>

              <p>
                [insert filters here]
              </p>
          </form>
				</div>
			</div>

		</div>
	</div>
```

**Comment by bencroker** [comment]
Unlike an `include` variables in the parent template are _not_ automatically passed into a Sprig component. To make this work, pass the entry ID into the component and then fetch the entry from the ID from within the component.

There's an example at https://putyourlightson.com/sprig/cookbook#nesting-components
