### ISSUE TITLE
Alphasorting stuck

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#129]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

### Additional context
Add any other context or screenshots about the support request here.
Craft 3.6.12
Sprig 1.5.2

I'm building filters with a search field (working), related entries select (working), and a button to change the sort order (not working)

If I update the query parameter in the address bar the sort order works as expected. However clicking the button doesn't do anything. I looked in the network tab and saw a status 200 so no error, but also no change.

Here is the relevant code:

```twig
  {# Ensure reset variable exists #}
  {% set reset = reset ?? false %}

  {# Set default values if `reset` is true or if value is not defined #}
  {% set search = reset ? '' : (q ?? '') %}
  {% set alphaSort = reset ? '' : (alphaSort ?? 'asc') %}
  {% set productType = reset ? '' : (productType ?? '') %}


  {% set relatedTo = ['and'] %}
  {% set relatedTo = productType ? relatedTo|merge([productType]) : relatedTo %}

  {# Reset to an empty array if no related elements were specified. #}
  {% set relatedTo = (relatedTo == ['and']) ? [] : relatedTo %}


  {# sent page entry cause it doesn't pass into sprig templates #}
  {% set entry = craft.entries.id(entryId).one() %}

		{% set entryQuery = craft.entries
    .section('products')
    .relatedTo(entry.productListingTypes)
    .relatedTo(relatedTo)
    .search(search)
    .orderBy('title ' ~ alphaSort)
     %}

{# more code here #}

{# 
// sort button 
// I expect the button to change the value from asc to desc or desc to asc depending on current value
#}
<p class="sort">
  Sort
  <button
    sprig
    s-trigger="click"
    s-val:alphaSort="{{ alphaSort == 'desc' ? 'desc':'asc' }}"
    class="">
      {{ svg('@webroot/assets/images/svg/sort.svg')|attr({class:'sort-icon ' ~ alphaSort }) }}
      <span class="ascending {{ alphaSort }}">A-Z</span>
      <span class="descending {{ alphaSort }}">Z-A</span>
  </button>
</p>
```

**Comment by bencroker** [comment]
As per the [docs](https://putyourlightson.com/plugins/sprig#s-val), the `s-val` attribute must be in lower-case and in `kebab-case` (dashes will be removed and the name will be converted to `camelCase`).

**Comment by CreateSean** [comment]
I replaced all instances of `alphaSort` with `alphasort` no camelCase anywhere and it's still not working.

**Comment by bencroker** [comment]
`camelCase` → `alphaSort`
`kebab-case` → `alpha-sort`

**Comment by CreateSean** [comment]
I realize that, but if all instances are `alphasort` then it's all lowercase with no spaces, dashes, or uppercase letters. Should work now, right?

```twig
{% set alphasort = reset ? '' : (alphasort ?? 'asc') %}
```

```twig
<button
                sprig
                s-trigger="click"
                s-val:alphasort="{{ alphasort == 'desc' ? 'desc':'asc' }}"
                class="">
                  {{ svg('@webroot/assets/images/svg/sort.svg')|attr({class:'sort-icon ' ~ alphasort }) }}
                  <span class="ascending {{ alphasort }}">A-Z</span>
                  <span class="descending {{ alphasort }}">Z-A</span>
              </button>
```

**Comment by bencroker** [comment]
Yes, your sort switch statement looks incorrect though.

```
s-val:alphasort="{{ alphasort == 'desc' ? 'asc' : 'desc' }}"
```

**Comment by CreateSean** [comment]
Of course it was user error. Thank you for your help.

**Comment by bencroker** [comment]
Sure thing!
