### ISSUE TITLE
Multi-lingual Websites

### ISSUE THREAD

**Issue by andrewfairlie** [putyourlightson/craft-sprig#13]
Hi! Are there best practices to make Sprig work well with multi-lingual sites? I might be missing a trick but it seems that the dynamic content (specifically a "search-as-you-type" widget) loads from the default (English) site even if you're on the French site.

I think I could pass through a parameter of site ID to run the query on, but that wouldn't solve any translation strings that use Twig's `|t` filter.

Update: I think this might be that the `sprig.include` bit is translated but any `sprig.request` bits aren't? I may be misdiagnosing this.

**Comment by bencroker** [comment]
I think this is probably something that should be handled by Sprig automatically, will look into it further and let you know.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-sprig/commit/cd68fbcb9ac5b31864983a550133ac9039bbc12f, can you please check if this solves your issue?

**Comment by andrewfairlie** [comment]
Hi @bencroker. Sure, will do. I'm not great at composer. Could you give me a clue about how I switch to that branch, please?

**Comment by bencroker** [comment]
This should do it:

```
composer require putyourlightson/craft-sprig:dev-develop
```

**Comment by andrewfairlie** [comment]
Yep that fixes it

**Comment by bencroker** [comment]
Great, coming in the next release.
