### ISSUE TITLE
<select> changed example

### ISSUE THREAD

**Issue by jamiematrix** [putyourlightson/craft-sprig#130]
### Question
Are there any examples of using a <select> element to trigger a Sprig component? I have a <select> filled with categories and wanting to re-query Craft any entries from the selected category.

### Additional context
The site is also using Select2 for <select> styling - my current goal is to check that the styling is being applied to the element after the component is re-rendered.

**Comment by bencroker** [comment]
Yup, there are a few examples in [Sprigboard](https://putyourlightson.com/sprig/videos#sprigboard). 

If you need to do something after re-rendering then you'll likely want to to listen to a htmx event, for example:

```js
   htmx.on('htmx:afterSwap', function(event) {
       // do something
   });
```

See the [docs](https://putyourlightson.com/plugins/sprig#javascript).

**Comment by jamiematrix** [comment]
Thanks!
Have you had much dealings with Select2 library and using Sprig? I've removed the Select2 classes to get the 'onchange' event to fire - which seems to be working correctly.

I thought Select2 would 'copy' the `sprig` attribute but it doesn't, so may have to resort to using Javascript to detect the Select2 when it changes.

**Comment by jamiematrix** [comment]
I've found a somewhat workaround whilst keeping with Select2, but it's not 100%.

The below triggers HTMX when the Select2 dropdown is selected/changed. This works
```
$('.js-select').on('select2:select', function(e) {
        htmx.trigger('#category', 'refresh');
    })
```
When the Sprig component refreshes with the new data, the Select2 control is no longer styled or setup for Select2, so I've set the `htmx:afterSwap` to re-do the Select2 control:
```
htmx.on('htmx:afterSwap', function(event) {
        $('.js-select').select2({
            minimumResultsForSearch: Infinity
        });
    });
```
This causes the dropdown to duplicate, one having the native HTML styling and the other having the Select2 classes. If I do the above in the console (without the htmx:afterSwap) then the native control disappears and the Select2 remains - what I want ... but ... the Select2 control no longer gets triggered when changed/selected

**Comment by bencroker** [comment]
Your approach looks correct, I guess you just need to tweak the timing of the events. Perhaps adding a `setTimeout` will help, or using an event that fires a few ms later such as `htmx:afterSettle`.

**Comment by jamiematrix** [comment]
Seems to be working so far. I now have the following:
```js
    $('.js-select').on('select2:select', function(e) {
        htmx.trigger('#category', 'refresh');
    })

    htmx.on('htmx:afterSettle', function(event) {
        $('.js-select').select2({
            minimumResultsForSearch: Infinity
        });

        $('.js-select').on('select2:select', function(e) {
            htmx.trigger('#category', 'refresh');
        })
    });
```
At first the 'select2:select' trigger wouldn't fire, my guess is that select2 being reset clears all the subscribed events. The above seems to do the trick so far.

Thanks for the help @bencroker

**Comment by bencroker** [comment]
Looks good. You could perhaps make it more DRY with a function.

```js
function initSelect2() {
    $('.js-select').select2({
        minimumResultsForSearch: Infinity
    });

    $('.js-select').on('select2:select', function(e) {
        htmx.trigger('#category', 'refresh');
    })
}

initSelect2();

htmx.on('htmx:afterSettle', function(event) {
    initSelect2();
});
```

**Comment by jamiematrix** [comment]
Oh I like! Cleaner too.

Thanks!
