### ISSUE TITLE
Hidden variable passed in via Sprig 'does not exist' when set to a comma seperated string.

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-sprig#131]
### Question
I am trying to pass in a hidden variable passed in via Sprig.
However, I am getting back the error that `_sections 'does not exist'` when _sections is set to a comma separated string and passed into the sprig template.

Here is a shortened version of my code:

**template.twig**
```
{% set sections = ['features', 'blog', 'researchPapers'] %}

{{ sprig('_includes/_sprig/search-megamenu.twig', {
  _sections: sections|join(','),
  nameSpace: 'technical',
  placeholderText: 'Search technical articles',
  allOptionsLabel: 'All Sections'
}) }}
```

**sprig.twig**
```
{% set section = section ?? '' %}

{% set alllowedSectionHandles = _sections|split(',') %}
{% set allowedSections = alllowedSectionHandles|map(handle => craft.app.sections.sectionByHandle(handle)) %}

{% set section = section in alllowedSectionHandles ? section : alllowedSectionHandles %}

  {% if alllowedSectionHandles %}
    <div>
      <label for="section" class="sr-only">Directory</label>
      <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
        <select
          sprig
          id="section"
          name="section"
          class="pr-6 {{ classes.input }}"
        >
          <option value="">All Sections</option>
           {% for allowedSection in allowedSections %} 
           <option value="{{ allowedSection.handle }}" {{ allowedSection.handle == section ? 'selected' }}> 
           {{ allowedSection.name }} 
           </option> 
           {% endfor %} 
        </select>
      </div>
    </div>
  {% endif %}
  ```
  
 When I dump `dd(_sections)` I get the array outputted.
 if I pass in just a single string as _section. All is ok and works.
 
What am I doing wrong?

**Comment by terryupton** [comment]
I should add that I had the above code working when fixing the `alllowedSectionHandles` to an array like so:
```
{% set alllowedSectionHandles = ['features', 'blog', 'researchPapers'] %}
```

Only when I try and pass this in as a variable does it become a problem.

**Comment by bencroker** [comment]
> When I dump `dd(_sections)` I get the array outputted.

Is this not what you would expect to have happen? I'm not following what exactly is not working?

**Comment by terryupton** [comment]
Hey @bencroker yeah this is what I would expect. 
However, if I don't `dd(_sections)` then I get the error that `_sections does not exist`. So the template breaks, but I would expect that the _sections instead outputs as the array passed in (or rather the comma separated string) that I then turn back into an array within the sprig template.

**Comment by bencroker** [comment]
The error should show you what line it is being thrown on with `devMode` enabled. Can you check?

**Comment by terryupton** [comment]
`{% set alllowedSectionHandles = _sections|split(',') %}`
<img width="1677" alt="Screenshot 2021-05-10 at 18 21 16" src="https://user-images.githubusercontent.com/5698596/117699369-ab400680-b1bc-11eb-95c1-1a9e47409120.png">

**Comment by bencroker** [comment]
There must be something else going on. This works fine when I test it locally.

```twig
{% set alllowedSectionHandles = _sections|split(',') %}
{{ alllowedSectionHandles|join(',') }}
```

**Comment by terryupton** [comment]
That's really odd.
I did try by using alternative variable names as well...
I will have another look tomorrow. Thanks @bencroker

**Comment by bencroker** [comment]
Can you test this code with nothing else?

```twig
{{ sprig('_includes/_sprig/search-megamenu.twig', {
  _sections: ['features', 'blog', 'researchPapers']|join(',')
}) }}
```

```twig
{% set alllowedSectionHandles = _sections|split(',') %}
{{ alllowedSectionHandles|join(',') }}
```

**Comment by terryupton** [comment]
Hey @bencroker. I have run the test with nothing else as requested.
However, I am still getting the same result/error.

<img width="1685" alt="Screenshot 2021-05-11 at 09 19 56" src="https://user-images.githubusercontent.com/5698596/117783288-4e833100-b23a-11eb-987f-067591f7d5df.png">


I am on the latest version of Craft and all plugins.

**Comment by terryupton** [comment]
@bencroker - I think I have found the problem (me). 
I have stripped it all down and your code is working just fine. I am working on rebuilding it back up and I think the problem is a result of an include I had not updated yet (doh). I will test and reveal shortly. But I think this is the cause.
Apologies for taking up your time....

**Comment by bencroker** [comment]
No problem and good luck!
