### ISSUE TITLE
Load More button for articles grid

### ISSUE THREAD

**Issue by nfq** [putyourlightson/craft-sprig#132]
### Question
We have a content builder which uses Neo (Craft 3.6). One of the matrix blocks is a News entries grid (grid of articles, when you click on one it loads the article). Under this grid we want to add a Load More button which loads more articles. But I'm getting this error (see screenshot): <img width="1315" alt="Screenshot 2021-05-10 at 23 55 12" src="https://user-images.githubusercontent.com/183354/117730836-523c9680-b1ed-11eb-9b9d-1ee5c625c94d.png"> `Variable "item" does not exist.`

If I pass in `item` to the sprig include, I get `The variable 'item' is an element of type 'benf\neo\elements\block' and cannot be passed into a Sprig component etc....` See the attached screenshot: 
<img width="1307" alt="Screenshot 2021-05-05 at 13 54 00" src="https://user-images.githubusercontent.com/183354/117732105-8f098d00-b1ef-11eb-801e-af4c86cbc1d4.png">

### Code
Here's a striped version of the code:

#### Content Builder parent template
```
{% for block in entry.contentBuilder.level(1).all() %}

  <section>
    <div class="container">
      {% for item in block.children.all() %}
        {% switch type %}

          {#- Layout Grid with content blocks -#}
          {% case 'unit' %}

            {% for child in item.children.all() if item is not empty %}
              {% include "/_shared/blocks/" ~ child.type %}
            {% endfor %}

          {#- News Carousel/Entries -#}
          {% case 'newsEntries' %}
            {{ sprig('/_shared/components/news/grid') }}
            {{ sprig.script }}

          {#- Card Group -#}
          {% case 'cardGroupEntries' %}
            {% include '/_shared/components/cards/cards' with { categories: item.cardEntries.all() } %}

        {% endswitch %}
      {% endfor %}

    </div>
  </section>

{% endfor %}
```

#### Child News item template
```
{% set channel = item.newsChannel %}
{% set category = item.newsCategory %}
{% set filter = ['and', { element: channel }] %}
{% set filter = category|length ? filter|merge([{ element: category }]) : filter %}
{% set sortOrder = item.newFirst ? 'desc' : 'asc' %}
{% set sourceSite = 'currentSite' ~ craft.app.language|upper %}

{% set entries = craft.entries()
    .site(sourceSite)
    .orderBy('postDate ' ~ sortOrder)
    .status(['live', 'pending'])
    .relatedTo(filter)
    .limit(limit)
    .all()
%}

<div class="z-10 -m-25">

    {% for entry in entries %}
        {% include
            '/_shared/components/news/item' with {
                'hasImages': item.hasImages,
                'hasTime': item.hasTime
            }
        %}
    {% endfor %}

    {% if item.isGrid %}
        <div class="button-container flex justify-center width-full">
            <a
                href="#"
                id="load-more"
            >
                Load more
            </a>
        </div>
    {% endif %}
</div>
```

**Comment by bencroker** [comment]
The error message already explains the issue. As per the [docs](https://putyourlightson.com/plugins/sprig#component-variables):

> Only values that can be passed over HTTP requests may be used (strings, numbers and booleans). Arrays and elements cannot be used (use comma-separated strings and IDs instead).

So you'll need to pass in the ID of the item and then refetch it within the component.

**Comment by nfq** [comment]
Thanks for this. Honestly though, I'm not sure how to get the ID of the item. I tried `item.id` without success.

**Comment by bencroker** [comment]
I'm pretty sure that putting a Sprig component inside a `for` loop is _not_ what you should be doing. I'd suggest trying to achieve the same result with a single component as is done with most of the sample components at https://putyourlightson.com/sprig/videos

**Comment by nfq** [comment]
@bencroker I'm confused. This is how the content builder works (has worked for a couple of years now). How would you suggest refactor this particular part to work with the a sprig component?

**Comment by bencroker** [comment]
A Sprig component is not the same as an include, that is the underlying reason you are getting an error when swapping one in for the other. I don't have the big picture of what you are doing, but I would suggest you try to group of all of the reactive elements on the page into a single Sprig component, similar to how it is done in Sprigboard.

**Comment by nfq** [comment]
@bencroker I get the gist in essence, but I'm still unsure how to include a sprig component in a Neo block. I think that's essentially the part I'm stumbling on.

**Comment by bencroker** [comment]
I personally don't use the Neo plugin so can't help you out here. Perhaps asking in discord will get you some hints.
