### ISSUE TITLE
Weird escape on variables that contains apostrophe

### ISSUE THREAD

**Issue by billmn** [putyourlightson/craft-sprig#133]
Hi guys,
I noticed that within a Sprig component, variables containing the apostrophe are "escaped".

I wrote a simple example that highlights the escape difference between Twig and Sprig:

**Create a `test.twig` file whit this code:**
```twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>

    <body>
        <main class="h-screen flex items-center justify-center space-x-6">
            <div class="border-2 border-blue-500 p-6">
                {% set test = "Sprig's test" %}

                <div class="text-xl mb-6">Outside Sprig component</div>

                <input type="text" value="{{ test }}" class="block border p-3">
                <input type="text" value="{{ "Sprig's test" }}" class="block border p-3">
            </div>

            <div class="border-2 border-yellow-500 p-6">
                <div class="text-xl mb-6">Inside Sprig component</div>

                {{ sprig('testComponent') }}
            </div>
        </main>

        {{ sprig.script }}
    </body>
</html>
```

**Create a `testComponent.twig` file whit this code:**
```twig
{% set test = "Sprig's test" %}

<input type="text" value="{{ test }}" class="block border p-3">
<input type="text" value="{{ "Sprig's test" }}" class="block border p-3">
```

***

Now if you load the `test.twig` template in the browser (e.g. http://domain/test) you will see this:
![Schermata 2021-05-13 alle 13 19 06](https://user-images.githubusercontent.com/779534/118118868-d0678b80-b3ed-11eb-941a-9910d7130a2a.png)

The problem seems to be this escape:
![Schermata 2021-05-13 alle 13 21 07](https://user-images.githubusercontent.com/779534/118119267-63082a80-b3ee-11eb-8bc8-fc17401a5aa8.png)

***

### Versions
- Plugin version: Tested on 1.4.0 and 1.5.2
- Craft version: 3.6.13

**Comment by bencroker** [comment]
This is Twig's autoescaping at play, which is enabled by default: 
https://twig.symfony.com/doc/3.x/templates.html#html-escaping

So nothing to do with Sprig. You can disable escaping using the [raw](https://twig.symfony.com/doc/3.x/filters/raw.html) filter, but you need to be very careful when doing this, otherwise you may be adding vulnerabilities to your code.

```twig
{{ "Sprig's test"|raw }}
```

**Comment by billmn** [comment]
Thank you @bencroker

Twig escape the `Sprig's test` string to `Sprig&#039;s test` but using Sprig was escaped to `Sprig&amp;#039;s test`. So it appears to be **double escaped**.

Does Sprig escape when rendering the template?
I spotted this problem while making a CRUD using Sprig.

**Comment by bencroker** [comment]
I'm not seeing this in the Sprig playground.

<img width="1185" alt="Screenshot 2021-05-13 at 13 27 11" src="https://user-images.githubusercontent.com/57572400/118125551-71a70f80-b3f7-11eb-817b-aa95451ab979.png">

**Comment by billmn** [comment]
I have not even seen it in the Playground.
In templates, if I use Twig (even with include) works fine, but using `{{ sprig('...') }}` it seems to be double escaped.

Using Twig `{% include %}` with the same code of the Sprig component the value is not double escaped.

**Comment by billmn** [comment]
@bencroker The problem seems to be in the `parseHtml` method, more specifically on line 225: 
https://github.com/putyourlightson/craft-sprig/blob/54ab13b4b0432fec5266b8eb3e0cd19ced84f116/src/services/ComponentsService.php#L218-L227

I tried to exclude the "value" attribute and the double escape problem was solved:
```php
// ...

foreach ($attributes as $attribute => $value) {
    if ($attribute !== 'value') {
        $element->setAttribute($attribute, $value);
    }
}
```

**Comment by bencroker** [comment]
Yes I'm also debugging that code right now. You're right that there is some double escaping going on, reopening this issue.

**Comment by bencroker** [comment]
So it seems that when the DOM is being converted back to HTML, the content is passed through `htmlentities`, resulting in a double encoding. I believe the safest way to deal with this is to reverse it, rather than trying to prevent it and possibly leaving untrusted input unencoded.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-sprig/commit/44f140321bc7401cf72ba2c1dcc1720d96baaf28 for the next release.

**Comment by billmn** [comment]
@bencroker Great! Thank you 🚀
