### ISSUE TITLE
Sprig Playground - Using multiple component variables not working

### ISSUE THREAD

**Issue by jayhlee** [putyourlightson/craft-sprig#135]
### Describe the bug
When using Sprig Playground, using more than one component variable throws an error stating that the variable doesn't exist. Using just one variable works properly. But any subsequent variable throws the error.

### To reproduce
Steps to reproduce the behaviour:
1. In Sprig Playground, create a component with more than one variable.
2. Define the variables in the "Component Variables" input field. 
3. Click "Create"
4. See error message "Variable "limit" does not exist at line 1."

### Screenshots
![sprig](https://user-images.githubusercontent.com/25807445/118696914-a0403400-b7c3-11eb-8863-20bb14852673.png)

### Versions
- Plugin version: 1.5.2
- Craft version: 3.6.14

**Comment by bencroker** [comment]
The variables should be separated by an ampersand (`&`).
