### ISSUE TITLE
Regenerate CSRF token when user password changed

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-sprig#136]
When a logged-in user's password changes, the CSRF token becomes invalid since it is generated from their old password.
https://github.com/craftcms/cms/blob/eceeec0ae98e40513284fc7d8be87e4cecabd576/src/web/Request.php#L1348-L1356

Sprig should regenerate the CSRF token if it detects a user's password has just changed.

**Comment by philipboomy** [comment]
I just want to mention that other Sprig components on the page will also fail unless the CSRF is regenerated for those as well.

**Comment by bencroker** [comment]
Good point, thanks for the note!

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-sprig/commit/765ff12318ce6949b6ad64f0b56693856735be74. Would be great if you could test in your setup.

**Comment by philipboomy** [comment]
Password change works on second try meaning csrf is regenerated. I guess its up to user to refresh other components on the page.

**Comment by bencroker** [comment]
Yes, I guess it will have to be.

**Comment by bencroker** [comment]
Released in 1.6.0.
