### ISSUE TITLE
Using load more with Calendarize

### ISSUE THREAD

**Issue by leightonhughes** [putyourlightson/craft-sprig#138]
### Question
I'm trying to incorporate the load more component with a calendarize query but having an issue outputting the entries. I have the error "Impossible to invoke a method ("all") on an array."
What modification do I need to make the example work with calendarize regarding the array?

### Additional context

[Calendarize usage](https://unionco.github.io/craft-plugin-docs/calendarize/#other-examples)

{% set entryQuery = craft.calendarize.after(eventDate, { section: 'events', limit: limit, offset: offset }) %}
{% set entries = entryQuery %}

If I remove the .all as an array is returns the first few entries but the view more button does not know that there are more entries to load.

**Comment by bencroker** [comment]
What exactly is your question?

**Comment by leightonhughes** [comment]
> What exactly is your question?

Haha, sorry about that. Just updated :)

**Comment by bencroker** [comment]
Since you don't have an element query to work with, you may need to output the load more button every time, regardless of whether there are more results left or not.

```twig
<button sprig s-val:offset="{{ offset + limit }}" s-target="this" s-swap="outerHTML">Load more</button>
```
