### ISSUE TITLE
Live search, s-replace: div results is not replaced correctly

### ISSUE THREAD

**Issue by palomamtnez** [putyourlightson/craft-sprig#139]
### Question
I have included a sprig component to my site:

```
{{ sprig('_partials/search-query', {
            query: craft.app.request.getParam('query')}) 
}}
```

And in my `_partials/search-query` file, I have:

```
{% if sprig.isInclude %}
    {% set query = query ?? '' %}

    <input sprig s-trigger="keyup changed delay:200ms" s-replace="#result" type="text" name="query" value="{{ query }}">

    <div id="result">
        {% if query %}
            {% set entries = craft.entries().search(query).orderBy('score').all() %}
            {% for entry in entries %}
                {{ entry.title }}
            {% endfor %}
        {% endif %}
    </div>

{% endif %}
```

So when I test this, it triggers the sprig search function (ajax):

URL : 
http://mysite.test/index.php?p=actions/sprig/components/render&query=test&sprig%3AsiteId=3efdba262d9eeb8df219de7ad3f88f764a1b121279be29c506693f28c98ca41f3&sprig%3Atemplate=2da19ff12bba17c7ad759e55f1ac15e08d93a0626c3d3a9258ead498e81aae6e_partials%2Fsearch-query&sprig%3Avariables%5Bquery%5D=dfaafcea991bb3710a99f62d0a7d54a8fd3ededca5625c840de62d0309bc4634

 And I get nothing on the response.
 
 I saw that the expected result, [as in the demo](https://putyourlightson.com/sprig/demo/2), should be something like:
 
```
 
<p>
    <input sprig="" s-trigger="keyup changed delay:300ms" s-replace="#results" type="text" name="query" value="s" autocomplete="off" placeholder="Search" hx-get="https://putyourlightson.com/index.php?p=actions/sprig/components/render" hx-trigger="keyup changed delay:300ms" hx-select="#results" hx-target="#results" hx-swap="outerHTML">
</p>

<div id="results">
            
                    <p>Sprig</p>
                    <p>Snaptcha</p>
                    <p>Sherlock</p>
                    <p>Plugin Sales</p>
                    <p>Amazon SES</p>
                    <p>CP Style Guide</p>
                    <p>Sendgrid</p>
                    <p>Sitemap</p>
            </div>

```

But instead, I'm getting nothing (not even the `<div id="results"></div>` with empty results).

Am I doing something wrong? 

### Additional context
Sprig version: 1.6.0

Craft CMS version: 3.6.16

**Comment by bencroker** [comment]
By wrapping your entire component in `{% if sprig.isInclude %}...{% endif %}`, you are saying that the contents should only be output when the component is included in its parent template and not in AJAX requests.

I suggest you start out with the sample live search component at https://putyourlightson.com/sprig/cookbook#search and tweak as necessary from there.
