### ISSUE TITLE
Help: Pagination with sorting, possible?

### ISSUE THREAD

**Issue by tom-byrom** [putyourlightson/craft-sprig#14]
Hi,

Im using your pagination example which works, do you have an pagination example where it includes basic sorting as well?

I have an issue where  each time you change the sorting via the select, it just reverts everything on the next instance of Sprig meaning sorting is reset and nothing actually happens.

How would I keep the selects selected `value` and `s-push-url` set to the correct select option each time its updated? Instead of just clearing it.

My JS adds the correct sorting value to the `s-push-url`, I see this via dev tools but then it immediately disappears as Sprig re-renders and it's not actually registered so no sorting happens, it doesn't actually update the URL param

```
// SORTING OPTIONS
{% set sortOptions = [
     {
        label: 'New - Old',
        value: 'postDate desc'
    },
    {
        label: 'Old - New',
        value: 'postDate asc'
    },
    {
        label: 'Name Z - A',
        value: 'title desc'
    },
    {
        label: 'Name A - Z',
        value: 'title asc'
    },
] %}

{% set selectedSortOption = craft.request.getParam('order', 'postDate desc') %}


// SORTING SELECT
<select sprig s-push-url=""  class="sort-web w-select" data-name="Sort" id="sortQuery" name="Sort">
    {% for sortOption in sortOptions %}
        <option value="{{ sortOption.value }}" {{ sortOption.value == selectedSortOption ? 'selected' }}>
            {{ sortOption.label }}
        </option>
    {% endfor %}
</select>

```

JS
```
var sortValue
var sortInput = document.getElementById("sortQuery")
sortInput.addEventListener("change", sort);
function sort() {
  sortValue = '?order='+sortInput.value;
  sortInput.setAttribute("s-push-url", sortValue);
}
```

**Comment by putyourlightson** [comment]
Happy to help but can you please clarify what exactly your question is and provide only stripped down versions of code instead of large amounts of mark-up?

**Comment by bencroker** [comment]
Happy to help but can you please clarify what exactly your question is and provide only stripped down versions of code instead of large amounts of mark-up?

**Comment by tom-byrom** [comment]
Fair one @bencroker probably out of my depth to be honest anyway - tried to update the question. I'm not sure if I explain it correct but really I just want o be able to add some basic sorting to your Pagination example recipe and for the sorting and pagination to work together....

**Comment by bencroker** [comment]
Let's start by getting the sort functionality working, can you test the following?

```twig
{% set sort = sort ?? null %}
...
{% set query = craft.entries.orderBy(sort).offset(offset).limit(limit) %}
{% set entries = query.all() %}
...
<select sprig name="sort">
    {% for sortOption in sortOptions %}
        <option value="{{ sortOption.value }}" {{ sortOption.value == selectedSortOption ? 'selected' }}>
            {{ sortOption.label }}
        </option>
    {% endfor %}
</select>
```

**Comment by tom-byrom** [comment]
Great thanks @bencroker yes that works so far, so when selecting an option in the dropdown it does sort data. The actual dropdown select always has the same label - but the data being sorted. And I can't sort by the first option. See end of GIF

Reference
![ezgif-7-46d7a82a8ce3](https://user-images.githubusercontent.com/34626292/89188245-4e148600-d596-11ea-83b4-dd88c7f21966.gif)

**Comment by bencroker** [comment]
So this is basic Twig logic now, since we're using the variable name `sort`, you'll need to check against that:

```twig
<select sprig name="sort">
    {% for sortOption in sortOptions %}
        <option value="{{ sortOption.value }}" {{ sortOption.value == sort ? 'selected' }}>
            {{ sortOption.label }}
        </option>
    {% endfor %}
</select>
```

**Comment by tom-byrom** [comment]
Missed that one cheers - Overall it look's like I've tried to over complicate things and I didn't even need any JS.... This is awesome - I'll spend some time wrapping my head around the changes you've given me.

It all works and with the pagination.

One small thing which I can live with if not possible - when you're on say page 4 of your paginated results and then you change the sorting, is there anyway to reset the URL param. I mean the minute you paginate next or previous it sorts it self out anyway so no drama if not.

Really appreciate the help mate, using Sprig in a few places now and its a good start to getting into reactive components.

**Comment by bencroker** [comment]
This should sort out the URL:

```twig
<select sprig s-push-url="your-page-url" name="sort">
```

**Comment by tom-byrom** [comment]
Boom cheers
