### ISSUE TITLE
Show input fields based on Quantity

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#141]
### Question
I want to collect guest's names based on the number of tickets selected. I have this working ok when there is only one ticket available, but (using Commerce product variants) if I have more than one I'm struggling to get it to work.

```
{% set qty = 'purchasables[' ~ loop.index ~ '][qty]' ? 1 %}
{% set guests = range(0, qty - 1)|map(i => ['']) %}
<div>
    <label>Quantity</label>
    <select sprig name="purchasables[{{ loop.index }}][qty]">
        {% for i in range(1, 5) %}
            <option value="{{ i }}" s-val:qty="{{ i }}" {{ qty == i ? 'selected' }}>{{ i }}</option>
        {% endfor %}
    </select>
</div>

<div>
    {% for guest in guests %}
    {# input name untested and likely incorrect #}
        <input type="text" name="purchasables[{{ purchasable.id }}][options][guests[' ~ loop.index0 ~ '][0]]'">
    {% endfor %}
</div>
```

Hopefully just missing something basic, and would appreciate any help 🙏🏻

**Comment by bencroker** [comment]
It looks like you should be getting the quantity from the `purchasables` variable rather than a string.

```twig
{% set qty = purchasables[loop.index][qty] ?? 1 %}
```

This of course assumes that we're already inside a loop.
