### ISSUE TITLE
Is it possible to search by the content of the entries rather than the title?

### ISSUE THREAD

**Issue by Radu033** [putyourlightson/craft-sprig#142]
I'm using Sprig for searching on my website, but it searches only based on the title. 
I have a "content" block and it has the "Use this field’s values as search keywords" enabled, however if I try to search its content using sprig, no results are being displayed. 

This is my search query:           `  {% set entries = craft.entries().search(query).orderBy('score').all() %}`

**Comment by bencroker** [comment]
This is not Sprig specific but a general Craft question. My suggestion would be to test with a plaintext field and then work your way up from there.
