### ISSUE TITLE
Get url based on last segment after a refresh

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-sprig#146]
### Question
I am trying to get the last part of a URL in sprig.
So this example URL - https://localdomain.loc/vehicles/bmw/
I want to get the last part as this relates to the brand.

On the first load this works fine as follows:
```twig
{% set vehicleBrandSlug = craft.request.getLastSegment() %}
{% set vehicleBrandQueryString = craft.entries.section('vehicleBrands').slug(vehicleBrandSlug).one().id() %}
```

However, after selecting a model on the dropdown and updating the sprig component this breaks as the URL passed in looks like this.
`https://pcdparts.loc/index.php/actions/sprig/components/render/?vehicleModel=5821&search=&vehicleBrand=1817&limit=25&sort=title%20ASC&sprig%3AsiteId=0e814a228a1930994d2ac540eaaed3c3914fb1a7346888b6de4fadf6f2b8ec882&sprig%3Atemplate=ab2609d00b638acec509c8b612aadf68b89b816417e844ec0812a01e54021ae3_includes%2Fsprig%2Fvehicles%2Fvehicle-board-brand.twig`

The variable I am setting for `vehicleBrandSlug` changes  from 'bmw' to 'render'

I have tried to wrap the initial statement inside `{% if not sprig.isRequest %}` but to no avail.

How can I get and fix the vehicleBrandSlug based on the URL so that this remains even after re-rending and changing the model dropdown etc.

Here are some screenshots for context.

**First Load**
<img width="1663" alt="Screenshot 2021-08-26 at 19 16 59" src="https://user-images.githubusercontent.com/5698596/131015062-0b8ab564-e4a3-42ba-b539-a80e9c784eed.png">

**After a Refresh**
<img width="1638" alt="Screenshot 2021-08-26 at 19 17 47" src="https://user-images.githubusercontent.com/5698596/131015119-532bcbc7-ac05-4c31-baef-a845710e055c.png">

_Notice the model box is gone and the brand is no longer set_

**Comment by bencroker** [comment]
Passing the brand into the Sprig component would simplify this significantly and hopefully solve this for you.

```twig
{{ sprig('my-component', { vehicleBrandSlug: craft.request.getLastSegment() }) }}
```

**Comment by terryupton** [comment]
Excellent. Thanks Ben.
