### ISSUE TITLE
hash_hmac() error when using Fetch plugin

### ISSUE THREAD

**Issue by jlabs** [putyourlightson/craft-sprig#15]
From what I can tell so far, using the Fetch plugin inside a component template produces the following error:
`hash_hmac() expects parameter 2 to be string, array given` in "vendor/yiisoft/yii2/base/Security2.php"
Moving the Fetch line out of the component template and into the page template fixes the error, but I'm trying to load data from an external API after the page has loaded.

**Comment by bencroker** [comment]
Can you show a stripped down version of your component code?

**Comment by jlabs** [comment]
Component code is just `{% set request = fetch(client, 'get', destination, options, 'xml') %}`  
If I do a `{% dd(request) %}` then I get the result, but taking that line out I get the previously mentioned error. Removing the 2 Sprig lines from the page template: 
`{{ sprig('_components/accommodation-results', { client: client, destination: destination, options: options }) }}
{{ sprig.script }}`
The page loads fine.

**Comment by bencroker** [comment]
As per the [docs](https://putyourlightson.com/plugins/sprig#variables):

> Only values that can be passed over HTTP requests may be used (strings, numbers, booleans).

So you should define the client, destination and options in the component if possible, otherwise as strings.

**Comment by jlabs** [comment]
Would help if I read all the docs!
I went straight to the cookbook and build up from there.
