### ISSUE TITLE
Problems with table field adding/removing rows.

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-sprig#150]
### Question
I've been following the Building a multi-row table field video on CraftQuest, and Ive hit a stumbling point with adding/removing rows. 

Here's the example code that I'm using (simplified down to test)

```twig
{% set rows = currentUser.testTable %}

    <form sprig s-method="post" s-action="users/save-user">

        {{ hiddenInput('userId', currentUser.id) }}

        {% set rows = rows ?? [['','']] %}
        {% if addRow is defined %}
            {% set rows = rows|merge([['','']]) %}
        {% elseif removeRow is defined %}
            {% set rows = rows|filter((val, key) => removeRow != key) %}
        {% endif %}

        {% for key, row in rows %}

            <textarea style="width:100%;" name="fields[testTable][ {{ loop.index0 }} ][col1]">{{ row.col1 ?? '' }}</textarea>

            {% if currentUser.hasErrors('testTable') %}
                <p>{{ currentUser.getFirstError('testTable')}}</p>
            {% endif %}

            {% if rows|length > 1 %}
                <button sprig s-val:remove-row="{{ loop.index0 }}" type="button">{{ 'Delete'|t }}</button>
            {% endif %}

        {% endfor %}

        <p><button sprig s-val:add-row="1" type="button">+ Add row</button></p>

        <input class="btn" type="submit" value="save">

    </form>
```

This seems to work when I perform one action and save. i.e  I add one row and save. Remove a row and save. 

If I try removing two rows, values get populated in wrong rows. It also won't let me add tow empty rows? Am I missing something obvious?

**Comment by bencroker** [comment]
I believe your columns should be zero indexed:

```twig
<textarea style="width:100%;" name="fields[testTable][ {{ loop.index0 }} ][0]">{{ row[0] ?? '' }}</textarea>
```

Also, the code `[['', '']]` indicates that your table field has two rows, but you only appear to be using one.

**Comment by shornuk** [comment]
I tried as per your example above previously (replacing `[col1]` with `[0]`) but when I do that, no values are getting saved. It always saves as an empty value?

> Also, the code [['', '']] indicates that your table field has two rows, but you only appear to be using one.

Yes, I've updated now that now. Missed that. However still get the same behaviour.

**Comment by bencroker** [comment]
Ah yes, you're right, the column name does indeed need to be `col1`. Updating the default row in your code should work.

```twig
        {% set rows = rows ?? [{col1: ''}] %}
        {% if addRow is defined %}
            {% set rows = rows|merge([{col1: ''}]) %}
        {% elseif removeRow is defined %}
            {% set rows = rows|filter((val, key) => removeRow != key) %}
        {% endif %}
```

**Comment by bencroker** [comment]
I also added this component as a [Sprig recipe](https://putyourlightson.com/sprig/cookbook#multi-row-table-field).

**Comment by shornuk** [comment]
That's great. Although this is still not working for me. Still getting the same behaviour. 

I'll get an example up and send it over to you 👍

**Comment by bencroker** [comment]
Be sure to use `col1` as the key, as per your original code sample.

**Comment by shornuk** [comment]
OK, here's the exact code I'm working with (this is inside my sprig component)...

```twig
{% set rows = currentUser.testTable %}

<div id="results" class="bg-sage-100 p-4 mb-12">
    {% if rows|length %}
        <ul class="list-inside list-disc">
            {% for row in rows %}
                <li>{{ loop.index }} - {{ row.text }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="py-4">No info</p>
    {% endif %}
</div>

<form sprig s-method="post" s-action="users/save-user">

    {{ hiddenInput('userId', currentUser.id) }}

    {% set defaultRow = {col1: ''} %}
    {% set rows = rows ?? [defaultRow] %}
    {% if addRow is defined %}
        {% set rows = rows|merge([defaultRow]) %}
    {% elseif removeRow is defined %}
        {% set rows = rows|filter((val, key) => removeRow != key) %}
    {% endif %}

    {% for row in rows %}
      <div class="flex items-center mb-6 space-x-2">
        <input class="bg-green-100 py-2 px-4 rounded-lg" name="fields[testTable][{{ loop.index0 }}][col1]" value="{{ row.col1 ?? '' }}" placeholder="Col1">

        {% if rows|length > 1 %}
          <a sprig s-val:remove-row="{{ loop.index0 }}" href="#" title="Remove row">
            <svg class="w-4 h-4" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 000 2h6a1 1 0 100-2H7z" />
            </svg>
          </a>
        {% endif %}
      </div>
    {% endfor %}

    <div class="mb-12">
        <button class="btn btn-green" sprig s-val:add-row="1">Add a row</button>
    </div>

    <input class="btn btn-rust" type="submit" value="Save">

</form>
```

If you visit [here](https://walkiees.co.uk/tables) you'll be able to see the table. (You'll need to log in, but I think you already have an account @bencroker - registered with a gmail address 👍 )

**Comment by bencroker** [comment]
Is your custom field handle in the CMS set to `rows`? Because that is what your code would suggest...

```
name="fields[rows][{{ loop.index0 }}][col1]"
```

**Comment by shornuk** [comment]
Yea, typo there, have updated now. To demo what's not working...

Click +row button twice. Only adds one row.

Add three rows by adding a row and save, add another and save etc. 

Then remove the last row, then remove the next one, the value changes.

**Comment by bencroker** [comment]
Can you show me via video or ideally a URL I can see this happening at?

**Comment by shornuk** [comment]
Here's a vid. https://cln.sh/iBkRI1

Url to test is linked above

> If you visit here you'll be able to see the table. (You'll need to log in, but I think you already have an account @bencroker - registered with a gmail address 👍 )

**Comment by bencroker** [comment]
My guess is that you haven't followed the recipe exactly: https://putyourlightson.com/sprig/cookbook#multi-row-table-field

For example, one thing I notice is your `rows` value is incorrectly set:

```
Yours:
{% set rows = rows ?? [defaultRow] %}

The recipe:
{% set rows = fields.rows ?? [defaultRow] %}
```

If the issue persists then please start with the recipe and work up from there.

**Comment by shornuk** [comment]
Maybe I was misunderstanding. In the recipe I was assuming that `fields.rows` is the table field ?

I set it to `rows` as I had already set it above to the table field

```
{% set rows = currentUser.testTable %}
``` 

Updating it to the following...

```
{% set rows = fields.testTable ?? [defaultRow] %}
```
...has fixed it 👍 

Thanks for taking a look, your help is much appreciated.
