### ISSUE TITLE
Sprig component with multiple request only allowing one without refreshing the browser

### ISSUE THREAD

**Issue by ConversioniaDev** [putyourlightson/craft-sprig#151]
### Question
How do I have multiple Sprig request in the same component?

### Additional context
I've created a search component that returns table rows in the results. Each row has two entry forms using Sprig that are visible by clicking a button within the row and displaying a modal. The issue is that I can only render one Sprig request without having to do a refresh. I've also noticed that I'm having the same issue with pagination. I have four Sprig functions including search, two entry forms, and pagination.

### Sprig Component

```twig
{% set entry = entry ?? create('craft\\elements\\Entry') %}
<div class="row">
    <div class="col-12 p-4">
        <div class="d-flex flex-row mx-4 my-3">
            {# Search field using Sprig with reactive search #}
            <div class="col-sm-12 col-md-4 col-lg-3 ms-auto">
                {# Sets to a default value if not defined #}
                {% set search = search ?? '' %}
                {% set jobQuery = craft.entries()
                    .section('jobs')
                    .search(search)
                %}
                <div class="">
                    <input sprig s-trigger="keyup changed delay:300ms" s-replace="#board" id="search" class="form-control" type="text" name="search" value="{{ search }}" autocomplete="off" placeholder="Search...">
                </div>
            </div>
        </div>

        <div id="board" class="row mx-4">
            <table id="jobSync" class="table table-dark table-striped table-bordered table-hover">
                <thead class="table-dark">
                <tr>
                    <th data-field="Verified Edit" scope="col">Verified</th>
                    <th data-field="Edit" scope="col">Edit</th>
                </tr>
                </thead>
                <tbody>
                {% set page = page ?? 1 %}
                {% set entryQuery = clone(jobQuery).orderBy('dateUpdated DESC').status(['live','disabled']).limit(limit) %}
                {# Paginates the entry query given the current page #}
                {% set pageInfo = sprig.paginate(entryQuery, page) %}
                {% set entries = pageInfo.pageResults %}

                {% for entry in entries %}
                    {% set rel = entry.defaultJobDescription.one() %}
                    {% set sectionId = craft.app.sections.getSectionByHandle('jobs') %}
                    {% set jobIdEdit = entry.Id %}
                    <tr id="jobRow">
                        <td class="text-center">
                                <form sprig s-action="entries/save-entry" s-method="post" class="form" accept-charset="UTF-8">
                                    {{ hiddenInput('sectionId', '3') }}
                                    {{ hiddenInput('entryId', entry.Id) }}
                                    {{ hiddenInput('fields[verifiedEdit]', '') }}
                                    {{ tag('input', {
                                        id: 'verifiedEdit',
                                        name: 'fields[verifiedEdit]',
                                        value: '1',
                                        checked: (entry.verifiedEdit ?? false) ? true : false,
                                        hidden: 'true'
                                    }) }}
                                    <div class="form-group">
                                        <button class="btn btn-danger btn-sm" type="submit">Verify</button>
                                    </div>
                                </form>
                                {{ _self.errorList(entry.getErrors('fields[verifiedEdit]')) }}
                        </td>
                        <td><button onclick="document.getElementById('jobEdit{{ entry.Id }}').style.display='block'" class="w3-button w3-black-outline">Edit</button></td>

                        {# Edit Form Modals #}
                        {% include '_partials/entryeditmodal' %}
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            {% if entries %}
                {% if page > 1 %}
                    {# Decrements `page` by 1 and pushes the new value into the URL on click #}
                    <button sprig s-val:page="{{ page - 1 }}" s-push-url="?page={{ page - 1 }}">
                        Previous
                    </button>
                {% endif %}
                {% if page < pageInfo.totalPages %}
                    {# Increments `page` by 1 and pushes the new value into the URL on click #}
                    <button sprig s-val:page="{{ page + 1 }}" s-push-url="?page={{ page + 1 }}">
                        Next
                    </button>
                {% endif %}
                <p>
                    <em>
                        Showing {{ pageInfo.first }}-{{ pageInfo.last }}
                        of {{ pageInfo.total }} entries.
                    </em><br>
                    <em>Page {{ pageInfo.currentPage }} of {{ pageInfo.totalPages }} pages.</em><br>
                    {% for i in 1..pageInfo.totalPages %}
                        {% if i == page %}
                            {{ i }}
                        {% else %}
                            {# Refreshes the component and pushes the new value into the URL #}
                            <a sprig s-val:page="{{ i }}" s-push-url="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </div>
</div>
```

### Modal Include with entry form using Sprig

```
<div id="jobEdit{{ entry.Id }}" class="w3-modal">
    <div class="w3-modal-content w3-animate-bottom w3-card-4 w3-round w3-padding-medium w3-padding-10">
        <header class="w3-container">
            <span onclick="document.getElementById('jobEdit{{ entry.Id }}').style.display='none'" class="w3-button w3-display-topright">&times;</span>
        </header>
        <div class="w3-container">
            <form sprig s-method="post" s-action="entries/save-entry" class="form" accept-charset="UTF-8">
                {{ hiddenInput('sectionId', '3') }}
                {{ hiddenInput('enabled', '1') }}
                {{ hiddenInput('entryId', entry.Id) }}
                
                {# Form Fields are here #}
                
                <button class="w3-button w3-round-large w3-margin-bottom w3-block w3-blue" type="submit"><i class="bi bi-save"></i> SAVE UPDATE</button
            </form>
        </div>
    </div>
</div>
```

**Comment by bencroker** [comment]
Can you explain what the issue/problem is? How can I replicate it and what errors are you noticing?

**Comment by ConversioniaDev** [comment]
I'm not seeing any errors logged. The issue is that the form in the modal causes Sprig to no longer work after submitting. The search and pagination as well as the "verifiedEdit" form no reacts to changes. Nothing is logged in the dev console's network tab when I try to submit a second entry form.

It acts like Sprig is disabled until I perform a browser refresh. I've tried removing each field in the form to find if one of them is causing the issue but no luck. I've also put the form directly in the component without using the include and that had no effect as well.

The crazy part is that the "verifiedEdit" form does not cause the issue. I have no idea why one would only work once and break Sprig and the other doesn't cause any issues. Both are build the same other than different input fields.

**Comment by ConversioniaDev** [comment]
Actually, anything using Sprig (search, verifiedEdit form, or pagination) causes the jobEdit form to no longer function too. So basically any Sprig action causes the jobEdit form to no longer work.

**Comment by bencroker** [comment]
Please define "no longer function" in this case – are you seeing an error or what happens? And what happens if you get rid of the modal and put the form inline, does it work then?

**Comment by ConversioniaDev** [comment]
No longer function meaning nothing happens when the submit button is clicked. Nothing is logged in the dev console either. No errors. The form acts as if it no longer has an action on submit.

Including the form inline doesn't make a difference. I get the same result.

**Comment by ConversioniaDev** [comment]
I just noticed that the </form> tag is getting moved above the form fields and submit button when rendered. The tag is clearly after the submit in the code.

<img width="1518" alt="Screen Shot 2021-08-31 at 11 31 19 AM" src="https://user-images.githubusercontent.com/61750899/131541096-f3dc63b5-da5a-46a8-9b2c-e213b2023993.png">

**Comment by bencroker** [comment]
Can you ensure that your HTML is valid? I see an unclosed `button` element in your code above...

```html
<button class="w3-button w3-round-large w3-margin-bottom w3-block w3-blue" type="submit"><i class="bi bi-save"></i> SAVE UPDATE</button
```

**Comment by ConversioniaDev** [comment]
Yes, it's closed. I must have deleted it while downsizing the code to post the issue.

**Comment by ConversioniaDev** [comment]
Correction on the form being inline. I included just one form field and put it inline just like the "verifiedEdit" form and it worked. The modal is not using JS so that's not an issue. I was thinking removing the include when you asked earlier.

The modal is obviously needed to display the form due to the limited space ini the row.

I've tried the bootstrap modal and a pure css modal with the same result.


EDIT: I used the dev console to move the </form> tag after the button but it had no effect. I just closed the modal after clicking the submit button but the form did not actually submit.

**Comment by bencroker** [comment]
So with the form inline, it works? If yes, then the issue is likely to do with the JS being used to display it.

**Comment by ConversioniaDev** [comment]
No JS is used to display the modal. It's all CSS. It thought the same when I was using Bootstrap but I created it using just CSS to make sure the JS wasn't the issue. Also, the fact that any Sprig that runs rather it's the pagination or search causes the form in the modal to no longer submit.

I removed all JS from the template to ensure it wasn't causing the issue and got the same result.

EDIT: I do have inline JS on the button that opens the modal. I would think if JS was the issue then it would not work on the first time I submit the form and performing a Sprig function would not cause the form to stop working.

**Comment by bencroker** [comment]
You didn't answer my last question and there is too much custom code in your example for me to replicate locally. Can you provide a simple code sample that I can test with, or alternatively a URL to page I can visit?

**Comment by ConversioniaDev** [comment]
Yes, it works inline. I'll put together a simple example and post it. I don't have a public version to provide you a url.

**Comment by bencroker** [comment]
Like I said, if it works inline then it must be an issue with your modal window. I would check if the modal markup stays inside the component or if is moved outside of it.

**Comment by ConversioniaDev** [comment]
Thanks for taking a look.
