### ISSUE TITLE
Refresh all components on a page

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-sprig#153]
### Situation
On a craft commerce page I list all products of a category.   
I have chosen to make every single product a component that can be added to the cart via sprig.   
When a product is added to the cart, its icon changes to reflect that it's already in the cart.  
No problem so far.  

At the end of the page I have a form where you can add ALL products from that category to the cart at once. 

### Question
After putting these items to the cart via the ALL products form, I update the mini cart to reflect the new number of items in the cart: 

	htmx.trigger(htmx.find('#mini-cart'), 'refresh');

No problem.  
But I still need to update all of the other components (products) to change their icon. Can I refresh all individual components at once? 
Something like: 

	htmx.trigger(htmx.find('.sprig-component'), 'refresh');

Does this even make sense performance wise, or would it be better to just refresh the page?  
Asking for a friend ;) 

### Additional context
All versions up to date

**Comment by bencroker** [comment]
It sounds like putting all products into a single component would simplify this for you and "just work". Otherwise your code above might work, but will trigger an individual AJAX request for every single product. The best thing to do is to just test out both approaches and see what you feel more comfortable with. Personally I lean on the side of simplicity (fewer components on the page) wherever possible.

**Comment by outline4** [comment]
I’ve tried to put the whole listing into one component. 
The disadvantage of this is, that when you try to add several products at once it will fail, since it has to re-render basically the whole listing for each product that you try to add. When each product of a listing is a component you can add multiple products as needed and the icons will get updated one after the other. 

I am still very new to sprig, and still don’t know what is best for me. 

Where can I ask more questions? 
I have a few questions but I am not sure where to ask? Btw. I am a sponsor, don’t even know if there’s a dedicated space for questions… 

Anyways. Twig makes me feel at least a +1 developer ;) 
Thanks

**Comment by bencroker** [comment]
In a production environment, the re-render should be fast enough (<200ms) to feel near-instantaneous, but you can also use an indicator to prevent adding new products until the re-render is complete (see the [indicator recipe](https://putyourlightson.com/sprig/cookbook#indicator)).

Feel free to open other issues with questions if you like.
