### ISSUE TITLE
Filter not working, when logged in

### ISSUE THREAD

**Issue by hhentschel** [putyourlightson/craft-sprig#154]
### Question
I made a sprig filter in a commerce setup, with some adjustments. 
(i filter different categories from different cat-groups) 
all working good,
but i noticed, that the filter does not work, when i am logged in in the backend.
then i get the following error in the console:

htmx.org@1.5.0:1 htmx:afterRequest

htmx.org@1.5.0:1 htmx:sendError

XHR failed loading: GET "https://terra-verde.ch.dali.sui-inter.net/index.php?p=actions/sprig/components/render&search=&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart&successMessage=aac9cc50b8b866f0366ea5ec0acedc9769adcc3d5a3a879cde495b9ae967383cArtikel%20Aceto%20Balsamico%20Modena%2C%20Oro%2C%20250ML%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=d486a9b1cf05859a5f3be3cf54b62f8b523e14e24a67e41c0ff5c42b2947a602Artikel%20Aceto%20Balsamico%20Modena%2C%20Argento%2C%20250ml%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=5dc8a1eb7537ac3582cae36b099e331618fed5fa25bce546ac1668edfaa5eccdArtikel%20Ketchup%20tradizionale%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=a44a08f573a5a05a9bd61ed83f758668801effdbbe299bd12377795acbafeb2dArtikel%20Balsamico%20bianco%20Condimento%20%22SUPERIORE%22%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=84b943a43e49d94ae861cc28cd13524c858c00949de061c6cc90a5302bfd82a6Artikel%20Riso%20Nerone%2C%20sottovuoto%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=757010a0eb308be01c4ebd89fb6b029cf9df6ef5c249cfa7a5172c7676c65677Artikel%20Salame%20di%20prosciutto%20Bio%20aus%20der%20Toscana%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=ca3763332d049eb1274052688215da236f7159fe017b3e9529dc34157338d0c8Artikel%20Sugo%20all%27arrabbiata%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=93089a4afec993feacedfec8efc7475726cee29fcd3ae43835cdd2967e04ce36Artikel%20Balsamico%20bianco%20Condimento%20Classico%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=c319a3e7a0f6ff1b68f7c499f5c5f12a9bd9a55b82791a16c172159338b016f1Artikel%20Funghi%20Porcini%20Secchi%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=fb1b4b1f9343fde38c03af296931b99ff46da846e541352f6d06452934a3e368Artikel%20Farina%20di%20Ceci%20italiano%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=5b31d4a74637f2c35afa261c8429f9540cb21a3dafc705ea8b28175068e9b7cdArtikel%20Olive%20Bella%20di%20Cerignola%20in%20Salamoia%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=d6cadadb6d78cb13465b7305d6a6d2dd6bfa138abc559fa08406f53a3ba1c5b4Artikel%20Olio%20d%27Oliva%20extra%20vergine%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=89c31c28581e3f88983720b2baa31a7d1cb4486389094261b00e99a5efe8592bArtikel%20Gallette%20di%20grano%20saraceno%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=cbfb7a0116f6fe362485a32b7478bc90722cc27ee6dde219c19090591bbe1729Artikel%20Nocciole%20ricoperte%20di%20cioccolato%20fondente%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=6cc169b9b849fab94aef78c4ee4db585e402655918de9e4b8b1cc54986b13237Artikel%20Passata%20di%20Pomodori%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&successMessage=a44a08f573a5a05a9bd61ed83f758668801effdbbe299bd12377795acbafeb2dArtikel%20Balsamico%20bianco%20Condimento%20%22SUPERIORE%22%20wurde%20zum%20Warenkorb%20hinzugef%C3%BCgt.&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&CRAFT_CSRF_TOKEN=knx_jPixcb4nJ4bBnxL2MO7eTK0a-qbaNPsynv1HG5gOah9j4EmDik0y-ZuXmNBctykTTKLrxhPvigdxE6xKFd3376vUHAAfxl6AvdbzNuzIo6s6kpME4_jjr9PXCLDC7NsqkaG1oBsd9PGulbJe6dAZXAvVKonkJB4y2QLGaOvsiN6XKcbbPIYiQm01zG9gffBqgoPUJOxbp-atXPfYTAXQxbmhXct2eLiIoIU87SPklyUui5xa343F7du9ANFiYL5Ucjhz2rrlSuOHtpzmx6BKTruOgibHc17Otq9ApkOo7CrgaczgjnqxfsqHJHjqSF9VFtl64NAxCsmto6_hboNIJnvDj6dx3rNlEnKZfXS7wIud4C9mfPM9tY21wA_Z-JqcDfelYdDM28zn4GuI8N2-HqnH1MR5LsbHn6LEbb6pTSVDohrbtFdYAL9PtV6tuMaU2328uF_0ZHcnQPVcAyeMW_6n5l3IapTC-xrBqi5D_pzdyjKDACHbwe_qZJ9oytBxffrLHZHa9L7v1FmAEwbIAiVgFLPYtSaW6eTsiYw%3D&purchasableId=13837&purchasableId=13835&purchasableId=12744&purchasableId=12808&purchasableId=12872&purchasableId=12938&purchasableId=12766&purchasableId=12830&purchasableId=12894&purchasableId=12960&purchasableId=12724&purchasableId=12788&purchasableId=12852&purchasableId=12918&purchasableId=12746&purchasableId=12810&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&qty=1&sprig%3AsiteId=9f4e768a9e819ecbde3087b117ea4bf514214365759ea705fecd505bb0daae001&sprig%3Atemplate=ccd44209767b6281615d1d8c51271e79542fa4022e52d3f45d46f57f0079151bsprig%2Fcomponents%2Ffilters%2F_components%2Ffilters".

htmx.org@1.5.0:1 Uncaught (in promise) undefined

as soon as i log out, the filter works again.

what i am doing wrong here?

**Comment by bencroker** [comment]
According to the URL, this request is updating the cart multiple times, so something must be wrong in your component.
```
&action=commerce%2Fcart%2Fupdate-cart&action=commerce%2Fcart%2Fupdate-cart...
```

**Comment by hhentschel** [comment]
I can't see the error.
here is my (reduced, normally i have 4 category groups) code.
a search field and one category group, with two categories, and pagination.

```
{% set search = search ?? '' %}

{% set articleCategoriesStatus = articleCategoriesStatus ?? [] %}

{% set limit = limit ?? 16 %}
{% set limitOptions = [16, 24, 48] %}

{% set page = page ?? 1 %}

{% set maxPages = 8 %}

{% if cart is not defined %}
  {% set cart = craft.commerce.carts.cart %}
{% endif %}

{% set catStatusOptions = craft.categories.group('catGroupStatus').all() %}

{% set filters = {
    articleCategoriesStatus: articleCategoriesStatus,
} %}

{% set productQuery = craft.products(filters|merge({
    search: search,
    limit: limit,
    with: [
        ['image', {
            withTransforms: ['productListing']
        }]
    ],
  }))
%}

{% if articleCategoriesStatus is not empty %}
    {% do productQuery.andRelatedTo(articleCategoriesStatus) %}
{% endif %}

{% set pageInfo = sprig.paginate(productQuery, page) %}

{% set products = pageInfo.pageResults %}

{% do sprig.pushUrl('?' ~ filters|merge({
    page: page,
})|url_encode) %}
```

**Comment by bencroker** [comment]
It's the form that appears to be the issue, not the filtering.

**Comment by hhentschel** [comment]
Yes. 
i use the basic craft commerce overview template, where you have the "add to cart" button right under each product image and title.  If i remove the `{{ csrfInput() }}` , then the filter also works for logged in users,
but i can't add a product to the cart, 400 error.

i added this from the craft info page, for removing the `{{ csrfInput() }}`:
```
<script type="text/javascript">
    window.csrfTokenName = "{{ craft.app.config.general.csrfTokenName|e('js') }}";
    window.csrfTokenValue = "{{ craft.app.request.csrfToken|e('js') }}";
</script>
```

but no luck, or do i have to alter this code?

i tried altering this code:
```
<form s-method="post" class="js-form">
           {{ actionInput('commerce/cart/update-cart') }}
```

to this, (got this from your page) 
`<form s-method="post" class="js-form" s-action="commerce/cart/update-cart">`

but also no luck.

what would you recommend for further try outs? 
thanks.

**Comment by bencroker** [comment]
Do you have multiple instances of the form in the component? If you can share a URL that I can see then I can take a closer look.

**Comment by hhentschel** [comment]
No, but i iterate over all products and they all have a form...
here is a link.
https://terra-verde.ch.dali.sui-inter.net/shop/produkte

there is the filter.

i've created a test user, so you can see it not working when logged in.
https://terra-verde.ch.dali.sui-inter.net/login
h21+test@pm.me
pswtest

**Comment by bencroker** [comment]
It looks like the Sprig request may be too large. Can you check the Craft logs for the exact error?

You should set up your forms to work with Sprig, which should also help reduce the request size.
```html
<form s-method="post" s-action="commerce/cart/update-cart" class="js-form">
```

**Comment by hhentschel** [comment]
i can't find anything in the web.log for the exact error.

i took the code above to alter the form tag, but does not change anything.

i can change the limit to only display 10 items, then it works.
everything above 10 breaks the filtering.

**Comment by bencroker** [comment]
In that case, it sounds like your component might need some rethinking.
