### ISSUE TITLE
Pagination Re-downloading All Images on Page Each Trigger

### ISSUE THREAD

**Issue by itsmattsoria** [putyourlightson/craft-sprig#156]
### Describe the bug
I'm using Sprig for pagination, using the [Pagination Recipe](https://putyourlightson.com/sprig/cookbook#pagination) from the Cookbook, and outside of the component, in the template the component is included in, there are a few images, and with the Network tab open in dev tools I noticed that every time I click through the pagination the browser re-downloads all of the images from the template (again, outside of the component) — images it downloaded on initial page load. It seems like this should definitely be avoided. Other assets like CSS and JS files are not being re-downloaded. After testing around a bit I realized that if I remove the `s-push-url` attribute from the buttons that updates the URL then the browser _doesn't_ download all of the images outside of the component, just the images _inside_ the component. This still seems less than ideal, but is there any way around it?

### To reproduce
Steps to reproduce the behaviour:
1. Create a component template and paste in the example component code exactly from [the pagination recipe](https://putyourlightson.com/sprig/cookbook#pagination).
2. Include that component in a template, and make sure `{{ sprig.script }}` is included somewhere in the template.
3. Make sure there is an image or two included somewhere else on the page.
4. Navigate to the page with the pagination component and pull up the Network tab in Dev Tools to monitor images downloaded.
5. Click through the pagination and note that all of the other images on the page downloaded on initial page load are re-downloaded every time you trigger a refresh of the component by clicking through the pagination.

### Expected behaviour
I would expect that images outside of the component would not need to be re-downloaded. It would be great if images included *in* the component were also not re-downloaded when the pagination landed on a page previously loaded as well, but that I would understand.

### Screenshots
[Screen Recording showing the behavior](https://share.mattsoria.com/Screen-Recording-2021-09-08-16-15-58/)

### Versions
- Plugin version: 1.8.1
- Craft version: 3.7.11

**Comment by bencroker** [comment]
Yes, I can also see this happening and it is far from ideal. Sounds like an issue with htmx so can you post an issue at https://github.com/bigskysoftware/htmx/issues and link to this one, ideally along with a CodePen or other publicly available URL that demonstrates this?

**Comment by itsmattsoria** [comment]
@bencroker thanks for taking a look! I've never used htmx alone so I may be missing something here but a quick test using just htmx to load another document in doesn't actually appear to have the same side effect of re-downloading images on the page. I set up a quick test: https://share.mattsoria.com/htmx-test.html

If you pull up the network tab and trigger htmx to load in the other test page the images are *not* re-downloaded. So I'm thinking either I am missing something with the test (very possible), or perhaps this issue is something Sprig-related?

**Comment by bencroker** [comment]
You're right about this example, but I believe this is still a htmx issue that is specific to a particular element structure – if you look at the recipe at https://putyourlightson.com/sprig/cookbook#pagination then you'll see that it does not happen there.

I'll need to dive deeper into this and will let yo know what I discover.

**Comment by itsmattsoria** [comment]
@bencroker oh man, I think this is a false alarm actually. Since you mentioned that it was **not** happening for the example on the cookbook I took a look and for me it actually **was** happening ([screen recording](https://share.mattsoria.com/Screen-Recording-2021-09-09-12-53-16/)), and then it occurred to me to try it out on other browsers, which I should have done to begin with. I was experiencing the issue in Brave, but then tested it in Safari, Firefox and Chrome (Canary) and none of those browsers were re-downloading the images, so it seems it's either a Brave AJAX issue or maybe an htmx + Brave issue. Either way, not here, but I appreciate you looking into it!

**Comment by bencroker** [comment]
Ok, well if it comes up again then let me know.
