### ISSUE TITLE
Running JS from component file

### ISSUE THREAD

**Issue by jlabs** [putyourlightson/craft-sprig#16]
Trying to run some JS (either using the Craft `{% js %}` tags or `{% do view.registerJsFile ... %}` and cannot get the Javascript to fire.
The Javascript code, currently, is just `console.log('hi');` which doesn't appear in the console.

**Comment by bencroker** [comment]
You cannot execute Javascript in AJAX responses as web browsers block this for security reasons. You should put any JS you need in the main template and listen for [htmx events](https://htmx.org/reference#events).

**Comment by jlabs** [comment]
Thanks - I will get the hang of this soon.
I don't think the JS can go in the main template as its counting elements when the compoenent has loaded (can take a few seconds sometimes).
Will look at the htmx events - thanks 👍

**Comment by bencroker** [comment]
If you listen for the `htmx:afterSettle` event, then the elements should already have been loaded into the DOM at that stage:
https://htmx.org/events/#htmx:afterSettle

**Comment by jlabs** [comment]
Thanks! I was just looking at afterRequest with the thought that the component is checking `if not sprig.request`
