### ISSUE TITLE
The importance of "name" value on input field

### ISSUE THREAD

**Issue by wallythewebdev** [putyourlightson/craft-sprig#160]
Hi Ben - 
First off, Sprig is amazing and the Docs are really well written and easy to follow - so thank you! 

I had a question about using **multiple sprig components on the same page**.

I have gotten this to work, but it would not do so until I had given each component a different name value of the input element.
I was operating under the assumption that the name value was optional i.e. name="query2" seen below:

`<input sprig s-trigger="keyup changed delay:300ms" s-replace="#results2" type="text" name="query2" value="{{ query2 }}">`

I didn't see this as a requirement so am making sure that my understanding of causation and correlation have not been skewed.

----------------------------------------

(the below is the full example of how I am using it, but might not be needed to answer the above - just better to give it to you off the bat)

-----------------------------------------

Full code below is very basic and uses almost verbatim the code from the docs: 
https://putyourlightson.com/plugins/sprig#how-it-works

Premis is, search component 1, search component 2 are included into the twig page so you can search for two different lists (I have not hooked up the two different lists as this is low level can the functionality work). 

component 1 path:
`/INCLUDES/components/search.twig`

```
{# Sets to a default value if not defined #}
{% set query = query ?? '' %}

<input sprig s-trigger="keyup changed delay:300ms" s-replace="#results" type="text" name="query" value="{{ query }}">

<div id="results">
    {% if query %}
        {% set entries = craft.entries().search(query).orderBy('score').all() %}
        {% for entry in entries %}
            {{ entry.title }}
        {% endfor %}
    {% endif %}
</div>
```

component 2 path:
`/INCLUDES/components/searchB.twig`

```
{# Sets to a default value if not defined #}
{% set query2 = query2 ?? '' %}


<input sprig s-trigger="keyup changed delay:300ms" s-replace="#results2" type="text" name="query2" value="{{ query2 }}">

<div id="results2">
    {% if query2 %}
        {% set entries2 = craft.entries().search(query2).orderBy('score').all() %}
        {% for entry2 in entries2 %}
            {{ entry2.title }}
        {% endfor %}
    {% endif %}
</div>
```

These are both included as per the docs instructions to the .twig page: 

```
{# Creates a component from the template path #}
{{ sprig('IMPORT/components/search') }}

{# Creates a component from the template path #}
{{ sprig('IMPORT/components/searchB') }}

{# Loads the required script from a CDN #}
{{ sprig.script }}
```

This works as expected: 

![image](https://user-images.githubusercontent.com/28821463/133421748-47443ab8-dfd2-4d9b-b97b-32c76c636ee3.png)

If the component (1 or 2) has its name changed to anything other than the query name, then the request fails to run:

From searchB.twig 

 name="awdawdad"

`<input sprig s-trigger="keyup changed delay:300ms" s-replace="#results2" type="text" name="awdawdad" value="{{ query2 }}">`

![image](https://user-images.githubusercontent.com/28821463/133421944-e20fa112-3e35-4b80-9012-7580a1bc0707.png)

--

This might be expected behavior (and given by the reaction I suppose it is) - just checking (also apologies for the drawn out example)

W

**Comment by bencroker** [comment]
As you've correctly figured out, the `name` attribute on an input fields (or select fields, textarea fields, etc.) is what ends up becoming available as template variables.

**Comment by wallythewebdev** [comment]
Thanks for your reply Ben and clearing that up!
