### ISSUE TITLE
Query entries in preview with token within sprig request

### ISSUE THREAD

**Issue by aloco** [putyourlightson/craft-sprig#162]
### Question
We have a Sprig component which loads a part of the entry dynamically. However, when this entry is not enabled, a query like `craft.entries().id(_productId).one()` won´t return the entry since its not enabled yet. (_productId is provided by the sprig component) This happens for instance in craft´s preview. I can query the entry when using `status(null)` but a more elegant way is to use the preview token which is available through the query params. Do you know how I can use the preview token to query an entry which is not enabled yet?

Update: It also looks like I can´t use `craft.request.isLivePreview()` to determine if I should use `status(null)` or not. On the initial page load it is true, when dynamically loading this via sprig, it returns false in preview

**Comment by bencroker** [comment]
This is a tricky one but let me look into it and I'll see if it makes sense for Sprig to do some magic with that token.

**Comment by bencroker** [comment]
I've made it so that Sprig components now pass the token parameter along so that they work seamlessly in a live preview scenario. You can test this manually by copying the addition in this commit: https://github.com/putyourlightson/craft-sprig-core/commit/cc7b597897245b9f0d68ca2c4ebdeb0aef37c760

**Comment by bencroker** [comment]
Released in version 1.9.0.

**Comment by aloco** [comment]
Hi Ben - Thank you for putting this into a new version!

**Comment by aloco** [comment]
Hi Ben, 

I have another tricky one related to the initial question :) When editing an entry, craft is creating a draft. When loading the entry in preview, sprig is not picking the draft version of the entry, but chooses the saved version. Not sure if this is even possible, but ideally, sprig loads the current draft of the entry which gets edited.

**Comment by bencroker** [comment]
Since the token param is now being passed down to Sprig components, I would have expected the draft version to appear. If this is not the case then please open a new issue with the steps to reproduce and I'll take a closer look.
