### ISSUE TITLE
Sprig search for entries and products at once in craft/commerce?

### ISSUE THREAD

**Issue by ballmannweber** [putyourlightson/craft-sprig#163]
hey there, 

we use your clever sprig plugin for a live search form but ran into the problem that it only finds the "normal" craft entries and no craft commerce products. is it possible to build a search that finds both types of entries?

thank you very much!

**Comment by davidhellmann** [comment]
@ballmannweber not tested but if you do something like this should be work:

```twig
{% set finalSearchItems = [] %}
{% set entries = craft.entries().search(query).orderBy('score').all() %}
{% set products = craft.products().search(query).orderBy('score').all() %}
{% set finalSearchItems = finalSearchItems | merge([entries]) | merge([products]) %}
```

**Comment by ballmannweber** [comment]
hi david, 

thanks for your help!

since I’m very new to sprig I have problems bringing your code and my (very basic from-the-docs-code) together, I always run into error messages. can you give me a tipp how to restructure this code?

```twig
	{% set query = query ?? '' %}

	<input sprig s-trigger="keyup changed" s-replace="#results" type="text" name="query" value="{{ query }}" placeholder="Suche">

	{% if query %}

		{% set results = craft.entries
			.section('ausstellungen,ausstellungsreihen,kampagnen,landingpage,seiten')
			.search(query)
			.anyStatus()
			.orderBy('score')
			.limit(15)
			.all() %}
			
		{% if results|length %}
			{% for entry in results %}
				{{ entry.title }}
			{% endfor %}
		{% else %}
			No Results
		{% endif %}
		
	{% endif %}
```
thank you so much in advance, I know those beginner-questions are annoying!
matthias

**Comment by bencroker** [comment]
The idea is to first merge the entry results with the product results, then output them all.

```twig
{% set query = query ?? '' %}

<input sprig s-trigger="keyup changed" type="text" name="query" value="{{ query }}" placeholder="Suche">

{% if query %}

    {% set entries = craft.entries.search(query).all() %}
    {% set products = craft.products.search(query).all() %}
    {% set results = entries|merge(products) %}
			
    {% if results|length %}
        {% for result in results %}
            {{ result.title }}
        {% endfor %}
    {% else %}
        No Results
    {% endif %}
		
{% endif %}
```

**Comment by ballmannweber** [comment]
hi bencroker,

thank you for your reply and help!
now I understand the idea behind the set up.

strangely this doesn’t function in my template: is seems the search isn’t initiated.
there are no results or the „else no results“ showing.

any idea why this doesn’t kick in?

**Comment by bencroker** [comment]
I just removed `s-replace="#results"` from the code above. Does that do the trick?

**Comment by ballmannweber** [comment]
ha, got it!

`{% set products = craft.products.search(query).all() %}`

the .search was missing in the products line :-)
thank you for helping!

regards
matthias

**Comment by bencroker** [comment]
Great, fixed it in the code above.
