### ISSUE TITLE
How to implement infinite scroll with Load more elements

### ISSUE THREAD

**Issue by KommerzM** [putyourlightson/craft-sprig#164]
I am using the Load more recipe from the Sprig Cookbook and was wondering how I can implement infinite scroll instead of the  button interaction. 

With many thanks in advance! Really love Sprig!

**Comment by bencroker** [comment]
This will be very similar to the load more component, but instead of a load more button, add an element with an `s-revealed` attribute. Here's a simple example to get you started.

```twig
{% set offset = offset ?? 0 %}
{% set limit = limit ?? 10 %}

{% for entry in craft.entries.offset(offset).limit(limit).all() %}
  {{ entry.title }}
{% endfor %}

<div sprig s-val:offset="{{ offset + limit }}" s-trigger="revealed" s-swap="outerHTML" s-target="this"></div>
```
