### ISSUE TITLE
Check if sprig comps exists

### ISSUE THREAD

**Issue by davidhellmann** [putyourlightson/craft-sprig#165]
### Question
Maybe stupid question but didn't found something in the htmx docs.
When I have something like this: 

```js
<script>
  htmx.trigger('#cartBubble', 'refresh');
</script>
```

All is well as long as the element is present somewhere but if not it throws  an error.

When I do it this way:

```js
<script>
  var cartBubble = document.getElementById('cartBubble');
  if (cartBubble) {
    htmx.trigger('#cartBubble', 'refresh');
  }
</script>
```

it's fine. Is this the way to go or should htmx itself check if the element exists and if not it skips his actions?

**Comment by bencroker** [comment]
Please submit this question to https://github.com/bigskysoftware/htmx/issues.

**Comment by davidhellmann** [comment]
Easy, no problem. [Here is it](https://github.com/bigskysoftware/htmx/issues/604)
