### ISSUE TITLE
Redirect https://unpkg.com/htmx.org@x.x.x

### ISSUE THREAD

**Issue by cosly** [putyourlightson/craft-sprig#166]
### Is your feature request related to a problem? Please describe.
Not a showstopper, but a small SEO (performance) issue.
The call to https://unpkg.com/htmx.org@x.x.x will cause a redirect to the full URL of this file.
https://unpkg.com/htmx.org@x.x.x/dist/htmx.min.js

### Describe the solution you would like
Call for the full file-url, instead of the short name to avoid a 301
Change line 254 in SprigVariable.php to =>
$url = 'https://unpkg.com/htmx.org@'.$this->htmxVersion.'/dist/htmx.min.js';

**Comment by bencroker** [comment]
Thanks, done in https://github.com/putyourlightson/craft-sprig-core/commit/5e94d7fc7e3fe554e992464dc5a18326bdf58886 for the next release.

**Comment by bencroker** [comment]
Released in version 1.9.0.

**Comment by davidhellmann** [comment]
@bencroker is there a way to load the HTMX script smarter without to do it by myself?
![image](https://user-images.githubusercontent.com/764292/138140465-a8cf177a-405e-4230-a1f9-4bde72af78ae.png)

**Comment by bencroker** [comment]
You can defer the loading of the script but then need to ensure you are not running htmx dependent code before it is loaded.

```twig
{{ sprig.script({ defer: true }) }}
```

**Comment by davidhellmann** [comment]
OK, means something like this is enough I think:

```js
document.addEventListener('DOMContentLoaded', function () {
      htmx.on('htmx:afterSwap', function (e) {
        window.scrollTo({
          top: 0,
          left: 0,
          behavior: 'smooth'
        });
      });
    });
   ```

sprig comp itself are not problem for the first load cause they are ssr. do i miss something?

**Comment by bencroker** [comment]
If the script should only execute after a swap, then putting this directly inside the component might simplify things.

```twig
{% if sprig.isRequest %}
    <script>
        window.scrollTo({
            top: 0,
            left: 0,
            behavior: 'smooth'
        });
    </script>
{% endif %}
```
