### ISSUE TITLE
Blitz and Sprig playing nicely together

### ISSUE THREAD

**Issue by cole007** [putyourlightson/craft-sprig#17]
We have a form appearing in the footer of our site (so on every page). The site uses Blitz to cache the site and we are trialling sprig to load in the form component as well as handle the form responses.

The issue we are having is that the CSRF token that sprig is generating is being rejected.

For example, our page footer:

    {{ sprig('/_components/newsletter/sign-up-mailchimp') }}
    {{ sprig.script }}

Then our form code (stripped back/simplified):

    <form sprig s-action="mud-module/default/mailchimp-subscribe" s-method="POST">
        {{ craft.blitz.getUri('/actions/snaptcha/field/get-field') }}
        <input type="text" name="email" required />
        <input type="submit" value="Submit" />
    </form>

The error message is 400 `Unable to verify your data submission` implying an invalid CSRF token is being submitted.

**Comment by bencroker** [comment]
Since Blitz is caching the page, you need to dynamically load the component on page load (see [this example](https://putyourlightson.com/sprig-cookbook#dynamic-content)), otherwise the CSRF token will become stale after it is used for the first time.

```twig
{% if not sprig.request %}
    <form sprig s-trigger="load"></form>
{% else %}
    <form sprig s-action="mud-module/default/mailchimp-subscribe" s-method="post">
        {{ craft.blitz.getUri('/actions/snaptcha/field/get-field') }}
        <input type="text" name="email" required />
        <input type="submit" value="Submit" />
    </form>
{% endif %}
```

Since your component is now fully dynamic, this is a better way to load the Snaptcha field, as `craft.blitz.getUri` requires executing Javascript code which is not allowed in AJAX responses.

```twig
{% if not sprig.request %}
    <form sprig s-trigger="load"></form>
{% else %}
    <form sprig s-action="mud-module/default/mailchimp-subscribe" s-method="post">
        <input type="hidden" name="{{ craft.snaptcha.fieldName }}" value="{{ craft.snaptcha.fieldValue }}"> />
        <input type="text" name="email" required />
        <input type="submit" value="Submit" />
    </form>
{% endif %}
```

**Comment by cole007** [comment]
Bingo, thank you Ben for your patience and fix. 
That seems to have resolved the issue.

**Comment by bencroker** [comment]
Great! One planned feature for the 1.0.0 release is an easier way to trigger a refresh on load.

**Comment by bencroker** [comment]
Just released version 1.0.0-beta.10 which makes it possible to set a trigger on the component as follows:

```twig
{{ sprig('/_components/newsletter/sign-up-mailchimp', {}, {trigger: 'load'}) }}
```

```twig
{% if sprig.request %}
    <form sprig s-action="mud-module/default/mailchimp-subscribe" s-method="post">
        <input type="hidden" name="{{ craft.snaptcha.fieldName }}" value="{{ craft.snaptcha.fieldValue }}"> />
        <input type="text" name="email" required />
        <input type="submit" value="Submit" />
    </form>
{% endif %}
```

**Comment by hongc-cc** [comment]
Using the code above will get error `Trying to get property 'childNodes' of non-object`

Need to use original one instead:
````
{% if sprig.request %}
    <form sprig s-action="mud-module/default/mailchimp-subscribe" s-method="post">
        {# <input type="hidden" name="{{ craft.snaptcha.fieldName }}" value="{{ craft.snaptcha.fieldValue }}" /> #}
        <input type="text" name="email" required />
        <input type="submit" value="Submit" />
    </form>
{% else %}
    <form sprig s-trigger="load"></form>
{% endif %}
````

**Comment by bencroker** [comment]
I'm not sure what your use-case is, but it should be noted that the format for this changed in version 1.0.0-beta.11 (https://github.com/putyourlightson/craft-sprig/blob/develop/CHANGELOG.md#100-beta11---2020-08-18).

```twig
{{ sprig('/_components/newsletter/sign-up-mailchimp', {}, {'s-trigger': 'load'}) }}
```

**Comment by hongc-cc** [comment]
I mean if the sprig component returns nothing, it get error `Trying to get property 'childNodes' of non-object`

**Comment by bencroker** [comment]
With which version of Sprig?

**Comment by hongc-cc** [comment]
sprig v1.0.0-beta.13

**Comment by bencroker** [comment]
This works in my local tests:

```twig
{{ sprig('_components/hello', {}, {'s-trigger': 'load'}) }}
```

```twig
{#--- _components/hello ---#}

{% if sprig.request %}
  Hello!
{% endif %}
```

Can you please double check that you are running 1.0.0-beta.13 which contains the following lines:
https://github.com/putyourlightson/craft-sprig/blob/1.0.0-beta.13/src/services/ComponentsService.php#L171-L173
