### ISSUE TITLE
Can not update or install version 1.9.1

### ISSUE THREAD

**Issue by SanboKyo** [putyourlightson/craft-sprig#171]
When I update or install version 1.9.1 I get the following error message:

> - Root composer.json requires putyourlightson/craft-sprig 1.9.1 -> satisfiable by putyourlightson/craft-sprig[1.9.1].
> - putyourlightson/craft-sprig 1.9.1 requires putyourlightson/craft-sprig-core ^1.0.1 -> satisfiable by putyourlightson/craft-sprig-core[1.0.1, v1.x-dev] from composer repo (https://repo.packagist.org) but putyourlightson/craft-sprig-core[1.0.0] from composer repo (https://composer.craftcms.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable.

What do I have to do? 

Thanks! : )

**Comment by bencroker** [comment]
Thanks for reporting this. `putyourlightson/craft-sprig-core` has been added to the `https://composer.craftcms.com` composer repo so it should work for you now.
