### ISSUE TITLE
 Multibyte character string in placeholder attribute is garbled

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-sprig#173]
### Describe the bug
Multibyte character string in placeholder attribute is garbled at version 1.9.1 and 1.9.2.
No issue with 1.8.1 and previous version.

My example code:
```
<input
      id="search_input"
      sprig
      s-trigger="keyup changed delay:300ms"
      s-replace="#search_results"
      class="ml-2 text-white bg-black w-full border-b-2 p-2 md:p-3 xl:p-4 font-light focus:outline-none"
      type="text"
      name="query"
      value="{{ query }}"
      placeholder="製品を検索"
    />

```

### Screenshots
![スクリーンショット 0003-10-14 13 59 41](https://user-images.githubusercontent.com/6081378/137262746-0f9121b8-48a7-4fd7-bbb2-2359c3ae750d.png)

### Versions
- Plugin version: 1.9.2
- Craft version: 3.7.16

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-sprig-core/commit/d5a0ae42cb386ad98612f5261a4ff11c52c25398 and released in version 1.9.3.
