### ISSUE TITLE
HTTP 404 – Not Found Caused by: Invalid Route

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#177]
recently upgraded and now getting an error in my Craft Commerce checkout

I use this to change gateways in my payment step

`<a sprig s-action="commerce/cart/update-cart" s-method="post" s-vals="{{ vals|json_encode }}" s-val:purchasable-id="{{ payment.id }}" s-indicator="#indicator" s-val:gateway-id="{{ gatewayId }}" href="#"  >`

After clicking now I get _HTTP 404 – Not Found Caused by: Invalid Route_

> Caused by: Invalid Route – yii\base\InvalidRouteException
> Unable to resolve the request "sprig-core/components/render?sprig:action=cd43d9372d657fbf981455a9a92034521f2434b7c9ab010df5b5e5e5662ca6afcommerce/cart/update-cart".

### Versions
- Plugin version: 1.10.1
- Craft version: 3.7.17

**Comment by bencroker** [comment]
Thanks! Fixed in https://github.com/putyourlightson/craft-sprig-core/commit/d4c8157576445b3174baac17487c416f48eb78f7 and released in 1.10.2.
