### ISSUE TITLE
Commerce Update Cart with a select field on change

### ISSUE THREAD

**Issue by davidhellmann** [putyourlightson/craft-sprig#179]
Hey Ben

I watched your commerce cart video and it's great and works fine.
But instead I have a + and - button to change the qty of a product
![image](https://user-images.githubusercontent.com/764292/138252443-d2473184-b14b-4992-abf6-1db26eafaf8b.png)

i need a select like this:
![image](https://user-images.githubusercontent.com/764292/138252600-65c20d72-b963-4efe-9ccc-44e3d2f4d6ac.png)

My Code:

```twig
{% set qty = qty ??? item.qty %}
{% set itemQty = { ('lineItems[' ~ item.id ~ '][qty]'): qty } | json_encode %}

<select sprig
  class="a-select__select"
  name="qty"
  s-method="post"
  s-vals="{{ itemQty }}"
  s-action="commerce/cart/update-cart">

  {% for a in amount %}
    <option
      value="{{ a }}" {{ item.qty == a ? 'selected' }}>
      {% if product.type.handle == 'wishlist' %}
        {{ (a * product.defaultPrice) | commerceCurrency(cart.currency) }}
      {% else %}
        {{ a }}
      {% endif %}
    </option>
  {% endfor %}
</select>
```

After change my select it's jump back to the old value. If I change again the value from my choice before is triggered. I'm not sure if it's possible at all or the syntax is wrong. 

Looks like he runs the `itemQty` and afterwards the `qty` var is changed. 

Hope it's clear what I mean.
Thanks

Plugin Version: 1.10.2

**Comment by bencroker** [comment]
Does this make any difference?

```twig
{% set qty = qty ?? item.qty %}
```

I'm also not seeing where `item` is defined? As an aside, being more explicit in the naming of your variables might help make the code more readable.

**Comment by davidhellmann** [comment]
Missing puzzles

```twig
{% set lineItems = cart.lineItems ??? null %}
{% for item in lineItems %}
          {% set product = item.purchasable.product ??? null %}
          {% set image = product.productImages.one() ??? null %}
          
          {% set currentSelectedQty = currentSelectedQty ?? item.qty %}
          {% set itemQty = { ('lineItems[' ~ item.id ~ '][qty]'): currentSelectedQty } | json_encode %}
          
          <select sprig
            class="a-select__select"
            name="currentSelectedQty"
            s-method="post"
            s-vals="{{ itemQty }}"
            s-action="commerce/cart/update-cart">
          
            {% for a in amount %}
              <option
                value="{{ a }}" {{ item.qty == a ? 'selected' }}>
                {% if product.type.handle == 'wishlist' %}
                  {{ (a * product.defaultPrice) | commerceCurrency(cart.currency) }}
                {% else %}
                  {{ a }}
                {% endif %}
              </option>
            {% endfor %}
          </select>
          
{% endfor %}
```

But here is the form data:
![image](https://user-images.githubusercontent.com/764292/138270927-33fc54bb-8e64-44df-b72f-a6f2cc530679.png)

```

The selected value is fine but the `currentSelectedQty` within this:
```twig
{% set itemQty = {
  ('lineItems[' ~ item.id ~ '][qty]'): currentSelectedQty
} | json_encode %}
```

is not updated.

**Comment by bencroker** [comment]
Since you're looping over all `lineItems`, it is rather likely that `currentSelectedQty` is being overwritten in each iteration. I suggest you "namespace" the quantity variable to distinguish it in each iteration, for example:

```twig
{% set selectedQuantities = {} %}

{% set lineItems = cart.lineItems ??? null %}
{% for item in lineItems %}
    {% set product = item.purchasable.product ??? null %}
    {% set image = product.productImages.one() ??? null %}

    {% set currentSelectedQty = selectedQuantities[product.id] ?? item.qty %}
    {% set itemQty = { ('lineItems[' ~ item.id ~ '][qty]'): currentSelectedQty } | json_encode %}
          
    <select sprig
        class="a-select__select"
        name="selectedQuantities[{{ product.id }}]"
        ...
```

**Comment by davidhellmann** [comment]
Thanks for the snippet.
Changed this line `{% set selectedQuantities = {} %}` to `{% set selectedQuantities = selectedQuantities ??? {} %}` but the problem still exists. I have to select the option twice. 

Here a gif maybe it's a bit more clear with it. 
![CleanShot 2021-10-21 at 22 25 11](https://user-images.githubusercontent.com/764292/138351667-3ae7b4be-3927-4607-963a-16f535a7add7.gif)

**Comment by bencroker** [comment]
I suppose the select field name has to be something that Commerce recognises. I've covered this in the Sprigcart video at https://putyourlightson.com/sprig/videos#3.-building-the-shopping-cart-component and the sorce code is available to sponsors.

**Comment by davidhellmann** [comment]
Ah! I think I know what I have to do now. Watched the video few weeks ago as I started (really helpful btw). 

Thanks Ben!

**Comment by bencroker** [comment]
Great!

**Comment by davidhellmann** [comment]
Works! 😅
