### ISSUE TITLE
Using AlpineJS inside of Sprig component?

### ISSUE THREAD

**Issue by danystad** [putyourlightson/craft-sprig#18]
Is it possible to use [AlpineJS](https://github.com/alpinejs/alpine) inside a Sprig reactive component like it is in [Livewire](https://laravel-livewire.com/docs/alpine-js)? 

I have a Twig template partial with some @click behaviour on HTML elements using AlpineJS but can't get that part to functioning when moving it into a Sprig component. I'm wondering if it simply won't work because of the reasons explained in https://github.com/putyourlightson/craft-sprig/issues/16

**Comment by bencroker** [comment]
The issue is that your Alpine JS code is injected into the DOM after Alpine has initialized itself and inspected the DOM.

According to [this issue](https://github.com/alpinejs/alpine/issues/359), running `Alpine.start()` after the [htmx:afterSettle](https://htmx.org/events/#htmx:afterSettle) event is triggered should (in theory) make it work for you. Let me know how that goes.

**Comment by billmn** [comment]
@bencroker any suggestion on how to handle the same thing using Vue?

**Comment by bencroker** [comment]
@billmn Not sure, although I'd recommend using either Vue _or_ Sprig components rather than trying to mix and match.

**Comment by terryupton** [comment]
@danystad did you manage to get this to work and if so how did you?
I am trying to load an off-screen 'filter menu' within a sprig component.

**Comment by bencroker** [comment]
Assuming `Alpine.start()` still works, this should do it.

```html
<script>
htmx.on('htmx:afterSettle', function() {
    Alpine.start();
});
</script>

**Comment by danystad** [comment]
@terryupton and @bencroker, I gave it another try today and found out what was causing the issue for me.

I was using Alpine's **@click** short syntax which won't work inside a Sprig component template. Somehow this type of attribute gets modified by Sprig to different attributes. I noticed that after inspecting the rendered code in the browser. Changing it to use **x-on:click** directives solves the problem for me and everything works.

I actually just found the following note about this in the Sprig documentation [here](https://putyourlightson.com/plugins/sprig#javascript) at the bottom of the section on JavaScript, which I missed before.

> If using a JavaScript library such as AlpineJS, you should avoid using invalid HTML attributes in your components such as @click, opting instead for the valid, more verbose form x-on:click. You may need to force AlpineJS to rescan the DOM after a component is re-rendered which you can do with Alpine.start() or one of the other methods described here.

@bencroker thanks for your help. In my use case, it works fine without having to force AlpineJS to rescan the DOM.

**Comment by terryupton** [comment]
Thanks @bencroker and @danystad - I can also confirm this was a result of using `@click` instead of `x-on:click`
I have swapped this over and now all working again. Also without having to force AlpineJS to rescan the DOM.

Thank you both.
