### ISSUE TITLE
Search input field trigger for "return"/"enter" key

### ISSUE THREAD

**Issue by jayhlee** [putyourlightson/craft-sprig#180]
I have something similar to the Sprigboard demo that includes a Live Search along with some other filters. 

```
<form>
   <input sprig s-replace="#results" s-trigger="keyup changed delay:300ms" value="{{ search }}" name="search" id="search" type="text" autocomplete="off">
</form>
```

Everything works as it should. That is, search results display as a user types a query, and any filters (e.g. Section selected) selected by the user is maintained.

However, if the search input field is active and the user hits the `return`/`enter` key, any and all other Sprig values (i.e. query params) that were pushed into the URL are cleared out. Everything (all params) is essentially reset aside from the search query in the URL bar.

So I'm wondering if there is, in addition to the `keyup` trigger, another specific trigger I need to include and target when the `return`/`enter` key is triggered on an input field. 

Alternatively, with Live Search type input fields, is there something like a `preventDefault()` that's applied to the input field so that if a user hits the `return`/`enter` key, everything isn't reset?

**Comment by bencroker** [comment]
Removing the `form` tag should make it work the way you want. Alternatively, add a `sprig` attribute too it so it doesn't result in a full page refresh.
