### ISSUE TITLE
When triggering Sprig requests in rapid succession I get a response Status Error Code 503

### ISSUE THREAD

**Issue by CAIDcreative** [putyourlightson/craft-sprig#181]
### Describe the bug
I have a somewhat large sprig component that I use to manage a craft commerce cart, with logic for refreshing the component. When a sprig refresh happens there's a chance the ajax request will fail with a 503 error code from index.php?p=actions/sprig-core/components/render. And once that happens every request from there will be a 503 until you wait for about a minute, or refresh the page.

It seems to happen when rapidly refreshing the component in rapid succession, and I'm not sure if this is some sort of cooldown to prevent spamming requests or whether it's craft, sprig/htmx, or some config on the web host's end. I've also put in a s-indicator which disables the clickable actions upon a sprig request, so it doesn't to be an issue of stacking request.

### To reproduce
1. Rapidly preform actions on a sprig component
2. Continue until the sprig request errors occur

### Expected behaviour
The component never fails

### Versions
- Plugin version: 1.10.4
- Craft version: Craft Pro 3.7.17.2

**Comment by bencroker** [comment]
It sounds like your server is being overloaded with requests and then blocking subsequent requests. I would suggest looking into whether you can reduce the overhead of the Sprig requests and whether there is a firewall set up that is blocking them. Either way, there's nothing that can be done in Sprig to avoid this.
