### ISSUE TITLE
Refresh small cart icon when added to cart using blitz?

### ISSUE THREAD

**Issue by mattgeminiworktops** [putyourlightson/craft-sprig#182]
Is it possible to refresh a small cart icon whilst using Blitz? I have a cart icon in my top navigation that shows the number of products in the cart that is cached and does not change when adding products to the cart. I was investigating potential of using 'Dynamic content' but not sure if this is suitable for what I am trying to achieve.

My cart page is not cached as I have excluded this.

Simple code used here:

 {% if addedToCart %}
                <script>
                    // document.getElementById('cart').dispatchEvent(new Event('refresh'));
                    htmx.trigger(htmx.find('#cart-total'), 'refresh');
                </script>
            {% endif %}

**Comment by bencroker** [comment]
If `#cart-total` is a Sprig component then your code should work. See the video at https://putyourlightson.com/sprig/videos#4.-communicating-between-sprig-components for some guidance.

If you want the cart to load dynamically on page load then the [Dynamic Content](https://putyourlightson.com/sprig/cookbook#dynamic-content) component is exactly what you want.
