### ISSUE TITLE
Malformed HTML when indenting attributes using the tab character

### ISSUE THREAD

**Issue by aaronbushnell** [putyourlightson/craft-sprig#183]
### Describe the bug
Sprig renders malformed HTML attributes if you use tab-based indentation on input fields.

### To reproduce
Steps to reproduce the behaviour:
1. Create an empty Sprig component
2. Add an `<input>` element, but use linebreaks and _tab-based_ indentation for each property. (This doesn't appear to be an issue if you use space-based indentation).
```html
<input
	class="p-4 text-lg w-full"
	type="search"
	sprig
>
```
3. The rendered HTML is malformed:
![Screen Shot 2021-11-04 at 3 13 15 PM](https://user-images.githubusercontent.com/315202/140404929-9f878ebd-6d97-4d44-8f28-10c83611481f.png)

### Expected behaviour
Tab indentation on an element should not cause the rendered HTML to have malformed attributes

### Versions
- Plugin version: 1.10.4
- Craft version: 3.7.18.1

**Comment by bencroker** [comment]
Thanks! Fixed in https://github.com/putyourlightson/craft-sprig-core/commit/97983cf4920d4d483be8c54d00c6018d8f42e4b6 for the next release.

**Comment by bencroker** [comment]
Released the fix in Sprig Core 1.1.6 which you can get by running `composer update`.

**Comment by aaronbushnell** [comment]
Thanks, @bencroker!
