### ISSUE TITLE
Is there anyway to get sprig to work with with crafts native flash messages when adding products to the cart?

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-sprig#186]
### Question
Is there anyway to get sprig to work with with crafts native flash messages when adding products to the cart via sprig?

**Comment by bencroker** [comment]
Thanks for reminding me to document an existing but undocumented variable ;)

```twig
{% set flashMessages = flashes ?? [] %}
{% for message in flashMessages %}
    {{ message }}
{% endfor %}
```

**Comment by bencroker** [comment]
Added in https://putyourlightson.com/plugins/sprig#controller-actions.

**Comment by terryupton** [comment]
Thanks @bencroker.
This is great. is there a way to access them like so? As I style them differently based on this.

```
{% set flashNotice = craft.app.session.getFlash('notice') %}
{% set flashError = craft.app.session.getFlash('error') %}
```

**Comment by terryupton** [comment]
This is it...

```
  {% set flashMessages = flashes ?? [] %}
  {% if flashMessages %}
    {% for message in flashMessages %}
      {% set flashNotice = flashMessages.notice ?? null %}
      {% set flashError = flashMessages.error ?? null %}
    {% endfor %}
  {% endif %}
  ```
  
  What was throwing my off was that in my include file for the flash notices.
  I had my javascript to hide them away after a few seconds in a `{% js %}` tag and this then writes the javascript to outside the sprig component.
  
  I had to swap this from a `{% js %}` to a normal `<script>` tag.
  Is there a better alternative for this Ben or is this ok to just have a `<script>` tag inline...?

**Comment by bencroker** [comment]
The `js` tag inserts code relative to the `body` tag, which a Sprig component does not normally contain, so you should be using `<script>` tags for any JavaScript inside your components.

**Comment by bencroker** [comment]
You can also simplify your code as follows.

```twig
{% set flashNotice = flashes.notice ?? null %}
{% set flashError = flashes.error ?? null %}
```

**Comment by bencroker** [comment]
You can also simplify your code as follows.

```twig
{% set flashNotice = flashes.notice ?? null %}
{% set flashError = flashes.error ?? null %}
```

**Comment by splendidrob** [comment]
Just wandering how this might work for craft 5 which now uses `getAllFlashes()` and has the `level` variable?

Ive tried this in a sprig component which I can refresh as needed but doesnt seem to receive any of my form messages...
```
{% set flashes = craft.app.session.getAllFlashes(true) %}

{% if flashes | length %}
  {% for level, flash in flashes %}
    <div class="message message--{{ level }} id="message">
      <p>{{ flash }}</p>
    </div>
  {% endfor %}
{% endif %}
```

**Comment by bencroker** [comment]
You should be able to use `sprig.message` to fetch the resulting message from an action request, see https://putyourlightson.com/plugins/sprig#s-action. If you have any further questions regarding this then please create a new issue.
