### ISSUE TITLE
Using custom global vars inside sprig template

### ISSUE THREAD

**Issue by arentsen** [putyourlightson/craft-sprig#187]
I am using `{{ sprig('/_sprig-catalogue.twig') }}`. Inside the sprig-catalogue I have to redeclare certain global variables since they are passed. This means I always have to declare them twice. Is it possible to retrieve custom global variables inside the sprig template?

**Comment by bencroker** [comment]
What exactly do you mean by "custom global variables"?

**Comment by arentsen** [comment]
Ah, I just mean a variable declared in the main layout file that is extended.
So my catalogue.twig extends `_layout.twig` (with main HTML and a variable declared that I would like to use within the twig module), which contains  `{{ sprig('_sprig-catalogue.twig') }}`. In that last template I would like to use the variable that has been declared in `_layout.twig`.

**Comment by bencroker** [comment]
You'll need to pass variables into the component, as explained at https://putyourlightson.com/plugins/sprig#component-variables

```twig
{{ sprig('_sprig-catalogue.twig', { myVariableName: myVariableValue }) }}
```

**Comment by arentsen** [comment]
Thanks, much appreciated.
