### ISSUE TITLE
Trying to get Pagination to work with Vue

### ISSUE THREAD

**Issue by KlingeSean** [putyourlightson/craft-sprig#188]
Hello, i'm trying to mix Sprig with Vuejs and when i do a push-url thats inside the pagination it just refuses to work.
Any thoughts on how i can fix this?

i basically used the cookbook pagination for this.

**Comment by bencroker** [comment]
Sorry but we can't help troubleshoot such a vague issue. Please provide a code sample or something more detailed if you'd like support.

**Comment by KlingeSean** [comment]
Sorry about the vague explaining.. we fixed the issue! thanks for replying nonetheless!
