### ISSUE TITLE
Trying to add a matrix blog to a sprig component

### ISSUE THREAD

**Issue by E2design** [putyourlightson/craft-sprig#189]
### Question
Need a hand. Trying to add a matrix block ids as variable to a component. Keep running into Key "id" for array with keys "0,1,2,3" does not exist errors.

    {# most requested #}
    {% set element = craft.entries().type('serviceLocations').one() %}
    {% set blocks = element.serviceLocations.orderBy('RAND()').limit(4).all() %}
    {% if blocks|length %}

	{# component: large screen #}
	<div>
        {{ sprig('_components/sprig/sprig-most-requested', {'blocksId': blocks.id}) }}
	</div>
	
	{# component: small screen #}
	<div>
        ...
    <div>

    {% endif %}

    {# component _components/sprig/sprig-most-requested #}
    {% for block in blocksId %}
	    <ul>
	         {% for row in block.listOfServicesKeywords %}
                <li>{{ row.keywords }}</li>
             {% endfor %}
	    </ul>
    {% endfor %}

**Comment by bencroker** [comment]
In the code above, `blocks` is an array of matrix blocks, so you cannot call `.id` on it.

Is there a reason you need two components here? If it was me, I would put all of your code into a single component and make life easy for yourself.

**Comment by E2design** [comment]
Avoiding duplicate queries. I'm using one component for small screen sizes and the other one for bigger screens. Just using CSS to hide and show, but the result of this approach is that I got duplicate queries, raising the load times.

**Comment by bencroker** [comment]
Duplicate queries can be easily avoided by storing the query result in a variable. For example:

```twig
{% set entries = craft.entries.section('handle').all() %}

{# component: large screen #}
<div>
    {# Use `entries` #}
</div>

{# component: small screen #}
<div>
    {# Use `entries` #}
<div>
```

**Comment by E2design** [comment]
Didn't think about that solution. Solved!
