### ISSUE TITLE
Reset/clear variables when another variable changes in multi-triggered sprig

### ISSUE THREAD

**Issue by gbowne-quickbase** [putyourlightson/craft-sprig#19]
We have a search form tied to a category, and a load more button since there are so many results. When someone changes the `category`, we want to start with the first selection, essentially resetting the `offset` used by load more. For now, I'm saving the `category` value in a hidden field `oldCategory` and doing a reset when they change, but it would be awesome to be able to pass along an explicit new value for `offset` when `category` changes, or to not pass it along at all. In the real world scenario, we also have a text search and a sort by dropdown, so there are a few inputs which need to reset the `offset`

```
{% set limit = 10 %}
{% set offset = 0 %}
{% set categories = craft.categories.group('applicationCategories').all() %}
<form sprig s-trigger="change" s-target="#results" s-swap="outerHTML">
    {# When category changes, we want to reset the offset to 0,
    so we start at the top of the category #}
    <select name="category">
        <option value="">Select a Category</option>
        {% for appCategory in categories %}
            <option value="{{ appCategory.id }}">{{ appCategory.title }}</option>
        {% endfor %}
    </select>
</form>

<div id="results">
    {% if category %}
        {% if oldCategory is defined and oldCategory != category %}
            {# hack? to reset offset to 0 #}
            {% set offset = 0 %}
        {% endif %}

        {% set apps = craft.entries()
            .section('applications')
            .relatedTo(category)
            .offset(offset)
            .limit(limit) %}

        {% if apps | default(null) %}
            {% set entries = apps.all() %}
            {% set totalEntries = apps.count() %}
            {# we only want to display the header when it's the first batch #}
            {% if offset == 0 %}
                <h4>Results {{ totalEntries }}</h4>
                {# These help with resetting when main items are clicked #}
                <input type="hidden" name="oldCategory" value="{{ category }}"/>
            {% endif %}

            <div class="card-row">
                {% for app in entries %}
                    {% include ['_components/appCard'] with { props: app } %}
                {% endfor %}
            </div>
        {% endif %}

        {# only show if there are more items #}
        {% if offset+limit < totalEntries | default(0) %}
            <div s-target="this" s-swap="outerHtml">
                <input type="hidden" name="offset" value="{{ offset + limit }}">
                <button sprig>Load more</button>
            </div>
        {% endif %}
    {% endif %}
</div>
```

**Comment by bencroker** [comment]
This should work using [s-vars](https://putyourlightson.com/plugins/sprig#s-vars), which adds parameters to submit with the request.

```twig
<form sprig s-trigger="change" s-target="#results" s-swap="outerHTML" s-vars="offset: 1">
```

**Comment by gbowne-quickbase** [comment]
I wasn't able to get the `s-vars="offset: 1"` to fire on subsequent requests, but when I tried `s-vars="reset: 1"` that did get sent along. Otherwise the `offset` variable was in the request with its existing value

**Comment by bencroker** [comment]
It was probably being overridden by `<input type="hidden" name="offset" value="{{ offset + limit }}">`. Try using `s-vars` only and it should work.

```twig
<button sprig s-vars="offset: {{ offset + limit }}">Load more</button>
```

**Comment by gbowne-quickbase** [comment]
Perfect! That did it. Thanks for the quick response. Like any new tool there's lots of little things to learn, but the reward is great!

**Comment by bencroker** [comment]
Indeed!

**Comment by bencroker** [comment]
FYI the `s-vars` attribute has been deprecated in Sprig 1.1.0. Read the details [here](https://putyourlightson.com/articles/sprig-1-1-0-released).
