### ISSUE TITLE
use checkbox to update cart item, with additional option (giftwrapped)

### ISSUE THREAD

**Issue by hhentschel** [putyourlightson/craft-sprig#191]
### Question
i have a craft commerce site and used sprig for updating the cart, adding a item to the cart, all working fine.
now i would like to use a checkbox to offer additional options, for example item to be giftwrapped.
i used the standard craft commerce code from here, 
https://craftcms.com/docs/commerce/3.x/orders-carts.html#working-with-line-items

i made a module, that if the item has the option giftwrapped, additional costs are applied to the item
without sprig it worked fine, but now i am struggling to sprigifiy it.

```
<label>
    <input type="checkbox"
            sprig s-action="commerce/cart/update-cart" s-method="post" 
            name="purchasables[{{ loop.index }}][options][giftNote]"
            value="purchasables[{{ loop.index }}][options][giftNote]"
             />
    Gift Wrapped
</label>
```
when i check the checkbox it rerenders the component, but then the checkbox is unchecked again,
and no additional costs are applied.
i guess its something with the value. I tried it also with s-vals, and set the vals similiar to the code, when removing an item.
`{% set vals = {('purchasables[{{  loop.index  }}][options][giftWrapped]'): 1}|json_encode %}`

### Additional context
Craft 3.7.26
Commerce Pro: 3.9.4.2
Sprig: 1.10.4

**Comment by bencroker** [comment]
Try this?
```
value="{{ purchasables[{{ loop.index }}][options][giftNote] }}"
```

**Comment by hhentschel** [comment]
Then i get this error:
`A hash key must be a quoted string, a number, a name, or an expression enclosed in parentheses (unexpected token "punctuation" of value "{".`

**Comment by bencroker** [comment]
```
value="{{ purchasables[loop.index][options][giftNote] }}"
```

**Comment by hhentschel** [comment]
_Variable "purchasables" does not exist._

could'nt find a quick solution how to add it properly, but have to go now.
have to dive in deeper next week.

**Comment by bencroker** [comment]
Just reread your message and see that you left out the `checked` attribute. Here is the general pattern you'll want to follow, which you can adapt to your use-case.

```
{% set checkMe = checkMe ?? false %}

<input sprig type="checkbox" name="checkMe" value="1" {{ checkMe ? 'checked' }}>
```
