### ISSUE TITLE
module installation of required js?

### ISSUE THREAD

**Issue by acalvino4** [putyourlightson/craft-sprig#194]
### Question
The docs show that to load the required js for this plugin, just add
`{{ sprig.script }}` in your head to load from a cdn.

Is there a way to load this via an npm package as well? (I prefer to manage all js through node+webpack). If not, consider this a feature request.

**Comment by bencroker** [comment]
Yes, you can load it via NPM as `htmx.org`, as per the docs at https://htmx.org/docs/#installing
