### ISSUE TITLE
Clear auto-suggest search results on form submission

### ISSUE THREAD

**Issue by georgeambition** [putyourlightson/craft-sprig#196]
Hi there,

I'm using a slightly modified version of the Search recipe from the Sprig Cookbook. I have wrapped the input in a form and have added a button that on submit takes the user to a results page.

```
{% set query = query ?? '' %}

<form class="search__form" action="{{ url('search/results') }}">
<input sprig s-trigger="keyup changed delay:200ms" s-replace="#results"
  type="search" name="query" value="{{ query }}" placeholder="What are you looking for?" class="search__input">
  <button class="search__button" type="submit"><i class="fas fa-search"></i></button>
</form>

<div id="results">
  {% if query %}
    {% set entries = craft.entries.search(query).all() %}
    {% if entries|length %}
      {% for entry in entries %}
        <a href="{{ entry.url }}">{{ entry.title }}</a>
      {% endfor %}
    {% else %}
    <div>
      No results
    </div>
    {% endif %}
  {% endif %}
</div>
```
This seems to work quite nicely except for once the results page has loaded, the autosuggestions within #results are still populated. Ideally I would like these to reset/refresh once the form has been submitted. 

If you could point me in the right direction to how I might be able to achieve this it would be greatly appreciated :)

**Comment by bencroker** [comment]
You could achieve this by showing the results only in Sprig requests, as follows.

```twig
<div id="results">
  {% if query and sprig.isRequest %}
    ...
  {% endif %}
</div>
```

See https://putyourlightson.com/plugins/sprig#sprig.isrequest
