### ISSUE TITLE
Scroll behaviour on load more

### ISSUE THREAD

**Issue by alanski66** [putyourlightson/craft-sprig#197]
### Question
I've been implementing load more as per the example here: https://putyourlightson.com/sprig/cookbook#load-more-complex

Is there a way to control the scroll behaviour when loading more? On Chrome it seems to scroll down past the new entries added and firefox just loads new content in the current scroll position.

**Comment by bencroker** [comment]
This is a htmx issue, please refer to the issues at https://github.com/bigskysoftware/htmx/issues
