### ISSUE TITLE
Form button not updating sprig request.

### ISSUE THREAD

**Issue by AbbeyDesign** [putyourlightson/craft-sprig#199]
### Question
I am having a little trouble getting a form with date field to work. It does not seem to update the request. The #board section refreshes but the dates do not update so it is always the same entries. It seems that I don't know how to get the form values pushed to sprig.

original dates
```
{% set startDate = now|date_modify('first day of this month')|date('Y-m-d') %}
{% set endDate = startDate|date_modify('last day of this month')|date('Y-m-d') %}
```
resets for new dates

```
{% set newStart = '' %}
{% set newEnd = '' %}
```
original querry with some items omitted for clarity
```
{% set entryQuery =
   craft.entries({
      section: ['xxxxxxxxx'],
      serviceDate: ['and', '>= ' ~ startDate, '< ' ~ endDate],
   })
%}
```
updated sprig query ( I am only including the start date here for clarity
```
{% if newStart %}
  {% set startDate = newStart|date('Y-m-d') %}
  {% do entryQuery.serviceDate(
      ['and', '>= ' ~ startDate, '< ' ~ endDate]
   ) %}
{% endif %}
```
This is where it is not working. "newStart" and "newEnd" don't seem to be pushed to the updated query. It's probably a silly omission on my part.
```
<form sprig s-replace="#board" s-indicator=".spinner">
      <div class="row align-items-end mb-3 align-bottom">
        <div class="col-sm-2 col-12">
          <label for="startDate">Start Date</label>
          <input type="date" class="form-control" name="newStart" id="newStart" autocomplete="off" value="{{ startDate }}"/>
        </div>
        <div class="col-sm-2 col-12">
          <label for="endDate">End Date</label>
          <input type="date" class="form-control" name="newEnd" id="newEnd" autocomplete="off" value="{{ endDate }}"/>
        </div>
        <div class="col text-end">
          <button type="submit" class="btn btn-success">Update</button>
        </div>
      </div>
    </form>
```

### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
Instead of resetting the values, give them default values if not set.

```twig
{% set newStart = newStart ?? '' %}
{% set newEnd = newEnd ?? '' %}
```

**Comment by AbbeyDesign** [comment]
I knew it was something ridiculously silly that I have spent all day looking at. ugh. Of course, it works now.
