### ISSUE TITLE
Dropdown filter (as part of multiple filters)

### ISSUE THREAD

**Issue by jamiematrix** [putyourlightson/craft-sprig#200]
I'm following along with [Component State](https://putyourlightson.com/plugins/sprig#component-state) using the hidden inputs to maintain value persistence (that's a lot of big words), and it works for all but the dropdown I have.

I have this dropdown on a page:
```
<select sprig name="area" id="area" value="">
   <option value="null">All Areas</option>
   {% for courseArea in courseAreas %}
      <option value="{{ courseArea.id }}">{{ courseArea.title }}</option>
   {% endfor %}
</select>
```
And at the top of the page I have:
```
{% set area = area|default("null") %}
{{ hiddenInput('area', area ) }}
```

When I change the dropdown I can see the network request, but there's 2 `area` variables being parsed. One is `null` and the other is the value of the selected item in the dropdown.
If I remove the hidden input then the `null` variable is removed but I can no longer maintain the component state.

I've tried using `s-val:area="{{ courseArea.id }}"` on the options, but that only parses the text of the option, not the value (e.g. the ID) so I think this is getting ignored.

If I remove `name` from the `<select>` then one of the `area` variables is no longer parsed but the remaining variable is always null.

**Comment by jamiematrix** [comment]
I've found a workaround that works for me.

Ended with:
```
<div>
      <select sprig name="area">
         <option>All Areas</option>
         {% for courseArea in courseAreas %}
            <option value="{{ courseArea.id }}" {{ area is defined and area == courseArea.id ? 'selected'}}>{{ courseArea.title }}</option>
         {% endfor %}
      </select>
   </div>
```
Removed the hidden input and kept the `{% set area = area|default("null") %}`. Seems to keep state and I check for `if area is defined` to apply filtering where needed.

**Comment by bencroker** [comment]
Yup, that's the solution!
