### ISSUE TITLE
&quot; inside rendered component

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#203]
### Describe the bug
Maybe a stupid question but is the CSRF token inside a rendered component meant to use html entities for the quotes?

`<form sprig s-method="post" s-action="commerce/cart/update-cart"  data-hx-headers="{&quot;X-CSRF-Token&quot;:&quot;F-xpTSfhM-GC49rRH38ZJFF_WxkOiRBf4SD1WjqcUUbrbKHwca4yWF4lwaDniNzt3rl6rlzD6m9jNcH0YxbdQhtkH8vDPNXDB7PjwyBawPFcldHVytjcIG1avPp0hjHTourJA85u--n0O5i1tebULjgcLV4vHIAFAW9Rwt2RMgGXlcg0r-oMhGsmZoreuu_jdulmwDlgq859h1x6bLty1t2uvbZzFWlIIkwKfje4XQvTUpYtYugeE40ClcAa_2Y9IkP1woHuvtrpjUPKaqDdWVMHp5BSd-omeV0orfpat_MygoX1Q2r1l2yssuyr4LkVCWqPyRbnVLWa3_pn_F-f0JdR84CCrY5vD0NgOUhw6nVtHGKTuqgDTMOnulfYsnjLPkAIvu7RvrcTlVPzAFmY-Q==&quot;}" data-hx-post="https://www.mysite.com/index.php?p=actions/sprig-core/components/render&amp;sprig:action=be48734bd8280136499a30da4a409da2aee07890411e283ceb2d6eb728c73549commerce/cart/update-cart">`

### Versions
- Plugin version:1.12.0
- Craft version:3.7.36

**Comment by bencroker** [comment]
Yes, that's intentional since it is inside of a HTML attribute. Is it causing any issues for you?

**Comment by john-henry** [comment]
Ill close this as seems unrelated to issues I was having
