### ISSUE TITLE
Profile Twig Components

### ISSUE THREAD

**Issue by aloco** [putyourlightson/craft-sprig#206]
### Question
Hi, I have a rather big site with a lot of custom modules and other stuff. I am experiencing slow loading times on some sprig components and would like to profile them to get further insights what is causing the slow loading times .. Is there any way to profile sprig components similar to regular twig templates in the debug bar? 

Thanks ✌️

**Comment by bencroker** [comment]
There's an AJAX tab in the debug toolbar that should show you profiling data for the Sprig component refresh request.

<img width="510" alt="Screenshot 2022-03-22 at 13 09 52" src="https://user-images.githubusercontent.com/57572400/159489524-dbb9d679-e0a6-452f-a807-a33b1eb97144.png">

**Comment by aloco** [comment]
ah, nice thank you, didn´t see that.
