### ISSUE TITLE
Contributing to Sprig?

### ISSUE THREAD

**Issue by aaronbushnell** [putyourlightson/craft-sprig#21]
After watching [Caleb Porzio talk about Livewire at Laracon](https://vimeo.com/394206954) I’m *very* sold on Sprig being an amazing way to build reactive UIs. Is there a way you’d like to see contributions to this project? What is most useful to continue building Sprig?

**Comment by bencroker** [comment]
Bringing your enthusiasm and spreading the word is one great way. Sprig is pretty much feature complete and the main reason for waiting to cut a 1.0.0 stable is some naming changes coming to htmx events in the near future. Otherwise, please start using it and sharing how it goes for you!

**Comment by aaronbushnell** [comment]
Fantastic! Thanks for your work on all this, @bencroker

**Comment by bencroker** [comment]
Go forth and create!
