### ISSUE TITLE
Update requires PHP ^7.1, but your environment is currently running PHP 8.1.4.

### ISSUE THREAD

**Issue by RyanRoberts** [putyourlightson/craft-sprig#215]
Looks like I can't upgrade Sprig because my PHP version is… too high? 

This screenshot should explain https://media.yep.digital/VTOQAs

**Comment by bencroker** [comment]
Whoops, fixed in https://github.com/putyourlightson/craft-sprig/commit/3198beb029ed2cf1e27aa83974a3fa275bd48ea8 and released in version 1.12.4, thanks for reporting!
