### ISSUE TITLE
Prevent Reload of Sprig Filter

### ISSUE THREAD

**Issue by sandrodunkel** [putyourlightson/craft-sprig#216]
### Question
I made a blog filter using sprig. Users can multi-select categories («Geschäftsbereiche», «Themen»). I used checkboxes for this, which worked perfectly fine. But since the filter is reloaded as well (which makes sense, because it is part of the component), de custom dropdown (using jQuery slideToggle) always resets to its closed state. This is a bummer since it is a multi-select, so users would have to open the dropdown several times to activate multiple categories.

### Additional context
Screenshot of the filter:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/102292752/163365983-c7f7ebe5-3fd2-41ce-b57e-7e04d7cd009c.png">

Any ideas how I can prevent the dropdowns from closing when the component is reloaded? Thanks in advance! :)

**Comment by bencroker** [comment]
Only replace the filterable content and not the filters, using [s-replace](https://putyourlightson.com/plugins/sprig#s-replace). 

See the recipe at https://putyourlightson.com/sprig/cookbook#search for an example of how to use it.
