### ISSUE TITLE
Tabs and add to cart problem

### ISSUE THREAD

**Issue by lucosius** [putyourlightson/craft-sprig#217]
Hello again,

As I mentioned in my previous post, I have the page where I use this example for creating tabs:

https://putyourlightson.com/sprig/cookbook#protected-variables

In those tabs I have other solution with sprig that you can find here:

https://dev.telefonai.eu/elektromobiliai/mercedes-eqa-250-2/sprendimai

Now I have two problems that cannot find the solution by myself. First problem is that if I go to the second tab (that is called premium) and choose the options for the product - i'm getting switched to the first tab (that is called elite). Second problem - if I choose options in the Elite tab - I'm getting those selections moved to other tabs. 

The code that I have for that page is here: https://github.com/lucosius/evioni/tree/main

Can someone help me out with this mess?

**Comment by bencroker** [comment]
> First problem is that if I go to the second tab (that is called premium) and choose the options for the product - i'm getting switched to the first tab (that is called elite).

You'll need to use a hidden input field to maintain the state of the selected tab.

```twig
{% set tab = tab ?? '' %}
{{ hiddenInput('tab', tab) }}
```

> Second problem - if I choose options in the Elite tab - I'm getting those selections moved to other tabs.

You'll need to namespace the input fields if you want them to be able to co-exist in multiple tabs, but not overwrite each other's values.

```twig
<input type="radio" name="elite-colour" ...>
...
<input type="radio" name="premium-colour" ...>
...
<input type="radio" name="basic-colour" ...>
```

**Comment by lucosius** [comment]
I'm getting closer and closer. Problem with changing tabs is solved now. I fixed a code a little bit (or maybe not) but now don't know how to setup the default tab to be opened (https://github.com/lucosius/evioni/blob/main/products.twig).

I was thinking about adding namespace in the inputs but if I do so - options are not getting selected at all. I did like this:

`<input sprig type="radio" name="{{ tabas }}-colour" value="{{ colourOption.id }}" {{ colour == colourOption.id ? 'checked' }}>`

So I get tab name in the input but in this case those inputs cannot be selected at all. I guess that I'm doing something wrong over here...

**Comment by bencroker** [comment]
In that case, maybe it's better to reset the field values when a new tab is selected.

```twig
{% set reset = reset ?? false %}
{% if reset %}
    {% set colour = null %}
    ...
{% endif %}

<div sprig s-val:tabas="basic" s-val:reset="1" ...
```

As previously mentioned, all of these concepts are explained via the Sprig videos.

**Comment by lucosius** [comment]
Lovely! That works as a charm! It would be nice to get some advice on "default tab" too 😊

**Comment by lucosius** [comment]
Trying to get closer to perfection...One more thing is relation with the stock. I want to have disabled options for both colour and length if they don't have stock. So for the first buttons (colour) I need to check if any of the colour have stock with any of the lengths. If not - disable, if yes - keep it selectable. And then same with the length - the ones that have stock keep selectable and ones that out of stock - disable from selection.

My starting point is something like this:

```
 {% for colourOption in colours %}
      {% set inStock = variantQuery|filter(v => v.hasStock())|length %}
<div class="column is-6">
    <label class="labl">
     <input sprig type="radio" name="colour" value="{{ colourOption.id }}" {{ colour == colourOption.id ? 'checked' }} {% if inStock == 0 %}disabled{% endif %}>
    <div>{{ colourOption.title }} {{ colourOption|length }}</div>
</label>
</div>
       {% endfor %}
```

But this one disable everything after the colour that doesn't have stock is selected. I'm not the best in the programming and help with this would be really appreciated ☺️

**Comment by bencroker** [comment]
> It would be nice to get some advice on "default tab" too 😊

```twig
{% set tab = tab ?? 'defaultTab' %}
```

> One more thing is relation with the stock. I want to have disabled options for both colour and length if they don't have stock.

Now you're asking for Commerce support, which is, for obvious reasons, outside of the scope of Sprig support.
