### ISSUE TITLE
Show modal after form submit

### ISSUE THREAD

**Issue by lucosius** [putyourlightson/craft-sprig#219]
Hello,

I have one more dumb question to ask... I made add to cart with product variants and now trying to get modal to appear after items added to the cart. I have Javascript that use this code for the button:

` <a class="js-modal-trigger" data-target="modal-js-examples"><button type="submit" class="button is-fullwidth is-cart-disabled">Cannot add to the cart</button></a>`

This one works for me because it have nothing to do with sprig. But when it comes to the sprig - it doesn't work.

As I understand I need to use s-trigger but I don't understand how should I change my code to get it working..

**Comment by bencroker** [comment]
Since that button is replaced in the DOM, you'll need to trigger the JavaScript each time the Sprig component is re-rendered. There are examples at https://putyourlightson.com/plugins/sprig#javascript, the easiest way is to put your trigger script inside the component.

```twig
<script>
// trigger the modal on click
</script>
```

**Comment by lucosius** [comment]
Trying to figure the solution with Javascripts and htmx but cannot understand... I have this JS to open navigation:

```
<script>
    /* Open when someone clicks on the span element */
function openNav() {
  document.getElementById("myNav").style.width = "100%";
}

/* Close when someone clicks on the "x" symbol inside the overlay */
function closeNav() {
  document.getElementById("myNav").style.width = "0%";
}
</script>
```

I think I need to do something like this but obviously something is wrong and don't understand how to fix it:

```
<script>
htmx.on("#openNav", "click", function(event) {
       document.getElementById("myNav").style.width = "100%";
   });
    </script>
```

Okay.. I'm starting to get something... So the code looks like this:

```
<div sprig id="openNav"><span>open</span></div>
<div id="myNav" class="overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="overlay-content">
Sprig filters
</div>
</div>
</div>

<script>
        var myEventListener = htmx.on("#openNav", "click", function(event){ document.getElementById("myNav").style.width = "100%"; });
    </script>
```

So now my popup uppears but dissapears few seconds after...

**Comment by bencroker** [comment]
This is just JS support at this stage, as we don't need Sprig to show/hide elements... define the `openNav()` function outside the Sprig component and call it in one of two ways.

Option 1:

```twig
<div id="openNav" onclick="openNav()"><span>open</span></div>
```

Option 2:

```twig
<div id="openNav"><span>open</span></div>

<script>
    htmx.on('#openNav', 'click', 'openNav');
</script>
```

**Comment by lucosius** [comment]
hmm. But how can I can fix the issue that that windows is getting closed after one of the sprig filters are set up? Because in that div I have some filters and every time when i choose any of them - the windows dissapears.

**Comment by bencroker** [comment]
Oh so you have Sprig elements _inside_ the modal? In that case you'll need to open the modal and maintain its state using Sprig.

For example:

```twig
{% set modalOpen = modalOpen ?? false %}

{{ hiddenInput('modalOpen', modalOpen) }}

<div sprig s-val:modal-open="1">Open</div>

<div id="myNav" class="overlay" style="{{ modalOpen ? 'width:100%' }}">
  <div sprig s-val:modal-open="0">Close</div>
  <div class="overlay-content">
    ...
  </div>
</div>
```

**Comment by lucosius** [comment]
That works great! I'm really sorry for asking so many "rookie" questions but I have some more 😭  

How can I fix it to have same thing on different elements? Now I have three buttons to open but if press one - all of them are opened. I tried to add ID but probably I'm doing something wrong. 

And also I'm thinking to have the same button for opening and closing. Is it possible to make it like this?

**Comment by bencroker** [comment]
You just need to namespace each one.

```twig
{% set modalXOpen = modalXOpen ?? false %}
{% set modalYOpen = modalYOpen ?? false %}
{% set modalZOpen = modalZOpen ?? false %}
```

**Comment by lucosius** [comment]
Okay, so I have to create different sets for that. Gotit. And what about using the same button for closing and opening? Is it possible to get that?

**Comment by bencroker** [comment]
```twig
<div sprig s-val:modal-x-open="1" s-val:modal-y-open="1">Open</div>
```

**Comment by lucosius** [comment]
No no.. I mean I have modal-x and I press Open to open it. After that I want to press the same button to close it.

**Comment by bencroker** [comment]
Remember, it's just Twig...

```twig
<div sprig s-val:modal-x-open="{{ modalXOpen ? 0 : 1 }}">Open/Close</div>
```
