### ISSUE TITLE
"Template Mode" issue while using other plugin

### ISSUE THREAD

**Issue by fvaldes33** [putyourlightson/craft-sprig#22]
I will create an issue with the offending plugin creator as well but figured I could add this here because the fix is quite simple.

When using Sprig in combination with the [Contact Form Extensions](https://github.com/hybridinteractive/craft-contact-form-extensions), the template mode is set back to the `View::TEMPLATE_MODE_CP` on form submission which then doesn't allow Sprig to find the templates provided by the request.

Not entirely sure why the author of that plugin is setting the template mode back to the `View::TEMPLATE_MODE_CP` but regardless, ensuring the the template mode is set to be `View::TEMPLATE_MODE_SITE` would avoid any conflicts or potential bugs moving forward.

```
# ComponentsController.php

public function actionRender(): Response
{
    // ... previous code 

    $template = Sprig::$plugin->request->getValidatedParam('sprig:template');

    // new lines of code to prevent incorrect template mode
    $view = Craft::$app->getView();
    $view->setTemplateMode(View::TEMPLATE_MODE_SITE);

    $content = $view->renderTemplate($template, $variables);

    // ... rest of code
}
```

**Comment by bencroker** [comment]
I've already created a PR https://github.com/hybridinteractive/craft-contact-form-extensions/pull/99 to address this issue, so you may want to nudge @DynamiteGoesBoom about this.

**Comment by fvaldes33** [comment]
Is there a reason why adding those two lines of code is a bad idea? Figured it would be easier to fix it in one place versus communicating to plugin authors as issues arise. Just curious.

**Comment by bencroker** [comment]
In my opinion Sprig shouldn't be responsible for fixing issues caused by other plugins, plus there may be cases where this is the desired behaviour. It appears that the PR has been merged.

**Comment by fvaldes33** [comment]
Totally get it. I commented on that PR also so hopefully that helped. Thanks again 👍🏽
