### ISSUE TITLE
Cannot read query string parameters in statically cached pages

### ISSUE THREAD

**Issue by goraxan** [putyourlightson/craft-sprig#220]
### Describe the bug
Because I statically cache pages, I load my sprig components using the `'s-trigger': 'load'` directive, so that an AJAX request to `index.php?p=actions/sprig-core/components/render` is made initially to get the dynamic contents of the component.
The problem is that the AJAX request doesn't include any query string parameters, and because of that they are lost and I cannot read them inside my component. And since the page is statically cached I cannot pass the initial query string parameter like this `{{ sprig('mycomponent', {page: craft.app.request.getParam('page') ?? 1}, {'s-trigger': 'load'}) }}`

### To reproduce
Steps to reproduce the behaviour:
1. Create a mypage.twig file and Initialize a component like this `{{ sprig('mycomponent.twig', {}, { 's-trigger': 'load'}) }}`
2. Inside mycomponent.twig, print the query parameter `page` like this
```
{% if sprig.isRequest %}
    {% dd page %}
{% endif %}
```
3. Try to load `mypage?page=5`
4. See an error `Variable "page" does not exist.`

### Expected behaviour
I'd expect the query string parameters to be included in the `index.php?p=actions/sprig-core/components/render` requests

**Comment by bencroker** [comment]
This should work if the page is cached with unique query strings. Are you using Blitz for the caching?

```twig
{{ sprig('mycomponent', {page: craft.app.request.getParam('page') ?? 1}, {'s-trigger': 'load'}) }}
```

**Comment by goraxan** [comment]
I am using Blitz for caching, but the page is served from Cloudfront

**Comment by bencroker** [comment]
What happens when you try with the code provided above, ensuring that `Cache pages with unique query strings as unique pages` is selected in the Blitz settings?

**Comment by goraxan** [comment]
After selecting the `Cache pages with unique query strings as unique pages` and configuring Cloudfront to send the `page` to the origin and include it to the cache key it works fine.

Thanks

**Comment by bencroker** [comment]
Great!

**Comment by harrison-drift** [comment]
@bencroker Sorry to drag this up, but is there a way to get this working that you've come up with if you're not caching query strings as unique pages?

**Comment by bencroker** [comment]
@Harry-Harrison You could probably use JavaScript to inject query string parameters as hidden input fields into the Sprig component _before_ it refreshes on load, if need be.

**Comment by harrison-drift** [comment]
If anyone lands on this thread in future trying to do what I was doing, this is how I've done it.

With Blitz set to "Cache URLs with unique query strings as the same page"...

```twig
{# Top level page #}
{{ sprig('mysprig/component', {}, { 's-trigger': 'load' }) }}
```

```twig
{# Component – ?id= is the param we're after #}
{{ hiddenInput('idVar', '') }}

{% js %}
    var urlParams = new URLSearchParams(location.search);
    document.getElementsByName("idVar")[0].setAttribute("value", urlParams('id'));
{% endjs %}

{% if sprig.isRequest %}
    {{ idVar }}
{% endif %}
```

If anyone has a better way, I'd love to know, but this worked great for me 👍
