### ISSUE TITLE
Handling unexpected ajax errors

### ISSUE THREAD

**Issue by russback** [putyourlightson/craft-sprig#223]
### Question
I have a compoent with some links on it that are loading dynamically with sprig. I made a call to a route that I didn't have access to and while I got a 503 in the console, the link click was dead from a UX point of view - the location href wasn't updated and no errors were reported.

Is there a way to listen for any ajax errors sprig encounters so they can be handled?

**Comment by bencroker** [comment]
There's nothing specific to handling error responses with Sprig, but you can read about error events in the htmx docs at https://htmx.org/docs/#requests

**Comment by russback** [comment]
Thanks @bencroker
