### ISSUE TITLE
s-listen or trigger refresh on component update?

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#224]
OK so currently I have 2+ components in a checkout page

`{{ sprig('checkout/_sprig-components/contact', {}, {id: 'checkoutContact'}) }}`

`{{ sprig('checkout/_sprig-components/shipping', {}, {id: 'checkoutShipping', 's-trigger': 'refresh'}) }}`

and

`{{ sprig('checkout/_sprig-components/summary', {}, {id: 'checkout-summary', 's-trigger': 'load,refresh'}) }}`

So if the customer contact details like address etc are updated in contact component then I do

```
{% if success is defined and success %}
	<script>
	htmx.trigger('#checkout-summary', 'refresh');
	htmx.trigger('#checkoutShipping', 'refresh');
	</script>
{% endif %}
```

But now I see the [s-listen](https://putyourlightson.com/plugins/sprig#s-listen)

So performant wise should I be doing?

`{{ sprig('checkout/_sprig-components/summary', {}, {id: 'checkout-summary', 's-listen': '#checkoutContact,#checkoutShipping'}) }}`
`{{ sprig('checkout/_sprig-components/shipping', {}, {id: 'checkoutShipping', 's-listen': '#checkoutContact'}) }}`

It seems a bit easier but `s-listen `is new to me so looking for your insights here

**Comment by bencroker** [comment]
Yes, I think that should do it.

```twig
{{ sprig('checkout/_sprig-components/summary', {}, {
    id: 'checkout-summary', 
    's-listen': '#checkoutContact,#checkoutShipping',
}) }}

{{ sprig('checkout/_sprig-components/shipping', {}, {
    id: 'checkoutShipping', 
    's-listen': '#checkoutContact',
}) }}
```

One thing to keep in mind is that any re-rendering of the contact component will now trigger a refresh of both of the other components, whereas in your original code it was only happening on success (`if success is defined and success`). This might be just fine, but I'd test it out with the network tab open, monitoring how many AJAX requests are made as the contact component is being interacted with. If too many, then it may make sense to use your original approach.
