### ISSUE TITLE
Entry form file input not working anymore

### ISSUE THREAD

**Issue by Jorrit-Verstappen** [putyourlightson/craft-sprig#225]
### Description
Somehow I am not able to send an image or multiple in an existing entry form that used to work prior.
What makes it even weirder is that I have another entry form for another section where it does work, even though the code is mostly the same (based on the former entry form), only difference between them is the fields that are saved and that the file input allows multiple images.

Below are the parts of the entry forms that handle the file input.

**Working Entry Form - Artists section**
```twig
{% if isEditable %}
    <div id="artistExistingImage" data-existing-image-urls="{{ imgUrl is defined ? imgUrl|json_encode : null}}" class='d-none'></div>
    <input id="artistImage" type="file" name="fields[profielAfbeelding]" required>
{% else %}
    {% if isNewEntry == false %}
        {% set image = artist.profielAfbeelding[0] %}
        {% if image %}
            <div class="col-12 d-flex overflow-scroll">
                {%- include "_partials/image" with {'image': image, 'title': image.title, transform: 'kunstenaarThumbnail', 'style': 'height: 200px; width: auto; object-fit: contain;' } only -%}
             </div>
        {% endif %}
    {% endif %}
{% endif %}
``` 

**Broken Entry Form - Artworks section**
```twig
{% if isEditable %}
    <div id="artworkExistingImages" data-existing-image-urls="{{ imgUrls is defined ? imgUrls|json_encode : null}}" class='d-none'></div>
    <input id="artworkImages" type="file" name="fields[kunstwerkAfbeeldingen][]" multiple required>
{% else %}
    {% if isNewEntry == false %}
        {% set images = artwork.kunstwerkAfbeeldingen.all() %}
        <div class="col-12 d-flex overflow-scroll">
            {% for img in images %}
                {%- include "_partials/image" with {'image': img, 'title': img.title, transform: 'kunstwerkThumbnail', 'style': 'height: 200px; width: auto; object-fit: contain; ' } only -%}
            {% endfor %}
        </div>
    {% endif %}
{% endif %}
```

Below also the code of the button that handle the submit event of the forms, this is identic to both entry forms:

**Entry Form Submit Button**
```twig
<button sprig s-val:is-magic-suggest-needed="{{ false }}" s-method="post" s-action="entries/save-entry" s-encoding="multipart/form-data" class="col-auto btn primary">{{ "Opslaan"|t }}</button>
``` 

### Expected behaviour
It should save the images inside the file input of the broken entry form to the field, like the other working entry form.

### Screenshots
As seen in the image below the field is not empty in the request but it gives me the error that it is.
![image](https://user-images.githubusercontent.com/47347978/167098540-9b34623c-76a4-4647-aa49-4e11075462a2.png)

### Versions
- Plugin version: **1.13.0**
- Craft version: **3.7.39**

**Comment by bencroker** [comment]
What makes you think this is a bug in Sprig? You mention that it used to work, can you downgrade to the version of Sprig that it worked on, to verify that it was indeed Sprig that changed and not Craft or something else unrelated?

**Comment by Jorrit-Verstappen** [comment]
I think it should indeed be a question instead of a bug, my bad, I'll see if downgrading Sprig does anything.

**Comment by Jorrit-Verstappen** [comment]
Downgraded Sprig but to no avail.
Guess it's a problem in the code but confused where since both pages are really similar in how they work.

Just find it weird that the image does seem to send because it shows (binary) at the request, but just doesn't accept it.
Do you have maybe some tips or ideas on how I could find out what the issue could be?

**Comment by bencroker** [comment]
I don't, as it's been a while since I've tried to do anything like this. I think this question is best suited to Craft support. Once you figure out how to do get it working with Craft, hooking it up with Sprig will be a cinch.
