### ISSUE TITLE
Select options blink on mobile

### ISSUE THREAD

**Issue by lucosius** [putyourlightson/craft-sprig#226]
Hey,

I have interesting problem that I'm not sure from where it coming out... So I have two select inputs with TWIG and they both related to each other.

```
{% set models = models ?? '' %}
{% set gamintojas = gamintojas ?? '' %}

{% if reset is defined %}
{% set models = '' %}
{% set gamintojas = '' %}
{% endif %}

{% set autoOptions = craft.categories.group('manufacturer').orderBy('title').all() %}
{% set modelsOptions = craft.entries.section('cars').orderBy('title').all() %}
	{% set cat_pavadinimas = craft.categories.id(gamintojas).one() %}
{% set relatedEntries = craft.entries.relatedTo(cat_pavadinimas).with(['title_filter']).all() %}
<div class="field">
  <label class="label is-size-6 mb-2">Pasirinkite EV gamintoją</label>

       <div class="select is-evioni-select is-medium">
    		<select sprig id="selection" name="gamintojas" value="{{ gamintojas }}" class="is-evioni-button is-fullwidth">
										<option value="">Visi EV gamintojai</option>
										{% set gamintojai = craft.categories.group('manufacturer').orderBy('title').all() %}

										{% for gamOption in gamintojai %}
										<option value="{{ gamOption.id }}" {{ gamintojas == gamOption.id ? 'selected' }}>
										{{ gamOption.title }}
										</option>
										{% endfor %}
									</select>
    </div>

</div>

<div class="field mt-5">
  <label class="label is-size-6 mb-2">Pasirinkite EV’s modelį</label>
  <div class="control">
    <div class="select is-evioni-select is-medium">
	<select sprig id="selection" name="models" value="{{ models }}" class="is-evioni-button is-fullwidth" {% if gamintojas|length == 0 %}disabled{% endif %}>
										<option value="">Visi EV modeliai</option>
										{% for modelsOption in relatedEntries %}
										<option value="{{ modelsOption.id }}" {{ models == modelsOption.id ? 'selected' }}>
										{% for category in modelsOption.title_filter %}
										{{ category.title }}
										{% endfor %}
										</option>
										{% endfor %}
									</select>
    </div>
  </div>
</div>

{% set ats = craft.entries.id(models).all() %}
<div class="field mt-6">
  <div class="control">
{% for entry in ats %}
    <a href="/elektromobiliai/{{ entry.slug }}/sprendimai">
    	{% endfor %}<button class="button is-evioni-buttons is-success is-fullwidth has-text-primary is-size-6"><span class="light-icon">Ieškoti sprendimų</span></button></a>
  </div>
</div>
```

Maybe it's not the best implementation... Not sure about that. What's happening wrong is that when you select "gamintojas" or later "models" entire options meniu appears once again for the second. I'm not sure why it's happening, maybe there's better options how to make this thing work properly?

**Comment by bencroker** [comment]
I'm not sure what your question is and I obviously can't run your code since I don't have your content setup. Please provide Twig code that I can use to replicate the issue, along with a clear and specific question.

**Comment by lucosius** [comment]
I uploaded as the video:

https://www.veed.io/view/7d4d5fdb-395c-4ccc-811d-4fc01506082f

As you can see, after I select the option in 2nd field - it popups out once again for a second. I'm trying to figure out the way why it's happening. Is it because of sprig or it's bad implementation?

**Comment by bencroker** [comment]
I honestly don't know. Does this happen in a desktop browser too?

**Comment by lucosius** [comment]
Nope. Maybe it can be because of the long entries list that are shown as the options?

You can see demo here: https://dev.telefonai.eu/

I cannot figure out why it's happening... Don't even have a clue of what should I look for 😆

**Comment by bencroker** [comment]
Yeah it's working just fine in Firefox. The fact that it doesn't happen in a desktop browser tells me it is not an issue with Sprig.
