### ISSUE TITLE
Alpine.start() after component re-render causes checkout issue

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-sprig#229]
I cannot understand why running Alpine.start() in my address component causes issues with my checkout which is not a Sprig component. In my address component I need to Alpine.start() to bind the new cart address data but since Alpine.start() re-renders all Alpine components then my checkout is re-rendered as well. This apparently breaks part of the checkout. I cannot see how but the order goes through but then (probably at the redirect step) it reloads the page with an error message "Order cannot be empty".

Everything works fine if I remove the Alpine.start() or refresh the browser before submitting the checkout form.

Its not a Sprig bug but after trying everything including ideas from Livewire on how to re-render an Alpine component I am out of ideas. I am guessing that Alpine creates a duplicate and submit both as when I check my error log it seems like the error belongs to a new order.

**Comment by bencroker** [comment]
I'm not seeing a question, but can you put to together a little example that demonstrates the issue?

**Comment by bencroker** [comment]
Also, have you asked in the `#alpine-htmx` channel of the htmx discord server?
https://discord.com/channels/725789699527933952/931549069141225613

**Comment by philipboomy** [comment]
I fixed this by not using a script tag and by having all my data and functions in the html. Similar to what Alpine author does in his components.

**Comment by bencroker** [comment]
Great! Can you perhaps show a simple example of how you solved it (versus what didn't work) for future reference?

**Comment by philipboomy** [comment]
Sure

This way works and this is actually how Alpine author does it in his component examples. I might use this approach for everything instead of using a script tag.

```
<div x-data="{ 
       cart : {
             billingAddress : {
                address1 : '{{  cart.billingAddress.address1 ?? '' }}',
                city : '{{  cart.billingAddress.city ?? '' }}',
                 zipCode : '{{  cart.billingAddress.zipCode ?? '' }}',
                  phone : '{{  cart.billingAddress.phone ?? '' }}',
             },
       },
       findBillingAddress() {
           //Some logic here
        },
</div>
```

Before when it was not working I had my data and functions in a script tag.

```
<div x-data="billingDeliveryAddress">
</div>

<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('billingDeliveryAddress', () => ({
        cart : {
                billingAddress : {
                    address1 : '{{  cart.billingAddress.address1 ?? '' }}',
                    city : '{{  cart.billingAddress.city ?? '' }}',
                    zipCode : '{{  cart.billingAddress.zipCode ?? '' }}',
                    phone : '{{  cart.billingAddress.phone ?? '' }}',
                }
       },
         findBillingAddress() {
               //Some logic here
            },
        }))
    })
</script>
```

My cart object inside the script tag was not updating when Sprig component was re-rendering. The cart object in the first example where I am not using a script is getting updated.

**Comment by bencroker** [comment]
Ah yes, using Alpine inline allows it to maintain state and improves readability through locality of behaviour. Thanks for sharing!
