### ISSUE TITLE
searching for a variant that matches a variant feature in a dropdown

### ISSUE THREAD

**Issue by mahajanl** [putyourlightson/craft-sprig#23]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

I have no idea what I'm doing wrong. sample code for parent, which has 2 variants for this test

PRODUCT PAGE TWIG
`{% extends 'shop/_layouts/main' %}

{% block main %}

	<div>
		<h1 class="text-3xl block sm:inline">{{ product.title }}</h1>
		<p>
			{{ product.description }}
		</p>
		<h4>
			{{ product.brand.one.title }}
		</h4>

		{# variant information into a partial for spriginess #}
		{{ sprig('shop/products/_variant', { product : product }) }}
		{{ sprig.script }}

	{#   {{ sprig('_partials/test') }} <-- search example from cookbook works fine so sprig installed correctly and functions #}
					
	</div>
{% endblock %}`

PARTIAL TO BE SPRIGIFIED:
`{# get the params from the url if they're there, null shit if not #}
{% set environment = craft.app.request.getParam('environment') %}
{# set up the empty variables so you dont get errors before shit is passed into the url #}
{% if environment == '' %}
  {% set environment = null %}
{% endif %}

{% set application = craft.app.request.getParam('application') %}
{% if application == '' %}
  {% set application = null %}
{% endif %}

{{ product }}
{# this outputs, so i know this partial is showing up, product is passed #}

<form action="{{ product.url }}">

  {# set an open array to plop all array stuff into #}
  {% set applications = [] %}            
  {% for variant in product.getVariants() %} 
      {% set applications = applications|merge(variant.application.all) %}
  {% endfor %}            

  {# take all the applications from all the variants and merge them into an array with only the unique values #}
  {% set applications = applications|unique %}
  <select sprig name="application">
    {% for application in applications %}
        <option value="{{ application.id }}">{{ application }}</option>
    {% endfor %}
  </select>

  {% set environments = [] %}            
  {% for variant in product.getVariants() %} 
      {% set environments = environments|merge(variant.environment.all) %}
  {% endfor %}            

  {% set environments = environments|unique %}
  <select sprig name="environment">
    {% for environment in environments %}
        <option value="{{ environment.id }}">{{ environment }}</option>
    {% endfor %}
  </select>

  <input type="submit" class="button" value="variant Search">
</form>

{# grab variants that match your above shit #}
{% set variantQuery = craft.variants.relatedTo(['and', {element: environment}, {element: application}]) %}
{% for variant in variantQuery %}
  {{ variant.title }}
{% endfor %}`

### Additional context
Add any other context or screenshots about the support request here.

sometimes github doesnt like twig code so i'll also include screenshots

THANKS!

![producttwig](https://user-images.githubusercontent.com/32281765/91761391-c9bc1f80-eba2-11ea-9ff9-0af8620773f3.JPG)
![varianttwig](https://user-images.githubusercontent.com/32281765/91761395-cc1e7980-eba2-11ea-82a8-c294abe656d8.JPG)

**Comment by bencroker** [comment]
From the [docs](https://putyourlightson.com/plugins/sprig#component-variables):

> Only values that can be passed over HTTP requests may be used (strings, numbers, booleans).

So your call to the `sprig` function should pass in the product ID and within the component you should fetch the product using the ID.

```twig
{{ sprig('shop/products/_variant', { productId : product.id }) }}
```

**Comment by bencroker** [comment]
Just updated my code above FYI.

**Comment by mahajanl** [comment]
appreciate you. i'm still missing something here but this for sure gets me closer to where i need to be.

**Comment by bencroker** [comment]
Ok, let me know how it goes once you've played around with it a bit more.

FYI to get twig code to format properly in Gihtub, you can use the following syntax:

```twig
```twig

    Your {{ twig }} code

Close the code block with 3 backticks (`)
```

**Comment by mahajanl** [comment]
WORKING! 

and thank you!

**Comment by bencroker** [comment]
Great, glad to hear it!
