### ISSUE TITLE
When request class is removed from s-indicator it removes other pending request classes also

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#231]
I have a large component with a product grid and each product has an add to cart button. This all works fine and I can add and delete with no problems from cart.

However I added a loading indicator `s-indicator` which works and shows fine, that is until I click another add to cart at the same time. When the first has finished adding to cart it removes the others spinners before they have added their items to cart

So in my layout I have 

```
<script>
	htmx.config.requestClass = 'loading';
</script>
```
And in my component I have this. I added a loop.index and even nested the htmx-indicator inside the button as the its the origin of the request but still the same result

```
{% for product in products %}
	<button sprig s-method="post" s-action="commerce/cart/update-cart" s-vals="{{ vals|json_encode }}"  s-indicator=".htmx-indicator{{ loop.index }}" >

<svg class="htmx-indicator{{ loop.index }} spinner-overlay " xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
	<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
		<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
	</svg>

</button>
{% endfor %}
```

So really wondering if Im coming up against a limitation or bug of some sort when request class is removed that it removes all on page at same time. Sending you video of behaviour via discord chat

**Comment by bencroker** [comment]
Currently, when the response returns from the server, it swaps out the entire component, overriding any loading indicators that were since activated. To get around this, you can replace just the button itself, as follows. Note that I've switched from using classes to IDs generated from the product ID, which seems more robust, but just a suggestion.

```twig
{% for product in products %}
    <button sprig s-method="post" s-action="commerce/cart/update-cart" s-vals="{{ vals|json_encode }}" 
        s-indicator="#button-{{ product.id }}" s-replace="#button-{{ product.id }}"
    >
        <svg id="button-{{ product.id }}" class="spinner-overlay" ...
```

**Comment by john-henry** [comment]
Great thanks. Ill take a look at the replace attribute. Only one product ID. Its complicated :)

**Comment by john-henry** [comment]
All working now with some tweaking. Thanks
