### ISSUE TITLE
Documentation CSS

### ISSUE THREAD

**Issue by bengreenbank** [putyourlightson/craft-sprig#232]
It looks like your documentation site has an issue with the z-index of the buttons. See screenshot.
![Screenshot 2022-05-30 at 11 31 55](https://user-images.githubusercontent.com/61185468/170974278-35722bef-f3c6-43c2-b2a1-01a791785d78.png)

URL: https://putyourlightson.com/plugins/sprig 
Browser: Firefox 100.0.2
OS: macOS 12.3.1

**Comment by bencroker** [comment]
Thanks, that appears to only happen on very wide screens, will make a note to fix this site-wide.
