### ISSUE TITLE
Load more doesn't update a query parameter when requested.

### ISSUE THREAD

**Issue by jackabox** [putyourlightson/craft-sprig#234]
Hey,

I've been working on a load more that appends data to a grid, following closely around and the discussion [here](https://github.com/putyourlightson/craft-sprig/issues/86#issuecomment-766399341).

Now, I basically have everything working with the code. I have a button that is appending data to a div with the following code:

```
<div class="lg:w-10/12 mx-auto grid grid-cols-1 md:grid-cols-2 gap-x-10 md:gap-x-20 lg:gap-x-40 xl:gap-x-60" id="results">
    {% for member in members %}
         {{ include('team/team-card', { member: member, even: loop.index is even }) }}
    {% endfor %}
</div>

{% if memberQuery.count() > offset + members|length %}
    <div class="text-center mt-6 mb-10 col-span-1 md:col-span-2 load-more">
	<button
	    sprig
		s-val:offset="{{ offset + limit }}"
		s-replace=".team-card"
		s-target="#results"
		s-swap="beforeend"
		class="p font-mono text-white/50 inline-block "
	>Load more</button>
</div>
{% endif %}
```
However, as I run this the button does not get refreshed. If I changed the code so the button gets refreshed alongside the div, I end up with a button being appended several times. 

My query stems from, If I do not replace the button it never sees the `s-val:offset` updated, and it never hides because the button doesn't see the query updated. 

Is there anyway to get these two to talk to each other, without having to re-append the button constantly, or is there a way to hide the old buttons upon update of the page?

**Comment by bencroker** [comment]
Yes, there's a complex load more recipe that should help get you started at https://putyourlightson.com/sprig/cookbook#load-more-complex

**Comment by jackabox** [comment]
Perfect, thanks that worked, I missed using the s-select rather than the s-replace.
