### ISSUE TITLE
Cannot place POST form inside spirig componet that makes post requests unrelated to that form

### ISSUE THREAD

**Issue by piotrpog** [putyourlightson/craft-sprig#236]
Below is my component. It uses buttons to swap its content which also includes POST form. Form itself is not supposed to be reactive in any way. When form is present in component, i get error 500 when i make sprig request using buttons:

`craft\web\View::renderTemplate(): Argument #1 ($template) must be of type string, null given, called in C:\xampp8\htdocs\test_updates\vendor\putyourlightson\craft-sprig-core\src\controllers\ComponentsController.php on line 62`

It seems that sprig is making request to `commerce/cart/update-cart` which gets redirected (code 302) to `actions/sprig-core/components/render`, but without any parameters.

When i remove form, sprig requests are made correctly. If i keep form and remove `s-method="post"` attribute from buttons i dont get error 500, but 400 instead:

`Post request required`

```
{% set variantParam = 'variant' %}

{# set product #}
{% set product = craft.products.id(productId).one() %}

{# set variant #}
{% set variant = product.defaultVariant %}

{# change variant if url param is present #}
{% if product.variants|filter(v => v.id == craft.app.request.getParam(variantParam)) is not empty %}
	{% set variant = product.variants|filter(v => v.id == craft.app.request.getParam(variantParam))|first %}
{% endif %}

<div id="sprig">

	{# basket #}
	<form action="" method="post">
		{{ actionInput('commerce/cart/update-cart') }}
		{{ csrfInput() }}
		{{ hiddenInput('purchasableId', variant.id) }}
		<button>Add to cart</button>
	</form>

	{# variant switcher #}
	{% if product.variants|length > 1 %}
		<div class="variant-widget">
		{% for option in product.variants %}
			<button 
				class="{{variant.id == option.id ? 'is-selected'}}"
				sprig 
				s-push-url="?{{variantParam ~ '=' ~ option.id}}" 
				s-replace="#sprig" 
				s-val:{{variantParam}}="{{ option.id }}"
				s-indicator="#preloader"
				s-method="post"
			>
				{{option.sku}}
			</button>
		{% endfor %}
		</div>
	{% endif %}
</div>
```

**Comment by bencroker** [comment]
I'm not seeing a question here, but if you want to avoid the form being part of the Sprig re-rendering, then you can put an `s-disable` attribute on it.

```twig
<form s-disable action="" method="post">
```

See https://htmx.org/attributes/hx-disable/

**Comment by piotrpog** [comment]
@bencroker 
I tried that, but it didnt halped. When i add `s-disable` to form, it is rendered as
`<form action="" method="post" s-disable="" data-hx-disable="" data-sprig-parsed="">`

Is `data-sprig-parsed`, suggesting that sprig didnt ignored it after all?

Also I notices that this form does not cause problems if i remove `{{ actionInput('commerce/cart/update-cart') }}` from it (but then its useless).

**Comment by bencroker** [comment]
Ok, seems I forgot that `s-disable` only disables re-rendering, not what is submitted. Try this?

```twig
<div class="variant-widget" s-include="this">
```

**Comment by piotrpog** [comment]
@bencroker 
Thank you, this helped. But why including `this` in the request made bu buttons stops the form from being processed instead? Not sure i completly understand it.

**Comment by bencroker** [comment]
By default, all input fields in a component are submitted in the Sprig request. If you inspect the component, you'll see `data-hx-include="this"` on it. In your case, this includes the `action` input field, which causes issues. By limiting what is submitted to only the buttons, you avoid the issue.

**Comment by piotrpog** [comment]
@bencroker 
Thank you!
