### ISSUE TITLE
Dynamically load component

### ISSUE THREAD

**Issue by bleepsandblops** [putyourlightson/craft-sprig#24]
Hello,

I'm sure I'm missing something really obvious here, but I've tried a few things referenced in other issues and can't figure it out.

I'm using barba.js to navigate between pages, which means my sprig component is loaded dynamically. How do I 'tell' sprig to start activating that component once loaded? 

I'm using the search demo with minimal changes.

Thank you!

**Comment by bencroker** [comment]
How do you generally execute Javascript code that exists in your pages when using barba.js?

**Comment by bleepsandblops** [comment]
I put it in events, like `afterEnter` which means the new page has been dynamically loaded and the DOM is ready. 

To clarify, in my case, if I load the page normally or refresh it my sprig components works fine, but if I navigate to it from another page (that navigation being ajax-ified), then it doesn't.

**Comment by bencroker** [comment]
Sprig uses [htmx](https://htmx.org/) which self-initialises on page load. It sounds like you'll need to manually initialise htmx in your `afterEnter` event. I've asked in the [htmx discord channel](https://htmx.org/discord) and perhaps @1cg can enlighten us.

**Comment by bencroker** [comment]
Can you try this?

```
htmx.process(document.body);
```

**Comment by bleepsandblops** [comment]
Perfect thank you, that worked!
