### ISSUE TITLE
Adding search and category filters on category entry pages

### ISSUE THREAD

**Issue by hello-jeff** [putyourlightson/craft-sprig#240]
I am hoping for a little guidance in getting search and checkbox category filters to work on category entry pages but I'm lost in how to access specific categories once you leave the category template which is necessary with creating a Sprig component template.

For the Craft site that I am currently developing, I have set up a set of entries as a channel called Selects. I also have four groups of categories for Brands, Types, Families, and Notes that are assigned through Category fields on the Selects entries. So each Select that is added as an entry, I assign one or more category entry to each. For example, this is for fragrances and candles, 

Entry Title - No. 5
Brands - Chanel
Type - Fragrance
Families - Amber, Fougere
Notes - Bergamot, Lavender, Vanilla

For the Selects entries index, I've successfully added a Sprig search and category filter system that works wonderfully. 

However, I would like it to work on the category entries pages as well. So, if I'm on entry page for the Vanilla notes category, I see only items with Vanilla as a note but I can filter by Brand, Family, and Type as well. I would want the same for Brands. If I'm on Chanel's brand category entry page, I would want to be able to filter the Type, Family, and Notes. 

I have attached 3 files. The "._entry" file is the basic category entry template file that works without a filter as I am able to use the relatedTo: category parameter. The" ._entry--FILTER" file is a version of the category entry template file that brings in the Sprig component. Finally, the "select-notes" file is the sprig component template file I'm using for the notes category. Everything I've tried so far to set the relatedTo: category variable either brings in all of the Selects as a whole not just for the selected note or it brings in the correct selects by notes but the filter/search doesn't work. At one point, I thought I had it working, and it would show the correct selects, but if I hit reset, it would show all selects entries. 

I hope I explained that all thoroughly. I'm still learning not only Sprig but Craft as a whole. Thank you for your patience.
[Twig-Files.zip](https://github.com/putyourlightson/craft-sprig/files/8903073/Twig-Files.zip)

**Comment by bencroker** [comment]
Great to see what you've created so far, but to be honest, your question is not Sprig specific. You're essentially asking how to filter by multiple categories in Craft, and I'm pretty sure I cover this in the [Sprig Filters](https://putyourlightson.com/sprig/videos#sprig-filters) videos using the [andRelatedTo](https://craftcms.com/docs/4.x/relations.html#the-andrelatedto-parameter) parameter. Here's some code to help get you started.

```twig
{# `category` is already set when viewing a category page #}
{% set entryQuery = craft.entries.relatedTo(category) %}

{% if brands is not empty %}
    {% do entryQuery.andRelatedTo(brands) %}
{% endif %}

{% if types is not empty %}
    {% do entryQuery.andRelatedTo(types) %}
{% endif %}
```

**Comment by hello-jeff** [comment]
Thanks, Ben. I guess the part that I am confused by is how I can use `{% set entryQuery = craft.entries.relatedTo(category) %}` when that line is in the Sprig component template file, not the actual category entry template file. Since everything is outside of that category entry file and merely being imported into it by something like `{{ sprig('components/filters/selects-notes') }}`, "category" becomes a variable that does not exist. 

Is there a way I can activate Sprig and have the entire sprig template file contents (.select-notes.twig) in the actual category entry template (._entry.twig)?

Regardless, I'm going to rewatch the videos you linked and do some further reading. Thanks for the quick response.

**Comment by hello-jeff** [comment]
I think I may have solved it thanks to a descriptive error message in Craft related to the Sprig component. If I add the following to the category entry template `{{ sprig('components/filters/selects-notes', { 'categoryId': category.id }) }}` I'm able to then use the following in the Sprig component file to pass the relatedTo category variable...

So far the results seem to be working. I'm going to add some more entries to test.

```
{% set category = craft.categories.id(categoryId).one() %}
{% set entryQuery = craft.entries({
	search: search,
	section: 'selects',
	relatedTo: category,
	with: [
		'selectsImage',
		'selectsBrand',
		'selectsType',
		'selectsNotes',
		'selectsFamily'
	],
}) %}
```

**Update - Tested with some dummy products and category entries. All seems to be working now.

**Comment by bencroker** [comment]
Glad to hear it!
