### ISSUE TITLE
sprig with form upload file attachments

### ISSUE THREAD

**Issue by pacoNew** [putyourlightson/craft-sprig#241]
Hey Ben,

I use the sprig plugin to load the form and bypass the cache. But I need to extend the form with upload file attachments. For that I use the enctype tag in the form.

`      <form class="kontakt--form" sprig="sprig" s-method="post" s-action="contact-form/send" enctype="multipart/form-data">
`

But I get this message 

`TypeError
Argument 1 passed to craft\web\View::renderTemplate() must be of the type string, null given, called in /app/vendor/putyourlightson/craft-sprig-core/src/controllers/ComponentsController.php on line 65.`

Am I missing something?

**Comment by bencroker** [comment]
It looks like you should be using the `s-encoding` attribute, see https://putyourlightson.com/plugins/sprig#s-encoding

**Comment by pacoNew** [comment]
Hey Ben,

I did already test it with `s-encoding ` . The Form works but no attachment arrives. If I test the same code, without sprig the attachment will arrive.

without sprig:

<img width="1115" alt="Bildschirmfoto 2022-06-15 um 09 37 07" src="https://user-images.githubusercontent.com/25824717/173770246-80068ee0-cf0b-4768-b198-b6e421731b8b.png">

with sprig:

<img width="737" alt="Bildschirmfoto 2022-06-15 um 09 36 59" src="https://user-images.githubusercontent.com/25824717/173770336-6d86f3d5-fa04-4f3c-9625-905a3509569d.png">

the input file looks like this:
`<input type="file" name="attachment[]" multiple="multiple">`

Do you have any idea what needs to be adjusted?

Thanks for you help,
Pascal

**Comment by bencroker** [comment]
I can't replicate this locally. Please send me a scaled down version of your form, that does not work.

**Comment by pacoNew** [comment]
Hi Ben,

here is scaled down version of my form. 

`<form class="kontakt--form" sprig s-method="post" s-action="contact-form/send" s-enctype="multipart/form-data"><input type="email" id="from-email" name="fromEmail" value="" autocomplete="email" required placeholder=" ">
<textarea id="message" name="message[body]" rows="10" cols="40" required placeholder=" "></textarea>
<input type="file" name="attachment[]" multiple>
<button type="submit" class="kontaktform__button">Senden</button>`

Thanks for watching it.
Pascal

**Comment by bencroker** [comment]
Looks like you have a typo, it should be `s-encoding="multipart/form-data"`.

**Comment by pacoNew** [comment]
wow, you are right. I'm sorry about your time. 
I took the `enctype="multipart/form-data"` from the craft contact form plugin Docs and just put an s in front of it. how embarrassing.  I think it's time for vacation. thank you very much

**Comment by bencroker** [comment]
Sure thing!
