### ISSUE TITLE
How post a form from a button outside the <form> tag.

### ISSUE THREAD

**Issue by maartenheideman** [putyourlightson/craft-sprig#242]
I am building an onepage checkout for Craft Commerce (see screenshot) where sprig is very helpfull. But there is one thing I'll can't get working. As you can see in the screenshot there are 2 buttons because there are 2 separate forms. `commerce/cart/update-cart` for next step and `commerce/payments/pay` for pay). I'll want to remove the next step button and trigger the submit of both forms with 1 button (the pay button). Both forms are seperate sprig components. 

When the form submit of update-cart is triggert by javascript from outside the sprig component or outside the <form> tag the page refreshes instead of sending a ajax post. When clicking the next step button it works perfectly (the submit button in the cart-update component in the updatecart <form> tag). 

Another question is how I'll can send a event or variable update from the payNow component to the updateCart component to trigger the submit of the pay form after the updatecart form component was successfully send and re-rendered.

Maybe there is a better way to do this? A custom controller for example but I'm not a php developer.

```
// updateCartComponent 
{% set payNow = payNow ?? null %}
<form id="updateCartForm" sprig s-method="post" s-action="commerce/cart/update-cart">
    <input type="hidden" name="billingAddressSameAsShipping" value="1">
    {{ redirectInput('webshop/checkout/onepagecheckout') }}
    ....
</form>
{% if payNow is true %}
    <script>
        var payForm = document.getElementById("payForm");
        payForm.submit();
    </script>
{% endif; %}
```
```
// payFormComponent
<form method="POST" id="payForm">
    ....
    <button type="submit" id="payNowButton">Pay now</button>
</form>
// Script
<script>
var payNowButton = document.getElementById("payNowButton");
payNowButton.addEventListener('click',function (e) {
    e.preventDefault();
    var cartForm = document.getElementById("updateCartForm");
    cartForm.submit();
});
</script>
```

![craft-onepagecheckout](https://user-images.githubusercontent.com/25221892/174661460-05f26bd0-2c52-46b8-9712-b8c492d02cc7.jpg)

**Comment by bencroker** [comment]
It's not possible to hit 2 controller endpoints in a single request. My approach would be to create a custom controller action that internally submits to both endpoints, returning a single result. 

If, however, you insist on using Sprig to achieve this then I'd suggest a single component and using JavaScript to handle the second submission. Here is some code to get you started but it will likely need tweaking.

```twig
<form id="form" sprig s-method="post" s-action="commerce/cart/update-cart">
    ...
</form>

{# On success, add an overriding action and resubmit the form. #}
{% if success is defined and success %}
    {{ hiddenInput('action', 'commerce/payments/pay') }}
    <script>
        document.getElementById('form').submit();
    </script>
{% endif %}
```
