### ISSUE TITLE
Nesting Sprig components when using component classes

### ISSUE THREAD

**Issue by stevendierick** [putyourlightson/craft-sprig#243]
We're building a shop (Commerce Pro) and using Sprig to render the overview pages using component classes. We're also using Verbb's Wishlist plugin so the customer can add products to their wishlist from an overview page.

The component class is working great. It gives us much more flexibility with filters. We're using Sprig in combination with Alpine.js to trigger the filters and refresh.

But I'm having an issue when using the Wishlist plugin as a nested Sprig component. Even if I add the wishlist code itself to my overview template. When clicking the wishlist toggle button the Sprig action has an error.

However, this is working fine when ditching the component class and going for good ol' Twig. So, I'm clearly missing something. Any idea what I'm doing wrong?

--

Craft CMS v3.7.45.1
Sprig v1.13.0

--

Error:

```
Argument 1 passed to craft\web\View::renderTemplate() must be of the type string, null given, called in /Volumes/.../vendor/putyourlightson/craft-sprig-core/src/controllers/ComponentsController.php on line 65
```

Books.php

```
class Books extends Component
{
    public $page = 1;
    public $limit;
    protected $_template = 'sprig/books';

    public function attributes()
    {
        $attributes = parent::attributes();

        $attributes[] = 'books';

        return $attributes;
    }

    public function getBooks()
    {
        $query = Craft::$app->getElements()->createElementQuery(Product::class);
        $query->limit($this->limit);
        $query->all();

        return $query;
    }
}
```

books/index.twig

```
{{ sprig('Books', { limit: 24 }, { id: 'books', 's-trigger': 'refresh' }) }}

{{ sprig.script }}
```

sprig/books.twig

```
{% set pageInfo    = sprig.paginate(books, page) %}
{% set pageResults = pageInfo.pageResults %}

{% if pageResults|length %}
    <div class="grid grid-cols-4 gap-8">
        {% for item in pageResults %}
            <ul>
                <li>{{ item.id }}</li>
                <li>{{ item.title }}</li>
                <li>
                    {{ sprig('sprig/wishlist', { bookId: item.id }, { id: 'books-wishlist-item-' ~ item.id }) }}
                </li>
            </ul>
        {% endfor %}
    </div>
{% endif %}
```

sprig/wishlist.twig

```
{% set item = craft.wishlist.item(bookId, null, 'wishlist') %}

<button sprig s-method="post" s-action="wishlist/items/toggle" s-vals="{{ { elementId: bookId }|json_encode }}">
    {% if item.inList %}
        Remove from wishlist
    {% else %}
        Add to wishlist
    {% endif %}
</button>
```

**Comment by bencroker** [comment]
> However, this is working fine when ditching the component class and going for good ol' Twig. So, I'm clearly missing something. Any idea what I'm doing wrong?

Can you showing me an example of the scenario in which it _is_ working, so I can compare the difference and investigate further?

**Comment by stevendierick** [comment]
Sure, in this scenario it works perfectly fine:

books/index.twig

```
{{ sprig('sprig/books', { limit: 24 }, { id: 'books', 's-trigger': 'refresh' }) }}

{{ sprig.script }}
```

sprig/books.twig

```
{% set page        = page|default(1) %}
{% set books       = craft.products().limit(limit) %}
{% set pageInfo    = sprig.paginate(books, page) %}
{% set pageResults = pageInfo.pageResults %}

{% if pageResults|length %}
    <div class="grid grid-cols-4 gap-8">
        {% for item in pageResults %}
            <ul>
                <li>{{ item.id }}</li>
                <li>{{ item.title }}</li>
                <li>
                    {{ sprig('sprig/wishlist', { bookId: item.id }, { id: 'books-wishlist-item-' ~ item.id }) }}
                </li>
            </ul>
        {% endfor %}
    </div>
{% endif %}
```

sprig/wishlist.twig

```
{% set item = craft.wishlist.item(bookId, null, 'wishlist') %}

<button sprig s-method="post" s-action="wishlist/items/toggle" s-vals="{{ { elementId: bookId }|json_encode }}">
    {% if item.inList %}
        Remove from wishlist
    {% else %}
        Add to wishlist
    {% endif %}
</button>
```

**Comment by bencroker** [comment]
Could the issue be with how you are calling `->all()` which returns the products, instead of the product query? Try this instead.

```php
    public function getBooks()
    {
        return Product::find()->limit($this->limit);
    }
```

**Comment by stevendierick** [comment]
Unfortunately the issue remains. I've tried both ways, even with and without `->limit()` and `->all()`.

**Comment by bencroker** [comment]
It's working for me locally, so I don't know what the issue might be. I notice that there's no real reason to have `books` as a Sprig component, since it contains no reactive elements (in your provided code). Perhaps making it a regular template and simplifying things makes more sense?

**Comment by stevendierick** [comment]
That's strange. I've simplified the provided code of the component class and templates to the bare minimum. The full code contains functionality to filter based on categories, order by, etc. Even with the simplified code, I cannot get the wishlist toggle working. I've made a short recording of what's actually happening on the front-end on my side.

https://share.cleanshot.com/UAsdHVwYWpem00eFtJnC

**Comment by bencroker** [comment]
Well I don't see any errors in your video, until you open the URL in a new tab which is to be expected since it is missing the posted parameters. So what exactly is the issue?

**Comment by stevendierick** [comment]
Ah, makes sense! I thought that error was because my code was failing.

The issue is the Wishlist component isn't adding/removing the product to the wishlist. In the video you can see, when I click "Add/Remove to wishlist", the Wishlist component refreshes and replaces the wishlist button with all of the products, it's not even adding/removing the product to the wishlist.

If you use the Twig example, this works perfectly fine. But we're trying to get this working with the component class.

**Comment by bencroker** [comment]
I see what was going on, fixed in https://github.com/putyourlightson/craft-sprig-core/commit/5c6b72e1f11e014d35b0d1b4931d90206a837244, you can test by running `composer update`. Let me know if that resolves it for you.

**Comment by stevendierick** [comment]
Yes, the update resolves it. Works like a charm now! Thanks @bencroker!
