### ISSUE TITLE
Complex view using multiple filters

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#244]
I have a form with multiple filters:

- A list of tag or categories that can be clicked;
- A list of pre-defined dates range (today, tomorrow, next week, ...);
- A free text input, where the keywords are filled in;

At first, these filters are not combined: using one filter is replacing the results of the other.

**Can sprig suit this complex setup?**

Because as example of the current state:

- We can only define one variable, which is linked to the field (its name): this is an issue for the query, if we have multiple input/buttons/options;
- We can't refresh the view after clicking the value of a button or dropdown field;

**Comment by bencroker** [comment]
Yes it should be able to, be sure to watch the Sprig filters videos at https://putyourlightson.com/sprig/videos#sprig-filters

**Comment by romainpoirier** [comment]
Thank you, I'll check it out if it's not missing a few needs. By any chance, would you share the source code?

**Comment by bencroker** [comment]
All components' source code is available to sponsors, as per the videos page.
