### ISSUE TITLE
Logic inside sprig component when using Blitz

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#245]
I'm using Sprig with Blitz on an ecommerce site.

On a product page I have sprig loading in a price for the product. Inside the sprig component it will load either the current price or the sale price based on user group rules.

Depending on what is cached with Blitz first the component will show a brief flash of either the onSale price or current price.

It could be me mistreating/forgetting fundamentals of both these plugins again?

Note I do intend in future to have all the product detail as one sprig component but as i have a good few sprig components on one page and they don't load in asynchronously, I think maybe its the lag of the se pending sprig holding up the logic inside this component?

_product.twig_

```
{% if activeProductVariant %}
	<h4 >
	{{ sprig('_components/price', {
			activeProductVariant:activeProductVariant.id,
		}, {id: 'groupPrice', 's-trigger': 'load'}) }}
	</h4>
{% endif %}
```

__components/price_

```
{% set activeProductQuery = craft.variants().id(activeProductVariant) %}

{% if activeProductQuery %}

	{% set activeProductVariant = activeProductQuery.one() %}

		{% if activeProductVariant.onSale %}
			<span class="price-discounted">{{ activeProductVariant.salePrice|commerceCurrency('USD', true) }}</span>
		{% else %}
			{{ activeProductVariant.price|commerceCurrency('USD', true) }}
		{% endif %}

{% endif %}
```

I will send you live URL via Discord

**Comment by john-henry** [comment]
Craft 3, Blitz 3.12.4 and Sprig 1.13.0

**Comment by bencroker** [comment]
This livestream shows how to use Sprig to inject dynamic content into statically-cached pages, including discussion about the exact scenario you describe. Please watch and let me know if you need any further help.
https://craftquest.io/livestreams/dynamic-content-on-statically-cached-pages

**Comment by john-henry** [comment]
Thanks. Will give it a look
