### ISSUE TITLE
Catch the old value and compare it with the new one.

### ISSUE THREAD

**Issue by jackabox** [putyourlightson/craft-sprig#246]
Hey,

I have a select that's being submitted with sprig. Once submitted, I want to try and compare the old value to the new one passed and see if there are any changes to the variable so I can reset other data in the component.

Every time I submit, the input appears to be resetting back to null and not remembering what it used to be. 

Is there any way to preserve variables between refresh? 

I am trying to attempt something like this:

```
{% set productAges = productAges ?? null %}
{% set productAgesOld = productAgesOld ?? null %}

{% if productAges != productAgesOld %}
	{% set productRanges = [] %}
	{% set productDietary = [] %}
{% endif %}

{% set productAgesOld = productAges %}
```

**Comment by bencroker** [comment]
Storing values in hidden inputs is the easiest way to persist data across requests.

**Comment by jackabox** [comment]
@bencroker Doh, that's painfully obvious now! Thanks for the quick response.
