### ISSUE TITLE
Update results when clicking the <input type="search">'s reset icon

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#248]
I guess this is more a htmx thing, but when using a `<input type="search">` input, the native reset cross icon that appears inside the corner of the field is not reactive.

I mean, this clear the input value as expected, but does not update the results like the `s-trigger` does on `keyup`:
`<input type="search" id="keywords" name="keywords" value sprig s-trigger="keyup changed delay:300ms" s-replace="#results" placeholder="keywords" autocomplete="off" spellcheck="false">`

I would like it to update the results like if we erase all the text in the field. How can I do, while maintaining the update on `keyup`? On top of that, I need that the `?page=x` query param is reset, so removed from the URL.

The demos in the doc are using simply `<input type="text">` instead of `<input type="search">` inputs.

**Comment by bencroker** [comment]
A `search` event is fired whenever the search input field is cleared, which you can listen for using `s-trigger="keyup changed delay:300ms, search"`.

**Comment by romainpoirier** [comment]
Thank you!

 It works, excepted for this:

> On top of that, I need that the ?page=x query param is reset, so removed from the URL.

How to reset the pagination query, as on a new search than on a reset of the search?

**Comment by bencroker** [comment]
Just use Twig as normal.

```twig
{% if search == '' %}
    {% do sprig.pushUrl('?') %}
{% endif %}
```

**Comment by romainpoirier** [comment]
Perfect! That works when the input is cleared.

I've a few more questions:

1. How can I put it to the end of the current path instead of the base URL? I tried this, but this is getting unwanted sprig paths instead: `{% do sprig.pushUrl(craft.app.request.getFullPath ~ '?') %}`;
3. Is there any function to totally clear the path instead of adding a `?` empty query? `sprig.pushUrl()` doesn't accept an empty parameter;
4. When I'm browsing at page `x`, and type new search keywords, the results are updated but not the URL which keeps the previous active page number in URL. How can I force it to reset to new page result? So, page 1, but keeps the pagination working when browsing the other pages;

**Comment by bencroker** [comment]
1. `{% do sprig.pushUrl('?') %}` will set the URL to the current path, with `?` at the end.
2. Not that I know of.
3. See the video series on Sprigboard, which contains both a search field and pagination: https://putyourlightson.com/sprig/videos#sprigboard

**Comment by romainpoirier** [comment]
I was asking this because `{% do sprig.pushUrl('?') %}` within the `{{ sprig() }}` template was replacing the entire path with `?`, so I was getting `website.dev/?` instead of `website.dev/section?`. Adding `{% do sprig.pushUrl('?') %}`  before/inside/after the sprig form did the same result. I finally found this solution (or workaround) bellow.

Pass `craft.app.request.getFullPath` as param to the `{{ sprig() }}` template:
```
{{ sprig('_sprig/agenda', {
	path: craft.app.request.getFullPath,
	limit: 5
}) }}
```

Within the `{{ sprig() }}` template, add this on top of the file:
```
{% if page ?? 1 == 1 %}
	{% do sprig.pushUrl(path) %}
{% endif %}
```

This make the path working correctly, and on top of that I'm not getting the unwanted `?` empty query param.
This is a simple reset solution, as I'm not dealing with other query params that the `?page=x`.
