### ISSUE TITLE
Blitz & Sprig cart not updating dynamically.

### ISSUE THREAD

**Issue by mattgeminiworktops** [putyourlightson/craft-sprig#249]
Good morning.
As discussed on Discord, I am having some difficulty trying to use Blitz and Sprig. I am trying to update the cart icon in my header to display the correct number of items in the cart. I am using s-trigger:load, which is working and ensuring that the cart qty is correct on every page load. The difficulty is when using the Add to Cart button. I would like this to update the cart widget dynamically so as soon as it is pressed, the number in the cartWidget in the header changes. I've stripped most of the code out below.

**Header** 
```twig
<header>{{ sprig('shop/cart/cartWidget', {}, { 's-trigger':'load'}) }} #}</header>
```

**Cart icon/cartWidget**
```twig
<div id="cart-icon">
{% if sprig.isRequest %}
 {% if cart.lineItems | length %}
<span class="absolute right-0 top-0 rounded-full bg-primary w-4 h-4 top right p-0 m-0 text-white font-mono text-xs leading-tight text-center">{{ cart.lineItems | length }}</span>
{% else %} 
SVG ICON
{% endif %}
```

**Add to cart button** 
```twig
<form sprig s-method="post" s-action="commerce/cart/update-cart">
  <input type="hidden" name="purchasableId" value="{{ variant.id }}">
  <button type="submit">
   FREE SAMPLE
  </button>
</input>
</form>

{% if addedToCart %}
            <script>htmx.trigger('#cart-icon', 'refresh');</script>
{% endif %}
```

I am using the Sprig Cart example so the code is pretty much identical. 
If Blitz is turned off, the above code works.

**Comment by bencroker** [comment]
Looks fine, except that you've overwritten the `refresh` trigger event from the cart component. 

This should help:

```twig
{{ sprig('shop/cart/cartWidget', {}, { 's-trigger': 'load,refresh' }) }} #}
```

**Comment by mattgeminiworktops** [comment]
Thank you - that works.
