### ISSUE TITLE
Pull value from input to use in s-vars

### ISSUE THREAD

**Issue by jsmrtn** [putyourlightson/craft-sprig#25]
Loving Sprig, it's proving to be a powerful addition for not only functionality but also time saving!

Is it possible to grab a value from an input to hand off to `s-vars` and `s-push-url`–something like the below.
```
<input class="border-2 border-gray-mid bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none w-full" type="search" name="f_search" placeholder="Search">
<button 
    sprig
    s-vars="f_keyterms:[name=f_search]" 
    s-push-url="?f_keyterms=[name=f_search]"
>
    Search
</button>
```

Examples on htmx utilise `hx-post`, but I don't want to be making a post request. In my use-case I am building out a stack of filters, like so:

```
{% set f_dates = craft.app.request.getParam('f_dates') ?? null %}
{% set f_keyterms = craft.app.request.getParam('f_keyterms') ?? null %}

{% for date in dates %}
    <span
        sprig 
        s-vars="f_dates:'{{ f_dates }},{{ date }}',f_keyterms:'{{ f_keyterms }}'" 
        s-push-url="?f_dates={{ f_dates }},{{ date }}&f_keyterms={{ f_keyterms }}"
    >
        {{ date }}
    </span>
{% endfor %}

<input type="search" name="f_search" placeholder="Search">
<button 
    sprig
    s-vars="f_dates:'{{ f_dates }}',f_keyterms:[name=f_search]" 
    s-push-url="?f_dates={{ f_dates }}&f_keyterms=[name=f_search]"
>
    Search
</button>
```

![2020-09-04 16 24 08](https://user-images.githubusercontent.com/1694957/92256124-36992780-eecb-11ea-93a2-ef9646cb801a.gif)

So you can build up a list of various filters–and I want to be able to pass the value of the input into the list of filters, too

Thanks!

**Comment by bencroker** [comment]
I'd recommend reading about how [component variables](https://putyourlightson.com/plugins/sprig#component-variables) work in Sprig work if you haven't already.

Instead of:
```twig
{% set f_keyterms = craft.app.request.getParam('f_keyterms') ?? null %}
```

You can write:
```twig
{% set f_keyterms = f_keyterms ?? null %}
```

And if you want the value of the input field to be assigned to the variable `f_keyterms` then I would suggest you simply rename the input field, as that will then become available as a variable when the component is refreshed:
```twig
<input type="search" name="f_keyterms" placeholder="Search">
```

**Comment by jsmrtn** [comment]
Cool, thanks Ben. The below is sending the value of the field to `s-vars` and is available on the parent template, but how can I get it into `s-push-url` too, so the URL can be shared or other filters can be chained?

```
<input type="search" name="f_keyterms" placeholder="Search">
<button 
    sprig
    s-vars="f_keyterms:'{{ f_keyterms }}" 
    s-push-url="?f_keyterms={{ f_keyterms }}"
>
    Search
</button>
```
When I commit a search, the URL doesn't seem to be updated with the variable `whats-on?f_dates=&f_keyterms=`, but the `f_keyterms` variable to the component is available and loads correctly

![Screenshot 2020-09-07 at 12 30 50](https://user-images.githubusercontent.com/1694957/92383328-08535c00-f106-11ea-846d-cfe8dbe64794.png)

However if I then select a different filter, the URL gets correctly updated to `whats-on?f_dates=01.01.2020&f_keyterms=12345`, but the `f_keyterms` variable stops being available in the component

![Screenshot 2020-09-07 at 12 31 07](https://user-images.githubusercontent.com/1694957/92383383-202ae000-f106-11ea-9a7f-63ad49e25db6.png)

If I reload the page with the URL params intact then both of the filters show correctly.

**Comment by bencroker** [comment]
The input field is what is holding and sending the value of `f_keyterms`, not the `s-vars` attribute.

Given your markup, I'm not sure whether you can use `s-push-url` to dynamically push a value into the URL from another element. You may want to read up on [hx-push-url](https://htmx.org/attributes/hx-push-url/) and you could ask in the [htmx discord server](https://htmx.org/talk), but you may find yourself having to use [htmx events](https://htmx.org/reference#events) to achieve this. Check out the example at https://putyourlightson.com/sprig-cookbook#refreshing-components

**Comment by bencroker** [comment]
FYI a new [sprig.pushUrl](https://putyourlightson.com/plugins/sprig#sprig.pushurlurl) function has been added in 1.1.0.

```twig
{% do sprig.pushUrl('?page=' ~ page) %}
```
