### ISSUE TITLE
Nested Components with Dynamic Content

### ISSUE THREAD

**Issue by johnj24** [putyourlightson/craft-sprig#250]
Hello, Ben. I'm just getting started using Sprig for a client and I wanted to thank you for all the hard work put into this plugin.

What I'm trying to do, and failing, is filtering entries by category and each entry has dynamic content when clicked. What's happening is when the filter is clicked, the dynamic content shows because it's within `{% if sprig.isRequest %}`.

Without going too far into the weeds, here's a high-level illustration of what I mean. You'll see a small amount of AlpineJs sprinkled in to show the overlay.

page.twig
```
{{ sprig('_sprig/portfolio', {
  entryId: entry.id
}) }}
```

_sprig/portfolio.twig
```
{% set entry = craft.entries.id(entryId).one() %}
<div>
  {% set categories = entry.displayCategories.all() %
  {% for category in categories %}
    <button sprig s-val:categoryId="{{ category.id }}">{{ category.title }}</button>
  {% endif %}
</div>

<div class="grid">
  {% set properties = craft.entries.({
    relatedTo: categoryId,
    section: 'properties'
  }).all() %}
  
  {% for property in properties %}
    {{ sprig('_sprig/property-overlay', {
      propertyId: property.id
    }, {
      id: property.id
    }) }}
  {% endfor %}
</div>
```
_sprig/portfolio-overlay.twig
```
{# These are the property cards that appear on the portfolio page #}
{% set property = craft.entries.id(propertyId).one() %}
{% if sprig.isInclude %}
  <a href="" sprig s-target="#portfolio-content-{{ property.id }}" s-swap="innerHTML" @click="showPropertyOverlay = !showPropertyOverlay"></a>
  <div x-show="showPropertyOverlay">
    <div id="portfolio-content-{{ property.id}}"></div>
  </div><!--/property overlay -->
{% endif %}

{% if sprig.isRequest %}
  {{ sprig('_views/details/property', {
    entryId: property.id
   }) }}
{% endif %}
```

_views/details/property.twig
**This is what is showing when I click a filtering button because the sprig request is already happening in a parent template.**
```
{# This is what appears in the portfolio overlay #}
{% set entry = craft.entries.id(entryId).one() %}
[property details]
```

My first question is: am I overcomplicating this? Do I need to include 3 sprig components? If this is actually an ok way to implement it, is there any way to keep the sprig request from passing into a child component?

**Comment by bencroker** [comment]
Hi John, if you've watched my videos at https://putyourlightson.com/sprig/videos, then you'll likely have heard me say that I always recommend using as few components as possible. If something doesn't _have_ to be a component, make it an include. It's hard to tell from they code above why exactly you have nested components 3 levels deep, but to me this is an immediate red flag. See if you can do it all with a single component and then, if you must, add child components.
