### ISSUE TITLE
How we can pass object to sprig component ?

### ISSUE THREAD

**Issue by vinodsnayvik** [putyourlightson/craft-sprig#252]
I want to pass current entry object to sprig component but it is giving error
```
The variable `casecategories` is an object and cannot be passed into a Sprig component.
Instead of passing an object, consider converting it to a string.
```
How i can fix it ?

**Comment by bencroker** [comment]
As the error implies, you cannot pass an object into a component. Consider either running the query to fetch categories inside the component, or if you must then pass array of category IDs into the component and then use them to fetch the categories using an element query.
