### ISSUE TITLE
Updating Sprig component state with DOM state set from local storage

### ISSUE THREAD

**Issue by braedenfoster** [putyourlightson/craft-sprig#253]
I am implementing a product filter using craft categories, in this case I am creating a brand filter.

The state is being updated correctly in DOM via Sprig by tracking the default input checkbox event.
Additionally, I am persisting the state of the checkboxes by using AlpineJs and the Persist plugin, however I am unsure of how trigger an update of the sprig component from Javascript on the component  being mounted.

Here is the code snippet:

```javascript
<ul class="text-sm flex flex-col gap-4 text-black mt-8 ml-4">
        {% for brand in productBrands %}
            <li class="flex gap-3 items-center">
                <input sprig
                    x-data="{isChecked: $persist(false).as('brand-{{brand.id}}')}"
                    x-init="
                     // Update State here possibly?
                    "
                    id="brand-{{brand.id}}"
                    name="brands[]"
                    value="{{brand.id}}"
                    @click="isChecked = !isChecked"
                    class="check"
                    type="checkbox"
                    :checked="isChecked"
                />
                <label for="brand">{{brand.title}}</label>
            </li>
        {% endfor %}
</ul>
```
I appreciate any help with this issue.

**Comment by bencroker** [comment]
Have you tried setting `s-trigger` to `load, refresh` on the component, as explained at https://putyourlightson.com/plugins/sprig#component-attributes, in order to trigger the component to refresh itself on load?

**Comment by braedenfoster** [comment]
Thank you so much for the swift reply. Your suggestion worked like a charm! Now the component re-renders with the local store data.

**Comment by bencroker** [comment]
Great!
