### ISSUE TITLE
s-listen only updates once

### ISSUE THREAD

**Issue by russback** [putyourlightson/craft-sprig#255]
I have a Commerce site with a cart count in the header.

`_partials/store/basketCount`:

```
{% set order = craft.orders.id(orderId).one %}

{% if not order %}
    {% exit 500 %}
{% endif %}

<div>
    Cart count = {{ order.totalQty }}
</div>
```

`_partials/store/basket`:

```
<div id="basket">
    {# functioning commerce cart form updating as expected with sprig #}
</div>
```

Layout:

```
{{ sprig('_partials/store/basketCount', { orderId: cart.id }, {'s-listen': '#basket'}) }}
```

When the cart (`#basket`) is first updated, the listening component updates. On subsequent updates, no update occurs.

- Craft v4.2.2
- Sprig v2.1.0

**Comment by bencroker** [comment]
You should be listening on the entire basket component, rather than a specific `div` inside it, which will be overwritten on each cart update. So putting the ID on the component (instead of inside the component) should solve this for you.

```twig
{{ sprig('_partials/store/basket', { }, { 'id': 'basket' }) }}
```

**Comment by russback** [comment]
Makes sense - thanks.

**Comment by russback** [comment]
@bencroker should this listen to multiple components? For example:

More than one of these:

```{{ sprig('_partials/store/basket', { }, { 'class': 'add-to-basket' }) }}```

Listened to by this:

```{{ sprig('_partials/store/basketCount', { orderId: cart.id }, {'s-listen': '.add-to-basket'}) }}```

**Comment by bencroker** [comment]
I'd expect it to, yes.
