### ISSUE TITLE
How to update a field before submitting a form

### ISSUE THREAD

**Issue by russback** [putyourlightson/craft-sprig#256]
Is it possible to achieve the following with Sprig?

1. User is viewing a Commerce basket (sprig component).
2. User clicks remove button on a line item
3. Confirm prompt fires to check user wishes to remove item
4. If user confirms, a hidden field's value is updated
5. Form is submitted to update basket
6. Component is refreshed

**Comment by bencroker** [comment]
Step 4 (a hidden field's value is updated) sounds like it would require JavaScript, but everything else sounds very doable with Sprig. See the Sprigcart videos for an explanation at https://putyourlightson.com/sprig/videos#sprigcart
