### ISSUE TITLE
Change how Sprig constructs its action URL

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-sprig#257]
Hi Ben,

we use Spring in our project but our Craft server is behind a proxy server and the action URLs Sprig is using are not routed to the Craft server.

Is: `https://<proxy server>/index.php/?p=actions/sprig-core/components/render&term=donau&status=&view=card&limit=9&sprig%253AsiteId=e81da0f9429668efd3e909d0b477c1924266926f3ffc46bf2f8a8793e7d72cc91&sprig%253Atemplate=bd06d5cc1e1c37a44e3c95a6b262d00330d51a1bd67e7412359fe03bd1928470_partials%252Fpatterns%252Fproject%252Fproject-search`

Our project can be reached with
`https://<proxy server>/<dirname>/`

Do you know if there is an easy way to change the action URL? Could it be e.g. `https://<proxy server>/<dirname>/?p=actions/...`

Is this even a SPRIG setting or some Craft basic configuration?

Thanks,
Matthias

**Comment by bencroker** [comment]
The action URL is determined by Craft. Is your site URL correctly set? How do other action URLs appear in your site?

**Comment by hiasl** [comment]
The Site URL is correctly set, it's https://<proxy server>/<dirname>/, all entry's URIs are created using this Site URL.
We currently do not have other action URLs in the site, only Sprig, and the CP has it's own domain which is fully routed to Craft but is not externally available and also not meant to be used for the Frontend.
I found `actionTrigger` in Craft's config, but I guess this is just the name of the GET param...

**Comment by hiasl** [comment]
OK, when I change the `actionTrigger` to e.g. `XXX`, it modifies my `p` GET var to XXX

`https://<proxy server>/index.php/?p=XXX/sprig-core/components/render...`

Should Craft/Sprig normally use the Site URL when building action URLs? Because the action URL looks like the URL after it's rewritten by the webserver...

**Comment by hiasl** [comment]
But I guess this issue is not SPRIG specific so unless you have a little hint for me, you can close this.

**Comment by bencroker** [comment]
This is not Sprig specific. You could try setting the `omitScriptNameInUrls` general config setting to `true`, not sure if that will make a difference though. Otherwise contacting Craft support might be your best bet.

**Comment by hiasl** [comment]
I have another question: Do you have any idea, why SPRIG action URLs are created as `<Site URL>/index.php?p=actions/... `but e.g. image transformation URLs as `<Site URL>/actions/...`

Because if Sprig created its actions URLs the second way then my problem would be gone.

**Comment by bencroker** [comment]
Sprig uses the `UrlHelper::actionUrl` method, perhaps image transforms us something else. Did you try setting `omitScriptNameInUrls` to `true` as I suggested above? 

It might help due to this: https://github.com/craftcms/cms/blob/3e0dd9a82bc1170ceeeaf139a1a4084a3466531c/src/helpers/UrlHelper.php#L613

**Comment by hiasl** [comment]
yes, I tried setting omitScriptNameInUrls to true:
 - Sprig URLs stayed the same (with index.php?...) 
 - after having removed omitScriptNameInUrls again, image transforms were still prettyfied/rewritten and Sprig URLs again kept the index.php?...

But I will try again, maybe there was an error on my side

**Comment by hiasl** [comment]
Here is what I have learned to get pretty action URLs in Sprig (and Craft):
- config option `omitScriptNameInUrls` must be set to `true` AND
- `pathParam` must be set to `null`

because this is what happens inside of Craft's `actionUrl` method:
```
        // Default to showing index.php if there's a pathParam
        if ($showScriptName === null) {
            $showScriptName = (bool)$generalConfig->pathParam;
        }
```

**Comment by bencroker** [comment]
Great, thanks for sharing!!
