### ISSUE TITLE
Change multiple text inputs from one dropdown

### ISSUE THREAD

**Issue by AbbeyDesign** [putyourlightson/craft-sprig#259]
I have this code and I am close but it only changes one input field. I need it to change more than one. This is a dumbed down version of the code. The dropdown option has two s-val items; cpt and price. Currently my code only changes the cpt, not the price. I am assuming it is the "name" on th select line.

```
<select sprig s-replace="#cptcode" name="cpt" class="form-select">
        <option value="">
          Code
        </option>
        {% for option in cpt_options %}
          <option s-val:cpt="{{ option.id }}" s-val:price="{{ option.number_price }}" {{ option.id == cpt ? ' selected' }}>
            {{ option.title~' : '~option.description }}
          </option>
        {% endfor %}
</select>
<div id="cptcode">
      <input type="text" name="fields[description]" value="{{ cpt }}"/>
      <input type="text" name="fields[billed]" value="{{ price }}"/>
</div>
```

**Comment by AbbeyDesign** [comment]
I figured it out, I needed to add "sprig" on the "<option>" line.

```
<option sprig s-val:cpt="{{ option.id }}" s-val:price="{{ option.number_price }}" {{ option.id == cpt ? ' selected' }}>
   {{ option.title~' : '~option.description }}
</option>
```

**Comment by AbbeyDesign** [comment]
So though this works. There is some weirdness with what is getting replaced. It seems to add duplicate text input fields when an option is selected. So the issue must be with my s-replace approach. Any suggestions?

**Comment by AbbeyDesign** [comment]
Removing "s-replace" from the select altogether fixed it.

**Comment by bencroker** [comment]
Great!
