### ISSUE TITLE
Prevent nested component from refreshing parent

### ISSUE THREAD

**Issue by pimago** [putyourlightson/craft-sprig#260]
I know nesting components is not the best thing to do. But I am not sure if this is already a nesting issue.
I have a list of users in a component that's loading more users like so https://github.com/putyourlightson/craft-sprig/issues/164
Each user has two nested components. A button and a number. The button should refresh the number. They are separated because there are things between them. And I would like to reuse them on other parts.

So when I press the follow button not only the followNumber is refreshed but also the parent userList component. Is that normal or am I doing something wrong?
This is a simplified version of my components.

```twig
{#-- main --#}
<main>
    {{ sprig('_components/userList') }}
</main>


{#-- _components/userList --#}
{% for user in users %}
    <div>
        <div>
            {{ sprig('_components/followNumber', {
                _userId: user.id
            },{
                'id': 'user'~user.id
            }) }}
        </div>
        <div>other things</div>
        <div>
            {{ sprig('_components/followButton', {
                _userId: user.id
            }) }}
        </div>
    </div>
{% endfor %}


{#-- _components/followNumber --#}
{% set user = craft.users().id(_userId).one() %}
{{user.totalFollowers}}


{#-- _components/followButton --#}
{% set followee = craft.users().id(_userId).one() %}

{% if success is defined and success %}
    <script>
        {# update the followNumber component #}
        htmx.trigger('#user{{followee.id}}', 'refresh');
    </script>
{% endif %}

<input type="hidden" name="followeeId" value="{{ followee.id }}">
<button sprig s-method="post" s-action="inter-action/follower/follow">Follow</button>
```

**Comment by bencroker** [comment]
> So when I press the follow button not only the followNumber is refreshed but also the parent userList component. Is that normal or am I doing something wrong?

That shouldn't happen. I suggest you switch to using [s-listen](https://putyourlightson.com/plugins/sprig#s-listen), which should simplify your component somewhat and hopefully make things work as you expect them to.

**Comment by pimago** [comment]
Thanks Ben. Yes it's working. Could it have any performance issues if a user would scroll through hundreds of users, and then load hundreds of listening components?

**Comment by bencroker** [comment]
No, scrolling through the page doesn't load more components, they are rendered on page load.

**Comment by pimago** [comment]
I meant because I am loading more users with s-trigger="revealed". Like this https://github.com/putyourlightson/craft-sprig/issues/164

**Comment by bencroker** [comment]
Right but you're loading more users in batches, right? Not individually?

**Comment by pimago** [comment]
Yes around 15-20

**Comment by bencroker** [comment]
So each batch will be a single database query, which should be fine for performance, but you should definitely have the Network tab open when testing this.

**Comment by pimago** [comment]
Alright thanks!

**Comment by aleximajine** [comment]
@bencroker  Hi, I'm having the same issue, in my case I need to pass a value to the refresh, so I am doing this to refresh the documentPreview component

```
onclick="event.preventDefault();
htmx.find('#documentPreview input[name=documentPreviewUrl]').value = '{{ asset.url }}';
htmx.trigger('#documentPreview', 'refresh');
"
```

and after refresh is reloading the documentPreview's parent component too, if this shouldn't be happening, any idea what could be happening and how to solve it?

**Comment by pmarconi** [comment]
@bencroker Hi, I'm having the same issue, in my case I need to pass a value to the refresh, so I am doing this to refresh the documentPreview component

```
onclick="event.preventDefault();
htmx.find('#documentPreview input[name=documentPreviewUrl]').value = '{{ asset.url }}';
htmx.trigger('#documentPreview', 'refresh');
"
```

and after refresh is reloading the documentPreview's parent component too, if this shouldn't be happening, any idea what could be happening and how to solve it?
