### ISSUE TITLE
Load more pagination fails to show next entries when query is using relations

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#261]
# Steps to reproduce the issue.

I've an entries' query which is a little bit more complex than in the example, as it's filtering using `section` and `categories`.
The entries are filtered using sprig checkbox inputs that send the data to the entries query, which should then be paginated.

Below is a reduced test case of my code.

### Section template
```twig
{{ sprig('_sprig/events', {
	limit: 3,
	base: entry.url
}) }}
```

### Sprig template
```twig
{% set offset = offset ?? 0 %}
{% set entries = craft.entries.section((sections ?? null is not empty) ? sections : ['events', 'museums']).andRelatedTo(categories ?? []).with(['category', 'cover']).offset(offset).limit(limit) %}

{% for option in [{
	type: 'sections',
	id: 'events',
	title: 'Events' | t
}, {
	type: 'sections',
	id: 'museums',
	title: 'Museums' | t
}] | merge(craft.categories.group('categories').relatedTo(craft.entries.section(['events', 'museums']).ids()).all() | map((value, key) => {
	type: 'categories',
	id: value.id,
	title: value.title
})) %}
	{{ tag('input', {
		sprig: true,
		type: 'checkbox',
		id: '{type}-{i}' | t({
			type: option.type,
			i: loop.index
		}),
		name: '{type}[]' | t({
			type: option.type
		}),
		value: option.id,
		checked: (option.id in sections ?? [] or option.id in categories ?? []) ? 'checked',
	}) }}
{% endfor %}

{% for entry in entries.all() %}
	<div id="entries">
		{% set attr = {
			href: '{base}/{slug}' | t({
				base: base,
				slug: entry.slug
			})
		} %}
		<a {{ attr(attr) }}>
			{{ entry.title }}
		</a>
	</div>
{% endfor %}

{% if entries.count() > offset + entries.all() | length %}
	{% set attr = {
		id: 'load-more-oob',
		sprig: true,
		's-vals': {
			offset: (offset + limit) - 1,
			sections: sections ?? [],
			categories: categories ?? []
		} | json_encode,
		's-target': '#entries',
		's-select': '#entries a',
		's-swap': 'beforeend',
		's-swap-oob': (sprig.trigger == 'load-more-oob') ? 'true'
	}%}
	<button {{ attr(attr) }}>
		{{ 'Load more' | t | typogrify }}
	</button>
{% else %}
	<button id="load-more-oob" s-swap-oob="true"></button>
{% endif %}
```

# A clear and concise description of what you expected to happen.

When the view is filtered using the `sections` ones, so first options, the pagination is working fine.
When the view is filtered using the `categories` ones, it shows the first correctly, the show more button, but when clicking on it I get an empty content.

I tried to debug by adding this after `<div id="entries">`:
```twig
{{ d({
	entriesCount: entries.count(),
	offset: offset,
	entriesAllLength: entries.all() | length,
	limit: limit,
	loadMore: entries.count() > offset + entries.all() | length,
	sections: (sections ?? null is not empty) ? sections : ['events', 'museums'],
	categories: categories ?? []
}) }}
```
While `entriesCount` is correct, and `loadMore` is `true`, the next entries are not showing and then the load more button disappears.

I also tried to simplify the `entries` query and options, by removing the `section` filter:

- Removing `.section()` from `craft.entries` and change `andRelatedTo` to `relatedTo`;
- Removing `events` and `museums` from the options;

But I finally end with the same problem: load more button is showing, but clicking on it load an empty content + hide the load more button.

It looks like there's a bug with Sprig when playing with relation (`relatedTo` or `andRelatedTo`).

# The plugin and Craft version numbers

- `craftcms/cms`: `4.2.3`
- `putyourlightson/craft-sprig`: `2.1.0`

**Comment by bencroker** [comment]
I looked through your code but it is far too complex and use-case specific for a bug report. Can you provide the simplest possible Sprig component that demonstrates this, so I can test and debug this locally?

**Comment by romainpoirier** [comment]
Thank you. It's already a reduced test case, if I simplify it, it would maybe not end with the expected result.

But I think you can mostly focus on this:
`{% set entries = craft.entries.relatedTo(categories).offset(offset).limit(limit) %}`

I'm filtering using categories, and it seems to be the issue: there's a bug where the load more button is showing, but the content is not added. This does not happen when not using `relatedTo()`, and for example filter by `section()`.

**Comment by bencroker** [comment]
As it is, the code is so specific that I cannot replicate locally. If you're claiming this is a bug in Sprig, please provide a test-case that I can work with. Otherwise, if the `relatedTo` parameter is not working as expected then perhaps that's a bug with Craft itself.

**Comment by romainpoirier** [comment]
Ok I understand. Below is the minimal setup to reproduce it. I can't delete more code, as it would not reproduce it.

### Setup

1. Create a new category group (`/admin/settings/categories`), and add at least two categories
2. Create a new Channel with a few entries
3. On each entry, add a Category field that will add some of the categories of the group previously created
4. Create the Section template + Sprig template (see code below), and start querying Channel's entries

### Section template
```
{{ sprig('_sprig/events', {
	limit: 3,
	base: entry.url
}) }}
```

### Sprig template (_sprig/events)
```
{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.relatedTo((categories ?? null is not empty) ? categories).offset(offset).limit(limit) %}
{% set entries = entryQuery.all() %}

{% for category in craft.categories.group('categories').all() %}
	{{ tag('input', {
		sprig: true,
		type: 'checkbox',
		name: 'categories[]',
		id: category.id,
		value: category.id,
		checked: (categories ?? null is not empty and category.id in categories) ? 'checked',
	} | filter) }}
	<label for="{{ category.id }}">
		{{ category.title }}
	</label>
{% endfor %}

<div id="entries">
	{% for entry in entries %}
		<div>
			{{ entry.title }}
		</div>
	{% endfor %}
</div>

{% if entryQuery.count() > offset + entries | length %}
	{% set attr = {
		id: 'load-more-oob',
		sprig: true,
		's-val:offset': offset + limit,
		's-val:categories': categories ?? [],
		's-target': '#entries',
		's-select': '#entries div',
		's-swap': 'beforeend',
		's-swap-oob': (sprig.trigger == 'load-more-oob') ? 'true'
	}%}
	<button {{ attr(attr) }}>
		{{ 'Load more' }}
	</button>
{% else %}
	<button id="load-more-oob" s-swap-oob="true"></button>
{% endif %}
```

### Remarks
- This is an adaptation from the documentaiton: https://putyourlightson.com/sprig/cookbook?page=3#load-more-complex
- So here, considering you have more than 3 entries to filter, the `Load more` button is showing only when checkbox are not checked
- In the unfiltered view, I you click the `Load more` button, nothing is added
- But if you delete `.relatedTo((categories ?? null is not empty) ? categories)` from the entries query, this is working
- The `relatedTo` parameter is working fine outside of the Sprig's load more button use, so it should be more a bug related to Sprig that Craft

**Comment by bencroker** [comment]
Thanks! Can you try writing the query so that `relatedTo` is only added if a value exists, as follows?

```twig
{% set entryQuery = craft.entries.offset(offset).limit(limit) %}

{% if (categories ?? null) is not empty %}
    {% do entryQuery.relatedTo(categories) %}
{% endif %}
```

**Comment by romainpoirier** [comment]
Thank you. I tried it but unfortunately without any change.

**Comment by bencroker** [comment]
Can you try removing this line?

```twig
		's-val:categories': categories ?? [],
```

**Comment by romainpoirier** [comment]
Removing this give fix this at least: on init, I can now click the _load more_ button to get more entries.

But after clicking the checkboxes to start filtering, the load more button disappears while the condition `entryQuery.count() > offset + entries | length` is `true`.

So that's not fixing the _categories_ bug that get related entries.

**Comment by bencroker** [comment]
Can you try using the source code from the cookbook recipe that works? You've modified some things and I suspect something you've done has broken it.

```twig
{% if entryQuery.count() > offset + entries|length %}
  <button id="load-more-oob" sprig s-val:offset="{{ offset + limit }}"
    s-select="#entries div" s-target="#entries" s-swap="beforeend"
    {{ sprig.trigger == 'load-more-oob' ? 's-swap-oob="true"' }}
  >
    {{ 'Load more' }}
  </button>
{% else %}
    <button id="load-more-oob" s-swap-oob="true" style="display: none"></button>
{% endif %}
```

**Comment by romainpoirier** [comment]
Thank you, now that works! Don't know why it was still not working in my previous answer, but you were right that it seems that the issue was `'s-val:categories': categories ?? []` which is useless.

**Comment by bencroker** [comment]
Great!
