### ISSUE TITLE
Event filter expression

### ISSUE THREAD

**Issue by S-n-d** [putyourlightson/craft-sprig#262]
What I am trying to do is explained in the following stackoverflow htmx question: https://stackoverflow.com/questions/66301453/minimum-number-of-characters-before-hx-get

The expression used in the example of the answer does not seem to work with sprig. I'm using `s-trigger="keyup[target.value.length > 2]"` on my input element.

Is something like this possible with sprig?

**Comment by bencroker** [comment]
Please refer to https://github.com/putyourlightson/craft-sprig/issues/251 to see why it doesn't currently work with Sprig.

**Comment by S-n-d** [comment]
I'll look into that, thanks!
