### ISSUE TITLE
[delay:..] is not working as expected

### ISSUE THREAD

**Issue by vandres** [putyourlightson/craft-sprig#263]
Maybe I have a misunderstanding of that feature or it might be a bug.

I am understanding "delay" as a kind of debouncing of requests. So whenever one of the input events changes, the old request is reset or cancelled and a new request is initialized with the same delay.

In the current state, Sprig doesn't reset or cancel any requests. Instead it only delays the requests and fires then multiple requests with the same keyword. When a request is already sent to the server, that request is not canceled and still running. This can lead to the first request answering after the second request.

You can reproduce that behavior in the Cookbook:

![image](https://user-images.githubusercontent.com/1436383/191299041-d38c0510-3814-40ff-abce-7c095ef88abd.png)

**Comment by bencroker** [comment]
According to the docs at https://htmx.org/attributes/hx-trigger/...

> `delay:<timing declaration>` - a delay will occur before an event triggers a request. If the event is seen again it will reset the delay.

Since this functionality is provided by htmx, please consider opening a discussion about this at https://github.com/bigskysoftware/htmx/discussions

**Comment by vandres** [comment]
@bencroker Looking at this demo, I have the feeling it's working there: https://htmx.org/examples/active-search/

**Comment by bencroker** [comment]
Yes it is, but the same happens with Sprig. Try the demo at https://putyourlightson.com/sprig/demo/2, which has a delay of 300ms.
