### ISSUE TITLE
Indicator with delay or after validation

### ISSUE THREAD

**Issue by pimago** [putyourlightson/craft-sprig#265]
Hi, I am using s-indicator on a contact form and on a guest entries form. It's working fine.
When the forms do not validate the indicator shows for a few milliseconds.

Is it possible to load the indicator with a delay or after the form validation?

**Comment by bencroker** [comment]
Not that I know of, but since this feature is powered by [hx-indicator](https://htmx.org/attributes/hx-indicator/), you'd be best off asking in https://github.com/bigskysoftware/htmx/issues.
