### ISSUE TITLE
How to cache Sprig queries?

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#266]
I'm using Sprig in a multi-filters + load more setup and find it a bit laggy when dealing with a lot of entries.
Do Sprig cache filtered queries? If not, how can I do it efficiently?

**Comment by bencroker** [comment]
No, the whole point of Sprig is that you can fetch dynamic content from the server. If you want to cache content, I suggest you use Craft's cache tags or a plugin like [Blitz](https://putyourlightson.com/plugins/blitz).

**Comment by romainpoirier** [comment]
Thank you. I understand. Is it possible to cache Sprig dynamic content in any way? I understand it's dynamic, but it also means in a filtered view that a lot of similar queries would be requested by users. Are Craft native cache and Blitz suitable in this way? Do you have any example how to use the `{% cache %}` tag with the `{{ sprig() }}` include?

**Comment by bencroker** [comment]
You can use Craft's `cache` tag inside of Sprig components, which improve the performance of loading heavy element queries.
