### ISSUE TITLE
404 response in preview templates

### ISSUE THREAD

**Issue by WHITE-developer** [putyourlightson/craft-sprig#269]
When viewing a page in preview mode, all the sprig request are returning a 404 error `Template not found: actions/sprig-core/components/render`.
On a normal page the request are working. The only difference I see in the request is that in the preview templates an extra parameter is passed to the render method (token) but this parameter has a `null` value, I suspect something isn't going right there?

https://i.imgur.com/dSHNiYn.png
https://i.imgur.com/jlwv2yb.png

Craft CMS 4.2.5.2
Sprig version 2.2.0

**Comment by bencroker** [comment]
Thanks, I'll take a closer look and see if this is indeed a bug and whether we can release a fix for it soon.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-sprig-core/commit/6adcb8989dfea41bb6e355f157486052e2f336e2 and released in Sprig 2.2.1.
