### ISSUE TITLE
Access to XMLHttpRequest at '' has been blocked by CORS policy

### ISSUE THREAD

**Issue by darylknight** [putyourlightson/craft-sprig#27]
### Describe the bug

Hi Ben,

Firstly, thank you for putting so much work into this. I've been trying it out on a personal project to replace Vue. Feel free to close this if it's irrelevant or not something Sprig can fix, but I think I've run into a similar issue to #12 which is related to Laravel Mix (which uses browsersync to refresh the page on save).

I'm using the most basic search function to make the search results reactive. When I search the first time, it works. When I click it again, I get this when using localhost:3000 proxied from reviews.test:

![image](https://user-images.githubusercontent.com/1250017/93015113-704eea00-f5bf-11ea-8662-495f16848521.png)

```
Access to XMLHttpRequest at 'http://reviews.test/index.php?p=actions/sprig/components/render&title=test&sprig%3AsiteId=b095d4a19a0c1a2027bf7e2dd79af21c0c1c99fcdcfedfe39d5c1f05b455a6d91&sprig%3Atemplate=01545b53a327c60f491c2dbbf5185f4dc64793c242e1589b6a93e15514617b02_includes%2Ffilters' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

htmx-0.0.8.js?v=1599985028:1004 htmx:afterRequest
> logError @ htmx-0.0.8.js?v=1599985028:1004
> triggerEvent @ htmx-0.0.8.js?v=1599985028:1020
> triggerErrorEvent @ htmx-0.0.8.js?v=1599985028:985
> xhr.onerror @ htmx-0.0.8.js?v=1599985028:1608
> error (async)
> issueAjaxRequest @ htmx-0.0.8.js?v=1599985028:1606
> eventListener @ htmx-0.0.8.js?v=1599985028:710

htmx-0.0.8.js?v=1599985028:1004 htmx:sendError
> logError @ htmx-0.0.8.js?v=1599985028:1004
> triggerEvent @ htmx-0.0.8.js?v=1599985028:1020
> triggerErrorEvent @ htmx-0.0.8.js?v=1599985028:985
> xhr.onerror @ htmx-0.0.8.js?v=1599985028:1609
> error (async)
> issueAjaxRequest @ htmx-0.0.8.js?v=1599985028:1606
> eventListener @ htmx-0.0.8.js?v=1599985028:710

GET http://reviews.test/index.php?p=actions/sprig/components/render&title=test&sprig%3AsiteId=b095d4a19a0c1a2027bf7e2dd79af21c0c1c99fcdcfedfe39d5c1f05b455a6d91&sprig%3Atemplate=01545b53a327c60f491c2dbbf5185f4dc64793c242e1589b6a93e15514617b02_includes%2Ffilters net::ERR_FAILED
> issueAjaxRequest @ htmx-0.0.8.js?v=1599985028:1614
> eventListener @ htmx-0.0.8.js?v=1599985028:710
```

However, if I use the normal reviews.test (Laravel Valet), it works aboslutely fine. So I'm assuming it'll work fine in production, and this is specifically related to browsersync proxying the domain to localhost:3000.

**Comment by bencroker** [comment]
This is a CORS issue in which the cross-domain AJAX request is being blocked. To allow it, add either a domain specific or a wildcard `Access-Control-Allow-Origin` header in your local development environment only.

```
    location / {
        # CORS Rules
        add_header Access-Control-Allow-Origin *;

        try_files ...
    }
```
