### ISSUE TITLE
Slideout with Sprig & Alpine

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#270]
I'm trying to mimic the functionality in Craft with Editor Slideouts and address on the frontend of my site with Sprig & Alpine.

I have everything very close to working, but with my current code Sprig refreshes the entire template, meaning the slideout appears for a couple of milliseconds before disappearing again.

Here is my simplified template:

```
{% set addresses = currentUser ? currentUser.getAddresses() : [] %}
{% set addressId = addressId ?? null %}
<div x-data="{ slideout: false }" x-cloak>
{% if addresses | length %}
	<div>
		<div class="grid grid-cols-2 gap-8 mb-8">
			{% for address in addresses %}
				<div x-on:click="slideout = true" sprig s-val:addressId="{{ address.id }}">
					{{ address|address }}
				</div>
			{% endfor %}
		</div>
	</div>
{% endif %}

{% embed '_components/slideout' %}
{% block slideoutContent %}
	{% set address = craft.addresses().id(addressId).one() %}
	<form method="post">
		{{ csrfInput() }}
  		{{ actionInput('users/save-address') }}
		{{ hiddenInput('addressId', address.id) }}
		<!-- Edit address fields -->
	</form>
	{% endblock %}
{% endembed %}
	</div>
```

This might be an Alpine thing and delaying the slideout by a second or two (I've tried `x-transition.delay` but without success) but also curious if something can be done with Sprig? I've tried `s-target` but the fields inside the slideout also need to refresh so I'm not sure if I can get that to work.

Apologies if this is out of the scope of support.

**Comment by bencroker** [comment]
Have you tried using [s-replace](https://putyourlightson.com/plugins/sprig#s-replace) to only replace the portion of the template that needs to be updated?

**Comment by shifuma** [comment]
Ah man. You know, I did try that but...but obviously just on the wrong spot. Got it working now, thanks!
