### ISSUE TITLE
Set flash message

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#271]
I'm using Sprig for some Campaign subscribe/unsubscribe toggles like this:

```
<button sprig s-method="post" s-action="campaign/forms/unsubscribe" s-val:mailingList="{{ list.slug }}" s-val:email="{{ currentUser.email }}" s-target="#comms">
    Subscribe/Unsubscribe
</button>
```

Is there a way I can set a flash message when doing it this way? In my other forms I'm doing `{{ hiddenInput('successMessage', 'Success.'|hash) }}`.

Thanks for your support as always!

**Comment by mattstein** [comment]
You can move that `successMessage` input into an `s-val` and make sure you’re displaying the message in your template, sort of like the [Product Variant Switcher example](https://putyourlightson.com/sprig/cookbook#product-variant-switcher):

```html
{# Display the success message if we’ve got it #}
{% if success is defined %}
    {{ success ? flashes.notice : flashes.error }}
{% endif %}

{# Use an `s-val` to define the success message #}
<button sprig
  s-method="post"
  s-action="campaign/forms/unsubscribe"
  s-val:mailingList="{{ list.slug }}"
  s-val:email="{{ currentUser.email }}"
  s-val:successMessage="{{ 'Success.'|hash }}"
>
  Subscribe/Unsubscribe {{ currentUser.email }}
</button>
```

Be careful with your messaging there if the subscriber needs to verify their unsubscribe via email after this step!

**Comment by shifuma** [comment]
Thanks, @mattstein! Sorry, I'm probably doing something dumb, but I'm not able to get that work yet. I have a notification component template that I'm trying to show the success message in.

```
# _components/notification

{% set message = craft.app.session.getFlash('notice', null, true) %}
{% if message|length>0 %}
    <div class="notification">{{ message }}</div>
{% endif %}
```

This is just being included in my `_base/layout.twig` - maybe that's why? Does it need to be Sprigified?

**Comment by mattstein** [comment]
> This is just being included in my `_base/layout.twig` - maybe that's why? Does it need to be Sprigified?

It does indeed! If Sprig doesn’t know about `{% if success is defined %}`, there’s nothing it can do to help you. 😄

**Comment by shifuma** [comment]
Hmmm sorry this is probably super annoying, but I do have this in my subscribe/unsubscribe Sprig template:

```
<button sprig
  s-method="post"
  s-action="campaign/forms/unsubscribe"
  s-val:mailingList="{{ list.slug }}"
  s-val:email="{{ currentUser.email }}"
  s-val:successMessage="{{ 'Success.'|hash }}"
>
  Subscribe/Unsubscribe {{ currentUser.email }}
</button>

{% if success is defined %}
    {{ success ? flashes.notice : flashes.error }}
{% endif %}
```

But then to get that to talk to my `_components/notification` is where I'm lost 🙃

**Comment by mattstein** [comment]
I’m not sure what to tell you without wandering into your template layout—but you can use includes however you’d like. It’s probably easiest to make sure the button and the notification templates are handled by a common `{{ sprig() }}` include function higher up the chain.

Otherwise you’ll probably want to directly use [JavaScript](https://putyourlightson.com/plugins/sprig#javascript) to wire the message up to your element of choice.

**Comment by bencroker** [comment]
I second @mattstein's suggestion of using JavaScript to make this work for your use-case.

**Comment by shifuma** [comment]
Yep good shout. I'll keep learning and playing. Thanks for your help @mattstein!
