### ISSUE TITLE
Passing data between 2 sprig components

### ISSUE THREAD

**Issue by robzor** [putyourlightson/craft-sprig#274]
Hi Ben,

I have a product detail page where for slightly complicated reasons, I have a sprig component for each 'add to basket' row.

When a user adds a product to the basket, I want to open/trigger another sprig component to refresh which will show a 'you just added X product to the basket' and suggest some other related items.

So I am trying to pass the variantId and quantity from the 'add to basket row' sprig component to the 'product added to basket' sprig component.

Looking at [this previous discussion](https://github.com/putyourlightson/craft-sprig/issues/123) and the htmx docs has got me as far as:

Master template (not sprig):
```
{{ sprig('__components/_sprig/product-add-to-cart-popup', {
      lastProductAddedToCartId: craft.app.request.getParam('test1'),
      lastProductAddedToCartQty: craft.app.request.getParam('test2'),
    }, {'id': 'sprig-product-add-to-cart', 'class': 'product-add-to-cart-popup'}) }}
```

Add to row Sprig component:

```
{% if success is defined and success %}
    <script>
      // Refresh add to cart modal, pass the ID and Qty along with it
      htmx.trigger('#sprig-product-add-to-cart', 'refresh', {lastProductAddedToCartId: {{ variantId }}, lastProductAddedToCartQty: {{ qty }}});

    </script>
  {% endif %}
  ```
  
But I can't seem to actually _access_ these variables in the add to cart popup component with `{{ lastProductAddedToCartId }}` or `{{ lastProductAddedToCartQty }}`. 

In the console I can see this for the Payload of the refreshed popup component:
![CleanShot 2022-10-20 at 4 55 38](https://user-images.githubusercontent.com/704032/196998582-a8a438b4-1e75-4bc1-b148-0f36666315ca.png)

Am I missing something obvious here?

**Comment by bencroker** [comment]
I'd suggest first creating input fields in the `sprig-product-add-to-cart` component for each of the variables, assuming they don't already exist.

```twig
{{ hiddenInput('lastProductAddedToCartId', lastProductAddedToCartId, { id: 'lastProductAddedToCartId' }) }}
{{ hiddenInput('lastProductAddedToCartQty', lastProductAddedToCartQty, { id: 'lastProductAddedToCartQty' }) }}
```

And then populate their values before triggering a refresh.

```twig
{% if success is defined and success %}
    <script>
        htmx.find('#lastProductAddedToCartId').value = {{ variantId }};
        htmx.find('#lastProductAddedToCartQty').value = {{ qty }};
        htmx.trigger('#sprig-product-add-to-cart', 'refresh');
    </script>
{% endif %}
```

**Comment by robzor** [comment]
Ohh, interesting. That's a nice idea, I'll give that a shot. Thanks!

**Comment by bencroker** [comment]
It's essentially the same solution as https://github.com/putyourlightson/craft-sprig/issues/209#issuecomment-1080468340

**Comment by robzor** [comment]
Thanks Ben, this worked perfectly for my needs :) I wish Commerce would add a 'last item added' function to their cart object but with your magical Sprig work I can get it sorted :)

**Comment by bencroker** [comment]
Great! That sounds like a good idea for a feature request to Commerce.
