### ISSUE TITLE
How to update other content instead of the whole included template

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#275]
I have a page with a form filters area, and a list area where entries should be updated.
The filters area stays sticky, and shrink, and I would like to maintain its current display when the view reloads.
So I'm looking for a way to add the filters as static content, to only update the entries area, where the content is updated.

After checking the htmx doc I've found this: https://htmx.org/examples/update-other-content/
But I'm confused about how to make it works using the required `{{ sprig() }}` method with the Craft's plugin.

Currently, I have added the form and entries areas in the `{{ sprig() }}` included template.
But on each action on filters, the whole included template is updated while I'm trying to only update the entries area.

Is it possible? How to do it?

**Comment by bencroker** [comment]
You can do this in a number of ways, I'd likely suggest using [s-replace](https://putyourlightson.com/plugins/sprig#s-replace). If this is for a filter then I suggest you check out the [Sprigboard](https://putyourlightson.com/sprig/videos#sprigboard) video, which explains exactly how to achieve this.
