### ISSUE TITLE
Category link channel entry to listing page with sprig filter

### ISSUE THREAD

**Issue by LieselotV** [putyourlightson/craft-sprig#276]
Hi,

Thank you for the wonderful plugin.

I have a category filter called news-category on the listing page news. This is built via sprig.
The news-category filter has categories: events, clients, ...
On this page everything works as desired.

Once you click on an entry. You arrive at an entry page with the content of the news article. Here you will also see the category linked to the entry. 
My goal: If you click on the category 'events' for example, you should be redirected to the listing page news where the filter is automatically presorted to 'events'.
So I don't want one to be redirected to another category listing page.

My questions:

1. To do this I would have to replace the category url with the listing page url. But I am not so sure how to create this news listing page url.  
My entry pages for all news articles are built via a channel. The listing page news is a structure template. How can I create a link on the entry page to this overview page? My website is multilang, so I would prefer not to enter the url manually but work through the ID of the listing page. Is there some code for this to get the url from an entered ID of a structure page?

I searched online and I tried: 
`{% set listing = craft.section.getSectionById(3363) %}
<a href="{{ listing.url }}">{{ cat.title }}</a>`
and 
```
{% set listing = craft.section.getEntryTypes('newsOverview') %}
<a href="{{ listing.url }}">{{ cat.title }}</a>
```
But it doesn't work

2.
I was thinking to pass the 'category.id' through the url. And to include it on the news listing page inside the filter: 
Something like, if a slug id is passed in. Then add it into the array newsCat. But afterward you can still deselect through the filter the passed in slug id.

Do you guys happen to have an example or more documentation on this? Or do you have another solution?
Thank you very much

Greetings,

**Comment by bencroker** [comment]
This really isn't Sprig specific. You can use routes or multiple other Craft concepts to achieve this, so I suggest you work through the Craft docs or ask in one of the official support channels.
