### ISSUE TITLE
Sprig/Unpkg issue - htmx unable to be loaded via CDN

### ISSUE THREAD

**Issue by robzor** [putyourlightson/craft-sprig#277]
Hi Ben,

If you see https://github.com/mjackson/unpkg/issues/343 you can see that today Unpkg has had some issues and is causing htmx not to be loaded. A few people in the comments suggest using jsDelivr instead to serve htmx.

I was wondering if the `{{ sprig.script }}` tag could have a fallback written into it? Although I have a feeling this might not work in this particular instance, perhaps something that checked for htmx and if it didn't exist, use a local version?

**Comment by bencroker** [comment]
Sprig uses the htmx recommended CDN, you're welcome to make the suggestion over at https://github.com/bigskysoftware/htmx/

You can replace the `{{ sprig.script }}` tag with your own, that either points to a local copy of htmx or one hosted on another CDN. There's no practical way for Sprig to ensure that a CDN is up before outputting a URL.

**Comment by robzor** [comment]
Hi Ben, 

I had a feeling you might say that, thanks for getting back to me though! I do prefer to use your tag rather than using my own though.

Have a good weekend!

Rob
