### ISSUE TITLE
CSRF tokens in multiple components on first cached request

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-sprig#279]
Using CSRF tokens in multiple components on the first cached request can result in CSRF requests failing. This is because the Sprig components are loaded asynchronously, without a session cookie existing for the user, as reported in https://github.com/putyourlightson/craft-sprig/issues/201 and related to https://github.com/putyourlightson/craft-blitz/issues/329.

The current suggested workaround is to use a dummy `init` component that on page load will force a session cookie to be generated and will then refresh all other components on the page.

```twig
{# _components/init #} 

{% if sprig.isRequest %}
    {{ csrfInput() }}
    <script>
        for (const component of htmx.findAll('.sprig-component')) {
            htmx.trigger(component, 'refresh');
        }
    </script>
{% endif %}
```

```twig
{# Main page #} 

{{ sprig('_components/init', {}, { 's-trigger': 'load' }) }}

{{ sprig('_components/form') }}
{{ sprig('_components/form') }}
{{ sprig('_components/form') }}

{{ sprig.script }}
```

This is a feature request for Sprig to add a convenience method for handling this use-case.

**Comment by bencroker** [comment]
Added a `sprig.triggerRefreshOnLoad` template variable that triggers a refresh event on all components on page load. 

Sample usage:

```twig
{{ sprig.triggerRefreshOnLoad() }}

{{ sprig('_components/form') }}
{{ sprig('_components/form') }}
{{ sprig('_components/form') }}

{{ sprig.script }}
```

@robzor you could help test by adding a `putyourlightson/craft-sprig-core` requirement in the main `composer.json` set to `dev-develop as 2.3.0` and running `composer update`.

**Comment by robzor** [comment]
Amazing! Thank you so much Ben, I owe you many drinks next time I see you.

I will give this a go shortly, there is also a 'basket total' component and another 'added to cart' sprig component on the same page so for my needs I think the first workaround might be better as I can target which component I need to refresh?

Will let you know how I get on!

**Comment by bencroker** [comment]
I didn't mention it above, but you can specify which components to refresh using CSS selectors. The default is `.sprig-component`, but you can customise this as follows.

```twig
{{ sprig.triggerRefreshOnLoad('.custom-component') }}
```

**Comment by robzor** [comment]
Oh very very cool :)

**Comment by robzor** [comment]
Do I need to still need to wrap the contents of the component in `{{ if sprig.isRequest }}`

**Comment by robzor** [comment]
Hi Ben,

Small error with the new template variable: This is the output of `{{ sprig.triggerRefreshOnLoad('.sprig-product-add-to-cart') }}` in my template

```
<div id="component-fvuaek" class="sprig-component" data-hx-target="this" data-hx-include="this" data-hx-trigger="load" data-hx-get="https://nameofmysite.test/index.php?p=actions/sprig-core/components/render" data-hx-vals="{&quot;sprig:siteId&quot;:&quot;856e610e0e8d299f995f2b638e00d564d46160b3d4e307fe185b20207007899e1&quot;,&quot;sprig:component&quot;:&quot;2e929725b6834a00ca160a3cddbde23bf392a674aa38f590b8666f7e393020d7RefreshOnLoad&quot;,&quot;sprig:variables[selector]&quot;:&quot;e5d6d216e9290d6ccd06671178253a5a47113d87f355840a580338ce3b5695ed.sprig-product-add-to-cart&quot;}" s-trigger="load">

<script>
        for (const component of htmx.findAll('.sprig-component')) {
            htmx.trigger(component, 'refresh');
        }
    </script>
</div>
```

**Comment by bencroker** [comment]
Right, fixed in https://github.com/putyourlightson/craft-sprig-core/commit/c9dfdb32a9ba1d5bde96a35e671a9a6bbc76205a.

**Comment by bencroker** [comment]
Is this working well for you @robzor? I'll likely be releasing it next week.

**Comment by robzor** [comment]
Hi @bencroker I've actually been using your original workaround as we had a site going live, so haven't had a chance to test the revised version since you updated it. Can I add multiple classes in the method? My current Sprig init template is this:

```
{% if sprig.isRequest %}
  {{ csrfInput() }}
  <script>
    for (const component of htmx.findAll('.sprig-product-add-to-cart')) {
        htmx.trigger(component, 'refresh');
    }
    for (const component of htmx.findAll('.sprig-delivery-estimate-cache-refresh')) {
        htmx.trigger(component, 'refresh');
    }
  </script>
{% endif %}
```

Weirdly, I am getting occasional 400 errors in that delivery estimate component but I can't replicate it so not sure how to fix it yet. I should have time to test the module tag on Monday.

Side note, when the new release comes out do I just remove the line sprig-core line from my composer.json and run composer update?

**Comment by bencroker** [comment]
> Can I add multiple classes in the method?

Yes, this should work.

```twig
{{ sprig.triggerRefreshOnLoad('.sprig-product-add-to-cart, .sprig-delivery-estimate-cache-refresh') }}
```

> Side note, when the new release comes out do I just remove the line sprig-core line from my composer.json and run composer update?

Correct.

**Comment by robzor** [comment]
I felt bad that I hadn't tested it yet, so just tried it and got this:

```
  <script>
        for (const component of htmx.findAll('.sprig-product-add-to-cart, .sprig-delivery-estimate-cache-refresh')) {
            htmx.trigger(component, 'refresh');
        }
    </script>
```

And everything on the product page worked fine, looks like a successful mission to me!

Thanks Ben, and have a good weekend :)

**Comment by bencroker** [comment]
Excellent, thanks for the help testing!

**Comment by bencroker** [comment]
Released in version 2.4.0.

**Comment by rbrv** [comment]
@bencroker any chance of applying the same fix for Craft 3? 😇

**Comment by bencroker** [comment]
Features are only added to new versions of the plugin, so you'll have to update to get it.

**Comment by rbrv** [comment]
I understand. Too bad we can't update yet. Still waiting on the sprout forms plugin to add Craft 4 support.
