### ISSUE TITLE
Search input

### ISSUE THREAD

**Issue by bleepsandblops** [putyourlightson/craft-sprig#28]
Not sure if this is a bug or a feature request, but is it possible to use an input type of search, and then have the 'clear' button tied to an event? 

Right now if I take the search demo and use a type="search" input, the clear event doesn't trigger anything.

**Comment by bencroker** [comment]
Using the `search` event as a trigger and adding the `incremental` HTML attribute should work:

```html
<input sprig s-trigger="search" type="search" incremental>
```

Note however the warning about this being "a non-standard feature" of HTML:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event

**Comment by bleepsandblops** [comment]
It did work indeed, thank you!
