### ISSUE TITLE
Implement Script Integrity Attribute for HTMX

### ISSUE THREAD

**Issue by baileydoestech** [putyourlightson/craft-sprig#280]
In general, JavaScript files loaded from another domain should be verified using the integrity attribute. We noticed that the following HTMX CDN does not have this implemented:

`<script src="https://unpkg.com/htmx.org@1.7.0/dist/htmx.js"></script>`

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by bencroker** [comment]
Loading htmx using `{{ sprig.script }}` will include an integrity attribute automatically. Otherwise, if loading htmx yourself, you can follow the instructions at https://htmx.org/docs/#installing which also include an integrity attribute.
