### ISSUE TITLE
Passing Checkbox Array Issue in s-val

### ISSUE THREAD

**Issue by bfjare** [putyourlightson/craft-sprig#281]
Been working on a calculator for a minute and now am working with check boxes.

This is heavily simplified.

I have two arrays set. One for the specific letter of the sign and another array if they choose to copy all of the settings to other letters.  It works everywhere except for the sign options checkboxes.

{% set options = _context['options-' ~ wordCount ~ '-letter-' ~ loop.index] ?? [] %}
{% set globaloptions = globaloptions ?? [] %}

Here are the inital arrays.

<img width="1278" alt="Screen Shot 2022-11-22 at 3 54 42 PM" src="https://user-images.githubusercontent.com/11744681/203438132-91cc7ad1-ccf7-4469-9bd8-86fb9382b696.png">

Once I check the checkboxes it fills in the lower single letter array correctly.

```
<div>
  <input 
     sprig
     s-replace="#word-{{ wordCount }}-letter-{{ letterCount }}"
     type="checkbox" 
     value="{{ option.id }}" 
     name="options-{{ wordCount }}-letter-{{ letterCount }}[]"
     {% if option.id in globaloptions %}
       checked
     {% endif %}
  >
  {{ option.additionalOptionName }}
</div>
```

<img width="1260" alt="Screen Shot 2022-11-22 at 3 58 24 PM" src="https://user-images.githubusercontent.com/11744681/203438281-12d979ad-4832-4349-88e1-21300fdc1ebc.png">

Once I click on the button to add it to the global array its converts to a string.

<img width="1287" alt="Screen Shot 2022-11-22 at 3 54 24 PM" src="https://user-images.githubusercontent.com/11744681/203438361-3bca393b-2f0b-4f8f-835a-ae6af4f390d6.png">

Passing the options as {{ options|json_encode }} works in the input field but not as the button.

```
<button 
  sprig 
  s-val:globalheight="{{ height }}"
  s-val:globaltype="{{ typeid }}"
  s-val:globaloptions="{% if globaloptions|length %}{{ globaloptions }}{% else %}{{ options|json_encode }}{% endif %}"
  s-replace="#word-{{ wordCount }}"
  type="button"
 >
    Copy Letter Settings 
</button>
```
Any ideas ben?

**Comment by bencroker** [comment]
JSON encoding an array returns a string, so this is the result I would expect.

**Comment by bfjare** [comment]
Is it possible to pass an array in s-val?  It throws the Array to string conversion error.

**Comment by bfjare** [comment]
Nevermind figured it out with join and split filters
