### ISSUE TITLE
Using multiple filters without erasing the first

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#282]
I have two Sprig filters in the one component; first searching for entries, and checkboxes to then filter other entries related to the the selected entries. It's tough to explain so hopefully my code does it:

```
{% set search = search ?? '' %}
{% set categorySelect = categorySelect ?? [] %}
{% set categories = craft.entries({section: 'categories', search: search}) %}
{% set articlesQuery = craft.entries({section: 'articles', limit: 20}) %}

{% if categorySelect is not empty %}
    {% do articlesQuery.relatedTo(categorySelect) %}
{% endif %}

{% set articles = articlesQuery.all() %}

<input sprig s-trigger="keyup changed delay:200ms" s-replace="#categories" type="text" name="search" value="{{ search }}">
<div id="categories">
    {% if search %}
        {% for category in categories %}
            <input type="checkbox" sprig s-replace="#articles" name="categorySelect[]" value="{{ category.id }}" {{ category.id in categorySelect ? 'selected' }}>{{ category.title }}
        {% endfor %}
    {% endif %}
</div>
<div id="articles">
    {% for article in articles %}
        {{ article.title }}
    {% endfor %}
</div>
```

This is working pretty well, with one large exception: I search once, check a category and the entries are filtered. I then want to check another category, but when I search again it clears the entire thing, and `categorySelect` is empty again.

Is there a way to have `categorySelect` persist when `search` changes?

**Comment by bencroker** [comment]
You'll likely want to use [s-replace](https://putyourlightson.com/plugins/sprig#s-replace) to achieve this, but this is explained in detail in the Sprigboard and Sprig Filters videos at https://putyourlightson.com/sprig/videos.

**Comment by shifuma** [comment]
Thanks for the reply. I did watch those actually, but mine feels a little more complex in that it's a two-step search. First, search for categories, then use those to filter the entries.

You'll see I'm actually already using `s-replace` on both the search input and the checkboxes. I guess because the search re-renders the checkboxes, those values are removed when a new search is performed.

There's a very decent chance I missed something in the videos, but I didn't see anything on how to handle this sort of thing.

**Comment by bencroker** [comment]
Oh, I see now. Could it be that the checkbox field needs an attribute of `checked`?

```twig
{{ category.id in categorySelect ? 'checked' }}
```

**Comment by shifuma** [comment]
I do have `{{ category.id in categorySelect ? 'selected' }}` already actually. I assume that gives the same result but just to be sure I changed to `checked` but the same issue persists.

**Comment by bencroker** [comment]
Using `checked` is the solution, it works in my local setup.

**Comment by shifuma** [comment]
That's super weird, it's not working for me. Are you using the code I added above or did you write something new?

**Comment by bencroker** [comment]
Your code, but with `{{ category.id in categorySelect ? 'checked' }}`.

**Comment by shifuma** [comment]
Hmmm so odd. The checkbox isn't been checked at all. Will keep debugging, thanks for your help.

**Comment by shifuma** [comment]
I really don't see how that's working for you but not for me. I search once, check a category and the entries show as expected. The network tab shows:

```
Query String Parameters
p: actions/sprig-core/components/render
search: news
categorySelect[]: 33192
```

I then clear the search input and get back:

```
Query String Parameters
p: actions/sprig-core/components/render
search
```

So the `categorySelect[]` array has been cleared, or does it just not show values that haven't changed?

**Comment by bencroker** [comment]
Clearing the search input _removes_ all of the category checkboxes for me, which is what I'd expect.

**Comment by shifuma** [comment]
Right...so that was my question from the first post:

> Is there a way to have categorySelect persist when search changes?

No, it's not possible?

**Comment by bencroker** [comment]
It is possible, and it works, provided the search results include the category that you want persisted. If it was to work any differently, it would be very confusing to the user. If you must persist the value, you can do this with a hidden input, but I doubt that's what you want to do.

**Comment by shifuma** [comment]
I want to build an advanced search kind of thing, where after checking the category checkbox, the entries are filtered and the category is added like a tag. This screenshot might show it best, where 'Pending' and 'Today' would be categories in my setup: https://cdn.dribbble.com/users/377320/screenshots/6171856/media/1e5c620a13489dd44999a1d6e79b14f2.jpg

That wouldn't be confusing to the user, but is obviously not possible to do it if re-searching empties the `categorySelect` array.

**Comment by bencroker** [comment]
You can do that, you just need to rewrite the part of the component that outputs the checkboxes. Right now, you're only outputting category checkboxes based directly on search results. Here's some new code that should get you started.

```twig
{% set categories = craft.entries.section('categories').id(categorySelect).all() %}
{% if search %}
    {% set searchCategories = craft.entries.section('categories').id(['not']|merge(categorySelect)).search(search).all() %}
    {% set categories = categories|merge(searchCategories) %}
{% endif %}

{% for category in categories %}
    <input type="checkbox" sprig s-replace="#articles" name="categorySelect[]" value="{{ category.id }}" {{ category.id in categorySelect ? 'checked' }}>{{ category.title }}
{% endfor %}
```

**Comment by shifuma** [comment]
Nice...this is definitely on the right track now, thank you!
