### ISSUE TITLE
Is there a way to choose the tagname of the component

### ISSUE THREAD

**Issue by rauwebieten** [putyourlightson/craft-sprig#284]
I see that sprig injects one DIV element per sprig component with all the necessary HTMX attributes. Something like:

```
<div class="sprig-component" data-hx-target="..." data-hx-include="..." >
    The actual sprig component content
</div>
```

Is it possible to change the tagname of this HTML element?

I'm working a lot with tables, and want to update row by row. (each table row is a sprig component)
The injected DIV between my TBODY and TR makes my HTML invalid, making the browser rendering wrong.

Kind regards.
Peter

**Comment by rauwebieten** [comment]
I guess this is not possible at the moment. Found this at the component service:

`$event->output = Html::tag('div', $content, $attributes);`

**Comment by bencroker** [comment]
Right, it's currently hard-coded as a `div`. If you're creating one component per table row, then you'll likely doing something wrong, or at least not recommended, as you should have as few Sprig components on the page as possible.
