### ISSUE TITLE
Custom module + sprig

### ISSUE THREAD

**Issue by ishetnogferre** [putyourlightson/craft-sprig#286]
We're using a custom module to simulate an "add to cart functionality", the buttons for that use following code:

```
<form method="POST" action="/cart/add" accept-charset="UTF-8">
  {{ csrfInput() }}
  {{ redirectInput(craft.app.request.url) }}
  
  <input type="hidden" name="entryId" value="{{ productId }}">
  <button type="submit">{{- "Order Sample"|t -}}</button>
</form>
```

When trying to turn this into a twig component as following, we get a **404 error** that the route can't be found.
```
<form sprig s-method="POST" s-action="/cart/add" accept-charset="UTF-8">
  <input type="hidden" name="entryId" value="{{ productId }}">
  <button type="submit">{{- "Order Sample"|t -}}</button>
</form>
```

Is there something else we need to add to the sprig code for using a custom module controller or to the module itself to make it work with sprig?

**Comment by bencroker** [comment]
It looks to me like `/cart/add` is not a valid action URL. If this is for the Commerce plugin then it should be `commerce/cart/update-cart`, see https://craftcms.com/docs/commerce/4.x/orders-carts.html#adding-items-to-a-cart

**Comment by ishetnogferre** [comment]
No, it’s not for commerce: the user can order free samples so for that we’re mimicking a part of a cart flow by using a **custom module**.

The action url is included like below and when using a normal HTML POST form to the url, it reaches the controller and does the intended flow:

```
Event::on(
  UrlManager::class,
UrlManager::EVENT_REGISTER_SITE_URL_RULES,
            function(RegisterUrlRulesEvent $event
        ) {
            $event->rules['cart/add'] = 'cart/cart/add';
            $event->rules['cart/update'] = 'cart/cart/update';
        });
    }```

**Comment by bencroker** [comment]
Ah I missed that part. Sprig will internally run whatever action is provided in `s-action`, so providing `cart/cart/add` as the value should work.

**Comment by ishetnogferre** [comment]
Oh okay, that works!

What's the reason sprig needs to use the direct controller action urls and not the defined url rules? Or do you need to add them in a different way then?

**Comment by bencroker** [comment]
Sprig sends requests to its own controller action, which then runs the action specified in `s-action`. It's the equivalent of using the recommended `action` query or body param, as explained in the docs at https://craftcms.com/docs/4.x/dev/controller-actions.html#making-requests
