### ISSUE TITLE
Triggering a replace from within alpine component

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-sprig#287]
Hi, 

I've searched the docs and issues, but struggling to find a way to make this work. I have a search field inside an alpine component. 

Here's a very stripped back example. 

```twig
{% set search = search ?? false %}

{% set entries = craft.entries()
    .search(search)
    .section('articles')
    .all() %}

<div x-data="{open: false}">
    <button x-on:click="open = true">Search</button>
    <div x-show="open">
        <input
            sprig
            name="search"
            s-trigger="keyup changed"
	    s-replace="#results"
	    type="text">
        {# I want this to update #}
        <button x-on:click="open = false">Show {{ entries|length }} entries</button>
    </div>
</div>
	
<div id="results">	
    <p>{{ entries|length }} entries</p> 
    {% for entry in entries %}
        {{ entry.title }}
    {% endfor %}
</div>
``` 

This works in as far that you can open the alpine component to show the search. You can enter a search term and it updates the entries query whilst the alpine component remains opened and unchanged. Pretty straightforward as it's just replacing the `#results` div. However I also want to update the line in the alpine component with the updated `{{ entries|length }}`. 

Is this do-able? I tried putting the alpine component within the `#results` div, but that closes the alpine components when the search is performed. Any chance you can point me in the right direction?

Many thanks!

**Comment by bencroker** [comment]
Sounds like a job for the [s-swap-oob](https://putyourlightson.com/plugins/sprig#s-swap-oob) attribute.

```twig
<button s-swap-oob="true" x-on:click="open = false">Show {{ entries|length }} entries</button>
```

**Comment by shornuk** [comment]
Thanks, I thought that might be a step in the right direction. However I'm getting a javascript/htmx error when I perform a search. 

`htmx:swapError`
`SyntaxError: The string did not match the expected pattern.`

**Comment by shornuk** [comment]
Ah ok, it needed an ID on the button. Added that and working as hoped for. Thank you!

**Comment by bencroker** [comment]
Glad to hear it!
