### ISSUE TITLE
Revealed trigger giving errors on Craft CMS V4

### ISSUE THREAD

**Issue by clarisse-catacutan** [putyourlightson/craft-sprig#288]
We just recently upgraded our Craft version to 4 but before that, the s-trigger="revealed" was working perfectly and smoothly.

After the update, every time the element is triggered, it won't load anymore and there is a recurring error message:

![image](https://user-images.githubusercontent.com/76716263/213611829-097fe966-2441-4193-8946-34c8fc01f416.png)

The first revealed trigger works fine, most of our elements are triggered with revealed but when we use it as a load more function when an element is revealed, that is when it gives us errors.

We tried to change the reveal element to a "load more" button instead and it worked properly.

We are just wondering if this is caused by the CMS upgrade?

**Comment by bencroker** [comment]
Updating Craft would have required updating Sprig, which would require a more recent version of htmx. Can you ensure that you're running the latest version 2.5.0 of Sprig and that it is including version 1.8.5 of htmx (you'll find this in the HTML source code).

Also, the docs on `hx-trigger` may be helpful: https://htmx.org/attributes/hx-trigger/
