### ISSUE TITLE
pushUrl with relation fields & `andRelatedTo`

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#290]
I'm chaining a bunch of relation fields to the URL like this:

```
{% set categoryOne = categoryOne ?? [] %}
{% set categoryTwo = categoryTwo ?? [] %}

{% if categoryOne is not empty %}
  {% do entriesQuery.andRelatedTo(categoryOne) %}
{% endif %}

{% if categoryTwo is not empty %}
  {% do entriesQuery.andRelatedTo(categoryTwo) %}
{% endif %}

{% do sprig.pushUrl('?' ~ {categoryOne: categoryOne: categoryTwo: categoryTwo, page: page, limit: limit}|url_encode) %}
```

It works ok but the the URLs end up like this, which is a bit ugly: `https://mysite.com/entries? categoryOne%5B0%5D=82464&page=1&limit=50`

Is there a way to make these prettier? Is it possible to have something like `/entries?categoryOne=myCategory&page=1&limit=50`, where `myCategory` is the slug rather than the ID?

Edit: apparently the `%5B0%5D` is [0], so I guess coming from the array somehow?

**Comment by bencroker** [comment]
If `categoryOne` is an array then it will end up as `categoryOne[0]=value`, URL encoded, which is what you are seeing. If `categoryOne` was a single ID then it would work the way you are hoping it to. Since you haven't shown the code you use to generate the categories, however, I'm unable to help with it.

**Comment by shifuma** [comment]
Thanks for the reply. I'm using checkboxes for filtering by multiple categories:

`<input type="checkbox" sprig name="categoryOne[]" value="{{ category.id }}" {{ category.id in categoryOne ? 'checked' }}>{{ category.title }}`

So I guess that means the URL will always end up as `categoryOne[0]=value`.

**Comment by bencroker** [comment]
Yes, it will.
