### ISSUE TITLE
Update Google Maps after filtering with Sprig

### ISSUE THREAD

**Issue by lennonpuype** [putyourlightson/craft-sprig#293]
Hi, I'm kinda stuck on how to refresh a google map that is added via the Google Maps API with a JavaScript file and which is showing some markers based on the loaded entries. But when filtering, the map stops working, which is kinda obvious because it needs to refresh the map with the filtered data which was not loaded in the JavaScript after filtering with sprig.

I tried something by setting the javascript of the map in the component itselfs, but then Google of course complains about calling it multiple times. The same with the variables of the script that are already been declared.

Is there any workaround for a dynamic google map and a working sprig filter?

The filter is working fine, but its just that the map is the big issue here.

Thanks in advance!

**Comment by bencroker** [comment]
If you want to recreate the map then you can simply do so on all Sprig requests (or you can get more sophisticated with the conditional if you want).

```twig
{% if sprig.isRequest %}
    <script>
        new google.maps.Map(document.getElementById('my-map');
    </script>
{% endif %}
```

**Comment by lennonpuype** [comment]
This is exactly what I need, I can continue from this. Thank you!
