### ISSUE TITLE
Problem removing data from session (redis) in a component

### ISSUE THREAD

**Issue by goraxan** [putyourlightson/craft-sprig#294]
I'm using Redis for the session management (I don't have this problem using the default file-based session engine, but my production environment is balanced so I need Redis).

In a custom controller I set a value to my session `Craft::$app->session->set('dipt_message', 'Board successfully deleted');`
Then I have a Sprig component (notification.twig) which should print this message only once (same behaviour as a normal flash message, which I cannot use due to how Sprig handles it by reading and removing them every time a component tries to render https://github.com/putyourlightson/craft-sprig-core/blob/develop/src/controllers/ComponentsController.php#L123).

This component is added to my base layout.twig file like this `{{ sprig('_components/notification', {}, {'s-trigger':'load'}) }}` so that at every page request an AJAX call is made to render that component.

And this is the code (it shows the message and remove it after 3 seconds).

```
{% if sprig.isRequest %}

    {% set message = craft.app.session.get('dipt_message') ?? '' %}
    {% do craft.app.session.remove('dipt_message') %}
    
    {% if message is not empty %}
    <section id="notification-msg" class="mdl-notify v-active">
        <div>{{message}}</div>
    </section>

    <script>
        setTimeout(function() {$("#notification-msg").removeClass("v-active")}, 3000);
    </script>
    {% endif %}
{% endif %}
```

The problem is that the key `dipt_message` is never removed from the redis session (actually it's removed an re-added!!), so it's shown every time a page is load.
I've monitored the redis instance and this is happening at every page request to my redis session key:
```
$ ddev redis-cli monitor | grep 39e16b4abb019d00dc70d7e169a3fa7c86804
1676461782.129229 [0 172.18.0.2:42762] "GET" "39e16b4abb019d00dc70d7e169a3fa7c86804"
1676461782.179073 [0 172.18.0.2:42762] "SET" "39e16b4abb019d00dc70d7e169a3fa7c86804" "bd62416aa8538ede709019a5e113eea5__flash|a:0:{}1031b8c41dfff97a311a7ac99863bdc5__token|s:100:\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\";1031b8c41dfff97a311a7ac99863bdc5__id|i:886;__authKey|s:144:\"[\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\",null,\"b9cbd8dc13f19f9e7eb854f472bfa274\"]\";1031b8c41dfff97a311a7ac99863bdc5__expire|i:1676465382;__duration|i:3600;dipt_message|s:26:\"Board successfully deleted\";" "EX" "1440"
1676461782.234887 [0 172.18.0.2:42780] "GET" "39e16b4abb019d00dc70d7e169a3fa7c86804"
1676461782.235110 [0 172.18.0.2:42776] "GET" "39e16b4abb019d00dc70d7e169a3fa7c86804"
1676461782.236054 [0 172.18.0.2:42778] "GET" "39e16b4abb019d00dc70d7e169a3fa7c86804"
1676461782.249493 [0 172.18.0.2:42776] "SET" "39e16b4abb019d00dc70d7e169a3fa7c86804" "bd62416aa8538ede709019a5e113eea5__flash|a:0:{}1031b8c41dfff97a311a7ac99863bdc5__token|s:100:\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\";1031b8c41dfff97a311a7ac99863bdc5__id|i:886;__authKey|s:144:\"[\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\",null,\"b9cbd8dc13f19f9e7eb854f472bfa274\"]\";1031b8c41dfff97a311a7ac99863bdc5__expire|i:1676465382;__duration|i:3600;" "EX" "1440" <-- This is due to the craft.app.session.remove('dipt_message')
1676461782.249906 [0 172.18.0.2:42778] "SET" "39e16b4abb019d00dc70d7e169a3fa7c86804" "bd62416aa8538ede709019a5e113eea5__flash|a:0:{}1031b8c41dfff97a311a7ac99863bdc5__token|s:100:\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\";1031b8c41dfff97a311a7ac99863bdc5__id|i:886;__authKey|s:144:\"[\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\",null,\"b9cbd8dc13f19f9e7eb854f472bfa274\"]\";1031b8c41dfff97a311a7ac99863bdc5__expire|i:1676465382;__duration|i:3600;dipt_message|s:26:\"Board successfully deleted\";" "EX" "1440"
1676461782.263644 [0 172.18.0.2:42780] "SET" "39e16b4abb019d00dc70d7e169a3fa7c86804" "bd62416aa8538ede709019a5e113eea5__flash|a:0:{}1031b8c41dfff97a311a7ac99863bdc5__token|s:100:\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\";1031b8c41dfff97a311a7ac99863bdc5__id|i:886;__authKey|s:144:\"[\"Idq0mfvL4VfgmlWSj0TwDjLx7ehOhh8KGZRUWGYWXBWHtsVIfhd1o98oNKkVlHkt5Ve3f7O2qHwh8rnSHee1b5L-L1v8qmZhe4Ky\",null,\"b9cbd8dc13f19f9e7eb854f472bfa274\"]\";1031b8c41dfff97a311a7ac99863bdc5__expire|i:1676465382;__duration|i:3600;dipt_message|s:26:\"Board successfully deleted\";" "EX" "1440"
```

Notice how the dipt_message variable is removed and later is being re-added somehow ¿?¿?

I don't know if it's Sprig's fault or what is happening here... any thoughts?

Thanks!

**Comment by bencroker** [comment]
> Notice how the dipt_message variable is removed and later is being re-added somehow ¿?¿?

It looks like it is re-added twice even. How and when is your custom controller being called? That appears to be the culprit.

**Comment by goraxan** [comment]
Yes I saw that, but I don't understand why and how that's happening since my controller is only called once, and before I delete the key from the session.
The controller is called from another sprig controller, and upon completion we are forcing a redirect to the home page

My controller:
``` 
   public function actionCreate() {

        $currentUser = Craft::$app->getUser()->getIdentity();

        $name = Craft::$app->getRequest()->getRequiredParam("boardName");
        $entry = $this->_createBoard($name, false, $currentUser);
        
        if(Craft::$app->elements->saveElement($entry)){
            Craft::$app->session->set('dipt_message', 'Board successfully created');

            Craft::$app->getUrlManager()->setRouteParams([
                'success' => '1',
                'model' => $entry
            ]);
            
            return $this->asSuccess();
        }
        else
            return $this->asModelFailure($entry, "Failed to create board");
    }
```

My component calling the controller:
```
{% if success is defined and success == '1' %}
    {% do sprig.redirect('/') %}
{% endif %}

...
        <form id="creation-form" sprig s-trigger="submit" s-action="site-module/boards/create" s-replace="#creation-form">
...
</form>

```
The component is added into a normal twig file this way `{{ sprig('_components/modals/board-creation') }}`

**Comment by bencroker** [comment]
It’s strange that this is only happening with Redis sessions. 

Have you tried using Craft’s flash sessions instead, which are intended for this exact use-case?

```php
Craft::$app->session->setFlash('dipt_message', 'Board successfully created');
```

You can then access it in your Sprig component directly and it should then be removed from the session automatically.

```twig
{% set message = flashes.dipt_message ?? '' %}
```

**Comment by goraxan** [comment]
No, that's not working because, I think, all the flash messages are removed every time a Sprig component is rendered (https://github.com/putyourlightson/craft-sprig-core/blob/develop/src/controllers/ComponentsController.php#L123 the true parameter removes all flash variables).

So, when my `board-creation` component re-renders after submitting the form, just before doing the redirect, the flash messages are lost, then my `notification` component gets a null in the flashes variable.

This is what happens, the first request is the form submission, which creates the flash message, the second is the redirect, which triggers some Sprig components renders (the `notification` component among them, which ideally should read my flash messages and show them to the user, but they are null at that point).

![image](https://user-images.githubusercontent.com/8337784/221804240-ea97e6db-ef08-49f9-b885-9777fbfd8174.png)

**Comment by goraxan** [comment]
@bencroker I've created a demo project, as simple as I could, to reproduce this behaviour, you can pull it from here https://github.com/goraxan/redis-sprig-test

To start it:
```
ddev start
ddev composer install
ddev launch
```
Add the following to the .env (staging will use the redis, dev will use the local files. You can switch environments to check how dev works whereas staging most of the time does not).
```
CRAFT_ENVIRONMENT=staging
REDIS_HOST=redis
REDIS_PORT=6379
```
To monitor redis:
```
ddev redis-cli monitor
```

Open https://redis-sprig-test.ddev.site/board-creation and submit & refresh to see what happens. It looks random... and I think it's due to having multiple sprig components being rendered at the same time (hence the "empty" components I added) and modifying the session (probably when reading the flash messages in your ComponentsController.php? I'm not sure...).

Demo:
https://user-images.githubusercontent.com/8337784/221846965-87db3595-9548-480b-a6dc-196a90d26a34.mp4

**Comment by bencroker** [comment]
Thanks for the repo. In which file are you removing the `dipt_message` session? I'm not seeing it anywhere.

**Comment by goraxan** [comment]
Here https://github.com/goraxan/redis-sprig-test/blob/master/modules/variables/SiteVariable.php#L16

**Comment by bencroker** [comment]
In my initial tests, removing the `empty` components solves the issue, can you confirm?

```twig
    {% block content %}{% endblock %}
    {{ sprig('_components/notification', {}, {'s-trigger':'load'}) }}
    {#
    {{ sprig('_components/empty', {}, {'s-trigger':'load'}) }}
    {{ sprig('_components/empty', {}, {'s-trigger':'load'}) }}
    #}
```

**Comment by goraxan** [comment]
Yes exactly, that's why I put them in the demo, because in my real project I have 3 components in the base layout, and if I remove one of the 3 it doesn't happen, but I can't do that, it sounds too random for a production-ready project :D

**Comment by bencroker** [comment]
I'm not sure what exactly is going on, but the fact that this is an issue only when using the Redis cache and extra Sprig components indicates that this is less a bug with Sprig and more an order-of-operations issue.

**Comment by goraxan** [comment]
I'd say this is a pretty common scenario though. Do you think it's a Craft's problem then? Do you know who can we report this to?
Also, do you have any ideas about how to display messages upon a sprig redirect without using the session?
Thanks for all your help.

**Comment by bencroker** [comment]
> I'd say this is a pretty common scenario though. Do you think it's a Craft's problem then? Do you know who can we report this to?

I don't disagree, but order-of-operations issues are tricky to resolve and I'm not sure where to tell you to report it.

> Also, do you have any ideas about how to display messages upon a sprig redirect without using the session?

If there's nothing sensitive or particularly unique in the confirmation page then a simple query string should do.

```twig
{% if success is defined and success == '1' %}
    {% do sprig.redirect('/confirmation=1?') %}
{% endif %}
```

```twig
{% if craft.app.request.get('confirmation') %}
    Board successfully created
{% endif %}
```

If that doesn't cut it then perhaps rethinking the order in which your Sprig components are loaded might be necessary, for example (untested):

```twig
    {% block content %}{% endblock %}
    {{ sprig('_components/notification', {}, {'s-trigger':'load'}) }}
    {{ sprig('_components/empty', {}, {'s-trigger':'load delay:1s'}) }}
    {{ sprig('_components/empty', {}, {'s-trigger':'load delay:1s'}) }}
```

**Comment by goraxan** [comment]
Delaying the components load sounds good to me and actually work on my setup, thanks for the tip and for looking into this!

**Comment by bencroker** [comment]
Glad to hear it!
