### ISSUE TITLE
Entries with same title pagination bug

### ISSUE THREAD

**Issue by green17** [putyourlightson/craft-sprig#295]
Strange one, we have several entries with the same title, and when clicking through pagination the information will sometimes not update. It seems to mainly happen when we use a category filter in a dropdown, and the entries are last on one page and first on the next.

To recreate, limit to show 1 entry per page and have several entries with the same title but different slugs. Search via a category filter and click through the pagination. Sometimes the information won't get updated when paging through. See below screens where clicking from pages 7 to 8 results in the info not updating.

![sprig_src_bug_01](https://user-images.githubusercontent.com/1113904/220076851-7b4784c7-8543-4cb6-9d8f-d640f2ce3c30.png)

When the info doesn't update, if you do a browser refresh it brings in the correct info as the below screen shows

![sprig_src_bug_02](https://user-images.githubusercontent.com/1113904/220077376-abae55ac-b3f3-424e-8317-d82e89f1dbbe.png)

Updating the entry title fixes the issue. Also including a search query via text input doesn't recreate the bug, seems to only be via category filter.

Using:
craft: Craft Pro 4.3.4
sprig 2.5.1

**Comment by bencroker** [comment]
Can you show me the code used for the element query to fetch and then paginate the entries?

**Comment by green17** [comment]
```twig
{% set entryQuery = craft.entries()
    .section('courses')
    .limit(limit)
    .with(['subject','mainCampusDescription','modeOfStudy']) 
%}

{% do entryQuery.subCourseParentId(':empty:') %}

{% if search is not empty %}
    {% do entryQuery.search(search) %}
    {% do entryQuery.orderBy('score') %}
{% else %}
    {% do entryQuery.orderBy('title') %}
{% endif %}

{% if level is not empty %}
    {% do entryQuery.qualLevel(level) %}
{% endif %}

{% if fullTime is not empty %}
    {% do entryQuery.fullTime(fullTime) %}
{% endif %}

{% if partTime is not empty %}
    {% do entryQuery.partTime(partTime) %}
{% endif %}

{% if campuses[0] is not empty %}
    {% do entryQuery.andRelatedTo(campuses) %}
{% endif %}

{% if qualifications[0] is not empty %}
    {% do entryQuery.andRelatedTo(qualifications) %}
{% endif %}

{% if topicCode[0] is not empty %}
    {% do entryQuery.andRelatedTo(topicCode) %}
{% endif %}

{% if subjectarea[0] is not empty %}
    {% do entryQuery.andRelatedTo(subjectarea) %}
{% endif %}

{% set pageInfo = sprig.paginate(entryQuery, page) %}
{% set courses = pageInfo.pageResults %}
```

**Comment by bencroker** [comment]
I'm not sure exactly what the issue is, but my guess is that the search results are being ordered differently on each request. Is the issue resolved if you change `orderBy('score')` to `orderBy('title')`? If so, then you might need to tweak the ordering of the search results somehow. Either way, though, I don't see how this could be considered a bug in Sprig.
