### ISSUE TITLE
Using Sprig with non craft dataset tables

### ISSUE THREAD

**Issue by playcraftSystems** [putyourlightson/craft-sprig#296]
Hello,

I wasn't able to find any examples of using Sprig with a database table not supplied by Craft. Is this possible? My use case is that we have several databases not related to Craft CMS, and our commerce items are located in a MS SQL Server.

**Comment by bencroker** [comment]
Sprig doesn't care what database you use – if it can be done via Twig or PHP then it can be done with Sprig.
