### ISSUE TITLE
Strict `andRelatedTo`

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#298]
You mentioned at 13:10 in video number 4 of the Sprig Filters series that your assumption is the user wants to return products matching that are in either 'casual' or 'elegant'.

I would like to update my filters to be both 'casual' and 'elegant' but I'm not sure how. I understand this might be general Craft / `andRelatedTo` but I figured since you mentioned it in that video maybe it's something you can help specifically with Sprig.

Here's my code (you helped me set this up here: https://github.com/putyourlightson/craft-sprig/issues/282)

```
{% set searchPeople = searchPeople ?? '' %}
{% set filterPeople = filterPeople ?? [] %}
{% set people = craft.entries.section('people').id(filterPeople).all() %}
{% if searchPeople %}
	{% set returnedPeople = craft.entries.section('people').id(['not']|merge(filterPeople)).search(searchPeople).all() %}
	{% set people = people|merge(returnedPeople) %}
{% endif %}

{% if filterPeople is not empty %}
	{% do matchesQuery.andRelatedTo(['and', {element: filterPeople, field: 'event.person',}]) %}
{% endif %}
```

So right now if I check Person 1 it correctly shows all events they relate to. If I also select Person 2, it'll add those events. What I would like is to show only events where Person 1 and 2 belong (and in this case, these are Entry fields inside a Matrix block.) I would have thought the `'and'` covers it but clearly not...

Thanks in advance for any support you can give.

**Comment by bencroker** [comment]
You'll need to put the `and` logic _between_ the people, which might look something like this:

```twig
{% for person in filterPeople %}
    {% do matchesQuery.andRelatedTo({ element: person, field: 'event.person' }) %}
{% endfor %}
```

**Comment by shifuma** [comment]
Lovely, that was it! Thanks!
