### ISSUE TITLE
Pass array into Sprig Component Class

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#299]
I've built a Sprig component class which I want to use to do some math on a bunch of entries. Is it possible to do this?

```
{# events.twig #}
{% set eventIds = clone(eventsQuery).limit(null).ids() %}
{{ sprig('RefreshRecords', {eventIds: eventIds}) }}
```

```
{# _components/refresh-records.twig #}
{% for eventId in eventIds %}
  {{ hiddenInput('eventIds[]', eventId) }}
{% endfor %}
```

```
{# sprig/components/RefreshRecords.php #}
$eventIds = Craft::$app->getRequest()->getBodyParam('eventIds');
$events = Entry::find()->section('events')->id(eventIds)->all();
## then do some math based on fields inside these events
```

As it stands, I get `Variable "eventIds" does not exist.` Is it not possible to pass an array into the Sprig component? Does it have to be a string?

**Comment by shifuma** [comment]
If I leave out the this part:

```
{# _components/refresh-records.twig #}
{% for eventId in eventIds %}
  {{ hiddenInput('eventIds[]', eventId) }}
{% endfor %}
```

Then it actually works; the component is processed and works well, but it performs the math on *every* entry, not just the ones in this array: `{% set eventIds = clone(eventsQuery).limit(null).ids() %}`

That's despite the response showing the correct number of Ids:
```
sprig:variables[eventIds]: 1fddc67b2128616674286237f847730ea134d68c933ecaf1084f7c1bd29678d4["870994","870864","867821","630245","629851","310389","310177","309649","310049","309495","310007","309881","309795"]
```

**Comment by bencroker** [comment]
Have you defined an `eventIds` property in the component class?

```php
class RefreshRecords extends Component
{
    public array $eventIds = [];
}
```
See https://putyourlightson.com/plugins/sprig#component-classes

**Comment by shifuma** [comment]
Ah, I missed that. Thank you!
