### ISSUE TITLE
CORS error when serving site from BrowserSync in Valet

### ISSUE THREAD

**Issue by furioursus** [putyourlightson/craft-sprig#3]
I’ve gone ahead and leveraged your pagination layout per your [cookbook entry](https://putyourlightson.com/sprig-cookbook#pagination) and everything seems to work great, as long as I’m not serving up the site from a proxy URL.

Valet takes my site and loads the domain `https://securitize20.test` as `https://localhost:3000`. As a result, if I try to refresh a component, it trips CORS in the process because the request isn't coming from the same domain and the whole thing crashes.

It’s not a deal breaker by any means, but it would be cool if we could leverage something similar to @nystudio107’s [Twigpack](https://github.com/nystudio107/craft-twigpack) plugin that allows you to specify the domain it should be serving from while Browsersync and a watch task are running.

Here’s the standard error I get when trying to work as mentioned above:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://securitize20.test/index.php?p=actions/sprig/components/render&sprig%3Atemplate=c39d718976b96fe6b5746a35c9fcb14e98d60e30d863e94a373c55fbd852dec1_components%2Fgrid-index&page=3. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://securitize20.test/index.php?p=actions/sprig/components/render&sprig%3Atemplate=c39d718976b96fe6b5746a35c9fcb14e98d60e30d863e94a373c55fbd852dec1_components%2Fgrid-index&page=3. (Reason: CORS request did not succeed).

afterRequest.htmx htmx-0.0.7.pre.js:138:50
sendError.htmx
```

**Comment by bencroker** [comment]
It doesn't seem like a good idea to me to bypass CORS in the plugin, as really it is there to prevent remote access. If it was possible to bypass it within the twig tag then it would be very easy to accidentally deploy that code to production and end up with a security vulnerability. Having the setting in a config file might help, but I still feel that this is something you can set up relatively easily using the `Access-Control-Allow-Origin` header in your server configuration. I found [this](https://gist.github.com/poul-kg/b669a76fc27afcc31012aa0b0e34f738) for Valet (I don't vouch for this code) which should get you on the right track.

**Comment by bencroker** [comment]
Did you find a solution to your issue @onebrightlight?

**Comment by furioursus** [comment]
Not yet, but like I mentioned, it’s not a huge barrier; it’s just something I noticed.

**Comment by bencroker** [comment]
Ok, thanks!
