### ISSUE TITLE
Refresh multiple other components?

### ISSUE THREAD

**Issue by eirabben** [putyourlightson/craft-sprig#30]
### Question
Is there any way to refresh multiple other components after a refresh?

Something like this?

```
{{ sprig('_components/component', {}, {
  '_': 'on htmx:afterSwap send refresh to #one, #another'
  // or
  '_': 'on htmx:afterSwap send refresh to [#one, #another]'
}) }}
```

Or is there a better pattern to use here?

If this is not currently possible, this might be a feature request instead of a support question.

**Comment by bencroker** [comment]
If you're using [hyperscript](https://hyperscript.org/docs/) then refer to the `then` keyword to trigger multiple events.

```html
<div _="on click add .fadeMe then wait 200ms then remove me">
  Fade & Remove Me
</div>
```
