### ISSUE TITLE
Posting to a custom controller in module

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-sprig#306]
Hi, 

Having a little issue. I've used Sprig several times for creating reactive forms for entry forms and the contact form plugin. 

However I've posting to a simple custom controller and not sure how I should be returning an error. 

The controller makes a few checks to ensure that the form has a valid email address.
If it fails, I just want to return an error at this point, but not sure how?

```php
public function actionUnsubscribe()
{
    $this->requirePostRequest();
    $request = Craft::$app->getRequest();

    $fullname = $request->getParam('fullname', false);
    $email = $request->getParam('emailAddress', false);

    if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        // return success false an error here
    } else {
        // do something & return success true
    }
}
```
Hope that makes sense? Just looking for a pointer really. Thanks.

**Comment by bencroker** [comment]
In Craft generally you’d use `$this->asModelSuccess` or `$this->asModelFailure` and this should work well with Sprig. See the usage of the Contact Form plugin, for example, at https://github.com/craftcms/contact-form/blob/c796765605978b80374b452285ac6d0f13fb11fe/src/controllers/SendController.php#L53-L68

**Comment by shornuk** [comment]
Thanks @bencroker - I did see that in digging around. Should have mentioned, that I'm on Craft 3 and believe `asModelSuccess ` and `asModelFailure ` came in Craft 4?

**Comment by bencroker** [comment]
Ah, in that case you’ll need to do something like the following.

```php
    if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        Craft::$app->getUrlManager()->setRouteParams([
            'email' => $email,
            'error' => 'Error message.',
        ]);

        return null;
    } 

    $this->redirectToPostedUrl();
```

**Comment by shornuk** [comment]
Apologies for not responding. Forgot I was working on this as the project was parked for a bit. Will come back in future if any issue, but thanks for the help so far. 👍

**Comment by bencroker** [comment]
Sure thing!
