### ISSUE TITLE
Included Query String Parameters in "advanced settings" are not being correctly filled in

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-sprig#307]
Hi, 

In my config file I had the following: 

'includedQueryStringParams' => ['rubrik', 'return', 'month', 'year', 'day', 'country', 'code'],

In the backend, I didn't fill in the "Included Query String Parameters" in the "advanced settings" or it was not available yet. 

Upon upgrade from craft 3.8 to craft 4.4 the migration script was attempting to fill the "Included Query String Parameters" table with values from the config file, but didn't do so. That left me with an empty table. 

<img width="986" alt="Bildschirmfoto 2023-05-05 um 11 58 23" src="https://user-images.githubusercontent.com/145828/236451959-e565ac9d-ea53-477e-bca6-cc12d4f3aa0f.png">

This caused an error on the site which unluckily I cannot reproduce again. 

Maybe this will help somebody else.

**Comment by bencroker** [comment]
As per the [changelog](https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#400---2022-05-04), the included/excluded query string parameters config setting format changed in version 4.0.0. Since the site was added, the new format is an array of nested arrays, for example:
```php
        // The query string parameters to include when determining if and how a page should be cached (regular expressions may be used).
        'includedQueryStringParams' => [
            [
                'siteId' => '1',
                'queryStringParam' => '.*',
            ],
        ],
```
