### ISSUE TITLE
Craft is namespacing form input names

### ISSUE THREAD

**Issue by isaacwingate** [putyourlightson/craft-sprig#310]
I'm using sprig in a custom plugin, which creates a custom field within the cms. I've ran input an issue when using a simple <input> field. Craft behind the scenes is changing the name attribute to be namespaced. eg,

`<input sprig name="query" />`

renders as 

`<input name="fields[matrixContent][blocks][14219][fields][query]" ...>`

From what I understand,  sprig uses the 'name' attribute on input fields to determine which variable to update. So is unable to target the variable to update. Is there a way around this?

**Comment by bencroker** [comment]
I'm not sure what exactly your question is, can you please elaborate more?

**Comment by isaacwingate** [comment]
Sure, sorry about that...
Take this example snippet:

    {% set query = query ?? '' %}    
    <input sprig s-trigger="keyup changed" type="text" name="query" value="{{ query }}" >
from what I understand, the 'name' attribute in the input field is used to specify which template variable  is updated. Which all works fine when using sprig on the frontend.

The issue I'm running into is when using sprig within a plugin in the cms. As stated above, craft is automatically changing my input fields 'name' attribute to be namespaced. Therefore sprig is unable to target the template variable I am wanting to attach the input field to.

So i guess the question is... Is there a way to target the template variable other than using the 'name' attribute?

**Comment by bencroker** [comment]
> Is there a way to target the template variable other than using the 'name' attribute?

There is not. You’ll need to somehow match the field’s name when using the variable. 

```twig
{% set query = fields['matrixContent']['blocks']['14219']['fields']['query'] ?? '' %}
```

There’s a [`namespaceInputName`](https://craftcms.com/docs/4.x/dev/filters.html#namespaceinputname) filter which might help, but it may be easier to construct the name using the field elements.

**Comment by isaacwingate** [comment]
Awesome. I wasn't aware you could do that, seems to have worked. Thanks for your time!
