### ISSUE TITLE
Barba.js x Sprig

### ISSUE THREAD

**Issue by lennonpuype** [putyourlightson/craft-sprig#311]
Hi,

I'm creating a website that uses barba.js for page transitions without reloading the page. But the issue is, when I change the page to one that has a filter created with Sprig, the filter won't trigger anymore which is obvious since the page already was loaded before.

I tried a workaround with `{% do sprig.refresh() %}` and `{{ sprig.triggerRefreshOnLoad() }}`

In screenshot below you can see where I put these reload options, but they don't seem to trigger.
![Screenshot 2023-05-26 at 11 31 46](https://github.com/putyourlightson/craft-sprig/assets/30866096/3d6819c1-40c4-4ee6-b50d-4d2dc6c51474)

Do you know a workaround with some implementation with a library like barba.js to make sprig work after changing the page when its not actually reloaded?

Thanks in advance!

**Comment by bencroker** [comment]
A similar question was answered in https://github.com/putyourlightson/craft-sprig/issues/65, does this help?

**Comment by lennonpuype** [comment]
That did the job, thanks!
