### ISSUE TITLE
Flash error isn't returned

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#313]
As explained in the [documentation](https://putyourlightson.com/plugins/sprig#controller-actions):

> The update-cart action will return a success value, as well as a flash notice or error, depending on the value of success. Sprig will load those return values into template variables for us, so we can use them as follows.

I try everything I could, but I don't get the returned error, while it works when I disable the Sprig plugin.

This is what I tried inside the controller:
```
Craft::$app->getSession()->setFlash('error', 'Oops');
Craft::$app->getSession()->setError('Oops');
Craft::$app->getSession()->set('error', 'Oops');
return $this->asSuccess();
```

`return $this->asSuccess('Oops');`

`return $this->setFailFlash('Oops');`

And the variables I tried to print inside the template:
`success`
`flashes`
`flashes.error`
`craft.app.session.getAllFlashes()`
`craft.app.session.getFlash('error')`
`craft.app.session.get('error')`

None of this return the error.

While Sprig is disabled, this is returning the error:
`craft.app.session.getFlash('error')`

Why and how to make it works?

Craft CMS version: `4.4.13`
Sprig version: `2.6.2`

**Comment by bencroker** [comment]
As of Craft 4, the recommended way to do this is using the `asFailure()` method.

```php
return $this->asFailure('Oops');
```

Can you see what this outputs?

```twig
{{ dump(flashes) }}
```

**Comment by romainpoirier** [comment]
Thank you, I can confirm that [`asFailure`](https://docs.craftcms.com/api/v4/craft-web-controller.html#method-asfailure) works.

As explained [here](https://github.com/craftcms/cms/issues/13218#issuecomment-1554138791), and as seen [in the doc](https://docs.craftcms.com/api/v4/craft-web-controller.html#method-setfailflash), I thought that `setFailFlash()` was the recommended method: _Sets an error flash message on the user session_.

**Comment by bencroker** [comment]
I would expect `setFailFlash()` to work, but you’ll need to then reference the flashes in the template as `flashes`.

```twig
{{ dump(flashes) }}
```

**Comment by romainpoirier** [comment]
Thank you, I tested again, and now can confirm that both works. First, it was not working because my `flashes` dump was inside a macro.

What method would you recommend? `asFailure` or `setFailFlash`? I don't really understand the differences, and why both exists, as both are returning the `flashes`.

**Comment by bencroker** [comment]
If your controller action should return a `Response` then use `asFailure` for failures and `asSuccess` for successes.
