### ISSUE TITLE
Question about using `s-val:` on a button

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#314]
I'm sorry to write for help on another one like this. I'm trying to include a different template based on the button that was clicked, per the code below. The `action` value shows in the Network tab of the browser, but nothing is loaded inside the slideout.

Can you spot anything obvious/silly that I'm missing? I'm using a Sprig Component Class to do some extra processing, not sure if that will make a difference.

```
{% set action = action ?? '' %}

<div class="relative" x-data="{ slideout:false }" x-cloak>
  <button sprig s-val:action="find" s-replace="#slideout" x-on:click="slideout = true">
    Find User
  </button>
  <button sprig s-val:action="create" s-replace="#slideout" x-on:click="slideout = true">
    Create User
  </button>

  {% embed '_components/slideout' %}
    {% block slideoutContent %}
      <div id="slideout">
        {% if action %}
          {% include '_component/' ~ action %}
        {% endif %}
      </div>
    {% endblock %}
  {% endembed %}
</div>
```

**Comment by bencroker** [comment]
I’d avoid using `action` as the parameter name. Craft uses this to trigger controller actions, so there may be a conflict. Can you check whether renaming the parameter makes any difference?

**Comment by shifuma** [comment]
Thanks Ben. Unfortunately, it doesn't make a difference.

**Comment by bencroker** [comment]
Have you defined `$action` as a public property in the PHP class?

**Comment by shifuma** [comment]
That was it! 🤦🏻‍♂️ Thanks Ben!
