### ISSUE TITLE
Executing a script after s-confirm?

### ISSUE THREAD

**Issue by smockensturm** [putyourlightson/craft-sprig#317]
HI.

Can I get to the action or vars after `s-confirm` is confirmed?

A Sprig shopping cart example: "Do you really want to remove this item"

Yes I do, and I also want to execute a javascript function that pushes to a GA4 dataLayer?

_Related: we'll also want to send GA4 data when we increase/decrease quantity in our Sprig shopping cart.  Where can I look to find out how to do this?_

**Comment by bencroker** [comment]
The [htmx:confirm](https://htmx.org/events/#htmx:confirm) event is triggered immediately after a trigger occurs on an element, so you can do this, for example.

```html
{{ sprig('_my-component) }}

{{ sprig.script }}
<script>
    htmx.on('htmx:confirm', () => sendGAData());
</script>
```

> Related: we'll also want to send GA4 data when we increase/decrease quantity in our Sprig shopping cart. Where can I look to find out how to do this?

For this I’d suggest using pure JavaScript.

```html
<button onclick="sendGAEvent();">Increase</button>
```

**Comment by smockensturm** [comment]
Lovely. Thanks.

Can you help me understaind why something like this has no effect, then?

```
{{ sprig.script }}
<script>
    document.body.addEventListener('htmx:confirm', function(evt) {
        evt.preventDefault();
        console.log("user clicked OK confirm");
    });
</script>

**Comment by bencroker** [comment]
That works as expected for me. Are you on the latest version of Sprig and do you have a `body` element in the HTML?

<img width="470" alt="Screenshot 2023-07-03 at 18 57 14" src="https://github.com/putyourlightson/craft-sprig/assets/57572400/6f02e2ad-47e0-48f6-98da-ca388482e53d">

**Comment by smockensturm** [comment]
Yes we do have a body element in the html.

We are using Craft 3.8.14 and Sprig is at version 1.13.0 for this release.

**Comment by bencroker** [comment]
The console log works fine in my test, having removed the `evt.preventDefault()` directive.

```twig
{{ sprig.script }}
<script>
    document.body.addEventListener('htmx:confirm', function() {
        console.log("user clicked OK confirm");
    });
</script>
```

**Comment by smockensturm** [comment]
Clearly I am not communicating very well.

I wish to call the analytics function **after** the user clicks OK, but **not**  if the user clicks cancel. Is that possible with sprig?

`<button sprig s-action="commerce/cart/update-cart" s-method="post" s-vals="{{ vals }}" s-confirm="Are you sure you wish to remove this item?">Remove</button>`

**Comment by bencroker** [comment]
Yes, that should be possible using the code I previously sent. 

```twig
{{ sprig.script }}
<script>
    htmx.on('htmx:confirm', () => sendGAData());
</script>
```

Although running it on action success might be a more robust way of doing it. 

```twig
{# This goes inside the component.  #}
{% if success is defined and success %}
    <script>
        sendGAData();
    </script>
{% endif %}
```

**Comment by smockensturm** [comment]
The cart is not a component. The buttons are. (tagged with `sprig`) I wish to specifically  send GA4 the `remove_from_cart` event. 

I have tried to make this as simple as I can, stripping out many specifics. But the function never fires. Here's the whole bit. 
```

<button sprig s-confirm="Are you sure you wish to remove this item?">Remove</button>

{{ sprig.script }}
<script>

    htmx.on('htmx:confirm', () => sendGAData());
    
    function sendGAData() {
        sessionStorage.setItem("hey", "you removed an item");
    }

</script>
```

I understand about the success action, but then I have to build all the logic to determine events, ie what has happened to the cart. (Did an item get added? Did an item get removed? Did a quantity change?)

Would much rather attach a couple of functions to my sprig buttons. Which is no problem except for this confirm situation.

**Comment by bencroker** [comment]
The button with the `sprig` attribute must be _inside_ the Sprig component, otherwise it looks fine to me.

**Comment by smockensturm** [comment]
It is. **All of this** is inside the sprig component. What am I missing?

```

<button sprig s-confirm="Are you sure you wish to remove this item?">Remove</button>

{{ sprig.script }}
<script>

    htmx.on('htmx:confirm', () => sendGAData());
    
    function sendGAData() {
        sessionStorage.setItem("hey", "you removed an item");
    }

</script>
```

**Comment by bencroker** [comment]
You seem to be mixing component code with non-component code, please refer to the docs on how to load Sprig components and let me know if you still have issues with this afterwards.

**Comment by smockensturm** [comment]
Yeah maybe.

This is in the _layout template:

`{{ sprig.script }}`

The cart component is loaded thusly:

`{{ sprig('_sprig/cart',{id:'cart'}) }}`

This element is inside the cart component template:

`<button sprig s-action="commerce/cart/update-cart" s-method="post" s-vals="{{ vals }}" s-confirm="Are you sure you wish to remove this item?">Remove</button>`

This script is inside the cart **parent** template:
```
<script>
        htmx.on('htmx:confirm', () => sendGAData());
 </script>
```
Also tried this here Sweet Alert example from the docs (loaded last), to no avail. (Yes I've loaded the swal library)

```
document.body.addEventListener('htmx:confirm', function(evt) {
    evt.preventDefault();
    swal({
      title: "Are you sure?",
      text: "Are you sure you are sure?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    }).then((confirmed) => {
      if (confirmed) {
        evt.detail.issueRequest();
      }
   });
});
```

The confirm dialog never gets intercepted. Why not?

**Comment by bencroker** [comment]
So after rereading the docs at https://htmx.org/events/#htmx:confirm, it turns out that the `htmx:confirm` event is triggered immediately when the button is clicked, _before_ the user is prompted to confirm the action. Since that is not what you want, it is probably better to use another event such as `htmx:beforeRequest`.

```twig
{{ sprig('_component') }}
{{ sprig.script }}
<script>
    htmx.on('htmx:beforeRequest', () => console.log('Send request.'));
</script>
```

**Comment by smockensturm** [comment]
Not quite. The request still does execute **after** the dialog is confirmed. So the `beforeRequest` event - though very helpful - doesn't even happen until after OK is clicked.

But now you understand what I am trying to do.

The example at  https://htmx.org/events/#htmx:confirm is exactly it. Yet you tell me above (emphasis mine)

> The console log works fine in my test, **having removed the evt.preventDefault()** directive.

This is exactly the behavior I need though! Can Sprig do that?

If not, I'll probably need to try this: https://htmx.org/examples/confirm/

**Comment by smockensturm** [comment]
On second thoughts. This works. Thank you for your help and  patience.

**Comment by bencroker** [comment]
Glad to hear it! Keep in mind that htmx is what powers most of the Sprig front-end functionality, so for anything low level like this, you can follow the htmx docs.
