### ISSUE TITLE
Query drafts and provisionalDrafts inside Sprig

### ISSUE THREAD

**Issue by jodeba** [putyourlightson/craft-sprig#318]
Hi!

I have my template code like this to have a working live preview:

main template:
```
{{ sprig('_site/sprig/news/default', {_entryId: entry.id, _isProvisionalDraft: entry.isProvisionalDraft}) }}
```

inside the sprig template:
```
{% if token is defined %}
    {% set entry = craft.entries.id(_entryId).drafts().provisionalDrafts(_isProvisionalDraft).one() %}
{% else %}
    {% set entry = craft.entries.id(_entryId).one() %}
{% endif %}
```

Is used the token variable to check because of your suggestion in #162
Without the `drafts().provisionalDrafts(_isProvisionalDraft)`, the query does not return an entry while previewing drafts.

Is this the correct way to do this? Because I think it looks like too much code for something native to Craft.

Thank you for your time!

**Comment by bencroker** [comment]
The outcome of #162 was that live preview should “just work” (without having to do what you’ve done above), is that not the case?

**Comment by jodeba** [comment]
No, when I check the raw query of `craft.entries.id(_entryId).one()`, there is still a 'draftId IS NULL' condition present.

**Comment by bencroker** [comment]
Ok, I'll look into it and let you know what I find.

**Comment by bencroker** [comment]
In my initial tests, it looks like this will work:

```twig
{{ sprig('_site/sprig/news/default', { _entryId: entry.canonicalId }) }}
```

```twig
{% set entry = craft.entries.id(_entryId).one() %}
```

Can you please test?

**Comment by jodeba** [comment]
Sorry for the late reply.

Looks fine, it works. Thanks! 👍 🙂
