### ISSUE TITLE
Variable in nested components only available on first page load.

### ISSUE THREAD

**Issue by metamachineco** [putyourlightson/craft-sprig#32]
### Question
So, i'm trying to update a craft commerce order status from the frontend. The page shows the current order status and underneath you have 2 buttons where you can update the order status. After clicking one of the buttons, the page does nothing and in `console` > `network`, I can see `Impossible to invoke a method ("setAttributes") on a null variable`.

I think the root cause is the following:
I retrieve the variable from the slug (in this case the order id), and this variable is apparently only available on the first page load. If I click on one of the buttons, triggering a refresh, the variable returns `null`.

Sidenote: I have to get/set the order id from the slug in the parent component (to show the status) as wel in the child component (so I can update it). Not ideal, but don't know if that matters? 

Example URL: http://website.test/app/order/1234

```
{# nesting-parent #}
{% set orderNumber = craft.app.request.getSegment(3) %}
{% set orderQuery = craft.orders()
    .id(orderNumber) %}
{% set order = orderQuery.one() %}
{{ order.orderStatus }} 
{{ sprig('app/_components/statusbuttons') }}
</div>

{# nesting-child #}
{% set orderNumber = craft.app.request.getSegment(3) %}
{% set orderQuery = craft.orders()
    .id(orderNumber) %}
{% set order = orderQuery.one() %}

{% set new = new ?? false %}
{% set inprogress = inprogress ?? false %}

{% if new == 1 %}
    {% do order.setAttributes({'orderStatusId': 1}, false) %}
    {% do craft.app.getElements().saveElement(order) %}
{% endif %}

{% if inprogress == 1 %}
    {% do order.setAttributes({'orderStatusId': 2}, false) %}
    {% do craft.app.getElements().saveElement(order) %}
{% endif %}

<a sprig s-vars="new: 1" href="#">New</a>
<a sprig s-vars="inprogress: 1" href="#">In progress</a>
```

**Comment by bencroker** [comment]
You shouldn't be using `craft.app.request.getSegment` in components because components are rendered independently of the parent template and the current request. Instead, you should pass the order number into the components as a variable, as per the recipe at https://putyourlightson.com/sprig-cookbook#nesting-components.

```twig
{{ sprig('_components/nesting-parent', {orderNumber: craft.app.request.getSegment(3)}) }}
```

```twig
{# nesting-parent #}
{% set order = craft.orders().id(orderNumber).one() %}
{{ order.orderStatus }} 
{{ sprig('app/_components/statusbuttons' {orderNumber: orderNumber}) }}
</div>
```

```twig
{# nesting-child #}
{% set order = craft.orders().id(orderNumber).one() %}
...
</div>
```

**Comment by metamachineco** [comment]
Thanks Ben, works like a charm now!

Now that I have a better grasp on this, I realized I even don't need nested components and can simplify the code much more.

**Comment by bencroker** [comment]
Glad to hear it!

**Comment by bencroker** [comment]
FYI the `s-vars` attribute has been deprecated in Sprig 1.1.0. Read the details [here](https://putyourlightson.com/articles/sprig-1-1-0-released).
