### ISSUE TITLE
"Back in Stock" form notification only works once

### ISSUE THREAD

**Issue by hhentschel** [putyourlightson/craft-sprig#320]
In my Craft Commerce Setup i have a form via the [Back in Stock Plugin](https://github.com/mediabeastnz/craft-commerce-back-in-stock/blob/master/README.md),
which lets the user be notified, when a product is available again.

There is a input field for the E-Mail Adress and a submit button.

As i want to use blitz i include the form with sprig like this.

```
{# Product page #} 

{{ sprig(
   'shop/backinstock-form.twig',
    {}, {'s-trigger': 'load'}
 ) }}
```

```
{# Back in Stock Form page / backinstock-form.twig #} 

{% if sprig.isRequest %}
  {% if success is defined and success %}

     You get notified.

{% else %}

    <form sprig
          s-action="craft-commerce-back-in-stock/base/register-interest"
          s-method="post"
          >

           Product not available. Please enter your email.

      <input type="hidden" name="variantId" value="{{ product.defaultVariant.id }}">
      <input name="email" type="email" value="{{ cart.email }}">

     {{ craft.snaptcha.field }}

    </form>

  {% endif %}
{% endif %}
```

This works only with a never used E-Mail Adress. If i want to test it again with the same E-Mail nothing happens.
Is the snaptcha field a problem?
I tried replacing the snaptcha field with this, but it did not help.

`{{ craft.blitz.getUri('/actions/snaptcha/field/get-field') }}`

I use the set-up above with the contact form from P&T and there i have no issues.

**Comment by bencroker** [comment]
Can you try adding an error clause to see if the action is unsuccessful?

```twig
{% if sprig.isRequest %}
  {% if success is defined %}
     {{ success ? 'success' : 'error' }}
{% else %}
```

**Comment by hhentschel** [comment]
If i use a new email i get a "success" message otherwise nothing happens, as before.

**Comment by bencroker** [comment]
The statement `{{ success ? 'success' : 'error' }}` must output one of two strings. Are you sure you tested this correctly? Is the AJAX request submitted and what is the response code and content?

**Comment by hhentschel** [comment]
Instead of `{% if success is defined %}` i had `{% if success is defined and success %}`.
After removing `and success` and using an already used email address,  
i get `error` / `You get notified` as response, but no email is being sent.

**Comment by bencroker** [comment]
Ok, so that indicates, as expected, that the Back in Stock plugin is returning an error.

**Comment by hhentschel** [comment]
ok, thanks. haven't found the error yet.
one last question:
i cannot be that this plugin has diificulties of being rerendered via the s-trigger:load action?

Sorry for asking 'dump' question for super clear situations, but want to get rid of all the question marks around.

**Comment by bencroker** [comment]
> i cannot be that this plugin has diificulties of being rerendered via the s-trigger:load action?

If you want the component to be refreshed on both `load` and `refresh` events (the default), then you should add both to `s-trigger`.

```twig
{{ sprig('shop/backinstock-form.twig', {}, { 's-trigger': 'load,refresh' }) }}
```

Try outputting `flashes` to see if any errors appear:

```twig
{{ dump(flashes ?? []) }}
```

**Comment by bencroker** [comment]
Closing this as it’s getting extremely specific to your use-case, though I’d be happy to offer more custom support via email.

**Comment by hhentschel** [comment]
Thanks Ben. I will get back to you, after i finished my overall upgrade process, if i still need help.
maybe the ported v4 of back-in-stock helps.
Its weird as it seem to work, but not for the logged in user.
