### ISSUE TITLE
Load More Complex  - possible to initially display 4 items and the load 2 more per button click?

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#321]
I'm using the code from the cookbook recipe - Load More Complex and all is working fine.

However I'd like to have 4 items initially and then 2 per load more button click.

I've tried setting different values for the offset at the top of the code block as well as the s-val:offset value in the button but notthing works as I want.

please advise

Below is my current code:

```twig
{# set block id #}
{% set block = craft.matrixBlocks.id(blockId).one() %}

{# Sets a default value if not defined by the `s-val:*` attribute on the button #}
{% set offset = offset ?? 0 %}

{% set imageQuery = block.images.offset(offset).limit(limit) %}
{% set images = imageQuery.all() %}

<div id="images" class="grid grid-cols-1 gap-6 md:grid-cols-2">
  {% for image in images %}
    {{ include('_includes/responsiveImage', {
      image: image,
      // various image settings
    }, with_context = false) }}
  {% endfor %}
</div><!-- /.grid grid-cols-1 -->

{# If the total entry count is greater than the number that has been displayed #}
{% if imageQuery.count() > offset + images|length %}
  {# Increments `offset` by the value of `limit` #}
  <button
    id="load-more-oob"
    class="mt-8 btn"
    sprig
    s-val:offset="{{ offset + limit }}"
    {# Appends all `#results img` elements to the `#images` element #}
    s-select="#images picture"
    s-target="#images"
    s-swap="beforeend"
    {# If this button was clicked then swap it out-of-band #}
    {{ sprig.trigger == 'load-more-oob' ? 's-swap-oob="true"' }}>
    Load more
  </button>
{% else %}
  {# Swaps the button out-of-band with a dummy button that is hidden #}
    <button id="load-more-oob" s-swap-oob="true" style="display: none"></button>
{% endif %}

```

**Comment by bencroker** [comment]
That should be doable by setting the limit to `4` initially and to `2` on the button’s `s-val` property.

**Comment by CreateSean** [comment]
Ben,

`s-val:offset="{{ offset + limit }}"` loads 4 new images

`s-val:offset="{{ offset + 2 }}"` or `s-val:offset="{{ offset + '2' }}"` or `s-val:offset="2"`   loads 4 images, but the first 2 are the same as the last 2 of the previous 4

`s-val="2"` loads the initial 4 images again

Not sure what I'm doing wrong.

**Comment by bencroker** [comment]
Here’s how I’d write it in the component. Then the `offset` value will take care of itself.

```twig
{% set limit = sprig.isInclude ? 4 : 2 %}
```

**Comment by CreateSean** [comment]
Ben,

Thank you. works perfect. I should've seen that myself.
