### ISSUE TITLE
sprig.pushUrl doesn't work when adding a hashtag to create a jump link

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#324]
I've got a matrix block that is sprig reactive and I am successfully pushing the category to the url so the tabs display correctlyk when deep linking. However what I need is to add a #section-4068 (4068 temporarily hard coded - is actually block.id from a matrix field) so that the browser will smooth scroll to the correct section on the page.

I've tried this:

```twig
  {% do sprig.pushUrl('?' ~ {categoryId: categoryId,} ~ '#section-4068' |url_encode) %}
```

but then I get an `Array to string conversion` error.

I tried a couple of other options but nothing seemed to work.

manually typing this for the browser works as expected but I need to be able to push the hash.

https://dpmc-2023.ddev.site/fellows?categoryId=4264#section-4068

**Comment by bencroker** [comment]
The error, assuming it pertains to the line you shared, seems to indicate that `categoryId` is an array. Since I can’t see the rest of your code though, I can’t say why that might be.

**Comment by bencroker** [comment]
This error is being caused by the fact that you’re concatenating a string (`'?'`) with an array (`{categoryId: categoryId,}`). Something like this should work.

```twig
{% do sprig.pushUrl('?categoryId=' ~ categoryId ~ '#section-4068') %}
```
