### ISSUE TITLE
TypeError Argument #1 ($template) must be of type string, null given

### ISSUE THREAD

**Issue by baileydoestech** [putyourlightson/craft-sprig#325]
Some requests to `p=actions/sprig-core/components/render` can result in an internal server error:

(note these are not normal requests we expect our site/users to be making, discovered by our security scanning solution looking for vulnerabilities)

Steps to reproduce the issue.
- Install sprig (latest), the following requests will trigger internal server errors:

`?p=actions/sprig-core/components/render&offset=%27");%7C]]]]]]]]]`
`?p=actions/sprig-core/components/render&offset=<!--`

![image](https://github.com/putyourlightson/craft-sprig/assets/3185073/a50be298-e1ff-42b1-ae81-52475649e467)

PHP 8.2.9
Craft Pro 4.5.3
Sprig 2.6.2

**Comment by bencroker** [comment]
This is the expected behaviour when a Sprig request is tampered with. What exactly is the bug or security issue here?

**Comment by baileydoestech** [comment]
No security issue as such, more that this floods our logs with 500 errors - should this not return some sort of 4XX error given that the request is malformed from the client?

**Comment by baileydoestech** [comment]
As an example, similar malformed requests to Craft generated 400 errors: 
![image](https://github.com/putyourlightson/craft-sprig/assets/3185073/9c734c98-b820-42eb-b604-2861e0758ae5)

**Comment by bencroker** [comment]
Ah I see, yes you’re right. Fixed in https://github.com/putyourlightson/craft-sprig-core/commit/8b621d7138c2c5c21beb71b6b16059184d0e3a84 for the next release. Thanks for reporting this!

**Comment by mark-chief** [comment]
Hello there, is there a way to get this release early as our logs are getting flooded with this error (am right in thinking the above fix will stop that!) It's a high traffic site 7k users per minute. Thank you.

**Comment by bencroker** [comment]
Aiming to release this tomorrow.

**Comment by bencroker** [comment]
Released in [2.7.0](https://github.com/putyourlightson/craft-sprig/releases/tag/2.7.0).
