### ISSUE TITLE
Component get repeatedly rendered on button click

### ISSUE THREAD

**Issue by yannkost** [putyourlightson/craft-sprig#327]
I'm trying to adapt the load more example and got it all set up and working, but there is a litte part of if I can't reproduce the  result of the sprig cookbok. [https://putyourlightson.com/sprig/cookbook?page=3#load-more](https://putyourlightson.com/sprig/cookbook?page=3#load-more)

```
{% set categ = categ ?? null %}
{% set limit = limit ?? 1 %}

{% set categories = craft.entries({
    section: 'category',
}).all() %}

{% if categ %}
    {% set selectedCateg = categories|filter(v=> v.id == categ) %}
{% endif %}

{% set entriesQuery = craft.entries({
    section: 'contentStructure'
}|merge(selectedCateg is defined ? {relatedTo: selectedCateg} : {})
).limit(limit)
%}

{% set entries = entriesQuery.all() %}
{% set count = entriesQuery.count() %}

<div class="load-more">
    {% for category in categories %}
        <button sprig
                s-val:categ="{{ categ == category.id ? '' : category.id }}"
                s-val:limit="{{ 1 }}"
                id="category-{{ category.id }}"
                class="{{ categ == category.id ? 'load-more--selected' : '' }}"
        >{{ category.title }}</button>
    {% endfor %}

    <ul id="category">
        {% for entry in entries %}
            <li>{{ entry.title }}</li>
        {% endfor %}
    </ul>

    {% if entriesQuery.count() > entries|length %}
        {# Increments `offset` by the value of `limit` and swaps itself out on click #}
        <button sprig
                id="test"
                s-val:limit="{{ limit + 1 }}"
                s-target="this"
                s-swap="outerHTML"

                >
            Load another
        </button>
    {% endif %}

    {{ hiddenInput('limit', limit) }}
    {{ hiddenInput('categ', categ) }}
</div> 
```

 When using this code, the whole component get repeated when clicking the "Load another" button. But if I remove the `s-target="this"` and the `s-swap="outerHTML"`, everything works fine. From the documentation and sprig cookbook I see that this should swap the button itself, not the entire component. What am I missing here?

Note: Great plugin by the way, working with it is fun!

**Comment by yannkost** [comment]
![image](https://github.com/putyourlightson/craft-sprig/assets/25202769/533703b5-9421-4a1c-bd12-88bfe46c3a02)

I forgot to add the screenshot, here we can see that the whole component get's rendered multiple times.

**Comment by bencroker** [comment]
It looks like you’re missing an offset, see https://putyourlightson.com/sprig/cookbook#load-more, and you’ll likely want to conditionally show the categories if `sprig.isInclude`. There’s also a more complex example at https://putyourlightson.com/sprig/cookbook#load-more-complex in case you need it.

**Comment by yannkost** [comment]
I'm not sure to understand. I intentionally did not use the offset. As I understand it, the whole template will be rerendered, so this is not a problem. Also, if I use the sprig.isInclude, the whole part with the categories just dissapears.

**Comment by bencroker** [comment]
Please use the code from the recipe I linked, to see how it works. If you are still stuck then I can look at your code again.
