### ISSUE TITLE
Combining live search + load more

### ISSUE THREAD

**Issue by mmorkt** [putyourlightson/craft-sprig#33]
Hi Ben love your work. Blitz cache really makes Craft CMS fly! 
Now i'm trying to get my head around Spring. 

### Question
Can you make an example combining the search + load more functions. Tried but the search gets inaccurate (guess its refreshing both components). 

Did try nesting the components as well but couldn't  use arrays in nesting.

My example:
```
{#--- _components/news ---#}
  
{% set query = query ?? '' %}
{% if sprig.isInclude %}
  <div class="w-full">
	  <input sprig s-trigger="keyup changed" s-target="#results,#replaceTwo" s-swap="outerHTML" 
	type="text" name="query" value="{{ query }}" placeholder="search..." class=" border border-blue p-3 w-full mb-4 placeholder-black placeholder-opacity-100" />
{% endif %}
  
  
<div id="results">
  
	{% set entriesOne = craft.entries.section('news').search('title:*'~ query~' *').orderBy('postDate desc') %}
	{% set entries = entriesOne.offset(offset).limit(_limit).all() %}
	
        {% for item in entries %}
	   <a href="{{ item.url }}"><img src="{{ item.image.one().url }}" class="w-full" /></a>
	{% endfor %}

 	  {% if entries|length %}
		  <div id="replace" class="text-center">
			<input type="hidden" name="offset" value="{{ offset + _limit }}">
			<button sprig s-target="#replace" class="button mb-10 py-2" s-swap="outerHTML">Load more</button>
		</div>
	  {% endif %}
	  </ul>
</div>
```

**Comment by bencroker** [comment]
What is the problem with your code? It looks to me like it should work...

**Comment by mmorkt** [comment]
it works sort of... load more works. But the search form is not as accurate as the default 'live search component'. it hides results that shouldn't be hided. 

Default live search component
Searching for: 'Ny'
• Nyhet 1
• Nyhet 2
• Nyhet 3

My live search component
Searching for: 'Ny'
• Nyhet 3
... and it refreshes a lot more

**Comment by bencroker** [comment]
So it is working, but not quite as you expect? I'm having trouble understanding how I can help you here...

**Comment by mmorkt** [comment]
Sorry if I was unclear. Is there a better way to combine the two modules? Would be great in the cookbook. I tried nested components but it didn't work with an entries array. If my question is irrelevant you may close the ticket.

**Comment by bencroker** [comment]
I tested your code and it is working for me. As for adding it to the cookbook, it seems too specific to your use-case, but I'm happy to answer any other questions you may have.
