### ISSUE TITLE
Sprig stops working after last update

### ISSUE THREAD

**Issue by venturini-dev** [putyourlightson/craft-sprig#330]
- To reproduce: Update Sprig from 2.6.2 to 2.7.2
- Expected Sprig to work like before
- We experience the issue on Craft PRO 4.5.6.1 and Sprig 2.7.2

Sprig initializes correctly and creates appropriate HTMX tags, but elements with the "sprig" attribute do not make requests anymore - the network tab is completely silent.
This happens both with the now deprecated {{sprig.script}} tag and without it.

We also tried copying the example in the backend to the frontend, same issue. It's like Sprig doesn't make network requests.
No error anywhere, browser console is clean.

**Comment by bencroker** [comment]
The only difference should be that instead of being loaded inline where the `sprig.script` tag used to be, the `htmx` file will be towards the end of the `body`. Do you have a link to a page that I could look at, or any other way for me to help troubleshoot?

**Comment by venturini-dev** [comment]
You can find the working version here (Sprig 2.6.2)
https://shop.cipriani-phe.com/en/scambiatori/

Whereas here you can find the broken one here (Sprig 2.7.2):
https://test-shop.cipriani-phe.com/en/scambiatori/

**Comment by bencroker** [comment]
I don’t see the `htmx` script being loaded anywhere in the latter. Are you using caching anywhere on the page?

**Comment by venturini-dev** [comment]
The only time we are using the {% cache %} tag is in an included template we use for the favicon, there is no other caching being done that i'm aware of. 
I just added a {{sprig.htmxVersion}} tag for you to see on the page, let me know if I can output anything else that can be of use!

**Comment by bencroker** [comment]
Hmm, that’s unusual. It seems like something is blocking Sprig from registering the htmx script.

Can you please try adding this to your layout template (wherever `sprig.script` used to be)?
```twig
{% do sprig.registerScript %}
```

For reference: https://putyourlightson.com/plugins/sprig#sprig-registerscript

**Comment by venturini-dev** [comment]
added {% do sprig.registerScript %} to all relevant layout templates, same behaviour.

**Comment by bencroker** [comment]
Can you ensure you have cleared caches, especially compiled templates and template caches?

**Comment by venturini-dev** [comment]
Yes:

![image](https://github.com/putyourlightson/craft-sprig/assets/68391851/7372f489-36f2-4476-863c-474dfe429b26)

**Comment by bencroker** [comment]
Are there any clues with `devMode` enabled, perhaps? And is the same thing happening in your local development environment?

**Comment by venturini-dev** [comment]
The site you can access has devMode enabled, I can't see any issue popping up. Can confirm I have the same issue in my local env, and a colleague can reproduce in their env too.

We also tried to do a fresh install of craft and sprig and everything works correctly there.

Is there anything in the logs I should check?

**Comment by bencroker** [comment]
Not really. Can you please test whether the htmx script is loaded using a simple template?

```twig
<html>
<head></head>
<body>
    {{ sprig('path/to/template') }}
</body>
</html>
```

**Comment by venturini-dev** [comment]
here you can find the test:
https://test-shop.cipriani-phe.com/sprig-test

i used one of your examples from the playground, and this does work correctly.

**Comment by bencroker** [comment]
Great, so that confirms that there must be something in your template setup that is preventing the registered htmx script from being output to the page.

**Comment by venturini-dev** [comment]
Hi Ben, yes, I can confirm that the issue was on our side.
4 months ago we introduced a bug that produced an invalid DOM structure, because it generated 2 closing body tags.
The issue was completely silent until now, because of the new way Sprig adds the script.
 THANKS a lot for your support.

**Comment by bencroker** [comment]
Glad to hear you solved it!
