### ISSUE TITLE
htmx not defined 

### ISSUE THREAD

**Issue by icreatestuff** [putyourlightson/craft-sprig#332]
I updated to 2.7.2 from 2.6.2 which includes the deprecation of the `{{ sprig.script }}` tag. Having done the update I now get `htmx is not defined errors` in the console, and some JS doesn't work. I have some site-wide JS loaded that utilises some of the HTMX events e.g.

```js
htmx.on('htmx:afterSettle', function(event) { 
    // Do some stuff
});
```

```js
htmx.on('htmx:afterSwap', function(event) {
    // Do other things...
});
```

It's this that looks to be causing an issue.

In my main twig layout template, I previously had this which worked: 

```twig
{{ sprig.script }}

<script src="{{ mix('js/main.js') }}"></script>
```

Post-update I have tried the following to force the registration and load of the htmx script, but this doesn't appear to work.

```twig
{% do sprig.registerScript %}

<script src="{{ mix('js/main.js') }}"></script>
```

The htmx script does load according to the dev tools network panel, but I get the impression that the `main.js` script is still running before it even with the order of scripts shown above. 

Is there anything else that could be done to rectify this, or does using Sprig/htmx in this way require that I now download and host (or pull from a CDN) the htmx library as described here: https://putyourlightson.com/plugins/sprig#htmx
I'd prefer to not have to remember to keep the hosted library version in sync with the version Sprig expects if possible.

Craft 4.5.6.1
Sprig 2.7.2

Thanks

**Comment by bencroker** [comment]
Sprig now loads htmx by registering it as a JS file, which means that it is loaded at the end of the body tag. Therefore, any JS code you run should be loaded via the `{% js %}` tag to ensure that it too is loaded at the end of the body. 

See the example at the end of this section: https://putyourlightson.com/plugins/sprig#javascript

**Comment by icreatestuff** [comment]
Thanks for the guidance @bencroker, given the URL to the main JS file is dynamic based on the `mix()` function I've tried the following (based on the [JS tag documentation](https://craftcms.com/docs/4.x/dev/tags.html#js))

```twig
{% do sprig.registerScript %}

{% set mainJsFile = mix('js/main.js') %}
{% do view.registerJsFile(mainJsFile) %}
```

Both scripts are loaded at the end of the body, but the htmx script is still loaded **last** resulting in still seeing the htmx undefined errors. It seems no matter what order I set the `{% do %}` tags htmx is always loaded last. I've tried disabling caching altogether and clearing compiled template and template caches between each variation.

**Comment by bencroker** [comment]
What happens if you add a `defer` attribute to your script? See https://craftcms.com/docs/4.x/dev/tags.html#with-2

**Comment by icreatestuff** [comment]
Ahh yes that did the trick. For anyone else (and probably my future self) here's what I have working:

```twig
{% do sprig.registerScript %}

{% set mainJsFile = mix('js/main.js') %}
{% do view.registerJsFile(mainJsFile, { 'defer': true }) %}
```

Thanks for the help @bencroker

**Comment by bencroker** [comment]
Sure thing, glad you got it working. I'll add a note about that to the docs.

**Comment by darylknight** [comment]
Thanks for this thread :) Just ran into the same problem on a site using Sprig to live-filter a Google map. Changing the code from:
```
{# Load Sprig's htmx requirement from a CDN #}
{% sprig.script() %}

{# When sprig filters the results, re-render the map #}
<script>
	htmx.on('htmx:afterSettle', function(event) { googleMaps.init('projects-map'); });
</script>
```
to:
```
{# Load Sprig's htmx requirement from a CDN #}
{# This replaces the old sprig.script #}
{% do sprig.registerScript() %}

{# When sprig filters the results, re-render the map #}
{% js %}
	htmx.on('htmx:afterSettle', function(event) { googleMaps.init('projects-map'); });
{% endjs %}
```
fixed the error.

**Comment by bencroker** [comment]
@darylknight FYI the `sprig.registerScript` tag is now only required if you’re doing something that would prevent Sprig from auto-registering it, so it most likely is safe to remove.

**Comment by darylknight** [comment]
You're right - I can remove the first 3 lines of that and it still works fine, thanks!

**Comment by CreateSean** [comment]
This thread is a life saver, thank you.
