### ISSUE TITLE
Sprig not working on element rendered initially through my own JS

### ISSUE THREAD

**Issue by charliestrafe** [putyourlightson/craft-sprig#333]
Hi there,

I am trying to get my sprig 'wishlist' component to work on an element that is loaded initially through an axios request on page load. However once loaded, clicking on the sprig wishlist button results in nothing happening.

The below code is the controller for my axios GET request, it returns the contents of the card as a HTML string.
```
foreach($entries as $item) :
       $html = $this->getView()->renderTemplate('cards/item.twig', ['item' => $item]);
       $return['results'][] = $html;
endforeach;
return $this->asJson($return);
```

Then after the JS inserts this HTML into the DOM.
```
        axios.get('/locations')
        .then( (response) => {
            this.data = response.data.results;
            this.container.insertAdjacentHTML('beforeend', this.data.join(" "))
        });
```

On the 'item.twig' file that is inserted into the JS, this is my sprig button to add the item to the wishlist.
```
<button sprig s-method="post" s-action="wishlist/items/add">Add to wishlist</button>
```

However when clicking it, nothing happens. No server request is sent in the network browser tab. I can see that sprig data attributes are being loaded onto the button element, which is leading me to believe that perhaps an event listener for the actual button needs to be recalled?

When I call and render the elements the normal using a craft entry query the add to wishlist button works fine, so its something to do with the fact I'm loading them in and inserting them via my own JS.

How can this be done? Thanks!

**Comment by bencroker** [comment]
You'll need to tell htmx to process the HTML after it has been inserted into the DOM, which you can do with `htmx.process()`, see https://htmx.org/api/#process

**Comment by charliestrafe** [comment]
I've just tried adding that into my .js file where the HTML is inserted however it doesn't seem to have made a change? I'm using webpack so I have included it like so:

```import 'htmx.org';```

```htmx.process(this.container)```

this.container being my HTML element that holds the appended HTML. Is there anything else I may need to do?

**Comment by bencroker** [comment]
I'm not sure about your specific setup, but the answer should be to have htmx reprocess the DOM. 

See https://github.com/putyourlightson/craft-sprig/issues/24 and https://github.com/putyourlightson/craft-sprig/issues/65 for reference.
