### ISSUE TITLE
Create or Update an Array via Checkboxes

### ISSUE THREAD

**Issue by AbbeyDesign** [putyourlightson/craft-sprig#334]
I am trying to create an array from a clicked checkboxes. I was hoping I could click on a checkbox and its value gets added to the array called in the #articles div. Unfortunately every sprig code combination results in nothing being replaced.

```
{% set assetsArray = assetsArray ?? [] %}


<div id="filters" >
{% set assets = craft.entries({section: 'someSection', limit: 5}) %}
	{% for asset in assets %}
		<input sprig s-replace="#articles" type="checkbox" s-trigger="click" name="assetsArray[]" value="{{ asset.id }}"/>
		<label for="coding">{{ asset.title }}</label>
	{% endfor %}
</div>

<div id="articles">
	{% set ids = assetsArray %}
	{% for asset in assetsArray %}x{% endfor %}
</div>
```

**Comment by bencroker** [comment]
I threw your code into the Sprig Playground and each time I check a checkbox, I see another `x`, so it appears to be working in the latest version of Sprig.

**Comment by AbbeyDesign** [comment]
I just tried in the playground and it works as you said. Why not the browser on its own. Did I miss step?

**Comment by AbbeyDesign** [comment]
I tried Safari, Chrome, and Firefox.

**Comment by bencroker** [comment]
Can you ensure you have Sprig set up and working in general with a quick test?

```twig
Value: {{ test ?? 0 }}
<button sprig s-val:test="1">Test</button>
```

**Comment by AbbeyDesign** [comment]
Ok, I see what was wrong. I was writing this code on a blank twig page without it being part of a block that extended the main craft site.

Adding it to a block made it work as intended.

Thanks!

**Comment by bencroker** [comment]
Glad to hear you figured it out! You can use Sprig that way too, but then you need to register the script manually.

**Comment by AbbeyDesign** [comment]
So I hate coming to github and not seeing the end solution after a back and forth with the developer. My code above was just the general idea to get me past an unrelated issue and could confuse future viewers. 

Here's the solution that worked. It's still general(and certainly not Dry), but can be adjusted for your needs.

I wanted to build an array  of ids from checking and unchecking boxes. 

```
{% set checkboxArray = checkboxArray ?? [] %}
<div id="filters">
	{% set checkboxes = craft.entries({section: 'someSection', limit: 5}) %}
	{% for checkbox in checkboxes %}
		<input sprig s-replace="#outPut" type="checkbox" s-trigger="click" name="checkboxArray[]" value="{{ checkbox.id }}"/>
		<label for="coding">{{ checkbox.title }}</label>
	{% endfor %}
</div>

<div id="outPut">
	{% set ids = [] %}
	{% for item in checkboxArray %}
		{% set ids = ids|merge([item]) %}
	{% endfor %}

	{% set entries = craft.entries({id: (ids)}) %}
	{% if entries %}
		{% for entry in entries %}
			{{ entry.title }}
		{% endfor %}
	{% endif %}
</div>
```
