### ISSUE TITLE
Clearing Search Results

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#335]
Craft 4.4.5
Sprig 2.6.2

I have a search component that displays results correct based off of this recipe https://putyourlightson.com/sprig/cookbook#search

Everything is working great. Except that when I navigate away from the search. I want the input to clear (which it does) and the results div to disappear which it does not.

In the screenshot previously had searched for **pimp** and got the results expected. When clicking away the search bar is cleared but the results remain. How can I remove the results - am using **AlpineJs** on the site.

![image](https://github.com/putyourlightson/craft-sprig/assets/6899490/0c0ecd47-d075-4cbd-b001-0fad9d4d4ead)

Current code

```twig
{# Sets a default value if not defined by the `query` input field below #}
{% set query = query ?? '' %}

  <div
    x-data="{ query: '' }"
    class="relative md:w-full">
    {# Replaces only the `#results` div on keyup or when the value is changed #}
    <input
      {# use alpine to clear in the input field when removing focus from component #}
      x-on:focusout="query = '';$dispatch('sprig-update', 'your-sprig-action')"
      x-model="query"
      sprig
      s-trigger="keyup changed delay:200ms"
      s-replace="#{{ searchId }}"
      type="text"
      name="query"
      value="{{ query }}"
      placeholder="Search All Episodes"
      class="max-w-screen-sm border rounded-sm placeholder:text-gray-600 placeholder:text-lg dark:bg-gray-300 dark:placeholder:text-gray-800">

    <div
      id="{{ searchId }}"
      class="absolute left-0 z-50 w-full bg-gray-100 border border-gray-700 rounded-sm shadow-xl top-full bottom-0-aa dark:bg-gray-500 sm:max-w-screen-sm scrollbar" style="max-height:50vh;">
      {% if query %}
        {% set entries = craft.entries.section('podcast').search(query).all() %}
        {% if entries|length %}
          {% for entry in entries %}
            <a href="{{ entry.url }}" class="block py-2 sm:mx-8 mx-4 border-gray-400 hover:bg-gray-200 dark:hover:bg-gray-400 dark:text-gray-50 hover:text-blue-medium {{ loop.first ? 'mt-4':'' }} {{ loop.last ? 'mb-6':'border-b' }}">{{ entry.title }}</a>
            {{ loop.last ? '<div class="md:hidden">&nbsp;</div>':''}}
          {% endfor %}
        {% else %}
            <p class="mx-8 mt-8 mb-4 border-gray-400 text-redBrand dark:text-gray-50">
              No Results
            </p>
        {% endif %}
      {% endif %}
    </div>
  </div><!-- /.relative -->
```

I looked at the docs and tried some things but couldn't get it to work. I then went to Chat GPT and it told me to use this line:

```$dispatch('sprig-update', 'your-sprig-action')```

but I am unable to figure out what to replace **your-sprig-action** with or if this is even the correct approach.

please advise.

**Comment by bencroker** [comment]
If you’re asking how to refresh the Sprig component, it is documented at https://putyourlightson.com/plugins/sprig#component-attributes.

To trigger a refresh from within the component should be possible as follows.

```
x-on:focusout="query = ''; htmx.trigger(this, 'refresh');"
```

**Comment by CreateSean** [comment]
Ben,
I did try that and it's not working for me.  Was actually one of the first things I tried.

**Comment by bencroker** [comment]
Well, if this is all you’re using Alpine for then it seems like overkill when you could just use Sprig and htmx (`s-on:*` was added in [2.7.0](https://github.com/putyourlightson/craft-sprig/releases/tag/2.7.0)).

```twig
  <div
    class="relative md:w-full">
    {# Replaces only the `#results` div on keyup or when the value is changed #}
    <input
      sprig
      s-trigger="keyup changed delay:200ms"
      s-replace="#{{ searchId }}"
      {# use htmx to clear in the input field when removing focus from component #}
      s-on:focusout="this.value = ''; htmx.trigger(this, 'refresh');"
      type="text"
      name="query"
      value="{{ query }}"
      placeholder="Search All Episodes"
      class="max-w-screen-sm border rounded-sm placeholder:text-gray-600 placeholder:text-lg dark:bg-gray-300 dark:placeholder:text-gray-800">
```

**Comment by CreateSean** [comment]
Ben, 

thanks but that's not working either. and now it doesn't clear the text in the input either.

**Comment by bencroker** [comment]
You can test this code in the Sprig Playground, it works.

```twig
<input
    sprig
    s-trigger="keyup changed delay:200ms"
    s-replace="#test"
    {# use htmx to clear in the input field when removing focus from component #}
    s-on:focusout="this.value = ''; htmx.trigger(this, 'refresh');"
    type="text"
    name="query"
    value="{{ query ?? '' }}"
    placeholder="Search All Episodes"
>
<div id="test">
    {{ query ?? '' }}
</div>
```

**Comment by CreateSean** [comment]
Ben,

I tested and it's not working as I expected. Made a short video https://www.dropbox.com/scl/fi/iyt0iywaf8llb8od4v1t9/sprig.mp4?rlkey=qox9x0o8ezptuflsaghhw7xr1&dl=0 detailing it.

**Comment by bencroker** [comment]
And you're running Sprig 2.7.0 or above, as per my previous comment? And are you loading htmx manually, or allowing Sprig to load it?

**Comment by CreateSean** [comment]
I wasn't at sprig 2.7.0, sorry - user error. All good now.
