### ISSUE TITLE
Sprig 'Load More' and SEO

### ISSUE THREAD

**Issue by garycrane** [putyourlightson/craft-sprig#336]
Hi there,

We have a client that's _very_ focussed on SEO and ensuring that their articles listing is a 'crawlable' as possible. 

Are you able to share any examples of using s-boost, specifically when using a 'Load More' button/link? I'm trying to find a way to ensure that the content listed behind their 'Load More Articles' button is still crawled by a search engine. Is s-boost the right solution for this or should I be looking elsewhere? 

Here's my current template code:

```
<button sprig s-val:offset="{{ offset + limit }}" s-target="this" s-swap="outerHTML">
    Load more articles
</button>
```

We're keen to make this as SEO friendly as possible? Is that doable? Keen to get your thoughts.

Look forward to hearing from you.

Thanks,
Gary

**Comment by bencroker** [comment]
What’s wrong with just using a [Sitemap](https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview), which is intended exactly for letting search engines know which pages to crawl?

**Comment by garycrane** [comment]
Yeah, fair point. We're using sitemaps, so that should do the trick. Curious to know if this is doable though, in case the client pushes back. If not that's OK. Just want to ensure it's as search engine friendly as possible.

**Comment by bencroker** [comment]
I’m not really sure how to answer your question. If they insist on having a page that lists all articles then you can simply create one in addition to the Sprig-powered page, right?

**Comment by garycrane** [comment]
Fair enough. I'll take that as a 'no'. I guess it was more of a question around an example of how to implement s-boost. Not to worry.

**Comment by bencroker** [comment]
You asked several questions and I tried to provide the most informative answer, but if anything is still unclear then let me know.

**Comment by garycrane** [comment]
Hey Ben – Really sorry if my original question was ambiguous. Let's forget about the SEO aspect. I completely agree with you that sitemaps will solve that problem. However, (rephrasing my original question) I'm still curious to know if you have a Sprig recipe for creating a 'Load More' button that works when javascript is disabled? I've been watching a couple of videos on YouTube which references 'hx-boost' but I'm struggling to see how to implement that in the context of Craft/Sprig.

Again, if the answer is 'no', that's totally cool. This is as much about satisfying my curiosity for future reference as much as anything 🙂

**Comment by bencroker** [comment]
Something like this do the trick? So with JS disabled, it will take the user to a page containing all articles.

```twig
<a sprig ... href="/all-articles">Load more</a>
```

**Comment by garycrane** [comment]
Yeah, of course...that would work. I think I've been massively overthinking this one. Thanks for your patience and support Ben 🙂

**Comment by bencroker** [comment]
Sure thing!
