### ISSUE TITLE
Sprig and triggering queue jobs

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-sprig#341]
Hey Ben

Bit of a Friday arvo question this one (which I apparently forgot to hit submit on...hence now Monday!)  - and no need to hurry with a response.

I am doing quite a bit of Sprig stuff in the control panel.  Most of this is order processing stuff, which basically takes orders from Commerce and processes those through a downstream inventory/accounting system (Cin7/DEAR).

Inventory systems...well, they suck, and they tend to be very slow.   This one is no exception.  And we're often processing a bunch of orders that have come in in a batch.

We have thus been having issues with direct requests timing out (PHP limit is 180s and I don't really think I should extend it further) - and things getting killed half way.  So, I am experimenting with moving things to Craft queue jobs (so I can set a longer TTR etc).

So far the actual queue jobs seems to be working well - however, I note that on my 'Sprig pages', I just don't get the little left hand panel progress updates.  They just don't ever come up.  I can only see them by doing a whole page reload - then I _can_ see these updates as the job progresses.

My guess here is that my toolbar component - a little info & control panel at the top of these pages - is perhaps the issue?  It uses an s-trigger to update itself, via polling, every 5 seconds.  (I can't tell you how much nicer Craft/Sprig would be with support for Server Side Events and/or websockets - hate polling!  To me a bit of server side communication seems such a natural fit for Sprig...).  

`<span id="trigger-toolbar" style="display:none;" sprig s-trigger="every 5s"></span>`

![image](https://github.com/putyourlightson/craft-sprig/assets/731309/d95906a1-859e-4da9-8294-12f115127c55)

...and, anyhow, I think that _may_ be interfering, somehow, with however Craft normally provides these updates?  I don't know - am clutching at straws here because basically what I expect is the toolbar to refresh itself (it being reactive) - but the rest of the page working as nomral - including the Craft queue updates.

Any ideas on this??  I'd really like to get my order processors into a place where they can see those jobs progressing (without forcing a clunky page reload).

(I can run all this stuff faultlessly via console commands, of course, but can't really give my order processing folks access to the console obviously..)

**Comment by bencroker** [comment]
> ...and, anyhow, I think that may be interfering, somehow, with however Craft normally provides these updates?

There shouldn’t be any correlation between Sprig polling and the queue job progress indicator. If you disable polling, does it then work as expected?

> I can't tell you how much nicer Craft/Sprig would be with support for Server Side Events and/or websockets - hate polling! To me a bit of server side communication seems such a natural fit for Sprig...

htmx supports websockets, so it would be possible to add to Sprig, but it’s not trivial to make this easy to use when Craft has no official support for it.

**Comment by bossanova808** [comment]
Well I'm an idiot.  I'd convinced myself it was only the Sprig page that wasn't showing the queue progress, but indeed no exisitng open window does, e.g. the Craft Dashboard open in another tab.  Only if I open a _new_ window does it then appear (which I must have been doing to check another window, rather than just looking at an open one...).  Got an idea stuck in my head and ran with it without thinking it through.  Sorry!

So you're right, nothing to do with the polling or really Sprig at all. Progress only shows on new windows (is that normal or have I stuffed up something about the job creation/updating progress?  I know I see your Campaign queues but not sure if that is only in newly opened things too...)

I suppose you're right - likely bolting on the htmx/sprig support for SSE/sockets would be (relatively, ha!) simple if Craft itself had support for these things.  There's just so many contexts where something happening on the server would ideally result in some sort of indication on the server it seems odd Craft hasn't done this yet (e.g. the rather feeble and late addition of the 'user editing' circles when multiple people are editing feels like the sort of thing that might have motivated a proper Server -> Client communication channel...)

**Comment by bencroker** [comment]
Glad to hear you figured it out!
