### ISSUE TITLE
Unable to Trigger Live Search using Two Components

### ISSUE THREAD

**Issue by milanaismail** [putyourlightson/craft-sprig#345]
I'm currently working on a Craft CMS project and trying to implement live search functionality using the Sprig plugin. However, I'm facing issues with the plugin, and despite my efforts, I haven't been able to resolve the issue.

I have a main layout (_layouts/main.twig) where I include the necessary scripts and styles, and a products template (products.twig) that extends the main layout. In the products template, I have a live search input field that should trigger a search and update the product container on keyup or change events.

When the search.twig and result.twig are combined under one twig file, it does work, but i want the search component to be placed somewhere else (in my main.twig) and not directly above the results. 

Here's a simplified snippet of my code:

_components/search.twig
```
{# Sets a default value if not defined #}
{% set query = query ?? '' %}

 <div class="field">
            <input sprig s-trigger="keyup changed" s-replace="#productContainer" type="text" name="query" value="{{ query }}" placeholder="Search" class="text">
        </div>
        
</div>

```

_components/result.twig
```
<div class="shop-container" id="productContainer">
            {% set entries = craft.entries().section('products').search(query).all() %}
            {% if entries|length %}
                {% for entry in entries %}
                    <div class="product">
                        {% set productImage = entry.productImage.one() %}
                        {% if productImage %}
                            <img src="{{ productImage.getUrl('imagePreview') }}" alt="{{ entry.title }}">
                        {% endif %}
                        <h2>{{ entry.title }}</h2>
                        <p>€ {{ entry.productPrice }}</p>
                        <button>Add to cart</button>
                    </div>
                {% endfor %}
            {% else %}
                No results
            {% endif %}
        </div>
```

_layouts/main.twig
```
<body>
    <!-- ... header and other content ... -->
   <div class="search">
                   {{ sprig('_components/search') }}
    <!-- ... other content ... -->
    {% block content %}
    {% endblock %}
</body>
```

products.twig
```
{% extends "_layouts/main" %}
{% block content %}
    <div class="shop">
        <!-- ... other content ... -->
                        {{ sprig('_components/result') }}
{% endblock %}

```

**Comment by bencroker** [comment]
A Sprig component must contain both the triggering element (in this case the search input) and the target (in this case the results). You cannot just split it into two unique components and expect it to work.

**Comment by milanaismail** [comment]
so its not possible to create two components? I hope i explained it right, but what i want to achieve is a searching component to be part of my header and the results component to be part of products.twig (so its not right on top of eachother)

**Comment by bencroker** [comment]
It is possible to create two components, but not to have live search work in this way. You’d need to force the search component to trigger a refresh on the result component. That is possible but requires some JS code. 

Here is some untested code to get you started.

### `_components/search.twig`
```twig
<input sprig s-trigger="keyup changed" type="text" name="query" value="{{ query }}" placeholder="Search" class="text">

{% if sprig.isRequest %}
    <script>
        htmx.find('#productContainer #query').value = event.detail.elt.value;
        htmx.trigger('#productContainer', 'refresh');
    </script>
{% endif %}
```

### `_components/result.twig`
```twig
<div class="shop-container" id="productContainer">
    <input type="hidden" id="query" name="query" value="">
    {% set entries = craft.entries().section('products').search(query).all() %}
    ...
</div>
```
