### ISSUE TITLE
Unable to use two sprig element making same task

### ISSUE THREAD

**Issue by Shanyb** [putyourlightson/craft-sprig#346]
Hi,

I use Sprig to search with Craft CMS. One of the search tools is checkboxes. For design reasons, I have to create a version of the checkboxes on mobile, and a version of these same checkboxes on desktop.

It seems impossible to have 2 search items (checkboxes) performing the same task. Is it possible to sync these checkboxes? 
Or any element like radio button, select, etc.

Thanks.

**Comment by bencroker** [comment]
It is possible, but each version of the checkbox will need its own unique name, for example `searchDesktop` and `searchMobile`. Then, in your Twig logic, you’ll need to check if either value is submitted.

```twig
{% set search = searchDesktop ?: searchMobile ?: null %}
```
