### ISSUE TITLE
Refreshing vs Reloading

### ISSUE THREAD

**Issue by pixelmachine** [putyourlightson/craft-sprig#347]
I have a single page checkout, each section of the checkout is a component and each component triggers a refresh on subsequent components when submitted.

For example checkout.twig contains:
```twig
{{ sprig('shop/_components/checkout/form-address.twig', {}, {'id': 'form-details'}) }}
{{ sprig('shop/_components/checkout/form-delivery.twig', {}, {'id': 'form-delivery'}) }}
```

Then form-address.twig contains:
```twig
<form 
  sprig 
  s-method="post" 
  s-action="commerce/cart/update-cart"
  s-indicator="#form-details">
    {{ actionInput('commerce/cart/update-cart') }}
    [.. address fields ..]
 </form>
 
 {% if sprig.isRequest %}
  {% tag 'script' %}
    htmx.trigger('#form-delivery', 'refresh');
  {% endtag %}
{% endif %}
```

Finally form-delivery.twig contains:
```twig
<form 
  sprig 
  s-method="post" 
  s-action="commerce/cart/update-cart" 
  s-trigger="change" 
  s-indicator="#form-delivery">
    {{ actionInput('commerce/cart/update-cart') }}
    [.. options that depend on what's submitted in form-address.twig ..]
</form>
```

I assumed that the `refresh` event was just reloading the component but if I submit `form-address` I get post data back from `form-delivery` component after it refreshes. So have I just misunderstood what the `refresh` event does?

**Comment by pixelmachine** [comment]
Nope! It's my own fault. Of course I find it once I post a question!

**Comment by bencroker** [comment]
No, your assumption sounds correct. I’m not quite following what is _not_ working correctly, though. Can you please clarify?

**Comment by pixelmachine** [comment]
I thought that might not be clear. So lets say `form-delivery.twig` has a field and some twig to display the value of the field when the form is submitted (`checkout.twig` and `form-address.twig` remain the same):

```twig
<form 
  sprig 
  s-method="post" 
  s-action="commerce/cart/update-cart" 
  s-trigger="change" 
  s-indicator="#form-delivery">
    {{ tag('input', {
      type: 'hidden',
      name: 'selectDelivery',
      value: 1
    }) }}
</form>
{{ craft.app.request.param('selectDelivery') }}
```

When the page is loaded nothing is displayed for `form-delivery`.
When `form-details` is submitted, it triggers a refresh on `form-delivery` and once it's reloaded a `1` is displayed.
Essentially it looks like the refresh method on the component is triggering the form.

(I should add this is Craft 3)

**Comment by bencroker** [comment]
From the docs:

> The values of all input fields (including textarea and select fields) in the component will automatically become available as template variables.

Reference: https://putyourlightson.com/plugins/sprig#how-it-works

Coincidentally, I’m giving a Sprig training session tomorrow on component variables:
https://putyourlightson.com/sprig/training

**Comment by pixelmachine** [comment]
Ah! Somehow I'd never noticed that detail. Thank you.

So just one question then @bencroker – from within my `form-delivery` component is there a way that I can tell if the form was submitted rather than the component refreshed?

I want to run some twig code after the form has been submitted but not when it's been refreshed.

**Comment by bencroker** [comment]
The form will submit via a POST request, whereas a refresh with a GET request, so you could check against that.
