### ISSUE TITLE
Build white label with sprig

### ISSUE THREAD

**Issue by Simone-98** [putyourlightson/craft-sprig#349]
Hi, i'm new in Craft cms and Sprig, my goal is build Ecommerce for a Client.
In one of the meeting he told to me that probably in the future he would sell product with White Label Form on others sites, 
withe all the feature of Ecommerce (add to cart, checkout, payment).
The white label must run in every site you put in, it is a JS file in cdn to add in a site.
So the question is:
If he asked me to build the White Label, can i use sprig for this Goal?
Have you every tried to build Withe Label?

Thanks

**Comment by bencroker** [comment]
I don't see any reason you couldn't use Sprig for such a use-case. You'll likely come up against CORS issues, but they can be worked around. 

It sounds like a challenging project, good luck!
