### ISSUE TITLE
Component element attribute?

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-sprig#35]
Hello Ben! Thank you for the great work on Sprig. 🏆

### Question

I wanted to ask if it is possible to set another HTML element than a `<div>` for the (surrounding) Sprig component element? 

### Additional context

I want to use a regular old `<ol>` list and add list item elements (load more) to the end of it. The Sprig div is already there, it is just not the right parent element for my list items. Adding an ordered list element breaks the list, as the div ends up inside the `<ol>` list element. 

Is there a different (better) semantic and accessible approach to have the component div, then the ordered list item followed by the list items? 

At the end I want to combine it with a filter component as well. The load more and filter component working together. I have it work, but the HTML is not right at the moment.  

#### Example

From this:

```html
<div id="component-tblode" class="sprig-component">
    <ol class="listing">
       <li class="list-element">
            Lorem ipsum dolor sit amet…
       </li>
    </ol>
</div>
```

to this:

```html
<ol id="component-tblode" class="sprig-component listing">
   <li class="list-element">
        Lorem ipsum dolor sit amet…
   </li>
</ol>
```

using something like this:

```twig
{{ sprig('_components/listing', {}, {
    '_element': 'ol',
    'id': 'listing-component',
    …
}) }}
```

**Comment by bencroker** [comment]
May I ask why it is so important to not put the `ol` inside the `div`?

**Comment by ghost** [comment]
Yes of course you can. I'm probably an old guy, but if I see the div that would work perfectly and save an extra element (ol) through becoming the ol I'm curious. 😅

Jokes aside, I modified the load more example from your docs and I have trouble to make the new results load into the ordered list element. 

```twig
{#--- _components/load-more ---#}

{# Sets a default value if not defined by the `s-vars` attribute on the button #}
{% set offset = offset ?? 0 %}

{% set entries = craft.entries.offset(offset).limit(limit).all() %}

<ol class="listing">
{% for entry in entries %}
  <li>{{ entry.title }}</li>
{% endfor %}
</ol>

{% if entries %}
  {# Increments `offset` by the value of `limit` and swaps itself out on click #}
  <button sprig s-vars="offset: {{ offset + limit }}" 
    s-target="this" s-swap="outerHTML">
    Load another
  </button>
{% endif %}
```

I started like this, but that means that the new results get rendered as another `<ol>` under my list instead of inside. 
Then I stripped the `<ol>`and put it outside of the component. But then I have end up with this:

```
<ol class="listing">
  <div class="sprig-component">
    <li>List item title 1</li>
    <li>List item title 2</li>
    …
  </div>
</ol>
```

Right now I have this set up. It works and if the div would be an ol/ul it would be semantically correct.

```twig
{# Listing results component (Sprig) #}

{% set offset = offset ?? 0 %}

{% set entries = craft.entries()
    .section('projectCol')
    .relatedTo(cat)
    .with(['media', 'builder', 'projectCategories'])
    .offset(offset)
    .limit(limit)
    .all() %}

{% set entriesTotal = craft.entries()
    .section('projectCol')
    .relatedTo(cat)
    .count() %}

{% for entry in entries %}
    {% include '_includes/builder/teaser.html.twig' %} {# <-- li inside that included twig template #}
{% endfor %}

{% if entries and entries|length == limit %}
    <button sprig
            s-vars="offset: {{ offset + limit }}"
            s-target="this"
            s-swap="outerHTML">
        {{ 'Load more' | t }}
    </button>
{% elseif entries
    and entries|length < limit
    and entriesTotal > limit %}
    {{ 'No more content to load' | t }}
{% endif %}

```

In a perfect world I'd like keep the button out of the `<ol>` too. 

Resulting in something like this in HTML:

```twig
<div class="sprig-component">
  <ol class="listing">
    <li>List item 1</li>
    <li>List item 2</li>
  </ol>
  <button>Load more</button>
</div>
```

So my struggle is how to nest or pack things up to load them into the ordered list defined in the listing component. 

Thank you for your wisdom Ben!

**Comment by bencroker** [comment]
Making the Sprig component be an `ol` element instead of a `div` will not get you your "perfect world" result.

I would approach this by first targeting the `ol` element (with ID `listing`) and using the `beforeend` swap strategy (see https://htmx.org/attributes/hx-swap/):

```twig
    <button sprig
            s-vars="offset: {{ offset + limit }}"
            s-target="#listing"
            s-swap="beforeend">
        {{ 'Load more' | t }}
    </button>
```

The final challenge is to only output the button on include and then update the offset on the button, which you could do using some simple JavaScript:

```twig
{% if sprig.isInclude %}

    <script>var offset = 0;</script>

    <button sprig
            s-vars="offset: offset"
            s-target="#listing"
            s-swap="beforeend"
            onclick="offset += {{ limit }}"
    >
        {{ 'Load more' | t }}
    </button>

{% endif %}
```

**Comment by bencroker** [comment]
On second thought this could be condensed down to:

```twig
{% if sprig.isInclude %}

    <script>var offset = 0;</script>

    <button sprig
            s-vars="offset: offset += {{ limit }}"
            s-target="#listing"
            s-swap="beforeend"
    >
        {{ 'Load more' | t }}
    </button>

{% endif %}
```

**Comment by ghost** [comment]
Thank you very much Ben,

but I'm still stuck. That's my current listing component:

```twig
{# Listing results component (Sprig) #}

{% set offset = offset ?? 0 %}

{% set entries = craft.entries()
    .section('projectCol')
    .relatedTo(cat)
    .with(['media', 'builder', 'projectCategories'])
    .offset(offset)
    .limit(limit)
    .all() %}

{% set entriesTotal = craft.entries()
    .section('projectCol')
    .relatedTo(cat)
    .count() %}

<ol id="listing">
    {% for entry in entries %}
        {% include '_includes/builder/teaser.html.twig' %}
    {% endfor %}
</ol>

{% if entries and entries|length == limit %}
    {% if sprig.isInclude %}
        <script>var offset = 0;</script>

        <button sprig
                s-vars="offset: offset"
                s-target="#listing"
                s-swap="beforeend"
                onclick="offset += {{ limit }}">
            {{ 'Load more' | t }}
        </button>
    {% endif %}
{% endif %}

```

Did I place the `<ol>`at the wrong place, because right now it still loads another ordered list element into the listing list?

PS: The last, more condensed code did not work for me.

**Comment by bencroker** [comment]
Ah right, the `ol` needs to only be output on the Sprig include.

```twig
{% if sprig.isInclude %}
    <ol id="listing">
{% endif %}

    {% for entry in entries %}
        {% include '_includes/builder/teaser.html.twig' %}
    {% endfor %}
    
{% if sprig.isInclude %}
    </ol>
{% endif %}
```

This component is getting quite bloated so you may want to ask if there's a better way of achieving this in the [htmx discord server](https://htmx.org/discord). You can see how [this example](https://htmx.org/examples/click-to-load/) suffers from the same issue.

**Comment by jreviews** [comment]
Could you set the offset value directly instead of using an expression?

```twig
        <button sprig
                s-vars="offset: {{ offset + limit }}"
                s-target="#listing"
                s-swap="beforeend">
                  {{ 'Load more' | t }}
        </button>
```

**Comment by bencroker** [comment]
Normally yes, however if the button is inside a `sprig.isInclude` condition, as it is above, then it will be rendered once and only once.

This works for me provided a Javascript variable called `offset` exists:

```
s-vars="offset: offset += {{ limit }}"
```

**Comment by ghost** [comment]
@bencroker thank you. 🏆

It works, but you are right. It's a bit "messy" for such a use case, hence my question to make the `<div>` the `<ol>` in the first place, so that there would not be an extra element to take care of like in this case. 
I can understand though that you are not very keen on making the element an available attribute. In htmx it would not even be a problem, as you put the htmx attributes to closest relevant element.

**Comment by bencroker** [comment]
An `ol` element inside a `div` element is semantically correct, so I would need a valid reason to introduce extra configuration into the plugin. As stated before, even if I was to introduce this as a configuration option, it would not solve your issue as you would end up with a `button` element inside of an `ol` element. 

If you really want a better solution to this then best to ask for it in htmx.
