### ISSUE TITLE
Sprig include for critical CSS not evaluating as I expected

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#351]
This is the following pattern I use for loading critical CSS into a site using Twigpack

`_includes/css-include`
```
    {# -- Critical CSS -- #}
        
        {% set cssPath = '/dist/css/all-styles.css' %}
        {% set cssHash = craft.twigpack.getModuleHash(cssPath, "legacy") %}
        {% do getCookie('critical-css') %}
        {% if getCookie('critical-css') %}
            {% set criticalCss = getCookie('critical-css') %}
        {% endif %}
        {% if criticalCss is defined and criticalCss == cssHash %}
            {{ craft.twigpack.includeCssModule(cssPath, false) }}
        {% else %}
            {% do setCookie('critical-css', cssHash, now | date_modify("+7 days").timestamp ) %}
            {{ craft.twigpack.includeInlineCssTags("@webroot/dist/criticalcss/" ~ criticalCSSTemplate|default() ~ '_critical.min.css') }}
            {{ craft.twigpack.includeCssModule(cssPath, true) }}
        {% endif %}
```

So on a Blitz & Cloudflare cached website, I thought a Sprig included here would be a good option in my` layout.twig`.

`{{ sprig('_includes/css-include', {criticalCSSTemplate:criticalCSSTemplate|default()}) }}`

However on page load and subsequent reloads it does not seem to evaluate the logic inside the sprig component.

I realize that the default trigger is refresh so tried load and combo load and refresh. I also tried `sprig.isInclude` and `sprig.isRequest` to no avail. 

What happens is even if cookie `critical-css `is there then it will still load the first half of the argument. 

I may be missing something fundamental here

Latest Craft, Twigpack, Blitz and Sprig with Cloudflare as reverse proxy

**Comment by bencroker** [comment]
Why would you want to put this in a Sprig component over a regular include? It seems like you’d want critical CSS to be loaded as early as possible and _not_ via an AJAX request.

**Comment by john-henry** [comment]
Normally, I do put it in a regular include, but I am wondering how I escape the Blitz cache here then?

**Comment by bencroker** [comment]
Surely you want critical CSS included in the cached page?

**Comment by john-henry** [comment]
Only if a new visitor to the site. Then cookie created and user's subsequent pages visits have full CSS

**Comment by bencroker** [comment]
Oh I see. But regardless, loading critical CSS via an AJAX request seems pointless to me.

Here’s an example I just tested, which appears to work.

```twig
{{ sprig('_components/test', {}, { 's-trigger': 'load' }) }}
```

`_components/test.twig`:

```twig
{% if sprig.isRequest %}
    <link rel="stylesheet" href="test.css">
{% endif %}
```

**Comment by john-henry** [comment]
Yeah, I see that now. Ok more of a Blitz question now on how to bypass that cache. K thanks for looking
