### ISSUE TITLE
Load logic on the component itself

### ISSUE THREAD

**Issue by yannkost** [putyourlightson/craft-sprig#354]
I have seen that a component, which has following logic does not trigger htmx to be included in the page: 
```
{{ sprig('_components/sprig/navbar-search.twig', {}, {'s-trigger': 'load'}) }}
```
The component is hidden in the menu, so with `display:none` at the load of the page. But with no htmx included, the sprig component request never get's to make the request that should be triggered.

Additional info: The component is in the page, but I only output html when following applies: 

```
{% if sprig.isRequest %}
```

Sprig Version: 2.7.3
Blitz version: 4.11.1
Craft-CMS: 4.7.1

**Comment by yannkost** [comment]
Also, when I include the htmx.min.js myself, then the component works just fine.

**Comment by bencroker** [comment]
Calling the `sprig()` function prompts the htmx script to be included in the page. Is the function used conditionally in a cached page, by any chance? If so then you’ll want to add `sprig.registerScript` to the layout, see https://putyourlightson.com/plugins/sprig#sprig-registerscript

**Comment by yannkost** [comment]
Thank you, I have missed this option in the docs. This does the trick. One think tough: On other components the sprig has been including the htmx, but these components are always visible. 

But on my side, this point is resolved :)

**Comment by bencroker** [comment]
Refreshing the cache might help resolve this, if things have since changed. Glad to hear it’s working for you now, either way.
