### ISSUE TITLE
Dynamic Limit - partially working

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#356]
I'm setting up a filter to display results via search and two dropdowns. Search is working, pagination is working. The first dropdown I'm working on is to change the number of results per page. it halfway works. if I manually update the query string with the correct value it works, but if I update the select it doesn't update anything

simplified template

```twig
  {# set variable for sprig to hook into first page load #}
  {% set page = page ?? 1 %}
  {# set search parameter here #}
  {% set search = q ?? '' %}
  {# set results/page #}
  {% set limit = limit ?? '10' %}

  {{ hiddenInput('page', page) }}
  {{ hiddenInput('limit', limit) }}

  {% set entryQuery = craft.entries
              .section('pmPurchaseOrders')
              .limit(limit)
              .search(search) %}

{# limit filter #}
        <select
          sprig
          id="limit"
          name="limit"
          class="mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6">
          <option value="10" {{ limit =='10' ? 'selected' }} >10</option>
          <option value="25" {{ limit =='25' ? 'selected' }}>25</option>
          <option value="50" {{ limit =='50' ? 'selected' }}>50</option>
          <option value="100" {{ limit =='100' ? 'selected' }}>100</option>
        </select>

  {# Paginates the entry query given the current page #}
  {% set pageInfo = sprig.paginate(entryQuery, page) %}
  {% set entries = pageInfo.pageResults %}


{% for entry in entries %}
  Search Results Here
{% endfor %}

```

Strangely on page load it shows 12 results despite having a default of 10 set. Also if I change the select to any value the url updates and says 12 like this `/orders?limit=12&q=&page=1` however if I change the limit parameter manually to 25 or 50 it works as expected.

Please advise.

**Comment by bencroker** [comment]
I advise you to remove `hiddenInput('limit', limit)`, as it will conflict with the `select` element, also named `limit`.

**Comment by CreateSean** [comment]
@bencroker that works, however I'm still showing 12 entries on first page load before using the filters, when I'm expecting to see 10.

**Comment by bencroker** [comment]
`12` must be coming from somewhere else not shown in your code. Perhaps when you call the `sprig()` function?

**Comment by CreateSean** [comment]
> `12` must be coming from somewhere else not shown in your code. Perhaps when you call the `sprig()` function?

yes - that's what I get for copy/pasting from another project.
