### ISSUE TITLE
How to pass flash message after submitting from a custom controller?

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#359]
Following [this Stack Exchange question](https://craftcms.stackexchange.com/questions/40839/sprig-how-to-redirect-to-a-url-after-submitting-to-a-custom-controller), I can redirect to a URL after submitting to a custom controller using this:
```php
Craft::$app->getResponse()->getHeaders()->set('HX-Redirect', $url);
```

This works as expected. However, it failed to pass my flash message:
```php
Craft::$app->getSession()->set('my-flash-key', 'My flash message');

if (Craft::$app->plugins->isPluginEnabled('sprig')) {
    Craft::$app->getResponse()->getHeaders()->set('HX-Redirect', $url);
    return $this->asSuccess();
} else {
    return $this->redirect($url);
}
```

When using `$this->redirect($url)`, it works. But with Sprig, it seems like the message in the session is lost during the redirect.

As an alternative, I also tried using `Craft::$app->getSession()->set('my-flash-key', 'My flash message')`, but it still does not get passed.

How to pass flash message after submitting from my custom controller?

**Comment by bencroker** [comment]
I’d expect that to work. Are you fetching the session value as follows?

```twig
{{ craft.app.session.get('my-flash-key') ?? '' }}
```

I responded to https://github.com/putyourlightson/craft-sprig/issues/358 with more detail.

**Comment by romainpoirier** [comment]
Thanks, it works this way. It was failing before because I was trying to get `craft.app.session.getFlash('success')` instead of `craft.app.session.get('success')`.

**Comment by bencroker** [comment]
Great!
