### ISSUE TITLE
Mixing regular component with component class

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#360]
As the title suggests, I'm trying to combine two separate components. This is how I think I need to do it:

```
## reports.twig
{{ sprig('reports/_PersonSearch') }}
{{ sprig('CalculateReport', {}, {'id': 'calculateReport'}) }}
```

```
## personSearch.twig
## search through all people entries, click on the one you wish to Calculate based on
{% set searchPeople = searchPeople ?? '' %}
{% set selectedPerson = selectedPerson ?? '' %}
{% set people = craft.entries.section('people').id(selectedPerson).one() %}
{% if searchPeople %}
  {% set returnedPeople = craft.entries.section('people').search(searchPeople).all() %}
{% endif %}

<input sprig s-trigger="keyup changed delay:300ms" s-replace="#people-list" type="text" name="searchPeople" value="{{ person.title ?? searchPeople }}"

<div id="people-list">
  {% if returnedPeople is defined %}
    {% for person in returnedPeople %}
      <a href="#"sprig s-val:selectedPerson ="{{ person.id }}">{{ person.title }}</a>
    {% endfor %}
  {% endif %}
</div>

{% if success is defined and success == true %}
  {{ hiddenInput('selectedPerson', selectedPerson) }}
  <script>htmx.trigger('#calculateReport', 'refresh');</script>
{% endif %}
```

```
## reports/_CalculateReport.twig
{% set selectedPerson = selectedPerson ?? '' %}
<form sprig s-action="calculateReport">
  {{ hiddenInput('selectedPerson', selectedPerson) }}
  <button>Calculate</button>
</form>
```

```
## CalculateReport.php
protected ?string $_template = 'reports/_CalculateReport';
## doing it's thing with the selectedPerson
```

My question is: could I combine them into one component? Either `PersonSearch` included by `_CalculateReport` or vice versa. If not, how can I get `selectedPerson` to work in the Calculate component?

I've tried some of the solutions in the docs and based on [a similar one](https://github.com/putyourlightson/craft-sprig/issues/353) you helped me with, but so far no luck.

I hope all is clear, appreciate any help!

**Comment by bencroker** [comment]
What’s preventing you from putting the logic from both components into a single component? If you could come up with a more basic code sample then I’m sure we can find a solution, but I can’t run the code above on a generic install of Craft.

**Comment by shifuma** [comment]
Ah you know what...I was trying in a single component but `searchPeople` wasn't returning anything. I just needed to add it to my component class:

```
public string $searchPeople = '';
public string $selectedPeople = '';
```

Sorry for the unneeded issue but thanks for the prompt!

**Comment by bencroker** [comment]
Sure thing, glad to hear you figured it out!
