### ISSUE TITLE
Url parameters issue with pushUrl(). 

### ISSUE THREAD

**Issue by Shanyb** [putyourlightson/craft-sprig#361]
### Support Request

I created a Sprig component to search on entries.
I have many parameters of different types. String (search), checkbox, numbers.

The system sends the parameters in the URL using the pushUrl() function. However, if I retrieve this URL and insert it in a new tab, some URL parameters are not retrieved and used as search parameters. Sprig does not see URL parameters.

Should Sprig pick up parameters without other line of code? Do we need to do anything else to retrieve the URL parameters?
The parameters seeming to cause problems are checkboxes (value="color[]").

The component works very well for search, it only has the URL parameter principle which is missing.

**Comment by bencroker** [comment]
Sprig should pick up URL parameters. Can you show me an example of a URL and some Twig code that demonstrates the issue, so I can test it locally?

**Comment by Shanyb** [comment]
Yes, sure.

URL:
https://dev.lachance.qc.ca/proprietes-a-vendre?recherche=&prixmin=0&prixmax=1700000&mode=liste&type%5B0%5D=37&type%5B1%5D=7&secteur%5B0%5D=39335&secteur%5B1%5D=4736&secteur%5B2%5D=39329&plans=&ordre=price%20ASC&page=1

(the site have a password, still in dev)

For the code, it's related to a lot of thing.
What part of the code would be useful?


EX:

{################################################
	Craft Fields available
################################################}

{% set allPlans = craft.entries().section('blueprintEntries').relatedTo(entryWithField).title('not *client*').orderBy('title ASC').all() %}
{% set sectorsAvailable = craft.categories().group('catZone').relatedTo(entryWithField).orderBy('title ASC').all() %}

{% set fielsHouseType = craft.app.fields.getFieldByHandle('houseType').options %}
{% set houseTypeAvailable = [] %}
{% set houseTypeAvailableID = [] %}
{% for entry in entryWithField %}
	{% set houseTypeEl = entry.houseType %}
	{% if houseTypeEl|length  %}
		{% for option in houseTypeEl %}
			{% if option.value not in houseTypeAvailableID %}
				{% set houseTypeAvailableID = houseTypeAvailableID|merge([option.value]) %}
				{% set houseTypeAvailable = houseTypeAvailable|merge([option]) %}
			{% endif %}
		{% endfor %}
	{% endif %}
{% endfor %}

{% set houseTypeAvailable = houseTypeAvailable|multisort(e => e.label) %}


{################################################
	Fields declaration
################################################}
{% set search = search ?? '' %}
{% set page = page ?? 1 %}
{% set searchZone = searchZone ?? [] %}
{% set priceRangeMin = priceRangeMin ?? 0 %}
{% set priceRangeMax = priceRangeMax ?? defautlPrice %}
{% set roomQt = roomQt ?? [] %}
{% set stairQt = stairQt ?? [] %}
{% set bathroomQt = bathroomQt ?? [] %}
{% set houseReady = houseReady ?? [] %}
{% set garage = garage ?? [] %}
{% set mode = mode ?? 'liste' %}

{################################################
	QUERY
################################################}
{% set entryQuery = craft.entries({
	search: search,
	section: 'forSaleHouseEntry',
	orderBy: orderBy,
	limit: 24,
}) %}

{% if priceRangeMin is defined and priceRangeMax is defined %}
	{% if priceRangeMin == 0 %}
		{% do entryQuery.price(['and', ">= 1", "<= #{priceRangeMax}"])  %}
	{% else %}
		{% do entryQuery.price(['and', ">= #{priceRangeMin}", "<= #{priceRangeMax}"])  %}
	{% endif %}
{% endif %}

{% if searchZone is not empty %}
	{% do entryQuery.relatedTo(searchZone) %}
{% endif %}

{% if roomQt is not empty %}
	{% do entryQuery.roomQt(roomQt) %}
{% endif %}

{% if stairQt is not empty %}
	{% do entryQuery.floorQt(stairQt) %}
{% endif %}

{% if houseType is not empty %}
	{% do entryQuery.houseType(houseType) %}
{% endif %}

{% if bathroomQt is not empty %}
	{% do entryQuery.bathroomQt(bathroomQt) %}
{% endif %}


{% if plans != ""%}
	{% do entryQuery.relatedTo(plans) %}
{% endif %}

{% if houseReady is not empty %}
	{% do entryQuery.forSaleHouseReadyStatus('houseReady').forSalePropertyStatus('not 0') %}
{% endif %}

{% if garage is not empty %}
	{% do entryQuery.garageAvalaible(true) %}
{% endif %}



{% do entryQuery.with(['sectorsCat', 'forSaleImg', 'forSaleImgCraft', 'housePlan']) %}
{% set pageInfo = sprig.paginate(entryQuery, page) %}
{% set entries = pageInfo.pageResults %}



{################################################
	Some part of TWIG
	**not all**
################################################}
 <div class="checkbox-dropdown dropdown">
	<button
		id="sector-dropdown"
		type="button"
		class="btn dropdown-toggle"
		data-bs-toggle="dropdown"
		aria-expanded="false"
		data-bs-auto-close="outside"
	>
		{{'Secteurs'|t}}
	</button>
	<div class="dropdown-menu">
		{% for zone in sectorsAvailable %}
			<div class="checkbox-input-wrapper dark mb-2">
				<input
					{# sprig #}
					{# s-indicator=".loader-wrapper" #}
					type="checkbox"
					id="searchZone-{{zone.id}}"
					name="searchZone[]"
					value="{{zone.id}}"
					{{ zone.id in searchZone ? 'checked' }}
				/>
				<label for="searchZone-{{zone.id}}">{{zone.title}}</label>
			</div>
		{% endfor %}
	</div>
 </div>


 <div class="checkbox-input-wrapper dark">
	 <input
		 type="checkbox"
		 id="garage-available"
		 name="garage[]"
		 value="{{true}}"
		 {{ garage ? 'checked' }}
	 />
	 <label for="garage-available">{{'Garage'|t}}</label>
 </div>

<div class="input-wrapper input-wrapper-search">
	 <input
		 type="text"
		 name="search"
		 id="search"
		 value="{{search}}"
		 class=""
		 placeholder="{{placeholder|t}}"
		 autocomplete="off"
	 >
 </div>



 <div class="input-wrapper-range">
	 <div class="multi-range">
		 <input
			 sprig
			 s-indicator=".loader-wrapper"
			 s-trigger="change delay:200ms"
			 name="priceRangeMin"
			 id="lower"
			 class="price-range price-range-min"
			 type="range"
			 step="50000"
			 min="0"
			 max="{{defautlPrice}}"
			 value="{{priceRangeMin}}"

		 >
		 <input
			 sprig
			 s-indicator=".loader-wrapper"
			 s-trigger="change delay:200ms"
			 name="priceRangeMax"
			 id="upper"
			 class="price-range price-range-max"
			 type="range"
			 step="50000"
			 min="0"
			 max="{{defautlPrice}}"
			 value="{{priceRangeMax}}"
		 >
	 </div>

	 <div class="range-value-wrapper">
		 <p class="range-value">{{priceRangeMin|number_format(0, ' ', ' ')}}$</p>
		 <p class="range-value">{{priceRangeMax|number_format(0, ' ', ' ')}}$</p>
	 </div>
 </div>


{% if entries|length %}
	 {% for entry in entries %}
		 <div class="col-12 col-md-6 col-lg-4 mb-4">
			 {{ entry.title }}
		 </div>
	 {% endfor %}
 {% endif %}

**Comment by bencroker** [comment]
Sorry, that is far too much code. If you can provide the smallest possible reproducible code, then I’ll gladly take a look and try to help you.

**Comment by Shanyb** [comment]
Sorry for that.
While preparing the elements to send to you, I found the error which prevented Sprig from recovering the parameters. So we can consider this ticket resolved.

Thank you very much for the offer of help, much appreciated.
I love the Sprig & Blitz expansions, amazing extention team.

**Comment by bencroker** [comment]
Glad to hear it!
