### ISSUE TITLE
Session variables isSuccess, isError etc are wrongly (I think) persisting

### ISSUE THREAD

**Issue by jamiepittock** [putyourlightson/craft-sprig#363]
### Bug Report

Once set, these variables are persisting across all Sprig components until they're either set again, or I close the browser to force a new session.

So for example, if `sprig.isSuccess` is set to true in one component, it will then be true by default across all components. Same goes for other variables such as `sprig.isError` and `sprig.message`.

### Plugin Version

3.0.0

### Craft CMS Version

5.0.4

### PHP Version

8.2

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-sprig-core/commit/4c71a6e6be6063bd32889b194a5b0d684943382f for the next release.

**Comment by jamiepittock** [comment]
Thanks @bencroker. Any idea when the next release will be?

**Comment by bencroker** [comment]
Released in [2.8.1](https://github.com/putyourlightson/craft-sprig/releases/tag/2.8.1) and [3.0.1](https://github.com/putyourlightson/craft-sprig/releases/tag/3.0.1).
