### ISSUE TITLE
Sprig is attempting to load the wrong TLD on multisite with discreet TLDs

### ISSUE THREAD

**Issue by MattWilcox** [putyourlightson/craft-sprig#366]
### Bug Report

We have a website that is using MultiSite to translate between two sites. It, and Sprig, work flawlessly on DDEV and our Staging server. We use Sprig for the live search, and the loading of the newsletter in the footer.

Both DDEV and Staging use the same TLD for both multisites.
They're set to a bare TLD and a sub-path for each language as follows:

- English: https://academy.viewcreative.agency
- Welsh: https://academy.viewcreative.agency/cy

The Sites do not use Aliases, but instead directly refer to `.env` variables (see attached).

## The problem

The live sites uses separate TLD's for each language:

- English: https://bcuhb-academy.co.uk
- Welsh: https://bcuhb-academi.co.uk

The English works fine. But Sprig does not work on the Welsh site - it appears to be attempting to load content from the English TLD and not the Welsh TLD, and so hitting CORS errors.

Is this a config problem, or a bug in Sprig?

Staging `.env`:
```
PRIMARY_SITE_URL="https://academy.viewcreative.agency"
SECONDARY_SITE_URL="https://academy.viewcreative.agency/cy"
```

Live `.env`:
```
PRIMARY_SITE_URL="https://bcuhb-academy.co.uk"
SECONDARY_SITE_URL="https://bcuhb-academi.co.uk"
```

<img width="435" alt="Screenshot 2024-04-29 at 15 38 56" src="https://github.com/putyourlightson/craft-sprig/assets/814039/fa3113cb-5c87-49ed-8dd0-992694f0bf9e">

<img width="435" alt="Screenshot 2024-04-29 at 15 39 06" src="https://github.com/putyourlightson/craft-sprig/assets/814039/fd4dc8da-20ce-4db6-9353-8ee169cda9df">

Requesting the wrong URL in the Network Inspector, getting a CORS error, and failing to load:

<img width="1280" alt="Screenshot 2024-04-29 at 15 57 23" src="https://github.com/putyourlightson/craft-sprig/assets/814039/bf544f83-7244-4b0c-aa00-ad21a513d818">

### Plugin Version

2.8.1

### Craft CMS Version

Craft Pro 4.8.10

### PHP Version

8.2

**Comment by bencroker** [comment]
This is happening due to behaviour recently changed in Craft. Make sure you’re not setting the `@web` alias or the `CRAFT_WEB_URL` environment variable anywhere in your codebase.

> Yeah, as of 4.8.1, we are building action URLs using the `@web` alias, which means the alias needs to be set correctly. If you’re overriding it, make sure it’s set to the exact same base path that Craft is being accessed from (up to but not including `index.php`).

Source: https://github.com/craftcms/cms/issues/14612

**Comment by MattWilcox** [comment]
Thanks Ben! Removing `CRAFT_WEB_URL` from the `.env` does indeed fix this. So, we are no longer explicitly setting `@web` anywhere, and that's solved this.
