### ISSUE TITLE
pageInfo / pagination issues on request

### ISSUE THREAD

**Issue by rhysmatthew** [putyourlightson/craft-sprig#367]
### Bug Report

Hi, wondering if you can help. 

I'm setting up Sprig as I usually do. This time however in Craft 5 for the first time and basically upon clicking a pagination button with these `sprig s-val:page="{{ page - 1 }}" s-push-url="?page={{ page - 1 }}"` attributes. I get an empty `pageInfo` variable on request. 

However on a first page load with url params ?page=3 for example, I get the expected pageInfo data. 

First page load:

```
putyourlightson\sprig\variables\PaginateVariable {#4738 ▼
  +first: 1
  +last: 8
  +total: 127
  +currentPage: 1
  +totalPages: 16
  +pageTrigger: "p"
  -_basePath: ? string
  +pageResults: array:8 [▶]
}
```

Second page sprig request:

```
putyourlightson\sprig\variables\PaginateVariable {#3393 ▼
  +first: 1
  +last: 0
  +total: 0
  +currentPage: 1
  +totalPages: 1
  +pageTrigger: "p"
  -_basePath: ? string
  +pageResults: []
}
```

Second page, standard page load: 

```
putyourlightson\sprig\variables\PaginateVariable {#4092 ▼
  +first: 9
  +last: 16
  +total: 127
  +currentPage: 2
  +totalPages: 16
  +pageTrigger: "p"
  -_basePath: ? string
  +pageResults: array:8 [▶]
}
```

I'm pretty certain that the sprig code is ok my end, as I've just pulled the same code we use on a lot of our sites so I don't feel I'm doing anything differently. But just let me know if you need me to add my full sprig code and I'll do so.

I thought it could also just be a local issue, but even when I push up to our staging environment I get the same issue.

Thanks

### Plugin Version

3.0.1

### Craft CMS Version

5.1.1

### PHP Version

8.2

**Comment by rhysmatthew** [comment]
I seem to have found the reason for the issue now. If I reposition my `<select sprig ...>` category picker outside of my main sprig `<div s-replace="#entry-container">`, then everything works as usual. Not sure why at this point, as this pattern has worked fine in the past. Will close for now but please let me know if you have any other insight, thanks!

**Comment by bencroker** [comment]
Can you provide a short code sample so I can test locally and investigate whether this is an issue?

**Comment by rhysmatthew** [comment]
@bencroker - sorry for the slow reply. I've gone back to this just to remind myself of the original issue, however I can't replicate what I was seeing before which is odd. Maybe my local environment wasn't working as expected or something but I vaguely remember testing on our staging env too and seeing the same.

Attached a video that somewhat shows what I did to fix, but now both attribute positions work fine... Sorry I can't be more helpful here, probably a non-issue. Also maybe you'd recommend always placing the sprig filters outside of the results container, I just never had issues with it either way. 

https://github.com/putyourlightson/craft-sprig/assets/77306946/cee8606f-405b-4b1c-9f1b-35d15842977d

**Comment by bencroker** [comment]
Ok, well thanks for sharing and glad it is all working for you now.
