### ISSUE TITLE
Integrating Sprig with Algolia hits

### ISSUE THREAD

**Issue by ax2000** [putyourlightson/craft-sprig#368]
### Support Request

Hi Ben,

My current project is an online shop where I'm using Sprig to add products to the cart dynamically. 

When using the default Sprig add to cart functionality, everything works like a charm.

The problem I'm experiencing is when trying to replicate the Sprig add to cart functionality in the Catalogue section of the website, which is powered by Algolia hits and all the product data is handled by the client.

I've been looking around older Sprig support tickets and I think I'm after something similar to the solution outlined [here](https://github.com/putyourlightson/craft-sprig/issues/65).

I'm sure I'm missing something, but after trying several options I can't figure out what I'm doing wrong.

My algolia hits looks like:

```hits({
    container: "#hits",
    templates: {
        empty: '<h5 class="mb-3"><i>No results for <q>{{ query }}</q></i></h5>',
        item: `
          <div class="result-card">
            <div>
              <div class="my-1 truncate-two-lines">
                {{ title }}
              </div>
              <p class="small my-1 text-muted">
                ISBN {{ productIsbn }}
              </p>
              <div class="card__actions">
                <div class="row">
                  <div class="col pr-0">
                    <div class="card__price d-flex align-items-center justify-content-between">
                      <div class="d-flex align-items-center">
                        <button type="button"
                              class="btn btn-add-to-cart-round js-re-render-htmx"
                              sprig
                              s-action="commerce/cart/update-cart"
                              s-method="post"
                              s-val:purchasable-id="{{ variantId }}">
                            <i data-feather="shopping-bag"></i>
                        </button>
                        <span class="h5 m-0 fw-bold">
                          {{ productSalePrice }}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        `,
    },
}),
```

Then in order to re-initialise the sprig button, I've got this logic in the `on render` callback:

```
.on('render', function() {
    //re render feather icons
    feather.replace();
    // Select all elements with the class 'js-re-render-htmx'
    const elements = document.querySelectorAll('.js-re-render-htmx');
    // Process each element with HTMX
    elements.forEach(element => {
        htmx.process(element);
    });
});
```

The render function gets called correctly as the `feather.replace();` icons get loaded correctly. 

Not sure if my approach is correct either or if it's something that I'm missing. Would you please be able to point me in the right direction?

Thanks heaps,
Alby.

### Plugin Version

2.8.1

**Comment by bencroker** [comment]
Where exactly is the Sprig component in the code above? The `sprig` and `s-*` attributes must be parsed to `hx-*` attributes for htmx to be able to detect them.

**Comment by ax2000** [comment]
Thanks for your prompt reply.

I think that my issue is getting my head around how to use the sprig component in this case.

Given that the sprig component is a server side render and Algolia's results are sent back after all server side rendering has finished, I'm struggling to make sense of how to make that work.

My non-algolia component that works correctly is as per below.
product-item.twig:
```
{{ sprig('_includes/_sprig/add-to-cart.twig', { variantId: product.defaultVariant.id, stock: stock }) }}
```
add-to-cart.twig:
```
{% set addedToCart = success is defined %}
{% set inStock = stock > 0 %}
{% if addedToCart %}
  <script>
      htmx.trigger("#cart", "refresh");
      if (typeof openCart !== 'undefined') {
          let openCart = document.getElementById("openCart");
      }
      openCart.click();
  </script>
{% endif %}
{% if inStock %}
  <button type="button"
    class="btn btn-secondary btn-lg w-100"
    sprig
    s-action="commerce/cart/update-cart"
    s-method="post"
    s-val:purchasable-id="{{ variantId }}">
    ADD TO CART
  </button>
{% else %}
  <button type="button"
          class="btn btn-secondary btn-lg w-100"
          sprig
          s-action="commerce/cart/update-cart"
          s-method="post"
          s-val:purchasable-id="{{ variantId }}">
    PRE-ORDER
  </button>
{% endif %}
```

For the algolia side of things, I didn't know how to call the `{{ sprig('_includes/_sprig/add-to-cart.twig', { variantId: product.defaultVariant.id, stock: stock }) }}` tag from within javascript so I parsed directly some of the contents of the `add-to-cart.twig`, as per my first comment, which basically are:
```
<button type="button"
    class="btn btn-secondary btn-lg w-100"
    sprig
    hx-action="commerce/cart/update-cart"
    hx-method="post"
    hx-val:purchasable-id="{{ variantId }}">
    ADD TO CART
  </button>
```
Note that I've tried changing all `s-*` to `hx-*` but I think that the issue has more to do with how I am approaching this rather than trying to re-render htmx manually.

I'm not sure even if what I'm trying to achieve makes sense with Sprig or if I'd be better replicating Sprig's behaviour using vanilla js for the algolia side of things.

Any pointers would be appreciated if you can. Please let me know if the above makes sense or if you'd need me to provide more info.

**Comment by bencroker** [comment]
Sprig can only be rendered server-side, and the parser does much more than just replace `s-` with `hx-`, so your attempt is not going to work. It sounds like you may want to use htmx alone, which is fully client-side, but doesn’t provide some of the benefits that Sprig does.

**Comment by ax2000** [comment]
Thanks for clarifying that Ben - now it does make a bit more sense why I was struggling with it.

I did play around with using htmx alone but I realised I'm missing a lot of niceties from Sprig.
