### ISSUE TITLE
sprig.isRequest and numbers/array of numbers

### ISSUE THREAD

**Issue by yannkost** [putyourlightson/craft-sprig#369]
### Support Request

After updating to sprig 3.0.1 i can see that multiple components have broken. Now numbers seem to be transmitted as strings, same for array of numbers.

![image](https://github.com/putyourlightson/craft-sprig/assets/25202769/c946507e-dc13-4041-8648-243be42a9aaf)

Is this bad use on my side? The call of the function happens here: 

```
 {{ sprig('_components/sprig/load-more-content-teasers.twig', {
                    section: list.contentTeaserContentType.value,
                    stepSize: list.contentTeaserNumberOfElementsPerStep,
                    sortBy: list.contentTeaserSortBy.value,
                    _id: 'id-' ~ random(),
                    applicationIds: applicationIds,
                    entryId: entry ? entry.id : null
                }, {'s-trigger': 'load'}) }}
```

In the sprig  component, the content is wrapped in a `sprig.isRequest`.

### Plugin Version

3.0.1

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-sprig-core/commit/995587cf66fbc5669b400a520c7277fc5c9c47ce and released in [3.0.2](https://github.com/putyourlightson/craft-sprig/releases/tag/3.0.2).
