### ISSUE TITLE
Navigating between full entries using Navigation Links

### ISSUE THREAD

**Issue by challahan** [putyourlightson/craft-sprig#37]
I see examples in the Cookbook showing how to Load More entries, but do you have any insight or examples you can provide on how to navigate between (a) full entries using Next / Previous or (b) full entires within the website's navigation menu without a full page reload? Essentially, replacing the current entry with the selected entry.

It seems this should be simple to do within this framework and would be a common use case.

My initial thinking is that Pagination could be utilized to exhibit this behavior by limiting to only 1 entry at a time for the Next/Previous example, but this would only work for entries that are in a particular sequence and not for general navigation.

Any insight would be much appreciated!

**Comment by bencroker** [comment]
I'm not sure what you mean by a "full" entry, nor how you might determine previous/next entries, but a simplified version of the [pagination recipe](https://putyourlightson.com/sprig-cookbook#pagination) should do the trick.

```twig
{% set offset = offset ?? 0 %}

{% set entry = craft.entries.offset(offset).one() %}

<h1>{{ entry.title }}</h1>

{{ entry.body }}

{% if offset > 0 %}
    <button sprig s-vars="offset: {{ offset - 1 }}">Previous entry</button>
{% endif %}

<button sprig s-vars="offset: {{ offset + 1 }}">Next entry</button>
```

**Comment by bencroker** [comment]
If you want to swap the content of a full page then this may be what you are looking for:
https://htmx.org/attributes/hx-boost/

**Comment by challahan** [comment]
Thank you Ben! The HX-Boost method is exactly what I was looking for. The pagination is also helpful.
