### ISSUE TITLE
Getting a 500 when adding an image from a field using the "AWS S3 for Craft" plug in

### ISSUE THREAD

**Issue by minimaldesign** [putyourlightson/craft-sprig#371]
This code works great:

```twig
{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.section('news').offset(offset).limit(limit) %}
{% set entries = entryQuery.all() %}

<ul class="about__news__list">
  {% for entry in entries %}
    <li>
	<div class="about__news__list__header">
		<h3><a href="{{ entry.url }}">{{ entry.title }}</a></h3>
		<time datetime="{{ entry.postDate|date('Y-m-d') }}">{{ entry.postDate|date('M d, Y') }}</time>
	</div>
	<div class="about__news__list__content">
	{% if entry.newsSummary|length %}
		{{ entry.newsSummary }}
	{% else %}
		{{ entry.newsContent }}
	{% endif %}
	</div>
    </li>
  {% endfor %}
</ul>
<div class="about__more">
  {% if entryQuery.count() > offset + (entries|length) %}
    <button class="btn btn--outline"
      id="load-more-oob"
      sprig
      s-val:offset="{{ offset + limit }}"
      s-select="li"
      s-target=".about__news__list"
      s-swap="beforeend"
      {{ sprig.trigger == 'load-more-oob' ? 's-swap-oob="true"' }}>
      Load more
    </button>
  {% else %}
    <button id="load-more-oob" s-swap-oob="true" style="display: none"></button>
  {% endif %}
</div>

```

But if I add this in the `entries` loop above, I get a 500 error
```twig
<div class="about__news__list__image">
  <div style="background-image: url({{entry.newsImageThumbnail.one().url}})"></div>
</div>
```

I'm assuming it's because the S3 images have not been fetched or something like that? Is there a way around this?

Thanks!

**Comment by bencroker** [comment]
This is almost certainly an error in your Twig code. What does the body of the 500 response contain when `devMode` is enabled?

**Comment by minimaldesign** [comment]
The line of Twig code that creates the error is:

```twig
<div style="background-image: url({{entry.newsImageThumbnail.one().url}})"></div>
```

Without it, everything works as expected.

The 500 in the console is not super useful to me… Maybe it will make more sense to you?

<img width="539" alt="SCR-20240524-kdcq" src="https://github.com/putyourlightson/craft-sprig/assets/20896/66237294-fa55-4745-ba41-0e9cc5a57d8c">

Thanks for your help!!

**Comment by bencroker** [comment]
Please open the response tab of the network request (generally under Network in the browser's dev tools), where you should see a helpful error. My guess is that you're calling `.url` on a `null` value, because the image doesn't exist.

**Comment by minimaldesign** [comment]
You were right… Thanks for helping me figure this out and sorry to bug you. Had nothing to do with your plug in… I should have figure this out myself!

**Comment by bencroker** [comment]
No problem!
