### ISSUE TITLE
Vite, CORS and pushUrl

### ISSUE THREAD

**Issue by robzor** [putyourlightson/craft-sprig#374]
### Support Request

Hi Ben!

I am currently building a site that is running locally in Docker with a Vite build chain. Docker serves the site at `http://localhost:8080/` and the Vite server runs at `http://localhost:3000`. 

Because of that, I'm using this code in my site header to make all my public Vite assets work ([see this if you want some fun reading](https://nystudio107.com/blog/using-vite-js-next-generation-frontend-tooling-with-craft-cms#vite-processed-assets))

```
{# Vite Dev: Set base HREF for all relative URLs #}
    {% if craft.vite.devServerRunning() %}
      <base href="{{ alias('@viteBaseUrl') }}">
    {% endif %}
```

But doing this causes the side effect of messing up the `pushUrl` method in Sprig, e.g. if I do this:

```
{% set urlParams = {
  page: page,
  type: type,
} %}
{% do sprig.pushUrl('?' ~ urlParams|url_encode) %}
```

I get a console error ala: 
`DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://localhost:3000/?page=1&type=events' cannot be created in a document with origin 'http://localhost:8080' and URL 'http://localhost:8080/news'.`

I tried changing the `sprig.pushUrl()` to include `craft.app.request.absoluteUrl` and various combinations of bits from the request but it is always passing the magical Sprig index.php action URL and not the current page URL. Is there a simple thing I'm missing here or should I just make a new variable to pass through to the Sprig component, something like 'current page URL'?

Thanks for any help you might be able to give,

Rob

### Plugin Version

3.0.2

**Comment by bencroker** [comment]
`sprig.pushUrl()` resolves to [`hx-push-url`](https://htmx.org/attributes/hx-push-url/), which accepts an absolute URL. Does it work if you hardcode the full URL?

```twig
{% do sprig.pushUrl('http://localhost:8080/?' ~ urlParams|url_encode) %}
```

**Comment by robzor** [comment]
It does work yes, but for instance, if I want to get the current segment "e.g. '/news' I wouldn't be able to do it dynamically.

So for instance, `siteUrl` works for the base URL bit.
 
Does sprig have a variable available for the current request URL or path segment/s that it's been called from?

**Comment by bencroker** [comment]
You can pass URL segments into a Sprig component on page load, but subsequent component refreshes are unaware of the current URL, since they are called via action requests.

**Comment by robzor** [comment]
> You can pass URL segments into a Sprig component on page load, but subsequent component refreshes are unaware of the current URL, since they are called via action requests. 

Yeah I thought so, it looks like there isn't an easy way to "override" the `<base>` html tag, maybe I just have to pass the segment through and the `siteUrl()` function to build the URL to belt and braces the request.

**Comment by bencroker** [comment]
Good luck with it!

**Comment by robzor** [comment]
For anyone looking at this in the future, this worked:

`{% do sprig.pushUrl(siteUrl('news', urlParams)) %}`

Obviously replacing news with a variable passed through to the Sprig component would be good if you needed to be more flexible!
