### ISSUE TITLE
Sprig and flatpickr calendar

### ISSUE THREAD

**Issue by dmitryvatagin** [putyourlightson/craft-sprig#375]
### Support Request

I don't really get how to combine properly sprig and js functionality.
I managed to filter item with using of sprig and flatpickr.
But if I want to add clear button, how can I refer to initial calendar?

For example, I have 
const myInput = document.querySelector(".myInput");
const fp = flatpickr(myInput, {});
const clearButton = document.querySelector(".clear"); 

clearButton.addEventListener('click', e => {
fp.clear();
});

somehow it reacts on the button, but after first sprig reload doesn't know anything about calendar (**fp**)

Is there a work around to make it work?

### Plugin Version

2.8.1

**Comment by bencroker** [comment]
The component refresh will wipe out the HTML elements that are tied to your calendar. You can either specify a partial to replace using [`s-replace`](https://putyourlightson.com/plugins/sprig#s-replace), or re-initialise the calendar using JS on each Sprig refresh, for example:

```twig
{% if sprig.isRequest %}
    <script>
        flatpickr(myInput, {});
    </script>
{% endif %}
```
