### ISSUE TITLE
sprig.pushUrl is not updating URL

### ISSUE THREAD

**Issue by svondervoort** [putyourlightson/craft-sprig#379]
### Bug Report

On [this page](https://werkenbij.vandervelden.com/vacatures) we have filtering using Sprig. In the Sprig partial we have the following pushUrl logic:

```
{% do sprig.pushUrl('?' ~ {page: page, query: query, zipcode: zipcode, distance: distance, function: function, educationLevel: educationLevel} | url_encode) %}
```

Somehow locally and on the staging environment the URL is updated but on the live version it doesn't.

My gut feeling says it might have something to do with the domain.
- Local: `van-der-velden-website.test/werkenbij/vacatures`
- Staging: `van-der-velden-staging.###.com/werkenbij/vacatures`
- Live: `werkenbij.vandervelden.com/vacatures`

The reason I'm thinking it is related to this is since we where also having trouble with CORS and HTMX headers on the live environment since it thinks it's a completely different domain. Probably because of the subdomain?

It is a multi-site setup and the Primary site is vandervelden.com and the secondary recruitment site is werkenbij.vandervelden.com.

Both sites Base URLs are set using .env parameters without using the @web alias. We do however have the @web alias set to the primary site .env parameter.

I don't see any console errors related to Sprig or HTMX

### Plugin Version

2.8.1

### Craft CMS Version

4.10.2

### PHP Version

8.2

**Comment by bencroker** [comment]
This is likely happening due to behaviour recently changed in Craft. Make sure you’re **not** setting the `@web` alias or the `CRAFT_WEB_URL` environment variable anywhere in your codebase.

> Yeah, as of 4.8.1, we are building action URLs using the `@web` alias, which means the alias needs to be set correctly. If you’re overriding it, make sure it’s set to the exact same base path that Craft is being accessed from (up to but not including `index.php`).

Source: https://github.com/craftcms/cms/issues/14612

**Comment by svondervoort** [comment]
Is the Craft CMS documentation not up to date then, because there they [state the following](https://craftcms.com/docs/4.x/config/#craftwebroot:~:text=To%20prevent%20a%20variety):

> To prevent a variety of security issues, we recommend explicitly setting the @web alias with a fully-qualified URL, either via a configuration file (see below) or [environment variable](https://craftcms.com/docs/4.x/config/#env).

I did test by unsetting the @web alias locally and it seems to be working. I will do some more testing on the staging by adding a second domain before pushing it to live.

**Comment by bencroker** [comment]
The Craft 5 docs on [Configuring Craft](https://craftcms.com/docs/5.x/configure.html#aliases) are up to date and state:

> Setting `@web` can be problematic in multi-site installations that span multiple domains, or when accessing the control panel at a different domain from the front-end. In general, we recommend letting Craft determine this automatically, and using [environment variables](https://craftcms.com/docs/5.x/configure.html#control-panel-settings) to define the full base URI for each site.

**Comment by svondervoort** [comment]
I wonder why the Craft CMS 4 docs haven't been updated yet, but it works so thats great :) and nothing breaks.
