### ISSUE TITLE
Front-end Form Checkbox

### ISSUE THREAD

**Issue by wbdzynr** [putyourlightson/craft-sprig#380]
### Support Request

I have a front-end form with a checkbox that I want to "sprigify" so I can use the checked value later to show/hide content.  Without Sprig, I can save the value and state all day long.  But when I use Sprig it won't save the state.  I am getting the same result when testing in Sprig Playground.

I have set my initial ttRestatement value using [0] and without (currently using it without).

The field name is "ttRestatement" and has a value of "yes".

```{% set ttRestatement = fields.ttRestatement ?? entry.ttRestatement %}

{% set ttRestatementOptions = craft.app.fields.getFieldByHandle('ttRestatement').options %}
{{ hiddenInput('fields[ttRestatement]', '') }}
{% for option in ttRestatementOptions %}
	<label><input sprig type="checkbox" name="fields[ttRestatement][]" value="{{ option.value }}"{{ option.value in ttRestatement ? ' checked' }}>{{ option.label }}</label>
{% endfor %}```

### Plugin Version

2.9

**Comment by bencroker** [comment]
When you say “it won't save the state”, where exactly are you expecting the state to be saved to? You haven’t specified what you]re saving it to, nor have you shown any form actions in your code, so I’m not sure how to respond.

**Comment by wbdzynr** [comment]
Sorry, I was trying to keep it all very simple.  It's a front-end entry form.  Whether the field is checked or unchecked in the control panel, it appears fine when you first load the page.  However, when you click to check/uncheck the box on the page, and sprig "refreshes" the page, the field doesn't stay checked or unchecked - even though inspector shows fields[ttRestatement][]=yes or fields[ttRestatement][]=.  Hope that helps?

**Comment by bencroker** [comment]
Should it not be `option.value in (fields.ttRestatement ?? []) ? ' checked'`?

**Comment by wbdzynr** [comment]
Assuming you mean this - it doesn't work.  
```{% set ttRestatementOptions = craft.app.fields.getFieldByHandle('ttRestatement').options %}
{{ hiddenInput('fields[ttRestatement]', '') }}
{% for option in ttRestatementOptions %}
	<label><input sprig type="checkbox" name="fields[ttRestatement][]" value="{{ option.value }}"{{ option.value in (fields.ttRestatement ?? []) ? ' checked' }}> {{ option.label }}</label>
{% endfor %}`

**Comment by bencroker** [comment]
Please provide a simplified version of the code, including the form element and actions.

**Comment by wbdzynr** [comment]
```{# main.twig #}
{% extends "_partials/_layout" %}
{% set title =  "Choose Documents" %}
{% block content %}
	{{ sprig('/sprig/choose-documents') }}
{% endblock %}


{# /sprig/choose-documents.twig #}
{% set entry = craft.entries
	.id(interviewId)
	.status(null)
	.one()
%}
{% set ttRestatement = fields.ttRestatement ?? entry.ttRestatement %}
<form method="post" accept-charset="UTF-8" id="cw_form" class="form">
	{{ csrfInput() }}
	{{ actionInput('entries/save-entry') }}
	{{ hiddenInput('sectionId', 8) }}
	{{ hiddenInput('enabled', 1) }}
	{{ hiddenInput('entryId', entry.id ) }}

	{% set ttRestatementOptions = craft.app.fields.getFieldByHandle('ttRestatement').options %}
	{{ hiddenInput('fields[ttRestatement]', '') }}
	{% for option in ttRestatementOptions %}
		<label><input sprig type="checkbox" name="fields[ttRestatement][]" value="{{ option.value }}"{{ option.value in (fields.ttRestatement ?? []) ? ' checked' }}> {{ option.label }}</label>
	{% endfor %}
	{# The following is relying on if the box is checked or not (via the entry or Sprig) #}
	{% if ttRestatement == "yes" %} 
		... then show this content 
	{% endif %}
</form>

**Comment by bencroker** [comment]
Your sprigified input field is set up to refresh the component but not submit the form. See the example of sprigifying a form at https://putyourlightson.com/sprig/cookbook#entry-form

Here’s an example of how you can put the reactive behaviour on the input field.

```twig
{% set ttRestatement = fields.ttRestatement ?? entry.ttRestatement %}

<input sprig s-method="post" s-action="entries/save-entry" type="checkbox" name="fields[ttRestatement][]" value="{{ option.value }}" {{ option.value in ttRestatement ? ' checked' }}>
```

**Comment by wbdzynr** [comment]
OK, I didn't have to do that on my dropdown fields but that's good to know.  So this is saving the "state" (and the entry).  However, the value of ttRestatement is not consistent.  For instance, the field is checked in the CP, and it's checked on the form.  But it's always showing "False".  If I change the top line to `entry.ttRestatement[0]`, then the value works but the state of the checkbox does not.  Argh...

```{% set ttRestatement = fields.ttRestatement[0] ?? entry.ttRestatement %}
{% set ttRestatementOptions = craft.app.fields.getFieldByHandle('ttRestatement').options %}
{{ hiddenInput('fields[ttRestatement]', '') }}
{% for option in ttRestatementOptions %}
	<label><input sprig s-method="post" s-action="entries/save-entry" type="checkbox" name="fields[ttRestatement][]" value="{{ option.value }}" {{ option.value in ttRestatement ? ' checked' }}> {{ option.label }}</label>
{% endfor %}
{% if ttRestatement == "yes" %}
	True
{% else %} 
	False
{% endif %}

**Comment by bencroker** [comment]
`ttRestatement` is set to an array of values, not a single value, so your comparison is expected to fail. This should work, similarly to the condition in the input field.

```twig
{% if 'yes' in ttRestatement %}
	True
{% else %} 
	False
{% endif %}
```

**Comment by wbdzynr** [comment]
OK, that appears to be working now.  Thanks Ben!

**Comment by bencroker** [comment]
Sure thing!
