### ISSUE TITLE
`csrfInput()` within Sprig components don't get updated when Craft's `asyncCsrfInputs` setting is `true`

### ISSUE THREAD

**Issue by chadwells** [putyourlightson/craft-sprig#381]
### Bug Report

We have a checkout page that is excluded from the Blitz + Cloudflare static caching that we have setup site-wide. We have the Craft config setting `asyncCsrfInputs(true)` set for the site. We're experiencing an issue where our checkout page's sprig components that have forms with `{{ csrfInput() }}` in them do not get their CSRF input tags swapped as expected. `{{ csrfInput() }}` outside the sprig components do though. 

### Plugin Version

2.8.1

### Craft CMS Version

4.10.5

### PHP Version

8.0.30

**Comment by bencroker** [comment]
You shouldn’t have to call `csrfInput()` within the Sprig component. Adding `s-method="post"` to elements with the `sprig` attribute should result in Sprig sending and refreshing CSRF values for you.
See https://putyourlightson.com/plugins/sprig#controller-actions

**Comment by chadwells** [comment]
oh my gosh... of course! Somehow I forgot that! Thank you. That gets me past this, but there are still issues elsewhere in my code that are affected only when `asyncCsrfInputs(true)` is set. I'm unsure at this point if it's even Sprig related (probably not at this point, just an implementation change we need to make)
