### ISSUE TITLE
Multiple forms in component and failing pagination URLs. Advice please

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-sprig#384]
### Support Request

Ok so I'm using Sprig for comments at the end of an entry. Comments are just entries. Some articles have hundreds and hundreds of comments and nesting too.

So I have a main sprig component with pagination implemented like your cookbook recipe

`{{ sprig('blog/_comments/parent', {'limit': 50, 'blogEntryId': entry.id}) }}`

Inside this i have another component for child/nested  comments (which there can be a lot of too). In here I have your load more example

`{{ sprig('blog/_comments/child.twig', { 'limit': 2 }) }}`

Each comment I have a sprigified form under to reply to comment. Similar to 

```
<form sprig s-method="post" s-action="entries/save-entry">
		 {% set section = craft.app.sections.getSectionByHandle('comments') %}
		 {{ hiddenInput('sectionId', section.id) }}
		 {{ hiddenInput('enabled', false) }}
```

And by now you've probably guessed why pagination will not work. As it is tagging every single hidden field from all the comment forms onto pagination URL so fails as to long.

Any suggestions for reorganisation of these components and how to deal with the hidden field and query string issue?

### Plugin Version

Sprig 2.11.0, Craft 4

**Comment by bencroker** [comment]
You can limit which element values are submitted using the [`s-include`](https://putyourlightson.com/plugins/sprig#s-include) attribute. By default, the entire component is used for the value of `s-include` but you can place it on an element that wraps your pagination.

```twig
{# Comment components #}

<div s-include="this">
    {# Pagination section #}
</div>
```

**Comment by john-henry** [comment]
Thanks Ben. Will give this a go

**Comment by john-henry** [comment]
@bencroker That works great thanks. Now gotta work on the performance of the paginated comments which is still very slow
