### ISSUE TITLE
Issue with new triggerRefresh function after Barba JS

### ISSUE THREAD

**Issue by lennonpuype** [putyourlightson/craft-sprig#385]
### Bug Report

Hi Ben,

Some months ago I opened an issue for when using Barba JS and Sprig which was resolved. The solution back then was to run something like `htmx.process($sprigComponent);`.

Now on the same website which has this working logic I am using in another Sprig component, the new `{% do sprig.triggerRefresh('#video-popup', { videoID: moqTale }) %}` which updates a specific Sprig component. This all works fine, but when coming from another page there are some issues.

Page A: Uses the triggerRefresh
Page B: A regular Sprig component, nothing special.
Page C: Has 0 Sprig components

**Page C > B:** Sprig working completely fine since it is refreshed using the `htmx.process()` function
**Page C > A:** I get a JS error when letting Sprig do its work (`htmlx.process()` is being triggered so it should refresh on load) `Uncaught ReferenceError: htmx is not defined at document.body.addEventListener.once`
**Page B > A:** I get a JS error when letting Sprig do its work (`htmlx.process()` is being triggered so it should refresh on load) `TypeError: Cannot read properties of null (reading 'dispatchEvent')
    at Object.he [as trigger]`

When going from Page C or B to Page A when the `{% do sprig.triggerRefresh('#video-popup', { videoID: moqTale }) %}` is not in the code, sprig is actually working, but then my functionality is gone which refreshes the video-popup sprig component.

Initially on a normal page load, the logics are working fine for Page A

### Plugin Version

2.12.0

### Craft CMS Version

4.11.4

**Comment by bencroker** [comment]
Can you please share a stripped down component so I can test it out locally? I'm specifically looking for the placing of the `htmx.process()` command.

**Comment by lennonpuype** [comment]
Here is the working logic where the htmx.process() is happening.

```
barba.init({
    timeout: 10000,
    resetNativeScroll: true,
    sync: false,
    transitions: [{
        name: 'fade',
        beforeEnter: function beforeEnter(data) {
            reloadSprig();
        },
    }]
})	  

const reloadSprig = () => {
    const $sprigComponents = document.querySelectorAll('.sprig-component');

    if($sprigComponents) {
	$sprigComponents.forEach($sprigComponent => {
	    htmx.process($sprigComponent);
	});
    }
}
```

**Comment by lennonpuype** [comment]
**The page with the components**
```
{% extends '_layouts/site' %}

{% set insights = craft.entries.section('insights').orderBy('postDate desc').all() ?? null %}

{% block videoPopup %}
    {{ sprig('_sprig/_video-popup.twig', {
    }, {
        'id': 'video-popup',
        's-trigger': 'refresh'
    }) }}
{% endblock videoPopup %}

{% block main %}   
    {{ sprig('_sprig/_insights.twig') }}   

    <div class="px-12 mt-52 max-md:mt-32 max-sm:mt-20 insights-overview">
        <div class="grid grid-cols-1 sm:grid-cols-2 ml:grid-cols-3 gap-x-6 gap-y-20 2xl:gap-y-32">
            {% for insight in insights %}                
                <label for="moqTale-{{insightVideo.vimeoID}}">                    
                    <h5 class="mt-4 mb-4 hyphens-auto">{{insight.customTitle|nl2br}}</h5>                   
                </label>
            {% endfor %}
        </div> 
    </div>
{% endblock %}

{% block _inline_js %}{% endblock %}
```

**The component with the triggerRefresh function**
```
{% set insights = craft.entries.section('insights').orderBy('postDate desc').all() ?? null %}

{% set hasVideo = false %}
{% set moqTale = moqTale ?? null %}

{% if insights ?? null %}
    {% for insight in insights %}
        {% set insightImage = insight.customImage.one() ?? null %}
        {% set insightVideo = insight.vimeoVideo.one() ?? null %}
        {% set isDefault = insight.type.handle == 'default' %}

        {% if insight.type.handle == 'moqTale' %}
            {% set hasVideo = true %}
            <input sprig type="radio" name="moqTale" value="{{insightVideo.vimeoID}}" id="moqTale-{{insightVideo.vimeoID}}" class="hidden" {% if insightVideo.vimeoID == moqTale %}checked{% endif %}/>
        {% endif %}
    {% endfor %}

    {% if hasVideo %}
        {% do sprig.triggerRefresh('#video-popup', { videoID: moqTale }) %}
    {% endif %}
{% endif %}
```

**Component to refresh**
```
{% set videoID = videoID ?? null %}

{{ dump(videoID) }}

```

### JAVASCRIPT
Here is the logic that works for other sprig component where the htmx.process() is happening inside JS.

```
barba.init({
    timeout: 10000,
    resetNativeScroll: true,
    sync: false,
    transitions: [{
        name: 'fade',
        beforeEnter: function beforeEnter(data) {
            reloadSprig();
        },
    }]
})	  

const reloadSprig = () => {
    const $sprigComponents = document.querySelectorAll('.sprig-component');

    if($sprigComponents) {
	$sprigComponents.forEach($sprigComponent => {
	    htmx.process($sprigComponent);
	});
    }
}
```

**Comment by bencroker** [comment]
Regarding going from page C to A, my guess is that the `sprig.triggerRefresh` function, which ends up outputting `htmx.trigger`, is being called before htmx has been loaded into the page. How does Barba JS load the htmx file when going from a page without it to one that includes it?

Please show me the full error when going from page B to A, so I can investigate what might be going on.

**Comment by bencroker** [comment]
Just had the thought that a simple fix would be to forcefully load htmx on every page, regardless of whether or not it contains a Sprig component, using [`sprig.registerScript`](https://putyourlightson.com/plugins/sprig#sprig-registerscript).

```twig
{% do sprig.registerScript %}
```

An alternative approach might be to follow the solution presented in this [Managing different scripts in separate pages while using barba.js](https://dev.to/rabibsust/managing-different-scripts-in-separate-pages-while-using-barbajs-e4i) article.

**Comment by lennonpuype** [comment]
I tried your last possible fix by using `{% do sprig.registerScript %}` to load htmx on every page, which seems like a logic solution. It looks like that issue from the `{% do sprig.triggerRefresh() %}` is gone now!

Meanwhile I bumped on the error I had that I said when going from page Page B > A and that issue was so stupid from my side. As you can see in my example code I added a block outside of the main, well that block was called outside of the barba container.

So by solving that now both the errors of htmx is not defined and dispatchEvent are solved!

**Comment by bencroker** [comment]
Glad to hear it!
