### ISSUE TITLE
Problem with Checkbox

### ISSUE THREAD

**Issue by wbdzynr** [putyourlightson/craft-sprig#386]
### Support Request

I have a checkbox field ("myFieldName") that has 5 options (options 1-5).  Here is my code:
```twig
{% extends "_partials/_layout" %}
{% set title =  "Choose Documents" %}
{% block content %}
	{{ sprig('/sprig/choose-documents') }}
{% endblock %}


{# /sprig/choose-documents.twig #}
{% set entry = craft.entries
	.id(interviewId)
	.status(null)
	.one()
%}
{% set ttRestatement = fields.ttRestatement ?? entry.ttRestatement %}
<form method="post" accept-charset="UTF-8" id="cw_form" class="form">
	{{ csrfInput() }}
	{{ actionInput('entries/save-entry') }}
	{{ hiddenInput('sectionId', 8) }}
	{{ hiddenInput('enabled', 1) }}
	{{ hiddenInput('entryId', entry.id ) }}

<div class="mt-2">
	{% set myFieldName = fields.myFieldName ?? entry.myFieldName %}
	{% set fieldNameVariable = craft.app.fields.getFieldByHandle('myFieldName') %}
	{{ hiddenInput('fields[myFieldName][]', '') }}
	{% for option in fieldNameVariable.options %}
		<div class="form-check">
			<input sprig  type="checkbox" name="fields[myFieldName][]" value="{{ option.value }}" {{ option.value in myFieldName ? ' checked' : '' }}>
			<label>{{ option.label }}</label>
		</div>
	{% endfor %}
</div>

{% if "option1" in myFieldName %}<p>Option 1</p>{% endif %} 
{% if "option2" in myFieldName %}<p>Option 2</p>{% endif %} 
{% if "option3" in myFieldName %}<p>Option 3</p>{% endif %} 
{% if "option4" in myFieldName %}<p>Option 4</p>{% endif %} 
{% if "option5" in myFieldName %}<p>Option 5</p>{% endif %}

<button type="submit" id="btnInterviewSubmit" class="btn btn-primary" sprig s-method="post" s-action="entries/save-entry" s-indicator="#indicator" s-val:buttonRedirect="{{ thisTemplatePath }}">Save Please!</button>
<button type="submit" id="btnInterviewSubmit" class="btn btn-primary" >Save Please!</button>


</form>
```

With `{{ hiddenInput('fields[client1_trustProtectorAppointedBy]', '') }}`, you can't check a box and have it stay checked after the sprig refresh.  But the form will save.  If I add brackets to that - `{{ hiddenInput('fields[client1_trustProtectorAppointedBy][]', '') }}` then any options that are checked will stay checked after sprig refreshes.  But the form won't save.  The logs show "'sprig:message' => 'Couldn’t save entry.'"  There are no errors in the inspector but the form just won't save.  

If I add `s-method="post" s-action="entries/save-entry"` to the input, it does try calling "entries/save-entry" but again, doesn't save the entry (same sprig message as above about couldn't save the entry).  (I'd also rather not have it try to save after each box is checked.)

At any point, I can successfully save the entry via the CP without any issues.

My primary "Submit" button was using Sprig so I added another regular "save" button to see if that helped.  It does not.

Any thoughts are greatly appreciated!

### Plugin Version

2.12.0

**Comment by bencroker** [comment]
This is likely how your input field should be written (the line breaks are just for readability). I would put the `sprig s-method="post" s-action="..."` attributes on the `form` element only, which should get you the expected behaviour on submission.

```twig
{% set myFieldValue = fields.myFieldName ?? entry.myFieldName %}
<input type="checkbox" 
    name="fields[myFieldName][]" 
    value="{{ option.value }}" 
    {{ option.value in myFieldValue ? 'checked' }}
>
```

**Comment by wbdzynr** [comment]
Hi Ben - I need to display another field if one of the boxes, so that's why the sprig tag was on the input.  

Also, I finally found the issue within the debug toolbar.  Even though it appears that everything saved right - it didn't.  It comes back and says 
`Element not saved due to validation Array
(
	[myFieldName] => Array
	(
		[0] => My Field Name is invalid.
	)
)`

**Comment by bencroker** [comment]
Glad to hear you figured it out!
