### ISSUE TITLE
Triggers in sprig components don't work on other components anymore

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-sprig#387]
### Bug Report

I have this code which used to work before HTMX2:

**product.twig**
```
{{ sprig('_partials/cart', {}, {'s-trigger': 'changed from:#addtocartform', 'id': 'cart'}) }}
{{ sprig('products/_addtocart.twig', { productId: product.id }, {'s-trigger': 'load','id': 'addtocartform'} ) }}
```

**_addtocart.twig**
```
{% if sprig.isSuccess %}
  Added to cart
{% else %}
  {# show the sizes form #}
  <form sprig s-method="post" s-action="commerce/cart/update-cart">
    {{ csrfInput() }}
    {{ actionInput('commerce/cart/update-cart') }}
    <button type="submit" class="btn btn-secondary btn-bold"/>{{ "Add to bag"|t }}</button>
  </form>
{% endif %}
```

This used to work. When the form inside _sizes.twig was posted, the whole #addtocartform component was re-rendered, and the #cart would also re-render (because #addtocartform changed). Since the update, it doesn't happen anymore.

### Plugin Version

3.5.0

### Craft CMS Version

Craft Pro 5.4.1

### PHP Version

8.3.3

**Comment by bartrylant** [comment]
I also tried doing this in _addtocart.twig, but no succes. The #cart component is not being rerendered.

```
{% if sprig.isSuccess %}
  {% do sprig.setRegisterScript(true) %}  
  {% set js %}
      htmx.trigger('#cart', 'refresh');
  {% endset %}
  {% do sprig.registerJs(js) %}
{% else %}
...
```

**Comment by bencroker** [comment]
Have you tested this using htmx v1?

Looking at the code, I wouldn’t expect it to work (in either version of htmx). You’re listening for a `change` event, but neither the `form` nor the `button` element would emit a `change` event, as far as I know. Maybe if you have a `select` field or `checkbox` group, then a `change` event would be submitted.

As a side not, your components could be simplified to something like this and it should then all work.

```twig
{{ sprig('_partials/cart', {}, { 's-listen': '#addtocartform' }) }}
{{ sprig('products/_addtocart.twig', { productId: product.id }, { id: 'addtocartform', 's-trigger': 'load' } ) }}
```

**Comment by bartrylant** [comment]
I'd like to give it a try with htmx 1 but when I try to not automatically insert the htmx 2 script with `{% do sprig.setRegisterScript(false) %}`, it still gets injected.

**Comment by bartrylant** [comment]
I changed it to

```
{{ sprig('_partials/cart', {}, { 's-listen': '#addtocartform' }) }}
{{ sprig('products/_addtocart.twig', { productId: product.id }, { id: 'addtocartform', 's-trigger': 'load' } ) }}
```

which indeed works, but it also refreshes the #cart on the initial load of products/_addtocart.twig. Which I do not need. I only want to load the cart when an item has been added.

**Comment by bencroker** [comment]
In that case, you can drop `s-replace` and use [`sprig.triggerRefresh`](https://putyourlightson.com/plugins/sprig#sprig-triggerrefreshtarget-variables) only on success instead.

```twig
{{ sprig('_partials/cart', {}, { id: 'cart' }) }}
{{ sprig('products/_addtocart.twig', { productId: product.id }, { 's-trigger': 'load' } ) }}
```

```twig
{% if sprig.isSuccess %}
    {% do sprig.triggerRefresh('#cart') %}
{% endif %}
```

I covered this topic in this [CraftQuest livestream](https://craftquest.io/livestreams/sprig-q-a-and-new-features-with-ben-croker).
