### ISSUE TITLE
Pagination not functioning on latest Craft 5 and Sprig 3.5

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-sprig#388]
### Bug Report

Just setting up pagination on a new sprig component in Craft 5 (latest release) and Sprig (latest release) and I have noticed that the pagination is not working.

I have tried from an existing working project which does work ok (Craft 4) and so i though perhaps it was something I had mucked up.

So I dropped in the raw sprig pagination example from the docs to test and I see the same issue.

I don't get any errors or any feedback, the buttons interact but the pagination just doesn't happen and the ?page part of url is not pushed.

I tried a native Craft pagination and this does work correctly.  

### Plugin Version

3.5.0

### Craft CMS Version

Craft Pro 5.4.1

### PHP Version

8.3.10

**Comment by bencroker** [comment]
Just tested using both the [pagination recipe](https://putyourlightson.com/sprig/cookbook#pagination) and the pagination example in the Sprig playground, and both work fine. Have you tested these and is there anything showing up in the network response?

![screenshot-1anFcHlb@2x](https://github.com/user-attachments/assets/9ab85b7c-8d23-4498-9a39-193f2648db33)

**Comment by terryupton** [comment]
Hi @bencroker,

Yes I have tested the Pagination recipe in the playground and it is the same outcome. 
Everything shows but the pagination doesn't paginate anything. It remains on page 1. This is the same if I click `Next` or any of the page numbers. 

The network tabs shows only that there was a new request with a 200 code as though it is all working. 
Would you like a screen recording?

Thanks.

**Comment by bencroker** [comment]
Yes please, with the network tab open.

**Comment by terryupton** [comment]
Video too large to upload here. So here is a link.
https://www.dropbox.com/t/HlOHKN22nNdYvKS0

Let me know if you need to see more info or anything else. Thanks.

**Comment by bencroker** [comment]
The responses are indeed successful, but you didn’t show their content so I’m not sure what I can suggest.

**Comment by terryupton** [comment]
Here is another video @bencroker 
https://www.dropbox.com/t/5FuY9zcRGYsStS1x

Not sure this will help though? I tried to show the content, but it is blank and there is not much on the response.
If you like I can give you a login to the site to check it out.

I will test another Craft site I have just setup to see if this works.
Any incline as to what it could be?
Thanks.

**Comment by terryupton** [comment]
Hi @bencroker 
I haver tried a brand new Craft site with only Sprig installed and one section with a handful of entries and I can am seeing the exact same issue in the Sprig playground on the back-end of that site too.

**Comment by bencroker** [comment]
> Not sure this will help though? I tried to show the content, but it is blank and there is not much on the response.

You didn’t show show the _raw_ response (the source code), so there’s nothing of use there.

Please send login credentials to support@putyourlightson.com or, better yet, a repo in which this is reproduceable.

**Comment by terryupton** [comment]
Have sent you the login credentials @bencroker and an invite to the Repo.
Thank you.

**Comment by bencroker** [comment]
So I discovered that you have set the [`pageTrigger`](https://craftcms.com/docs/5.x/reference/config/general.html#pagetrigger) general config setting to `page`, which is overwriting the variable in your component to always be `1` (which is the default if it is not found in the URL). Changing it back to the default `p` (or anything else) solves the issue, as does renaming the `page` variable in the component to something else. 

So this, for example, should work, without having to make any other changes.

```twig
{% set currentPage = currentPage ?? 1 %}

{% set entryQuery = craft.entries.limit(limit) %}

{# Paginates the entry query given the current page #}
{% set pageInfo = sprig.paginate(entryQuery, currentPage) %}

...
```

**Comment by terryupton** [comment]
Ah that is a great find @bencroker - thank you.
