### ISSUE TITLE
Pagination in Search Results

### ISSUE THREAD

**Issue by petenice** [putyourlightson/craft-sprig#39]
### Describe the bug
I'm returning search results with your awesome Sprig plugin, but if I paginate results the pagination URLS that craft renders for prevUrl, currentPage, and nextUrl return the path for /actions/sprig/components/render

Screenshots follow, I hope this helps. 

Also, pasted /_components/search in below

### Versions
- Plugin version: Sprig 1.0.0-beta.17
- Craft version: 3.5.11

SCREENSHOT
https://pasteboard.co/Jvn00dU.jpg

CODE
https://pastebin.pl/view/0b2026c2

**Comment by bencroker** [comment]
You'll need to create your own pagination using `offset` and `limit`. There is a recipe in the cookbook that does exactly that:
https://putyourlightson.com/sprig-cookbook#pagination

**Comment by petenice** [comment]
Thanks

**Comment by bencroker** [comment]
FYI a new [sprig.paginate](https://putyourlightson.com/plugins/sprig#sprig.paginateelementquery) function has been added in 1.1.0.
