### ISSUE TITLE
Sprig error on multisite

### ISSUE THREAD

**Issue by heychicochico** [putyourlightson/craft-sprig#390]
### Support Request

Hello,
I followed the tutorial to build a sprig board, but I ran into two issues.

I was trying to build it on backstage.mydomain.com but none of the sprig elements work and I get this error message:
`htmx:invalidPath           htmx.min.js?v=1726070015:1`
`w @ htmx.min.js?v=1726070015:1
 de @ htmx.min.js?v=1726070015:1
 fe @ htmx.min.js?v=1726070015:1
 he @ htmx.min.js?v=1726070015:1
 (anonymous) @ htmx.min.js?v=1726070015:1
 i @ htmx.min.js?v=1726070015:1`
 
 I set up the same page on the primary domain and sprig works as it should.

The second issue is that on both my primary and backstage domain have this error:
`htmx:invalidPath           htmx.min.js?v=1726070015:1`
`w @ htmx.min.js?v=1726070015:1
  de @ htmx.min.js?v=1726070015:1
  fe @ htmx.min.js?v=1726070015:1
  he @ htmx.min.js?v=1726070015:1
  (anonymous) @ htmx.min.js?v=1726070015:1
  i @ htmx.min.js?v=1726070015:1`

Even with the error, sprig works on the primary site but not on backstage.

Craft 4.12.1 (waiting for a bugfix to upgrade to 5)
Sprig 2.13.0

Thanks!

### Plugin Version

2.13.0

**Comment by bencroker** [comment]
It sounds like the requesting domain is different from the target domain, which is disallowed by htmx. Can you show me the network tab in the browser console for the request in question, as well as some more details about the development environment you’re using?

**Comment by heychicochico** [comment]
I'm using ddev
![image](https://github.com/user-attachments/assets/aefa1198-28fa-4e16-8afe-7d9a1de3fe5e)

**Comment by bencroker** [comment]
Are there any details shown when you expand those two console errors?

**Comment by heychicochico** [comment]
![image](https://github.com/user-attachments/assets/73a4c514-93c5-48a9-af56-169fc3fe8397)

**Comment by heychicochico** [comment]
both point this spot:
![image](https://github.com/user-attachments/assets/4a795356-0512-4208-bf63-5b9929bcb6f7)

**Comment by bencroker** [comment]
Thanks, it turns out that doesn’t give much insight into the issue. 

Can you please take a look at the HTML source code and check the value of the `data-hx-get` attribute on the `div` element representing the Sprig component? If the domain is different to the domain that the browser is displaying in any way then that would explain the issue. What commonly causes this is explicitly setting the `@web` alias or setting the [`CRAFT_WEB_URL`](https://craftcms.com/docs/5.x/reference/config/bootstrap.html#craft-web-url) environment variable. Please check if either of those have been defined and, if so, remove them and allow Craft to determine the web URL itself.

**Comment by heychicochico** [comment]
Hi Ben, I removed the `@web alias` and now sprig works on the backstage site. Thanks for that!

Do you know any implications for removing it? I don't believe we're calling `@web` anywhere. It just shows up here:
![image](https://github.com/user-attachments/assets/2bd2e39b-e53c-4422-b7a6-8bad5debc85b)

Also, the first error is still kicking around, but again, sprig still functions.
![image](https://github.com/user-attachments/assets/2b3312ce-7120-458b-a975-45d39f36f40d)

Additionally

**Comment by bencroker** [comment]
Glad to hear it!

I already have a bug report open for that in https://github.com/craftcms/cms/issues/15739.

I’m not sure what the syntax error is about but it seems unrelated.
