### ISSUE TITLE
Getting an error that I've never seen. Just updated to craft v4

### ISSUE THREAD

**Issue by brianhorace** [putyourlightson/craft-sprig#391]
### Bug Report

I'm seeing this error since upgrading to craft 4:

Twig Runtime Error – [Twig\Error\RuntimeError](http://twig.sensiolabs.org/api/2.x/Twig/Error/RuntimeError.html)
Neither the property "script" nor one of the methods "script()", "getscript()"/"isscript()"/"hasscript()" or "__call()" exist and have public access in class "putyourlightson\sprig\variables\SprigVariable".

<img width="1512" alt="Screenshot 2024-09-16 at 10 22 18 PM" src="https://github.com/user-attachments/assets/485f123c-ea72-4187-90f7-f75171b51d20">

### Plugin Version

2.13.0

### Craft CMS Version

4.12.1

### PHP Version

8.3

**Comment by bencroker** [comment]
Thanks for the report! The `sprig.script` tag was deprecated in Sprig 2.6.0, but was inadvertently removed in a recent version. 

I’ve reverted the removal in Sprig Core [2.12.2](https://github.com/putyourlightson/craft-sprig-core/releases/tag/2.12.2), but you should ideally remove it from your template code as it is no longer required.
