### ISSUE TITLE
`The file or directory to be published does not exist` error

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-sprig#392]
### Bug Report

I don't think this is a bug, but maybe rather something odd happening in my setup. I've started noticing this regularly in my error logs:

```
The file or directory to be published does not exist: /home/vendor/putyourlightson/craft-sprig-core/src/resources/lib/htmx/2.0.1
```

I've tried running `composer update` in case it's out of date dependencies, but it persists. I have sprig-core 3.5.1 in my `composer.lock`.

`ComponentsService.php` also lists the correct version: `public const HTMX_VERSION = '2.0.2';`

I've cleared caches and so I'm confused where to look next. Any thoughts?

### Plugin Version

3.5.0

### Craft CMS Version

5.4.4

**Comment by bencroker** [comment]
If the htmx version constant says `2.0.2` but the file that cannot be found is `2.0.1` then it really must be a caching issue. I don't see any other explanation.

**Comment by shifuma** [comment]
Thanks Ben, I'll keep digging.

**Comment by lbriet** [comment]
We've been running into this issue sporadically for a long time too. After getting many alert notifications this last weekend across a couple of projects, dug a bit deeper:

The request context on these errors points to the `htmx.min.js` script, loaded from `cpresources`. E.g.:

```
"REQUEST_URI":"/cpresources/1f967182/htmx.min.js?v=1738314972",
```
When visiting our websites' front-end, that JS script gets cached in browser. The `htmx()` function within that script defines a `Q` constant which specifies a specific htmx version (currently 2.0.4). 

If I were to visit the website in the future, after we've run dependency updates, that script will presumably still be served from disk cache and expect the now outdated version to be present. Hence, the error. This would explain why we've been seeing them sporadically, across various projects, and for different htmx versions too.

I suppose this is something we can only adjust through our own webserver config? I.e. telling Nginx to never cache the `htmx.min.js` script?

(Perhaps relevant too, our server configs are generally based on nystudio107's blueprints [here](https://github.com/nystudio107/nginx-craft/blob/master/sites-available/somedomain.com.conf))

**Comment by bencroker** [comment]
It sounds like the URI to the stale resource is being cached in your templates or in a static cache on the server (or in a CDN). Do you run any commands to clear the cache updater running Craft plugin updates?

**Comment by lbriet** [comment]
During deployment, we create a new 'build' which runs `composer install` followed by (amongst others) `php craft clear-caches/all` indeed.

Following news shared in the CraftCMS Discord, we _did_ deploy new builds across all projects on Friday - that must explain the influx of errors. We don't have any specific caching mechanisms in place on these projects (a single one on Cloudflare, but it reported the lowest number of errors too) though.

Could these all have been users who had the website open on their device, and, by chance, revisited it post-deployment? 🤔

If so, then perhaps the follow-up question becomes - is there anything we can do to prevent these errors? 

Remains a strange one - we _have_ been seeing these errors regularly, not just immediately following new builds, for different htmx versions too (1.9.9, 2.0.1, 2.0.2, and now this weekend 2.0.3)..

**Comment by bencroker** [comment]
This still sounds like a caching issue, OPCache perhaps? Users visiting the site post-deployment should get the latest template render, which will include the latest htmx version.

**Comment by MatthiasBrodelet** [comment]
I also have this issue.
This error gets logged 337 times for 60 users in the last 7 days.
We obviously do not cache any sprig related templates.
If cache was the issue then all users would have this issue I guess.

What confuses me is how the server knows that a specific URL like `https://www.my-domain:80/cpresources/bd398b4c/htmx.min.js` requests a specific htmx version like 2.0.3?

`The file or directory to be published does not exist: /var/web/vd30621/public_html/vendor/putyourlightson/craft-sprig-core/src/resources/lib/htmx/2.0.3`

Nothing in either the vendor folder or the main project references this version number.
The current referenced version is 2.0.7.
Weirdly enough it does not seem like this is an actual issue for the visitors.
But I might be wrong of course. I might just not have run into the issue myself and visitors are maybe just not complaining.

**Comment by bencroker** [comment]
> What confuses me is how the server knows that a specific URL like `https://www.my-domain:80/cpresources/bd398b4c/htmx.min.js` requests a specific htmx version like 2.0.3?

That is a Craft/Yii feature, in which published assets are written to hashed folder names in the `cpresources` directory.
