### ISSUE TITLE
Duplicate search fields not working with Craft Cloud - htmx:targetError

### ISSUE THREAD

**Issue by bryandugan** [putyourlightson/craft-sprig#394]
### Bug Report

I've run across an issue where duplicate filters are throwing errors on Craft Cloud. I'm trying to build a desktop/mobile search with Craft Cloud, with the search fields showing/hiding depending on the on viewport size. The code I have works on my local ddev instance, but doesn't work on the Craft Cloud prod server.

I've talked this over with the Craft team and we narrowed it down to Craft Cloud is a little more strict than ddev with the way it's handling the code with Bref.

In Sprig Playground, I have modified the default search and duplicated the search field, and applied the changes from the dealing with duplicate filters using JS section of the Sprig training video here:
https://putyourlightson.com/sprig/training

When I run the code with both fields, both fields are stuck loading with htmx error, and when I remove one of the fields, the search is able to display results.

Example code:

```
{# Sets a default value if not defined #}
{% set query = query ?? '' %}
{% set search = search ?? '' %}


<input sprig s-replace="#results" s-trigger="keyup changed delay:400ms" s-on:keyup="htmx.find('#searchMobile').value = this.value" id="searchDesktop" name="search" value="{{ search }}" placeholder="Search terms" class="w-full rounded-full px-4 pl-10 py-2 border-slate-500 border">

<input sprig s-replace="#results" s-trigger="keyup changed delay:400ms" s-on:keyup="htmx.find('#searchDesktop').value = this.value" id="searchMobile" name="search" value="{{ search }}" placeholder="Search terms" class="w-full rounded-full px-4 pl-10 py-2 border-slate-500 border">

<div id="results">
    {% if query %}
        {% set entries = craft.entries.search(query).all() %}
        {% if entries|length %}
            {% for entry in entries %}
                <h2>{{ entry.title }}</h2>
            {% endfor %}
        {% else %}
                No results
        {% endif %}
    {% endif %}
</div>
```

### Plugin Version

3.5.0

### Craft CMS Version

5.4.6

### PHP Version

8.2.22

**Comment by bencroker** [comment]
This sounds like a bug in Craft Cloud, not in Sprig. To work around it, you’ll need to ensure your code only contains a single input field with the `name="search"`. I imagine something like this should work, in which only the desktop search field is sprigified, which the mobile search field triggers a `keyup` on the desktop version.

```twig
<input 
    sprig 
    s-replace="#results" 
    s-trigger="keyup changed delay:400ms" 
    s-on:keyup="htmx.find('#searchMobile').value = this.value" 
    id="searchDesktop" 
    name="search" 
    value="{{ search }}" 
    placeholder="Search terms" 
    class="w-full rounded-full px-4 pl-10 py-2 border-slate-500 border"
>

<input 
    s-on:keyup="htmx.find('#searchDesktop').value = this.value; htmx.trigger('#searchDesktop', 'keyup')" 
    id="searchMobile" 
    value="{{ search }}" 
    placeholder="Search terms" 
    class="w-full rounded-full px-4 pl-10 py-2 border-slate-500 border"
>
```

**Comment by bryandugan** [comment]
Thanks, Ben. That workaround seemed to do the trick! I'll forward this over to the Craft team if it may help them figure out what the bug could be on their end.
