### ISSUE TITLE
selfRequestsOnly or no @web alias

### ISSUE THREAD

**Issue by svondervoort** [putyourlightson/craft-sprig#395]
### Support Request

We have multiple Craft sites that have a Multidomein setup. One of the issues is that Sprig does requests to the "primary site".

Recently a colleague fond a solution to this issue by setting the following meta tag:
```<meta name="htmx-config" content='{"selfRequestsOnly": false}' />```

But I know there is also another solution by not setting the `@web` allias to the `$PRIMARY_SITE_URL` from the `.env` file.

Now we are just not sure what the best approach is in your opinion and would like your point of view on this.

**Comment by bencroker** [comment]
The right solution is to not define `@web`. Disabling `selfRequestsOnly` could be considered a security risk and should be avoided unless absolutely necessary.

**Comment by svondervoort** [comment]
Thanks for the insight!
