### ISSUE TITLE
DIY widget

### ISSUE THREAD

**Issue by spotd** [putyourlightson/craft-sprig#396]
### Support Request

Would like an assist getting sprig live in diy-widget templates (where standard twig is alive and well) -> https://github.com/carlcs/craft-diywidget
This didnt seem to get sprig going -> https://putyourlightson.com/plugins/sprig#control-panel-usage
Any pointers?

**Comment by bencroker** [comment]
I can take a look at some source code, if you can provide it?

**Comment by bencroker** [comment]
Closing due to lack of response.

**Comment by spotd** [comment]
Apologies, as went on holiday. But so you know he has now added support for sprig - https://github.com/carlcs/craft-diywidget. is working nicely together

**Comment by bencroker** [comment]
Glad to hear it!
