### ISSUE TITLE
Blitz Cache and Sprig Query Params

### ISSUE THREAD

**Issue by svondervoort** [putyourlightson/craft-sprig#397]
### Support Request

We are using **Sprig** in combination with **Blitz Cache** and noticed when caching a page with a Sprig include the sprig component does not pick up any of the query params in the URL.

The Sprig include code is:
```
{{ sprig('_pages/search-page/partials/index/sprig/results.twig', {}, {'s-trigger': 'load, refresh'}) }}
```

Even stranger is that when we try to change any of the query params it forces/redirects you back to the cached version (with different query params) of that page. This does not happen when Blitz Cache is disabled.

We are not sure if this is a configuration issue on our side or maybe a misunderstanding.

Here is a link to a video showcasing the scenario above: https://vimeo.com/1019780072/5d0a251c31

#### Application Info

- PHP version: 8.3.11
- Craft edition & version: Pro 5.4.7.1
- Database driver & version: MariaDB 10.10.7

#### Installed Plugins

- Blitz: 5.9.0
- CKEditor: 4.2.0
- Embedded Assets: 5.1.2
- Environment Label: 5.0.0
- Formie: 3.0.8
- Laméco Blitz: 5.0.0
- Navigation: 3.0.4
- Smith: 3.1.0
- Sprig: 3.5.0
- Vite: 5.0.1

### Plugin Version

3.5.0

**Comment by bencroker** [comment]
What is the `Query String Caching` plugin setting set to? And do you have any redirect tags in your Sprig component?

**Comment by svondervoort** [comment]
The `Query String Caching` setting is set to "Cache URLs with unique query strings as unique pages" which makes it kind of weird. And we don't have redirect tags inside the Sprig component.

**Comment by bencroker** [comment]
Are you using [server rewrites](https://putyourlightson.com/plugins/blitz#server-rewrites) and, if so, have you added the correct rewrite for `Cache URLs with query strings as unique pages`?

**Comment by svondervoort** [comment]
I checked and can confirm we are using the first of the NGINX server rewrites with the `$args`.
The video is of a local environment, but this also happens on the staging environment.

**Comment by bencroker** [comment]
So I’m not sure why the redirect is happening, but in general I think it’s a bad idea to cache search results as it can result in the cache store being flooded with both legitimate search queries and spam queries. I realise this doesn’t fully answer your question, but would excluding the search results page from being caching should resolve this for you?

**Comment by svondervoort** [comment]
Yes thats what we did in the end, exclude the pages that have the queries because of the reason you are describing.
Thanks anyway for try to figure it out :)
