### ISSUE TITLE
Improve Sprig documentation

### ISSUE THREAD

**Issue by funkysoul** [putyourlightson/craft-sprig#398]
### Which section of the documentation or concept needs improving and why?
there are a bunch of template vars that have been deprecated you know best which ;-) 
I noticed it while looking at an older Project which used sprig.isRequest and sprig.isError

### Your suggestions for how to better explain this section or concept.

Would be nice to either update accordingly and maybe also offer examples for alternative methods that could be used.

**Comment by bencroker** [comment]
All deprecations should be documented in the [changelog](https://github.com/putyourlightson/craft-sprig/blob/develop/CHANGELOG.md) (also the [v2 changelog](https://github.com/putyourlightson/craft-sprig/blob/2.x/CHANGELOG.md)). 
Let me know if anything is missing and I’ll be sure to fill in the gaps.

**Comment by funkysoul** [comment]
well for example here? :-) 
https://putyourlightson.com/plugins/sprig#template-variables

**Comment by bencroker** [comment]
[`sprig.script`](https://putyourlightson.com/plugins/sprig#sprig-script) is documented as deprecated, otherwise everything in the docs should be current. Did I miss any?

**Comment by funkysoul** [comment]
isn't sprig.isError deprecated too?

**Comment by bencroker** [comment]
No. `sprig.getIsError` was deprecated in favour of `sprig.isError`, however I believe I saw that PhpStorm’s Symfony plugin gets confused and marks `sprig.getIsError` as deprecated. Is that what you’re seeing?

**Comment by funkysoul** [comment]
Yes, PhpStorm is also showing it as deprecated. 
ah and I just noticed what i got wrong on your changelog.. (the USE word goes under all the various properties. :-/ (my bad)
