### ISSUE TITLE
No results on Live Search when specifying an Element Query for section

### ISSUE THREAD

**Issue by nfq** [putyourlightson/craft-sprig#4]
If I specify a section or sections in the query, no results are found when searching.

This is the included code:
```
<div class="search-form">
	{{ sprig('_shared/components/search/results', {
		query: craft.app.request.getParam('query'),
	}) }}
</div>
```

And the component itself:

```
{% set query = query ?? '' %}

{% if sprig.include %}
	<input sprig s-trigger="keyup changed" s-target="#search-results" s-swap="outerHTML"
		type="text" s-indicator=".htmx-indicator" name="query" value="{{ query }}" type="search" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="search-input font-sans"
	>
{% endif %}

<div id="search-results">
	{% if query %}
	{% set entries = craft.entries()
		.section(['pages', 'news'])
		.search(query)
		.orderBy('score')
		.limit(20)
		.all()
	%}
		{% if entries|length %}
			{% for entry in entries %}
				{{ entry.url }}
				<a href="{{ entry.url }}" class="mx-10">{{ entry.title }}</a><br>
			{% endfor %}
		{% else %}
			No results
		{% endif %}
	{% endif %}
	<span class="htmx-indicator">Searching...</span>
</div>
```

**Comment by nfq** [comment]
Importantly, using `{{ entry.url }}` doesn't render anything either. `entry.title` does.

**Comment by bencroker** [comment]
Sounds like your entries might not have URLs?

**Comment by nfq** [comment]
How would they not? I mean, they show using a basic Craft search.

**Comment by bencroker** [comment]
I'm just going by your earlier comment that the `entry.title` renders correctly, or did I misunderstand that?

> Importantly, using {{ entry.url }} doesn't render anything either. entry.title does.

**Comment by nfq** [comment]
First and most relevant issue is that Pages and News entries aren't being found.

**Comment by nfq** [comment]
> I'm just going by your earlier comment that the `entry.title` renders correctly, or did I misunderstand that?
> 
> > Importantly, using {{ entry.url }} doesn't render anything either. entry.title does.

If I do
```
{% set entries = craft.entries()
	.search(query)
	.orderBy('score')
	.limit(20)
	.all()
%}
```

It finds every entry. And then the Title renders. But even then, the url does't.

**Comment by bencroker** [comment]
Can you try stripping your code down to the bare minimum and build it up from there? I'm not seeing anything obvious with the code and don't know your Craft setup so can't be of much more help at this stage.

**Comment by nfq** [comment]
ok, I did already. I'll try again. As for the actually query, what should I strip off it?

**Comment by nfq** [comment]
I imagine this is the bare minimum I'll need:
```
{% set entries = craft.entries()
	.section(['pages', 'news'])
	.search(query)
	.all()
%}
```
?

**Comment by bencroker** [comment]
Well start with `{% set entries = craft.entries.all() %}` and build up from there I guess.

**Comment by nfq** [comment]
Yes, I actually already tried that. All entries are then found. It's only when I add `.section(['pages', 'news'])` that no results are found.

**Comment by bencroker** [comment]
What about `.section('pages, news')`?

**Comment by nfq** [comment]
Same, 'No results'

**Comment by nfq** [comment]
The  Entry URI Format for 'pages' is `{parent.uri}/{slug}`.

**Comment by bencroker** [comment]
But it works in a normal template without Sprig? 
Can you share a link to a page on which it is working and not working? 
Sprig beta.5?

You can see a working example here:
https://putyourlightson.com/sprig-cookbook#search

**Comment by bencroker** [comment]
Is this still an issue for you using the latest version of Sprig?

**Comment by nfq** [comment]
Hi Ben,

I haven't actually tried the latest version yet. I ended up abandoning the Sprig approach and using Element API with an autocomplete.js plugin. But I'd be happy to test again.

**Comment by bencroker** [comment]
The example at https://putyourlightson.com/sprig-cookbook#search should get you there as is, if not then post a stripped down version of your code here and I'll take a closer look.
