### ISSUE TITLE
Pagination not working, when using browser "back"

### ISSUE THREAD

**Issue by vandres** [putyourlightson/craft-sprig#400]
### Bug Report

We've implemented the pagination example for ourself and it is working great, when using the navigation buttons or just when refreshing the page. But when using the browser back-arrow, we have some mixed behaviour.

It's reproducable on the Cookbook: https://putyourlightson.com/sprig/cookbook#pagination

1. Open the page
2. Press "Next"
3. Use back arrow
4. Press "Next"
5. Use back arrow

### Plugin Version

2.7.3

### Craft CMS Version

4.7.2

### PHP Version

8.2.x

**Comment by bencroker** [comment]
What is the exact behaviour you’re seeing that might be a bug?

**Comment by vandres** [comment]
Sorry. The first page is

```
Blitz
Campaign
Sherlock
```

When following the reproduction, the result is 

```
Cache Igniter
Sprig
Snaptcha
```

That is page two. So when going from url `?page=2` to the page without the page parameter, the page is not updated correctly.

**Comment by vandres** [comment]
I am using latest Firefox.

**Comment by bencroker** [comment]
My guess is that this is a limitation of htmx, which snapshots each version of the history. Going back, then proceeding might be throwing off subsequent back actions, but you’ have to ask in the htmx [repo](https://github.com/bigskysoftware/htmx/issues) or [Discord server](https://htmx.org/discord) for a more complete answer.
