### ISSUE TITLE
Browser history back and forward breaks history

### ISSUE THREAD

**Issue by pimago** [putyourlightson/craft-sprig#401]
### Bug Report

Hi Ben, I am not 100% sure if am facing the same issue as https://github.com/putyourlightson/craft-sprig/issues/400

My problem is happening with this part where a sprig component loads a new entry into another component. https://github.com/putyourlightson/craft-sprig/issues/209

When I load an entry, I can go back with the browser’s back button, no problem.
But when I load an entry a second time after I went back, the back button only changes the url but leaves my container with the entry open. So if load something new after I went back once, the history gets mixed up.

Another strange thing is, when the debug tool bar is activated I cannot go back from my overlay without getting an 500 error and the toolbar disappears. It's saying a variable is null. If remove that part I get a 404 error and it says there is and error in simple HTML line.

Am I facing the same Issue here. Or could I fix the history somehow?

### Plugin Version

3.5.1

### Craft CMS Version

5.4.9

### PHP Version

8.3.8

**Comment by bencroker** [comment]
This sounds exactly like the same issue as #400. htmx does its best to seamlessly snapshot history, but going back and forwards appears to throw it off, unfortunately.

**Comment by pimago** [comment]
Thanks for confirming!

**Comment by pimago** [comment]
Hi Ben,

while trying to find a solution I realized I cannot even go one step back. I get the 404 error in the console because it's trying to open /null however it is going back to the correct page.

What I am doing is loading a component that loads a new entry. This component has '{% do sprig.pushUrl(siteUrl~'projects/'~entry.id) %}'. If I remove pushUrl I can go back without an error, but then I am of course one page too much back in history.

**Comment by bencroker** [comment]
Can’t you wrap the `sprig.pushUrl` statement in a conditional, so that it is only executed if an entry ID exists?

**Comment by pimago** [comment]
I have a conditional around it. Loading the component with the sprig.pushUrl is working (I guess). Going with the browser back button, and removing that component, is the problem.

**Comment by bencroker** [comment]
Unfortunately this appears to be a htmx issue, so there’s nothing that Sprig can do about it.

**Comment by pimago** [comment]
That’s odd. What is pushUrl used for then, when it‘s not possible to go back the history entry it creates? I still feel like I am doing something wrong.

**Comment by bencroker** [comment]
It should push an entry to the browser’s session history stack using [pushState()](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState), but you’ll get more details asking in a htmx support channel.
