### ISSUE TITLE
Submitted Data was Tampered

### ISSUE THREAD

**Issue by funkysoul** [putyourlightson/craft-sprig#402]
### Support Request

Hi Ben, Im having a little issue with my sprig form, and for the love of life, i can't find out where the issue really is. 

I have a Form: 

`<form sprig s-method="post" s-action="bmw-integrations/order-controller/save">
        {{ csrfInput() }}
        <input type="hidden" name="sectionId" value="5">
        <input type="hidden" name="typeId" value="5">
        <input type="hidden" name="orderStatus" value="inProgress">
        <input type="hidden" name="currentUserId" value="14">
        <input type="hidden" name="title" value="{{ "Order from: " ~ random() }}">
        <input type="submit" value="Place Order" class="btn">
    </form>`
    
and here the controller (enabled, plugged into a module)

    
    ` public function actionSave(): Response
    {
        $request = Craft::$app->getRequest();
        // create an order entry
        $entry = new \craft\elements\Entry();
        $entry->sectionId = $request->post('sectionId');
        $entry->typeId = $request->post('typeId');
        $entry->authorId = $request->post('currentUserId');
        $entry->title = $request->post('title');
        $entry->setFieldValue('orderStatus', $request->post('orderStatus'));
        $entry->setFieldValue('userselector', [14]);

        try {
            Craft::$app->elements->saveElement($entry);
        } catch (ElementNotFoundException $e) {
            var_dump($e);
        } catch (Exception $e) {
            var_dump($e);
        } catch (\Throwable $e) {
            var_dump($e);
        }

        $message = new Message();
        $message->setTo('recipient@example.com');
        $message->setFrom('test@example.com');
        $message->setSubject('New Order Received');
        $message->setTextBody('test');

        // send the email
        Craft::$app->mailer->send($message);

        /*return $this->asJson(['message' => 'Howdy!']);*/
    }`

To the problem: my entry is created, thats fine, the email is sent, also fine. but I constantly see the message "Submitted data was tampered." in the debug bar. So clearly i'm doing something wrong. 
Currently I don't even know where to look for clues what exactly could be the issue. 
Thanks for your help!
    
Best Regards,
Tiago 

### Plugin Version

3.5.1

**Comment by bencroker** [comment]
Which debug bar, exactly? Can you show me what you're seeing?

**Comment by bencroker** [comment]
Note also that your controller action should be returning a generic success response, rather than a JSON response.

```php
return $this->asSuccess(['message' => 'Howdy!']);
```

**Comment by funkysoul** [comment]
I meant the Craft Debug Toolbar. 
anyhow.. the return asSuccess did the trick apparently.  not getting any error messages. thanks Ben!

**Comment by bencroker** [comment]
Glad to hear it!
