### ISSUE TITLE
Multisite rendering wrong URL's?

### ISSUE THREAD

**Issue by kevinmu17** [putyourlightson/craft-sprig#403]
### Support Request

I have a multisite setup with 2 domains. DomainA.com and domainB.com. When loading a sprig component on domainB.com it's rendering domainA.com.
for example when using `s-action="contact-form/send"` it's rendering `https://domainA.com/index.php?p=actions/sprig-core/components/render`

am i missing something here??

### Plugin Version

2.13.1

**Comment by bencroker** [comment]
That is expected behaviour. All Sprig requests go through the Sprig endpoint. On the backend, Sprig will run the action with the route `contact-form/send`.

**Comment by kevinmu17** [comment]
Why is this expected? When i'm viewing site domainB i expect it to render the data-hx-get with domainB and not domainA. This is throwing endless CORS issues

**Comment by bencroker** [comment]
I apologise, I misread the issue. It sounds like you may have defined the `@web` [alias](https://craftcms.com/docs/5.x/configure.html#aliases) (or [`CRAFT_WEB_URL`](https://craftcms.com/docs/5.x/reference/config/bootstrap.html#craft-web-url) environment variable). This is recommended against in Craft and is likely causing the issue. Check the [Blitz diagnostics utility](https://putyourlightson.com/plugins/blitz#diagnostics-utility) (assuming you have have Blitz installed) to see what it says about the `@web` alias.

**Comment by kevinmu17** [comment]
Thanks for the quick response!

diagnostics utility says:
The [@web](https://craftcms.com/docs/4.x/config/#aliases) alias is explicitly defined.

In my general.php:
`'@web' => App::env('PRIMARY_SITE_URL'),`

FYI: craft cms version 4.10.5

**Comment by bencroker** [comment]
Exactly, that’s the problem. You should allow Craft to determine the `@web` alias based on the current URL instead.

**Comment by kevinmu17** [comment]
Ah thanks! removed the alias + the env CRAFT_WEB_URL and now it's working! Thanks for the quick help!

**Comment by bencroker** [comment]
Glad to hear it!
