### ISSUE TITLE
Button Redirect Not Working

### ISSUE THREAD

**Issue by wbdzynr** [putyourlightson/craft-sprig#406]
### Bug Report

We just updated a site from Craft 4.x to Craft 5.x.  Our button redirects are working on the Craft 4 site, but not the Craft 5 site.

Here is the code for the button
`<li class="nav-item{% if segment3 == 'choose-documents' %} active{% endif %}"><button type="submit"  class="btn btn-sidebar-menu" sprig s-method="post" s-action="entries/save-entry" s-indicator="#indicator" s-val:buttonRedirect="/interview/getting-started/choose-documents">Choose Documents</button></li>`

This is at the top of the template
```
{% if success is defined and success %}
	{% do sprig.redirect(buttonRedirect) %}
{% elseif sprig.isError %}
	{% if errors is defined %}
		{% for error in errors %}
			<p class="error">{{ error|first }}</p>
		{% endfor %}
	{% endif %} 
{% endif %}
```

When I run the inspector (Firefox Developer) and go to Network, the Craft 4 site shows a sprig action after the render, while the Craft 5 site does not (see screenshot). However, when I look at the Console for the Craft 5 site, it shows the correct values (see screenshot) 
<img width="1089" alt="Craft 5 Sprig Console" src="https://github.com/user-attachments/assets/4962c14d-f0be-4ae8-bf44-827ea558f942">
<img width="1387" alt="Craft 4 vs 5 Sprig Redirect" src="https://github.com/user-attachments/assets/cb5916c1-bc97-4d6a-96ad-239d124c7218">

### Plugin Version

3.5.1

### Craft CMS Version

Craft Pro 5.5.5

### PHP Version

8.2.15

**Comment by bencroker** [comment]
What response does the POST request give? Is it a 200 status code, and what does the response body look like?

**Comment by wbdzynr** [comment]
Post request is 200 status code.  But as the image shows, the "File" is different between Craft 4 and Craft 5.  The response body just shows the existing page that I was on.  The headers show the current page as the HX-Current-URL and the Referer.  The HX-Target just shows "component-lqhhal".  And per the attachment, the buttonRedirect is correctly showing the page it should go to.

**Comment by bencroker** [comment]
Can you test using this?

```twig
{% if sprig.isSuccess %}
    {% do sprig.redirect(buttonRedirect) %}
{% elseif sprig.isError %}
    ERROR:
    ...
{% else %}
    NOTHING
{% endif %}

**Comment by wbdzynr** [comment]
That was it!  Everything is working now as expected.  Thanks Ben!

**Comment by bencroker** [comment]
Great!
