### ISSUE TITLE
sprig.swabOob vs sprig.triggerRefresh?

### ISSUE THREAD

**Issue by robzor** [putyourlightson/craft-sprig#407]
### Support Request

Hi Ben,

I've watched the excellent livestream about these 2 function (I hadn't realised they had been added for all this time!) but I can't really work out why I would use one over the other? It seems that `swapOob` is the 'best one' as it only creates one request, so in my head, it's 'better'.

In my situation I have a product page, a checkout and a basket page that all have multiple sprig components, although the communication is normally one way, e.g.

product page: product added to cart - > update basket price in header sprig component
basket page: product quantity changed -> update basket price in header sprig component + update basket price in 'in page' sprig component

So I guess, the short version of my question is: 

What are the pros and cons of each function?

Thanks!

P.S. (This site is on Craft 4)

### Plugin Version

4.23.9

**Comment by bencroker** [comment]
I discussed the differences in the livestream and am not sure what part is unclear. It’s not a question of pros and cons, it’s more a question of which is appropriate for what you’re trying to do. In your case, it sounds like `swapOob()` would be the more appropriate and optimal approach.

**Comment by robzor** [comment]
Hi Ben, 

Thanks for your reply. I have watched the livestream twice, but in my noob-ishness I am failing to understand the use cases for one vs the other (rather than a pros/cons list, I guess). In the livestream you use both methods to achieve the same result (although you do a nice thing with the basket total var in the `swapOob` example, but that appears to also be possible with the `triggerRefresh` example as they both accept variables)

In the short term, I have refactored the places where I was using `htmx.trigger` to now use `triggerRefresh` but yeah, I guess my question would be:

When would you want to use `triggerRefresh`, when would you want to use `swapOob`? 

Because in the livestream it appears that swapOob is 'better' as it uses less requests, but I do not possess the knowledge to work out if there are any 'risks' or 'considerations' to be made when choosing which method to use over the other one.

Apologies for the rambling message, just genuinely interested in it :)

**Comment by bencroker** [comment]
If you explicitly need a Sprig component to refresh itself, use `triggerRefresh()`. If it is enough to simply swap out the DOM, use `swapOob()`.

**Comment by robzor** [comment]
Beautiful. That's what my janky brain was looking for. Thanks Ben!
