### ISSUE TITLE
Spring mangles non-standard html attrs (like Alpine's @ handlers) 

### ISSUE THREAD

**Issue by timkelty** [putyourlightson/craft-sprig#41]
Something like this works fine in normal twig, but when it is in a Sprig component, it chokes on it.

```<button @click="open = false;">```

In this case, it will actually render

```
<button false><button>
```

**Comment by bencroker** [comment]
Sprig parses the HTML tags in components using [HTML5DOMDocument](https://github.com/ivopetkov/html5-dom-document-php) and it is getting tripped up by the invalid HTML attribute `@click`. I'm not sure how to best work around this as using regular expressions is not a realistic option. My suggestion would be to use Alpine's full syntax. 

```html
<button x-on:click="open = false;">
```

**Comment by timkelty** [comment]
Thanks ben! that's what I ended up doing – just wanted to make the issue in case someone else ran into it.

**Comment by bencroker** [comment]
Yup, thanks Tim! It's kind of unfortunate that VueJS and AlpineJS have popularised invalid HTML attributes.
