### ISSUE TITLE
Inter component communication

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-sprig#44]
Hello Ben,

I'm working on a listing of entries that is encapsulated in a component. I have a second component that is a list of filters. Both live in individual twig files.

I now would like to have the filters component send the currently active filter(s) to the listing component so that it updates the listing accordingly.

I saw the "refreshing components" example in the Sprig cookbook, but I do not know how to pass a value(s) along. I guess I have to use "_hyperscript" for that to work? Do you have suggestion how to pass the parameters into the listing (and refresh it)?

Thank you very much.

**Comment by bencroker** [comment]
It sounds like ideally you'd have both the filter and listing in the same component, is there something preventing you from doing that?

**Comment by ghost** [comment]
No Ben, that's what I do right now. The filter has the results as a child. I'm just trying to dig deeper of what's possible out of the box and where the current limitations are.

**Comment by bencroker** [comment]
In that case, take a look at the [s-swap-oob](https://putyourlightson.com/plugins/sprig#s-swap-oob) attribute, which would allow you to inject an input field into another part of the DOM, essentially passing a new variable into another component.

**Comment by ghost** [comment]
Yes I was eye balling this already. Thank you very much for the tip Ben! 

Thank you for reaching 1.0 🏆
