### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by rauwebieten** [putyourlightson/craft-sprig#45]
I tried to listen for some events, like this:

    document.body.addEventListener('htmx:beforeRequest', function(evt) {
        console.log('htmx:beforeRequest');
    });

    document.body.addEventListener('htmx:afterRequest', function(evt) {
        console.log('htmx:afterRequest');
    });

    document.body.addEventListener('htmx:beforeOnLoad', function(evt) {
        console.log('htmx:beforeOnLoad');
    });

    document.body.addEventListener('htmx:afterOnLoad', function(evt) {
        console.log('htmx:afterOnLoad');
    });

But only beforeRequest and beforeOnLoad are triggered. 

I am missing something?
Any idea?

**Comment by bencroker** [comment]
Sounds like this issue resurfacing: https://github.com/bigskysoftware/htmx/issues/79

Please create an issue in the htmx Github repo for this.
