### ISSUE TITLE
Trigger Javascript function when component has loaded

### ISSUE THREAD

**Issue by jamiematrix** [putyourlightson/craft-sprig#46]
I'll try to explain the use case as much as I can.

Using Sprig, I've 'upgraded' a page that used to build a bunch of (hidden) data in table rows on a page, and when a user clicked a button, a JavaScript function would grab the data and spit out a CSV file to download.

The data is coming from Craft Commerce Orders which (currently) is several thousand rows, and is likely to increase - this cause the page to take some time to fully load.

Sprig to the rescue! I've replaced the rows to use a component instead. Now the hidden data isn't fetched until the button is clicked - making the page load in seconds. The problem I have is when the button is clicked, the component updates with the hidden data (this works), but when the data is captured I want the JS function to be called. I wasn't sure which HTMX trigger would be used in this instance?

Pseudo code is as follows:
```
show the row of text 
show a button to download with a s-vars of download=true

if download=true
  build the hidden data
  trigger the download
endif
```

I assumed sticking some {% js %} tags in the component would mean when the component re-loads (with download set to true) the JS will be executed, but it's not.

**Comment by bencroker** [comment]
The `htmx:afterSwap` event should work for what you need. Put the JS code in the parent template as per the recipe at https://putyourlightson.com/sprig-cookbook#refreshing-components .

```html
<script>
htmx.on('htmx:afterSwap', function(event) {
    // trigger the download
});
</script>
```

**Comment by jamiematrix** [comment]
Thanks!
I have looked at the example, but think I'm making more trouble for myself. Because there are (currently) 12 rows of data (each row has a component), when the afterSwap gets called it gets called multiple times even though I can set each component individually. 

Another idea would be to set the XML to a single component, then have the component refresh with the required data when the corresponding button is clicked. Needs testing.

**Comment by bencroker** [comment]
You can give each component an ID and then just target one specific component.

```twig
{# Sets the `id` attribute on the component #}
{{ sprig('_components/row1', {}, {'id': 'row1'}) }}

<script>
document.getElementById('row1').addEventListener('htmx:afterSwap', function(event) {
    // trigger the download
});
</script>
```

**Comment by jamiematrix** [comment]
I've probably done something completely wrong, but the event listener is getting triggered multiple times - less times than there are components though e.g. I have 13 components (with different IDs) and the event listener (currently only console.logging) gets called 4 times.

**Comment by bencroker** [comment]
Your code?

**Comment by jamiematrix** [comment]
On the main page:
```
{% for event in craft.entries.section('eventEvents').level(1).orderBy('title asc').all() %}

                <div id="{{ event.slug|replace({'-':''}) }}" 
                    data-eventName="{{ event.title }}" 
                    class="event-parent">
                    {{ sprig('_components/slug', 
                        { "slug" : event.slug, "download": false},
                        { "id" : event.slug|replace({'-':''}) }
                    ) }}
                </div>

                <script>
                    document.getElementById('{{ event.slug|replace({'-':''}) }}').addEventListener('htmx:afterSwap', function(event) {
                        console.log(this.id);
                    });
                </script>
            {% endfor %}
            {{ sprig.script }}
```

slug component:
```
{% set eventQuery = craft.entries().section("eventEvents").level(1).slug(slug) %}
{% set event = eventQuery.one() %}

<div class="grid download-wrapper">
    <div class="col-6">
        {{ sprig.isRequest ? '' : event.title }}
    </div>
    <div class="col-6 button-wrapper">
        <button id="festibutton" class="button" sprig s-vars="download: true" s-target="this" s-swap="outerHTML">
            {{ sprig.isRequest ? "Downloading..." : "Download CSV" }}
        </button>        
    </div>
</div>
{% if sprig.isRequest %}
        {# build the XML data here #}
{% endif %}
```
Apologies for the potato code that VSCode has pasted in.

**Comment by bencroker** [comment]
That looks like it should work.

**Comment by jamiematrix** [comment]
I assumed it may have been too many sprig.isRequests, but I've just cut that down to one.

Also tried reducing the initial list of entries to 5, and it still calls the javascript 4 times.

**Comment by bencroker** [comment]
Test it with one component to help narrow the issue down. I could take a closer look but I'd need to have access to all of your templates, feel free to email me about such work at info@putyourlightson.net.

**Comment by jamiematrix** [comment]
Thanks. Will try cutting it down some more and go from there. You may get an email from me tomorrow ... maybe :)

**Comment by bencroker** [comment]
Good luck!

**Comment by jamiematrix** [comment]
Think I have it.
I've taken out the s-* attributes from the button after 'sprig' attribute and the JS is being called once. I guess having those in there are making the component reload/change too?

I'm now left with:
`<button id="festibutton" class="button" sprig>`
That's the only change to the component.

**Comment by bencroker** [comment]
Yeah that makes sense, you want the button to re-render the entire component, not just itself.
