### ISSUE TITLE
Bug/Enhancement - Incompatability with AlpineJS

### ISSUE THREAD

**Issue by stevenjwright** [putyourlightson/craft-sprig#47]
### Describe the bug
Trialling Sprig with a client site that's already using [AlpineJS](https://github.com/alpinejs/alpine). The two work alongside each other just fine until I add any AlpineJS within a Sprig Component, the `x-data`, `@click` etc. is stripped from the element. 

`x-data` declares the scope of the AlpineJS component (ie `x-data="{ foo: 'bar' }"`), `@click` attaches an event listener, but then when loading up the page, it seems Sprig/HTMX has removed all of this from within the component. 

_**Technically a bug, but I understand the two both serve similar purposes so it may be unrealistic to expect compatibility, figured I'd submit though just in case.**_

### To reproduce
1. Setup a file that uses both AlpineJS and a Sprig Component.
2. Add some AlpineJS to an element within the Spring Component. 
3. Load up the page. AlpineJS will now have been stripped from the component. 

### Expected behaviour
AlpineJS directives to remain intact in the DOM.

_Ps. thanks for an awesome plugin, Ben!_

**Comment by bencroker** [comment]
I've added a section to the docs that addresses compatibility with AlpineJS:
https://putyourlightson.com/plugins/sprig#javascript

Let me know if that solves it for you.

**Comment by stevenjwright** [comment]
Perfect, thanks for that. Tested and working 👍
