### ISSUE TITLE
Search with input type text in combination with s-push-url

### ISSUE THREAD

**Issue by jan-dh** [putyourlightson/craft-sprig#49]
### Question
I'm having trouble figuring out how I can make this scenario work. This is my current setup

```
{% set title = title ?? '' %}
<input
    type="text"
    name="title"
    value="{{ title }}"
>
<button
    class="button
    sprig
    s-vars="title: '{{ title }}'"
    s-push-url="?title={{ title }}"
>Update value</button>
```

I want on button submit to push the value of the input to the url. However, since that value should also be reflected as the value of the input field, i'm chasing my own tail here. First time around the `title` variable is empty. I want to update that value from my input field and then push it to the url.

**Comment by bencroker** [comment]
You should be able to make this work using the `HX-Push` [response header](https://htmx.org/docs/#response-headers).

```twig
{% if title %}
    {% do craft.app.response.headers.add('HX-Push', '?title=' ~ title) %}
{% endif %}
```

As for using `s-push-url`, I don't think there's any way to make it work with your setup but it might be worth asking in the [htmx discord server](https://htmx.org/talk).

**Comment by jan-dh** [comment]
Thanks! Will update this question with a possible solution if I find one

**Comment by jsmrtn** [comment]
@jan-dh I worked around this by modifying the `hx-push-url` on `beforeRequest`, not sure if it would be suitable for you. Appreciate it's a bit hacky, but I couldn't find a way to push the initial value so like you the URL value was always one step behind what was being entered in the text field.

```
document.body.addEventListener('htmx:beforeRequest', evt => {
    let searchVal = document.querySelector('[name=title]');
    if (searchVal) {
        let search_param = searchVal.value;
        let hxPushUrl = evt.detail.elt.getAttribute('hx-push-url').replace(/title=(.*)&/g, 'title=' + search_param);
        evt.detail.elt.setAttribute('hx-push-url', hxPushUrl);
    }
});
```

**Comment by bencroker** [comment]
FYI a new [sprig.pushUrl](https://putyourlightson.com/plugins/sprig#sprig.pushurlurl) function has been added in 1.1.0.

```twig
{% do sprig.pushUrl('?page=' ~ page) %}
```
