### ISSUE TITLE
Array parameters throws an error

### ISSUE THREAD

**Issue by jeffreyschmitz87** [putyourlightson/craft-sprig#5]
I've created a page with a filter. The filter is submitted by a form and parsed as parameters into the URL (e.g. `?type%5B%5D=25`). This will throw an error `hash_hmac() expects parameter 2 to be string, array given`.

This happens because the line below doesn't check if `$value` is a string/array.
https://github.com/putyourlightson/craft-sprig/blob/1c5297c3a58c150f8243da5fdeef5d9c61465418/src/services/ComponentsService.php#L76

I'm using the latest beta version (8).

**Comment by bencroker** [comment]
As per the docs at https://putyourlightson.com/plugins/sprig#variables:

> Only values that can be passed over HTTP requests may be used (strings, numbers, booleans).

Can you show me the code that is triggering the error?

**Comment by jeffreyschmitz87** [comment]
This is the code I'm using:
```
<form method="get">
	<label for="type-a">
		<input type="checkbox" id="type-a" name="type[]" value="25"> Type A
	</label>
	<label for="type-b">
		<input type="checkbox" id="type-b" name="type[]" value="26"> Type B
	</label>
	<button type="submit">Apply</button>
</form>

{{ sprig('components/sprig/load-more.html.twig', {
	offset: 0,
	_limit: 9,
}) }}
```

Within the `components/sprig/load-more.html.twig` I've followed the steps from the docs. If I press the 'Apply' button the request parameter `type[]` will be set in the UR (`?type%5B%5D=25`) and this parameter will be passed on to the `ComponentsService`. This request parameter is an array type and because of this the error will throw since it expects a string.

The request parameters are added as variables in beta version 6: https://github.com/putyourlightson/craft-sprig/blob/develop/CHANGELOG.md#100-beta6---2020-07-03

**Comment by bencroker** [comment]
Thanks @jeffreyschmitz87, fixed in https://github.com/putyourlightson/craft-sprig/commit/f93a7e41377905a913b12b6747f1cdcb1efa4700 for the next release.

**Comment by bencroker** [comment]
Thanks @jeffreyschmitz87, fixed in https://github.com/putyourlightson/craft-sprig/commit/f93a7e41377905a913b12b6747f1cdcb1efa4700 for the next release.
