### ISSUE TITLE
Handle checkbox groups (group values)

### ISSUE THREAD

**Issue by jan-dh** [putyourlightson/craft-sprig#50]
### Question
I was wondering if there's a way to handle checkbox groups. Sprig exposes a variable with the same handle as the name of an input, but checkbox groups share a name with an empty array `[]`. All the values are being sent through ok in the request, but are not combined.

```
audience[]: 6038
audience[]: 6039
audience[]: 6040
```

I can't really make a twig variable with those brackets in the name, so I'm wondering if there's a way to drop the brackets behind the name and I can get all the values in a comma seperated string. That way I can use the "audience" variable and the comma separated list is easy to `|split(',')` so I can use them in an Array to check for checked states.

If I remove the array notation it works, but I only get the last value.

**Comment by bencroker** [comment]
Can you show a minimal code sample?

**Comment by jan-dh** [comment]
Yes ofcourse, 

So I'm looping over categories in a category group "audience":

```
{% set categories = craft.categories.group('audience').all() %}
{% for cat in categories %}
    <input type="checkbox" value="{{ cat.id }}" name="audience[]" >
{% endfor %}
```

That outputs:
```
<input type="checkbox" value="6038" name="audience[]" >
<input type="checkbox" value="6039" name="audience[]" >
<input type="checkbox" value="6040" name="audience[]" >
```

When I inspect the request I see the values being passed:
![image](https://user-images.githubusercontent.com/5801781/97450560-2afa3800-1933-11eb-96e5-a073a268019c.png)

If I paste these values manually in the url like this: `sprig?audience=6038,6039,6040` I'm able to work with them. I can't seem to figure out how I can push these to the url in this format.

**Comment by bencroker** [comment]
The variable `audience` will be available in your template as an array. Test as follows:

```twig
{{ audience is defined ? dump(audience) : '' }}
```

**Comment by jan-dh** [comment]
Perfect!

**Comment by j-greig** [comment]
Are you able to share your solution for this somewhere @jan-dh? Bit stuck with my version... 😳

**Comment by bencroker** [comment]
Check out [sprig.pushUrl(url)](https://putyourlightson.com/plugins/sprig#sprig.pushurlurl), probably the simplest solution, also explained in this video:
https://putyourlightson.com/sprig/videos#7.-pushing-url-updates

**Comment by jan-dh** [comment]
@j-greig yep I got it working. Hit me up on Craft discord if you want some more info. I used @bencroker 's example from above and got it working
