### ISSUE TITLE
Using Sprig in a plugin template

### ISSUE THREAD

**Issue by jamiematrix** [putyourlightson/craft-sprig#51]
I'm looking to add a page to the admin CP (have already got a plugin created and added to the nav, and can get a basic template/page showing) that makes use of the awesome Sprig, but when adding the component to the page I get an error to say the component/template cannot be found.

I was hoping to keep the component in a /templates/_components folder, but I've yet to find the correct path for this to be referenced. I'm guessing it's because the plugin path doesn't match up with the path displayed in the browser?

**Comment by jamiematrix** [comment]
Found in the Extending Craft docs there's a section related to [Template Roots](https://craftcms.com/docs/3.x/extend/template-roots.html#plugin-control-panel-templates). I've set a reference to the _components folder within the plugin's core PHP file

**Comment by bencroker** [comment]
So does that solve it? Care to share your solution for others?

**Comment by jamiematrix** [comment]
Seems to so far. Here's my e.g:

In my /project/plugins/company/plugin-name/src/plugin-name.php I have the following included:
```
use craft\events\RegisterTemplateRootsEvent; // Added this line
use craft\web\View; // Added this line
use yii\base\Event;

public function init()
{
    parent::init();
    
    // Added the below event
    Event::on(
        View::class,
        View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS,
        function(RegisterTemplateRootsEvent $event) {
            // My component is in the project-root/templates/_components.
            // The following creates a reference to the above path - I've used ['_components'] to keep it simple.
           // Whatever gets entered into the brackets can then be used in the plugin template file e.g. {{ '_helloworld/componentname' }}
            $event->roots['_helloworld'] = __DIR__ . '/../../../../templates/_components';
        }
    );
  // End of additional code
}
```

**Comment by bencroker** [comment]
By default, Craft will be looking in the control panel templates, so the following would work if you put the template in your plugin's template directory.

```twig
{{ sprig('plugin-handle/template-name') }}
```

**Comment by jamiematrix** [comment]
I had tried that, but couldn't get it to work. Have just noticed that the pluginfactory.io generator had added a '-' to the handle.

Least I have 2 options :)
