### ISSUE TITLE
Using Sprig and Flatpickr Date time input

### ISSUE THREAD

**Issue by strandofgenius** [putyourlightson/craft-sprig#52]
### Question
Hi, I was wondering if there is currently a way to hook into sprig that would allow me to filter entries between two dates while using the [Flatpickr date/time package](https://flatpickr.js.org/getting-started/).

**Comment by bencroker** [comment]
Sure, just use the dates in your entry query to narrow down the search. See the docs at https://craftcms.com/docs/3.x/entries.html#postdate.

**Comment by strandofgenius** [comment]
Just to get started. Should this example work right out of the box? I was seeing how these examples worked before getting too deep. It works in the playground but not the frontend.

```
{% set query = query ?? '' %}

<form sprig>
    <input type="text" name="query" value="{{ query }}">
    <input type="submit" value="Search">
</form>

<div id="results">
    {# Outputs the result if `query` is not empty #}
    {% if query %}
        {% set entries = craft.entries().search(query).orderBy('score').all() %}
        {% for entry in entries %}
            {{ entry.title }}
        {% endfor %}
    {% endif %}
</div>

    {{ sprig.script }}
```

**Comment by bencroker** [comment]
`{{ sprig.script }}` belongs in the parent template only.

**Comment by strandofgenius** [comment]
I have a couple other `{% extends %}` before being at the base level, but this is what I have for my page template to test sprig. 

```twig
{% extends '_layouts/general-page-layout.twig' %}

{% block main %}

    {% set query = query ?? '' %}

    <form sprig>
        <input type="text" name="query" value="{{ query }}">
        <input type="submit" value="Search">
    </form>

    {% if query %}
        {% set entries = craft.entries.search(query).all() %}
        {% for entry in entries %}
            {{ entry.title }}
        {% endfor %}
    {% endif %}
{{ sprig.script }}
{% endblock %}

**Comment by bencroker** [comment]
Please read the docs on how to use the `sprig` function: https://putyourlightson.com/plugins/sprig#how-it-works

**Comment by strandofgenius** [comment]
@bencroker I did get it working. Thanks for the patience and assistance. As a side note question are there any performance things to consider when querying entries/categories within components to dynamically populate multiple select dropdowns to filter the main query related to the selected entries/categories plus the date selectors? Is it re-querying the select dropdown options? Should each select be a nested component?

![Screen Shot 2020-11-02 at 8 29 53 AM](https://user-images.githubusercontent.com/11370639/97881897-97d15180-1ce8-11eb-9459-33893fe7147a.png)

**Comment by bencroker** [comment]
I think it's fine to do it that way, just use the best practice of [eager-loading](eager-loading) element queries whenever possible.
