### ISSUE TITLE
Delete line items in Cart Craft Commerce

### ISSUE THREAD

**Issue by pacoNew** [putyourlightson/craft-sprig#53]
### Question
Hello Ben, i would like to use sprig to delete items in the cart of a Commerce Project. I tried to use the following Code, but without any success.

    <form sprig s-method="post" s-action="commerce/cart/remove-line-item">
        <input type="checkbox" name="lineItems[40][remove]" value="1">
        <input type="submit" value="Remove from Cart">
    </form>

Server Response: Unable to resolve the request: commerce/cart/remove-line-item

I also tried to use s-action="commerce/cart/update-cart", also without any success. 

Do you have any solution?

Thanks in advance

**Comment by bencroker** [comment]
It doesn't look like `commerce/cart/remove-line-item` is a valid controller action in https://github.com/craftcms/commerce/blob/develop/src/controllers/CartController.php. Do you have a working example that is not using Sprig?

**Comment by pacoNew** [comment]
Hi Ben, 

yes i got this code from an answer from Luke:

https://github.com/craftcms/commerce/issues/277#issuecomment-377667782

But I just saw, this action Url is deprecated. Instead I tried this, and it seemed to work. But anyway, do see any solution to get this done with sprig?

https://github.com/craftcms/commerce/issues/277#issuecomment-408345413

**Update:**
Hi, Ben i figured out, now it works with sprig
```
<form sprig s-method="post" s-action="commerce/cart/update-cart">
  <input type="hidden" name="cartUpdatedNotice" value="Updated line items.">
  <input type="checkbox" name="lineItems[{{itemId}}][remove]" value="1">
  <input type="submit" value="remove to cart">
</form>
```

**Comment by bencroker** [comment]
Glad to hear it!
