### ISSUE TITLE
Live Search Filter List

### ISSUE THREAD

**Issue by challahan** [putyourlightson/craft-sprig#55]
Is there a way using the [Live Search](https://putyourlightson.com/sprig-cookbook#search) recipe as a baseline to list all entries by default and then live filter those entries as the user types the query in the search field (rather than displaying nothing but the search field at first)? Any help is appreciated!

**Comment by bencroker** [comment]
Sure, just remove the condition for a query.

```twig
<div id="results">
    {% set entries = craft.entries.search(query).all() %}
    {% if entries|length %}
      {% for entry in entries %}
        <a href="{{ entry.url }}">{{ entry.title }}</a>
      {% endfor %}
    {% else %}
        No results
    {% endif %}
</div>
```

**Comment by challahan** [comment]
Thank you! This works great.
