### ISSUE TITLE
Making back button work on initial page 

### ISSUE THREAD

**Issue by simonkuran** [putyourlightson/craft-sprig#56]
I have a paginated and filterable list of entries that I'm tracking the history of via `{% do craft.app.response.headers.add('HX-Push', '?page=' ~ page ~ '&' ~ categoriesString) %}`

It works just fine, except if the back button is clicked to go back to the _first_ page that was rendered (when `{% if sprig.isRequest %}` is false). The page doesn't re-render via Sprig because htmx doesn't have history for that page. So the page is what the browser saw last and that often has a popup filtering form expanded.

If I add `{'s-trigger': 'load'}` to my Sprig component and only render when `{% if sprig.isRequest %}` is true like in the docs for [Dynamic Content](https://putyourlightson.com/sprig-cookbook#dynamic-content) it works well, except I can't figure out a way to pass in the initial URL parameters _only_ if the back button was used to load the first page (whether or not that URL has URL parameters).

I also tried adding '{'id': 'grid'}' to my Sprig component and running `document.getElementById('grid').dispatchEvent(new Event('refresh'));` on page load. This works for the first use of the back button to the initial page. But this sequence will get it back to a stuck "browser's last seen state": initial load > use filter > back button > use filter > back button (trying to see the initial load for a second time).

I just need htmx to know the state of the initial page load and have it loaded into to the browser's history. How can I accomplish this?

**Comment by bencroker** [comment]
> It works just fine, except if the back button is clicked to go back to the first page that was rendered (when {% if sprig.isRequest %} is false). The page doesn't re-render via Sprig because htmx doesn't have history for that page. So the page is what the browser saw last and that often has a popup filtering form expanded.

This sounds like native browser behaviour, not sure it can be changed.

> I just need htmx to know the state of the initial page load and have it loaded into to the browser's history. How can I accomplish this?

Seeing as though this is a htmx specific question, I'd suggest asking in the [htmx github issues](https://github.com/bigskysoftware/htmx/issues).
