### ISSUE TITLE
Set search query dynamically

### ISSUE THREAD

**Issue by clake2310** [putyourlightson/craft-sprig#57]
I have a search results page on a separate page and on the results page there is a variable to set the initial query.

In my site wide header I have the following form:

 <form action="{{url('search/results')}}" class="search">
       <span class="icon-search"></span>
        <input type="search" placeholder="Search the website…" name="q" id="search-input" aria-label="Search 
        Website" >
</form>

I am using the below to fetch the query:
 {% set searchQuery = craft.app.request.getParam('q') %}

This is then used in a JavaScript function that filters the loaded search results by this query.

When using with Blitz cache disabled it works fine and returns the query and results as expected. When using this with Blitz cache enabled it obviously caches the query the first time and from this point the query cannot be changed.

I was hoping I would be able to make this value dynamic with the help of sprig but when i'm trying to set the searchQuery nothing is returned presumably because the url its looking at is /index.php?p=actions/sprig/components/render instead of the page URL. Is there a way I can achieve my desired result or do I just need to leave the cache disabled for search queries? (This significantly slows down my site!)

Many thanks for your time!

**Comment by bencroker** [comment]
Have you set the “Query String Caching” setting in Blitz to `Cache URLs with query strings as unique pages`?

**Comment by clake2310** [comment]
I haven't, I cached as same page. It lands on an Algolia instantsearch.js page where all the results are dynamic anyway and its just the initial search query that I need as dynamic in the template. I figured caching as unique pages could potentially create many pages that are essentially the same? I appreciate your thoughts?

**Comment by bencroker** [comment]
> I figured caching as unique pages could potentially create many pages that are essentially the same?

It could, but each page is unique if it needs to know about its query string using Twig/PHP. If you're using JavaScript to perform the search then you should be able to use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to dynamically get the query string parameters.
