### ISSUE TITLE
Using the {% redirect %} tag

### ISSUE THREAD

**Issue by mikeymeister** [putyourlightson/craft-sprig#58]
### Question
Hi Ben, thanks for the plugin. I have a sprig component that submits a form, then based on the information submitted and a successful response from the controller I either want to show another form for some extra information or redirect the user to another page. When I use the twig {% redirect 'url' %} tag it prints the content of the controller response to the template. Should the redirect tag be off-limits in a sprig component?

### Additional context
Sprig: 1.0.3
Craft: 3.5.12.1

**Comment by bencroker** [comment]
That's something I've been considering very recently, will let you know what I come up with.

**Comment by bencroker** [comment]
Started experimenting in https://github.com/putyourlightson/craft-sprig/commit/f1b6b8c0dca7473731192c4f6a7495ef940ad1f1 but really it would be ideal if htmx could handle this natively. Hoping for a response in https://github.com/bigskysoftware/htmx/issues/230.

In the meantime, I'm working around it by outputting this in my components:

```html
<div><script type="application/javascript">window.location = "redirect-url";</script></div>
```

**Comment by bencroker** [comment]
FYI a new [sprig.redirect](https://putyourlightson.com/plugins/sprig#sprig.redirecturl) function has been added in 1.1.0.

```twig
{% do sprig.redirect('/new/page') %}
```

**Comment by mikeymeister** [comment]
Great! Thanks.
