### ISSUE TITLE
Nested Sprig Components

### ISSUE THREAD

**Issue by wesleygooch** [putyourlightson/craft-sprig#6]
First off... LOVE this plugin! It's working great. I know it's in beta so this may be out of scope for this version... 

I'm using your "Load More" and "Add to Wishlist" recipes from your Sprig Cookbook. Everything is working great except when there's a nested "Add to Wishlist" sprig component inside of a "Load More" sprig component. The initial page load renders the nested "Add to Wishlist" components just fine but on a sprig.request the "Load More" breaks. If I remove the nested "Add to Wishlist" components then the load more works as expected. 

Any ideas of a workaround?

Thanks again for your hard work. I think you could make this plugin a paid-for plugin. It adds a lot of value. 

Cheers,
Wes

**Comment by bencroker** [comment]
Glad to hear you're enjoying Sprig!! Nesting components, as you are trying to do, is high up on my list of features to implement. As it's a fairly complex feature, I'm not sure whether it'll make it into the 1.0 version but I'll be working on it in the coming days/weeks.

**Comment by bencroker** [comment]
I've got a working draft of this feature at https://github.com/putyourlightson/craft-sprig/commit/de51b6c708079846fbbfa46d9a7f2c4848d019f0, feel free to play with it.

**Comment by wesleygooch** [comment]
Thanks for the prompt reply and glad to hear nested components is on the to-do list! I'll keep playing around with sprig and let you know if I run into anything else. So far it's a great plugin and you did a great job on the documentation as well! 

Cheers,
Wes

**Comment by bencroker** [comment]
Just released 1.0.0-beta.9 which adds support for nesting components. Note that variables defined in nested components will also be submitted and available in parent components. Let me know how it goes!!

**Comment by wesleygooch** [comment]
That fixed it! I didn't have to change anything. Just re-added the nested component and everything is working smoothly! GREAT WORK! 

If you make this a paid-for plugin I will be your first customer! Love your plugins, you write great code! Looking forward to working with more of your plugins in the future! 

Cheers,
Wes

**Comment by bencroker** [comment]
Glad to hear it! I've added a recipe to the cookbook to demonstrate this:
https://putyourlightson.com/sprig-cookbook#nesting-components

**Comment by wesleygooch** [comment]
Ben, 

Thanks again for your hard work on this plugin. I'm using it extensively and love it! 

I've run into a limitation with nested components. When using the same scenario that we discussed above. The request URL's seem to grow larger and larger on each "Load More" render requests. After a certain point, my server is returning a 414 URL Too Long error. 

Again, this takes a lot of "Load More" clicks before this scenario occurs so it's going to be rare if a user encounter this. However, is there a way to keep the URL Lengths to a minimum?

It looks like the CRAFT_CSRF_TOKEN is duplicated on every subsequent request. Thoughts? 

Feel free to test it out here (site is locked, use password demo) and use the load more for the page results:
https://staging.visitpinedale.org/search?q=pinedale   

**Here's an example URL that's throwing a 414...** 

http://staging.visitpinedale.org/index.php/actions/sprig/components/render?CRAFT_CSRF_TOKEN=Ya7w1AH3QfFno_9bOGRF8GaVypfNnO4fjhNCE8uZ748YcO3zJE4WPWtXNxUSZnBqtlefzQ8jfZK17xC3VYnUuwXZx3F0mPKHc5l5QGUG_BaNs5jgriyfgzJyqGbJUfAqy_j1dbwAEh3GwXk3NdQInnHT3Yo_T4jA1rQJnz1N5lJoSWJQKbqdAODbMqMeoF6bA0O0O__w89CeRFQsSEQYI4mlnjIMjmsnSL3dGA6sOXnGDSiBOcAz8SXQd3WhB4GgW6c8HFn-X2-Mty_oNy8GqlOdhqNGpxSCC-60GVpcF4ogwq3Zv8y0fbhWAV6tqKvVTDGZkhQiXHcXMVIidlRJUodk-6g3Gxmh0Ykg1W3vsoNj4fRGQvuUt0r9THgEPp8nuoGt08gf-uUCQ55QqjOUSK6ekBTYNysqpfNKQUKTWMsCv5DBfS2wkqzyXvhzP7YICn8nE2TcrES6j3PXf5Ay0Uk_hUfbwor0r3dwGjk3LW2nyslraP4IEiffkmxAxnFBs3R_2V6TXr5g_y4axkrW1m3Jc2wsjQsg-8B1nURJcOU%3D&CRAFT_CSRF_TOKEN=Ya7w1AH3QfFno_9bOGRF8GaVypfNnO4fjhNCE8uZ748YcO3zJE4WPWtXNxUSZnBqtlefzQ8jfZK17xC3VYnUuwXZx3F0mPKHc5l5QGUG_BaNs5jgriyfgzJyqGbJUfAqy_j1dbwAEh3GwXk3NdQInnHT3Yo_T4jA1rQJnz1N5lJoSWJQKbqdAODbMqMeoF6bA0O0O__w89CeRFQsSEQYI4mlnjIMjmsnSL3dGA6sOXnGDSiBOcAz8SXQd3WhB4GgW6c8HFn-X2-Mty_oNy8GqlOdhqNGpxSCC-60GVpcF4ogwq3Zv8y0fbhWAV6tqKvVTDGZkhQiXHcXMVIidlRJUodk-6g3Gxmh0Ykg1W3vsoNj4fRGQvuUt0r9THgEPp8nuoGt08gf-uUCQ55QqjOUSK6ekBTYNysqpfNKQUKTWMsCv5DBfS2wkqzyXvhzP7YICn8nE2TcrES6j3PXf5Ay0Uk_hUfbwor0r3dwGjk3LW2nyslraP4IEiffkmxAxnFBs3R_2V6TXr5g_y4axkrW1m3Jc2wsjQsg-8B1nURJcOU%3D&CRAFT_CSRF_TOKEN=PQ7hBt2kHkuS0chYBowJzHB19KUfXvoa9eC3HwEGKV6c-TWBMy2-2_AevrTIVJ01SEv031_B_YkJK9n39LjvcCONeGkLjmAF6kG-XEAKmw-kNDhR_p4a587XuXlUcnrpEO7tvTM6N_AR7dxJAe0PK2bw2tH1KfL6dlm8c_ySstzkZk2-m8xSIzWFT-6di6zg4DxnukCyii-meybWcPEKuddhaQwviYjL6Dx-u0--ae-2MqAIUGKONA2INtSbkruboFdxQBq5ae3NU9ow26tfGQ89l3Ga9Es4_pyDGmS0W7Y2IpPrbQ6geMOl9FJnN20EyLhB4ANB9JGMeNuDrGakDXl4kLpn-Zm6bU3plczeiUhFtUtePe0GNdMli2QhMvg-kwYNYpitf4H-5o9PNxAei3WIiNxXDQ7Hct_vP3aqX34VnJeat0vKqAwf6xSy4OKGhlAI_daqY2dv0Q6a_LvAqqpAVsZkgPMLl0gC4AGCP_f5Dj5VS_nr_odeMc8B1CHXw0v3UDcx43tIp2-7_N_s7ZY5PjBvyj2iuiSARajNKVY%3D&CRAFT_CSRF_TOKEN=PQ7hBt2kHkuS0chYBowJzHB19KUfXvoa9eC3HwEGKV6c-TWBMy2-2_AevrTIVJ01SEv031_B_YkJK9n39LjvcCONeGkLjmAF6kG-XEAKmw-kNDhR_p4a587XuXlUcnrpEO7tvTM6N_AR7dxJAe0PK2bw2tH1KfL6dlm8c_ySstzkZk2-m8xSIzWFT-6di6zg4DxnukCyii-meybWcPEKuddhaQwviYjL6Dx-u0--ae-2MqAIUGKONA2INtSbkruboFdxQBq5ae3NU9ow26tfGQ89l3Ga9Es4_pyDGmS0W7Y2IpPrbQ6geMOl9FJnN20EyLhB4ANB9JGMeNuDrGakDXl4kLpn-Zm6bU3plczeiUhFtUtePe0GNdMli2QhMvg-kwYNYpitf4H-5o9PNxAei3WIiNxXDQ7Hct_vP3aqX34VnJeat0vKqAwf6xSy4OKGhlAI_daqY2dv0Q6a_LvAqqpAVsZkgPMLl0gC4AGCP_f5Dj5VS_nr_odeMc8B1CHXw0v3UDcx43tIp2-7_N_s7ZY5PjBvyj2iuiSARajNKVY%3D&CRAFT_CSRF_TOKEN=X2aOmAhpcdQtSHZeyxpT4cV7LHhUgLXilSIlMGokpkuurBt5yaNUMVninvZcpsFLy1KxSZV5uesSMUizLk9bDgSRjTkP8w-agN6wphs7CymHZ36Ewd2GAtZdf7sFHVgoDBcgH1neMyXSyiH7kAoddw_HORZP0pbCrmYKy1P_Cas5XTQZKtLb9pzPJx3HxHaQB_WDtB0mr2eHArWlBjj8izdxUn04l1GRuwa00pcqlFzQlX2kSOJZoVOClqB3ns-UqmQK9Jz0mFU18ubXihyJ9m1V-O9POSSnQQU9HKkiAZuDLEs2JtDvgKNnZn0MFeIR-u1vGPnPHnslhPvBOJT4c_ph1SytQd3Ydld40RYpPTZiqb4OOZBpqrm6hZ56A2gYsFVLt6fu42TmbEmNZn88SmlxRX496QoSsfgSjedNTSJ8q3RdDbCukNQgXawdjVnxW2txWme06rLGm2ZppvQa2k2Jssg5FNZDtjGRk3dLycUZHgUkXOcypNRk-6bZQNxkpewq_C-xNO4Wrc_PENOY4pwKRYTph8waQoW8ovl6_7k%3D&CRAFT_CSRF_TOKEN=PQ7hBt2kHkuS0chYBowJzHB19KUfXvoa9eC3HwEGKV6c-TWBMy2-2_AevrTIVJ01SEv031_B_YkJK9n39LjvcCONeGkLjmAF6kG-XEAKmw-kNDhR_p4a587XuXlUcnrpEO7tvTM6N_AR7dxJAe0PK2bw2tH1KfL6dlm8c_ySstzkZk2-m8xSIzWFT-6di6zg4DxnukCyii-meybWcPEKuddhaQwviYjL6Dx-u0--ae-2MqAIUGKONA2INtSbkruboFdxQBq5ae3NU9ow26tfGQ89l3Ga9Es4_pyDGmS0W7Y2IpPrbQ6geMOl9FJnN20EyLhB4ANB9JGMeNuDrGakDXl4kLpn-Zm6bU3plczeiUhFtUtePe0GNdMli2QhMvg-kwYNYpitf4H-5o9PNxAei3WIiNxXDQ7Hct_vP3aqX34VnJeat0vKqAwf6xSy4OKGhlAI_daqY2dv0Q6a_LvAqqpAVsZkgPMLl0gC4AGCP_f5Dj5VS_nr_odeMc8B1CHXw0v3UDcx43tIp2-7_N_s7ZY5PjBvyj2iuiSARajNKVY%3D&CRAFT_CSRF_TOKEN=2ID9Gv96jaxQHUbG4Tt9Oz6kMvMlybgMdyksGAUz8teXpPIfjFyBKAIAsdjkG1vKY-khbzcB72QLWrt1jkw2PBWqK8eU8BIbRoN0Tc1kG7t95fKtvKb2Dw3uzkOV2rrgzSm34G-T6glYgl_FeGXsqnwAqtJDjKpP800WyDj5bIbh6nFatzoMn2wS0jpDgKLu5PdGgOizlnalQ9JDgIRwbfRPiXVeO5jwYHwjZhwi5SNza-n0dZiNtsECITpczfmT-wM7_NHxm8VyTcl0CANNnOqzi224KtjfPFANhIMDL0F481W9V5nibkFsb1VjAraNw-WGfrwwy2J-ZtTvgCli8lLaRQoPOYtXbzyLF7YqUARzkhjwopN0K3_nQXWsXHiKStfHntqVk2k93_h19rjegqhP0oELpNM-O7Bssw8ivP8PbOeZAe6SHYkLQa92izzcg9w0GfpcPds2RpNOIrDOpK6Ld_zMge9SlHD2dfH3RSPaIN4sOkv7xQ8ebBJSSK0bBhK-rBLL4PmELXhVO4Cu5c1tdIykgs-KBTqTAXtlO9M%3D&CRAFT_CSRF_TOKEN=2ID9Gv96jaxQHUbG4Tt9Oz6kMvMlybgMdyksGAUz8teXpPIfjFyBKAIAsdjkG1vKY-khbzcB72QLWrt1jkw2PBWqK8eU8BIbRoN0Tc1kG7t95fKtvKb2Dw3uzkOV2rrgzSm34G-T6glYgl_FeGXsqnwAqtJDjKpP800WyDj5bIbh6nFatzoMn2wS0jpDgKLu5PdGgOizlnalQ9JDgIRwbfRPiXVeO5jwYHwjZhwi5SNza-n0dZiNtsECITpczfmT-wM7_NHxm8VyTcl0CANNnOqzi224KtjfPFANhIMDL0F481W9V5nibkFsb1VjAraNw-WGfrwwy2J-ZtTvgCli8lLaRQoPOYtXbzyLF7YqUARzkhjwopN0K3_nQXWsXHiKStfHntqVk2k93_h19rjegqhP0oELpNM-O7Bssw8ivP8PbOeZAe6SHYkLQa92izzcg9w0GfpcPds2RpNOIrDOpK6Ld_zMge9SlHD2dfH3RSPaIN4sOkv7xQ8ebBJSSK0bBhK-rBLL4PmELXhVO4Cu5c1tdIykgs-KBTqTAXtlO9M%3D&CRAFT_CSRF_TOKEN=2ID9Gv96jaxQHUbG4Tt9Oz6kMvMlybgMdyksGAUz8teXpPIfjFyBKAIAsdjkG1vKY-khbzcB72QLWrt1jkw2PBWqK8eU8BIbRoN0Tc1kG7t95fKtvKb2Dw3uzkOV2rrgzSm34G-T6glYgl_FeGXsqnwAqtJDjKpP800WyDj5bIbh6nFatzoMn2wS0jpDgKLu5PdGgOizlnalQ9JDgIRwbfRPiXVeO5jwYHwjZhwi5SNza-n0dZiNtsECITpczfmT-wM7_NHxm8VyTcl0CANNnOqzi224KtjfPFANhIMDL0F481W9V5nibkFsb1VjAraNw-WGfrwwy2J-ZtTvgCli8lLaRQoPOYtXbzyLF7YqUARzkhjwopN0K3_nQXWsXHiKStfHntqVk2k93_h19rjegqhP0oELpNM-O7Bssw8ivP8PbOeZAe6SHYkLQa92izzcg9w0GfpcPds2RpNOIrDOpK6Ld_zMge9SlHD2dfH3RSPaIN4sOkv7xQ8ebBJSSK0bBhK-rBLL4PmELXhVO4Cu5c1tdIykgs-KBTqTAXtlO9M%3D&CRAFT_CSRF_TOKEN=4mwgc7Jja7pQa-fhZgmq7PK07LEDjMqyLdPL8RGc-xkc0r4blGbqVS-nyEiy9GINADGjaK8ifK-NxCDa6KNNyhdIA--I9VOKKWqTXive9LRJYalVvdREOeMJ4bZ_pRqCnrk5BwdJvtmEXL7FQmYHUunkmlFAUQrNSuuVej8v70FONdB-MemYzijpCnvf9nSr1ilAy94pRbTaZi53z7Jk0wXRZQpBejc-moIWZDo6Zc4Zkr4ZFubG7a2ic2xb1yzrXYIZqinH2b451wF8rCtkidBfVgT1Mz7JPCasowQx-Ja044v_cdyQ0BuWiLx3rb9DSJPKeqQKoB9Twa1_1sZbNTECxw2XGhic6aIQuNDFK_JxcDDYvpY1uhAOpmZK5peFflOcZtvnIV_TONeAHMd-4PvfXGZjfofu526NszUhVweaiNcaAjMynzCtwh1xXb8bLAOVPXyPqYpyvUsPvsYY4ZxVcbf6GzyQ61UKQb7BUZ0rvjJTJQpUC_XgWRB0UC32bOvpQXG1q6LojSoDPJp7nWvsVtpctI3xTqBbCd9NEsY%3D&CRAFT_CSRF_TOKEN=exAsxoG3TTdlbmonFtXtIkGymiCmb5-yw5OnUUUTImQyhlaDHqcxrjdlq_JeRsebsyol-mGCTnbTP7HyjKz68_izHcw0_Pbo7j1TmHHmO5R97-dgsR3xnrK2E14jn6VDwNGpIPWTvRnyMp2oSVcIQjrhwJkZyrp67m7zjGJTUsbBD0499nh8nVxrjrMZy1Pzemxslsewio34TQ51O6D9dqGPH2lUJ0fdWnemapLV3efrWk7PlxCWVUarVsel-NugMt4jvcJgERIPth0XtDJ6k0kjWrHG5xhECSMhZXTtv1gH5f1u1D_F0PXW5BwjImY-Zsci4i7Le-RLA87FOnT-o4IZQZ9ZuipFt1mBkLTKnMueiy77Ap-Q2NdZZqAQ3lilSt3SU9culPiChyVoQP3BIaW3zEGRpIQukQCu3j4QWBdJjY3SW6iCKJQopOssIQKcozkLfrseTdkGP8_HePs_uTAQXerjgvOpyX4qQ0rTyDiP4EgwMFck6DUV6R7cv5XfniMZl_BD-xoDhA-owrWM1gSwbM23E0VdeMFHYsdUDNw%3D&CRAFT_CSRF_TOKEN=fpxY0g9SULjlg7y19nRNtxofHdhHcErWshK2O4iAMGlKyRXOtbQqf8DrNH10GFc3sZZO6HX4Q_tLMVvBT_7MjCevYfl0141jHzbHsShl2PPqbAXzR4sh3-mexKQtIFwFbc_G2qtjnoPdIY5U8sLiA10sLyVmGoB8e35Hytv0kxWW8cKhaxc8XalF7ZRmzezV7SxmBLQtmT9qiPUPidY4HIxGkEG7nikjDWOJbWio2h2ISrpzaoAxesqFyXJMy_ckmUApZzUibvJD7oUC6PCiJUyvLqVIAgXLic7395RMH81cSHqWNSAQtIRX9XbusXQzHohhr4XYYDW8jVFKECpuD4ClKo1NwCfIL1dro3eYqrRBl1LOQrTrUyZS8olJXbvC3V4wwCG4RLnZr_KSTkI4Zwipo7vPVKe0vhO9IoWFslYuQGJuJHi4LgE4EK2VhsNP9MeH4iZxDRnzEazgB_2An6dQV3iQH-AbW7vROfilDVKiKccY3-5KFmIBxhkmwpIl_TPtKw3TXDWPqpAdK4agUq8uZhdAUTq9NJnfd5uW1Go%3D&CRAFT_CSRF_TOKEN=OO5x--44ajvY2y6Rp2rKT2B--gBM1CkzaOaznDF8Kh5aF9y3ddGxi_RltEIe2GG_BRdvyrjQB_sN7Ut1j8DJ13o2C_sx2v-aqTgeWZQsMSalWr29eN9A1jJ9ph65ihJsMSG75AT1fqA_Y8ObJxAYxN5xz37NaWqvPgUbRzzYJixSjnQoGMkoCj3s9U-xctots1-NeZoS81CjVNiDEMcifNu6AsEJrsVXDMotxnLRi4Dn5k_qP5b-QXgV8X-FN-rwzFFfHaQyyDbvnuuQnNTxsQrdB4ypaD9ItJZl08VSmDUmKZ1OPoRzUV6j8NFXTW5EDlao1kW9-8GIA9F1eupYhzQkC6-A6GPIaYt7F7emr-8cDjjMB7mZqpBcK2H1FFIXkmiIjh7sJbACTJAo2uh2DlRH3oVgwkeXXFHw7VBXSJGtHYI1jwtS_URDTCByqnZ2MLgxa1WvGU5nuLQ70EK2Z_kjvAW-IIp0kmf8tWG0FzL11VWYbd6mYmOoYrI8u8O4kp8YsljFkw49OqgQ4nq9hvo_EG3RQZx5mOmx5e-yh_4%3D&CRAFT_CSRF_TOKEN=bj4hFnEKnyBujPJJusTBQJRWpqUrPxGpP8542Q5kx76v7XwxgoBV7eShHHKVP3-fwHzSrNBafWS3F2NdmfERki9VBdkPtIIae4HhUeR43Ff_9deI2dMeDfdl71T9fgzfSUZljCaV0c57k8FFcP3XVp-QPcf_mHmbs-_fmlJvefwUN8GxC_c1zei1PTFjqHj2zHwLBEaXQg1dkmFHCSj79xwgwSPXdJ7Nhu_kvaADnOKZOvIF3Et6z2-UPHfJS3rc5R7wiPgjHEuPaPi81SRKgVwNV2E2WspTAsG5C9j8kzrSAcHrWW9LywmLO5RoVYPk-6wIULLsH6eYx3lF8Q1Gp_FPtsnoYhlX03FTP6GXd6pJbTbuOdfkKkLl1GmFQL9myMfiu7_ge2vHVNlinhxovSwgAO1Couj5GKHyMwe6hwPs_HCMvfpBycmpiP0cHSmmdgGE8kaRBImy4XxFApgUvIYAOnhipTspbKFFcXhbzrkyT5Z6swT9-OmNq8nuadTa7EOlXbsYF4Aqu2UYrgYtqtNwv_iNUEgE-B-iyaZCPM4%3D&CRAFT_CSRF_TOKEN=bj4hFnEKnyBujPJJusTBQJRWpqUrPxGpP8542Q5kx76v7XwxgoBV7eShHHKVP3-fwHzSrNBafWS3F2NdmfERki9VBdkPtIIae4HhUeR43Ff_9deI2dMeDfdl71T9fgzfSUZljCaV0c57k8FFcP3XVp-QPcf_mHmbs-_fmlJvefwUN8GxC_c1zei1PTFjqHj2zHwLBEaXQg1dkmFHCSj79xwgwSPXdJ7Nhu_kvaADnOKZOvIF3Et6z2-UPHfJS3rc5R7wiPgjHEuPaPi81SRKgVwNV2E2WspTAsG5C9j8kzrSAcHrWW9LywmLO5RoVYPk-6wIULLsH6eYx3lF8Q1Gp_FPtsnoYhlX03FTP6GXd6pJbTbuOdfkKkLl1GmFQL9myMfiu7_ge2vHVNlinhxovSwgAO1Couj5GKHyMwe6hwPs_HCMvfpBycmpiP0cHSmmdgGE8kaRBImy4XxFApgUvIYAOnhipTspbKFFcXhbzrkyT5Z6swT9-OmNq8nuadTa7EOlXbsYF4Aqu2UYrgYtqtNwv_iNUEgE-B-iyaZCPM4%3D&CRAFT_CSRF_TOKEN=bj4hFnEKnyBujPJJusTBQJRWpqUrPxGpP8542Q5kx76v7XwxgoBV7eShHHKVP3-fwHzSrNBafWS3F2NdmfERki9VBdkPtIIae4HhUeR43Ff_9deI2dMeDfdl71T9fgzfSUZljCaV0c57k8FFcP3XVp-QPcf_mHmbs-_fmlJvefwUN8GxC_c1zei1PTFjqHj2zHwLBEaXQg1dkmFHCSj79xwgwSPXdJ7Nhu_kvaADnOKZOvIF3Et6z2-UPHfJS3rc5R7wiPgjHEuPaPi81SRKgVwNV2E2WspTAsG5C9j8kzrSAcHrWW9LywmLO5RoVYPk-6wIULLsH6eYx3lF8Q1Gp_FPtsnoYhlX03FTP6GXd6pJbTbuOdfkKkLl1GmFQL9myMfiu7_ge2vHVNlinhxovSwgAO1Couj5GKHyMwe6hwPs_HCMvfpBycmpiP0cHSmmdgGE8kaRBImy4XxFApgUvIYAOnhipTspbKFFcXhbzrkyT5Z6swT9-OmNq8nuadTa7EOlXbsYF4Aqu2UYrgYtqtNwv_iNUEgE-B-iyaZCPM4%3D&CRAFT_CSRF_TOKEN=frQnxCiGbCQkSI_J66u2TRgLSyQC38CXm9c2G1-xhHzf0t90ubOE5A6k5STX7sSPqmmUugJ17TMmC0RrPGdQXRNNICRM3iO3NA95vifuHT2cl_Y5bI3RUd86idr6vBx-mK_AfjGvgnqR-V-Le1BouDSKf3AklZg51HkCxCif-FfYncO2TLUGEsFM3bHSG__aK29qsV8_GR_QiBVqF8SS5At0qAs4c5nGGLbAwbKEioIXrmWjicU-K3YX4rTGsHnxzYznd-K5MjD6AW0rnBjkuUyHUbNv1jlXSAXEi4mT5DdeXCxqcI-a9a2SdVY5gMAmi5OrFYnfzq5ywoATs9z9t5ta8N86TYkAQm10CQQBNmV1dRMTer1Fhw1rTIZG1n4Mq6XDCgq-tDfvC7_smd54HP3JpR9VmLtN8sts_QwXOO1H5jI7Zvega64_VaNm7agNuquG9QHTN1abGJzFsyuTkGETW817DWA74bsxXGa3p6olG_9SXAP683fUj7X87sK6Ytcy--6WU2QzOLvbof0uh_viqAeXymZ_jXY3Xu9-kvY%3D&elementId=7640&elementId=7286&elementId=7396&elementId=7390&elementId=7352&elementId=7346&elementId=7340&elementId=7320&elementId=7529&elementId=7281&elementId=7402&elementId=7384&offset=15&sprig%3Atemplate=bcc8f51aaaa78ec1a6ea0b832a0b845010c6503e4ad6575ef91d74c60cd0e74fsearch%2F_types%2Fpages-loader&sprig%3Avariables%5Blimit%5D=ccff9ae649830c4a6fe697f20ee973463f87575c103f81e1572bfda6daec25753&sprig%3Avariables%5BsearchQuery%5D=a7250113b80bdcaae60d1cefc4a44173214eefe7f2759a9f7fb84055b51216e7pinedale&sprig%3Avariables%5BtotalResults%5D=315d04fef99309e9bf130f2657582e29b4b6851d21aee75d6481509252eb7c5e54

**Comment by bencroker** [comment]
Yup it is the duplicate CRAFT_CSRF_TOKEN input fields that are causing this. Will look into a better way of handling them.

**Comment by bencroker** [comment]
Can you please test with the change at https://github.com/putyourlightson/craft-sprig/commit/b3cf132550f0c3652927c1bfb4730abe0d3471a5, which shouldn't repeat the CSRF token fields.

**Comment by wesleygooch** [comment]
Confirmed that the CSRF tokens are no longer repeating. Nice Work! Thanks!

**Comment by bencroker** [comment]
Released in 1.0.0-beta.10.
