### ISSUE TITLE
Support request [not a bug]: Calls to Craft plugin within the component template

### ISSUE THREAD

**Issue by uaextension** [putyourlightson/craft-sprig#60]
When I make a call to an existing/working Craft plugin in the component template, my Sprig component's failing (template refuses to process):

`{% set searchQueryAnalytics = eventAnalytics('Search Queries', 'Site search', searchQuery) %}`

This must have to do with Sprig's nature of doing things (scope? access Craft's to plugins?), because:

* in my regular templates the `eventAnalytics()` call works fine. 
* changing it to `{% set searchQueryAnalytics = "" %}` makes the template work again.

Is there anything I can declare, or do some workaround, to be able to make that 'eventAnalytics' call?

**Comment by bencroker** [comment]
Where is the `searchQuery` variable being defined? Sprig components don't inherit variables from parent templates, instead you'll have to pass it in if you aren't already.
See https://putyourlightson.com/plugins/sprig#component-variables

**Comment by uaextension** [comment]
Yup, solved: `searchQuery` wasn't defined _(missed that I had that commented out)_. Sorry about that and thanks for the lead. 
Really digging the Sprig plugin, by the way.

**Comment by bencroker** [comment]
Great, glad to hear it!
