### ISSUE TITLE
The “s-vars” attribute in Sprig components has been deprecated for security reasons.

### ISSUE THREAD

**Issue by thefubon** [putyourlightson/craft-sprig#61]
The “s-vars” attribute in Sprig components has been deprecated for security reasons. Use the new “s-vals” or “s-val:*” attribute instead. vendor/putyourlightson/craft-sprig/src/services/ComponentsService.php:231

### Versions
- Plugin version: 1.1.0
- Craft version: 3.5.15.1

**Comment by billmn** [comment]
This is not a bug, with `1.1.0`, you should use the new `s-vals` attribute.

Take a look here: https://putyourlightson.com/articles/sprig-1-1-0-adds-features-security

**Comment by thefubon** [comment]
Is this file not in the template but in the plugin?

**Comment by billmn** [comment]
The plugin uses a `_parseAttribute` method that parse attributes used in your components: https://github.com/putyourlightson/craft-sprig/blob/develop/src/services/ComponentsService.php#L308

If it finds that `s-vars` is used in your templates, it reports it to you as deprecated.

**Comment by thefubon** [comment]
Ok. Thanks!
