### ISSUE TITLE
Refresh component B from component A and pass data from B to A

### ISSUE THREAD

**Issue by jamealg** [putyourlightson/craft-sprig#63]
### Question
I figured out how to [refresh a sibling component](https://putyourlightson.com/sprig-cookbook#refreshing-components) but what if I want to refresh that component with the data from another Sprig component?

We build our front end into twig includes and this is what our "component tree" looks like:

- template.html
  - faceted-search-view.html
    - filters.html
      - filter-block.html
    - grid.html

Each `filter-block` is a set of filters that need to manipulate the element query in `grid.html`. I guess we could flatten the structure so that `faceted-search-view.html` is the only component and we just repeat our HTML. But that is not ideal. We could also probably just use htmx directly. 

I'm wondering is this use case outside the scope for Sprig or is there some technique I'm missing to achieve this?

**Comment by bencroker** [comment]
It sounds like making `faceted-search-view` a Sprig component would be the simpler approach (and simpler is generally better when working with Sprig components). You can still use `{% include %}` tags in your code to avoid repeating yourself.

But to answer your question directly, you need to populate the target component with input field values before dispatching a refresh event. Assuming those fields already exist it might look something like this.

```js
// Update the value of the input field
document.getElementById('filter-field').value = 'new value';

// Dispatch the refresh event
document.getElementById('grid-component').dispatchEvent(new CustomEvent('refresh'));
```

htmx actually provides a nice [API](https://htmx.org/reference/#api) for making this more concise.

```js
// Update the value of the input field
htmx.find('#filter-field').value = 'new value';

// Dispatch the refresh event
htmx.trigger('#grid-component', 'refresh');
```

**Comment by jamealg** [comment]
Ok I think I see now. I was originally thinking that `filter-block` would need to be a Sprig component too since it contained the inputs. But it sounds like the play is to leave that as a simple include, then add hidden inputs to `grid` and use the javascript you shared to populate them when my inputs in `filter-block` change.

I guess I was hoping there would be some magic way to do it with attributes. But now that I think about it I'm not sure if that even makes sense.  In any case, thank you for your speedy and thoughtful response.

**Comment by bencroker** [comment]
A Sprig component should ideally be a grouping of elements that encompasses all related responsive behaviour. So, if it works for your markup, I would put all the filters inside the same component as the grid that they affect. That way, the filters will be reactive by default, using the `sprig` attribute, and the grid will be re-rendered any time a filter changes.

Good luck!
