### ISSUE TITLE
Multiselect/Array Support

### ISSUE THREAD

**Issue by spharion88** [putyourlightson/craft-sprig#64]
First of all: Really nice plugin, saves a lot of time and is easy to use.

## Question
Is there a way to handle multi selects or form inputs with array notation in general with sprig? Using craft/php I would be able to get the selected values using `{{ craft.app.request.post('zip') }}` or `$_POST['zip']` but using sprig i only get an array with the first selected value.

I used the following in component in playground to test it:
```
{% set zip = zip ?? [] %}

<select name="zip[]" multiple size="5" sprig s-trigger="change">
    <option value="1010"{{ '1010' in zip ? ' selected' : '' }}>1010</option>
    <option value="1020"{{ '1020' in zip ? ' selected' : '' }}>1020</option>
    <option value="1030"{{ '1030' in zip ? ' selected' : '' }}>1030</option>
    <option value="1040"{{ '1040' in zip ? ' selected' : '' }}>1040</option>
    <option value="1050"{{ '1050' in zip ? ' selected' : '' }}>1050</option>
</select>
<br/><br/>

Selected zip codes:
<ul>
{% for i in zip %}
    <li>{{ i }}</li>
{% endfor %}
</ul>
```

**Comment by bencroker** [comment]
This is a known issue in htmx, see https://github.com/bigskysoftware/htmx/issues/238.

**Comment by spharion88** [comment]
Thank you for your quick response and forwarding the issue

**Comment by bencroker** [comment]
This has been fixed in https://github.com/bigskysoftware/htmx/commit/fda4957d653ebf683d6017c07a6ef34ed2d72983, but looking at the issue, this should already work for you:

```twig
<select name="zip[]" multiple="true" size="5" sprig s-trigger="change">
```

**Comment by spharion88** [comment]
Didn't work for me with htmx version 1.0.0 (also tried `multiple="true"` and `multiple="multiple"`), but it works as expected with version 1.0.1
