### ISSUE TITLE
Using Sprig with Barba.js or similar

### ISSUE THREAD

**Issue by dhmax88** [putyourlightson/craft-sprig#65]
Hi Ben,

Do you have an example or some guidance on how Sprig can be used when part of a page is loaded in via AJAX? I can't seem to see how a component can be triggered on page change, and triggers don't seem to be working when I come from one page to another. 

Thank you

**Comment by dhmax88** [comment]
I've found the htmx.process() function, which when called on page change (passing in the new element) seems to do the trick!

**Comment by willbocc** [comment]
Hi @dhmax88 would you be nice enough to share how you implemented htmx.process() to get this to work.
I am using Swup and have stumbled on the same issue but not exactly sure how I can use htmx.process().
Thanks in advance

**Comment by dhmax88** [comment]
Sure. Working with Mudpack by any chance 😉 

```
barba.hooks.beforeEnter(({ next }) => {
	// Init Sprig components on new page
	htmx.process(next.container);
}
```

**Comment by willbocc** [comment]
@dhmax88 I didn't realise it was you!
All sorted thanks.
