### ISSUE TITLE
Adding additional variable to sprig component

### ISSUE THREAD

**Issue by arentsen** [putyourlightson/craft-sprig#68]
I would like to send an additional variable to the included sprig component, like you can do with includes:

`{{ sprig('artists/_sprig-catalogue.twig') with variableName }}`

but it does not work. When I add the if statement inside the sprig component, it does not re-render properly on search. I want to do a relatedTo search depending on craft.app.request.getSegment(2) in the URL. 

`{% if entry is not defined and secondSegment|default %}`
`     {% set variableName = craft.entries.section('specialSection').slug(secondSegment).one %}`

**Comment by bencroker** [comment]
Please refer to the docs on how to pass variables into components: 
https://putyourlightson.com/plugins/sprig#component-variables
