### ISSUE TITLE
Load more `if entries` still shows if there are no more to load, and requires one last click to remove the button...

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-sprig#69]
### Question
I have noticed that when testing if there are entries, that the button still shows/appears even if there are no more entries to load. Clicking it again then sets this correctly, but it feels wrong having that last click load nothing more and then the button hides. I believe this should happen on the last element that is loaded.
I have posted my code blow, but I also checked the cookbook and it appears the same thing occurs.
Is there anyway to set/do this check on each load?

###Code
```
{% extends "_layouts/global-variables.twig" %}
{% block htmlPage %}
  {% set offset = offset ?? 0 %}
  
  {% set entries = craft.entries
    .section('blog')
    .relatedTo({
      targetElement: entryId,
      field: 'relatedServices'
    })
    .with('teaserImage')
    .offset(offset)
    .limit(limit)
    .all() %}
  
  <div class="grid lg:grid-cols-2 gap-x-8 divide-y divide-gray-100 gap-y-8 lg:gap-y-20 lg:divide-y-0 mb-8">
    {% for entry in entries %}
      {% include '_routers/teasers.twig' %}
    {% endfor %}
  </div>
  
  {% if entries %}
    <button
      sprig s-val:offset="{{ offset + limit }}"
      s-target="this"
      s-swap="outerHTML"
      class="p-4 border border-white shadow-md transition ease-in-out duration-200 ///// text-white  duration-300 {{ class.btnLinks }}"
    >
      Load more articles
    </button>
  {% endif %}
{% endblock %}
```

### To reproduce
Click the load more articles button and it loads 2 more articles (this shows 4 in total - the 2 initially loaded ad the 2 new ones loaded). This is all the articles related. However, the load more articles button still appears until it is clicked again, then it is removed/hidden.

When I check the `entries|length` it starts ff as 2, clicking the button it remains at 2, clicking again it is then correctly set to 0.

**Comment by bencroker** [comment]
This isn't a bug. You can use `.count()` on an entry query to check how many total entries the query would result in if no limit was set, to determine whether or not the load more button should be displayed.

**Comment by terryupton** [comment]
Thanks for this Ben. I am able to get the count on the entries but I am unsure how to check if to show the button if the current entry is more than the count. As the length is reset to 2 each time and the index/loop resets each time a new set is loaded in.

**Comment by bencroker** [comment]
You should be able to compare the value of the count with the offset plus the limit to know if you’ve reached the end.

**Comment by terryupton** [comment]
Aha. Thanks Ben. I see...

**Comment by bencroker** [comment]
For reference, I updated the load more recipe to use this technique:
https://putyourlightson.com/sprig/cookbook#load-more
