### ISSUE TITLE
Keeping it DRY and passing in element queries

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-sprig#70]
### Question
So I am using a load-more module and I was looking at ways to keep this dry and reusable.
At the moment I have hard coded the entries query into the template like so;
```twig
{% set entries = craft.entries
  .section('blog')
  .relatedTo({
    targetElement: entryId,
    field: 'relatedServices'
  })
  .with('teaserImage')
  .offset(offset)
  .limit(limit)
  .all() %}
```

I was tripped up at first as I was trying to set the entry in the `targetElement` as an entry, but then passed it in as an id via the sprig include (as it suggest on the error) like so:
```twig
{{ sprig('_includes/_sprig/sprig-load-more', {
  'limit': 2,
  'entryId': entry.id
} ) }}
```

However, what would be the best approach to make the whole entry query dry and pass in any query?
Say I wanted to use the same component for another section (without relatedness). Or change the with fields as an example.
I am not sure I can pass in a whole entire query via the include.

Would this be possible or would you suggest just doing different spring components each time?

**Comment by bencroker** [comment]
You won't be able to pass the query in as a parameter since it is an object. You can of course pass the section handle into the component, and then based on that determine which other fields to set on the entry query.

```twig
{{ sprig('_includes/_sprig/sprig-load-more', {
  'limit': 2,
  '_entryId': entry.id,
  '_section': 'blog',
} ) }}
```

```twig
{% set entryQuery = craft.entries
  .section(_section)
  .relatedTo({
    targetElement: _entryId,
    field: 'relatedServices'
  })
  .offset(offset)
  .limit(limit)
%}

{% if section == 'blog' %}
  {% do entryQuery.with('teaserImage') %}
{% endif %}

{% set entries = entryQuery.all() %}
```

Note how I am making `_entryId` and `_section` protected variables so they cannot be tampered with, see https://putyourlightson.com/plugins/sprig#component-variables.

**Comment by terryupton** [comment]
This is great. Thanks Ben. 
I really appreciate your quick response and support.
