### ISSUE TITLE
Push URL – multiple parameters

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#71]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

I have a component working where I can switch the view between a list and grid view - this works perfectly. I furthermore want to have each view have pagination. Currently pagination only works on the grid view as it's the default option. `{% set gridListView = gridListView ?? "grid" %}`

When paginating from the list view the page refreshes and returns to the grid view. Am using the pagination code from the [cookbook](https://putyourlightson.com/sprig/cookbook#pagination).

have added this code `{% do sprig.pushUrl('?page=' ~ page ~ 'gridListView=' ~ gridListView) %}` to my template but the urls don't update correctly, there is no `&` between the variables page and gridListView. If I add the ampersand like this `&gridListview=` I get a PHP notice

> A non well formed numeric value encountered

### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
I would expect `{% do sprig.pushUrl('?page=' ~ page ~ '&gridListView=' ~ gridListView) %}` to work.

In this [video](https://putyourlightson.com/sprig/videos#7.-pushing-url-updates) I use the `url_encode` filter to do it as follows.

```twig
{% do sprig.pushUrl('?' ~ {page: page, gridListView: gridListView}|url_encode) %}
```

**Comment by bencroker** [comment]
> A non well formed numeric value encountered

This error might be indicating that you are using `page` as a number when it is not one. Be sure to set it to `1` by default.

```twig
{% set page = page ?? 1 %}
```

**Comment by CreateSean** [comment]
Ben,
Now I'm not getting the `non well formed numeric error` but when on the list view and paginating it still switches back to the grid view.

If I manually update the url to page 2 and list view it works as expected. However when clicking the pagination links it switches back to grid. If I copy the generated page 2 link for listview I see this:

`https://local.test/exhibits/sustaining-memories/survivor-stories/?page=1&gridListView=list#` and after clicking the resulting url is `https://local.test/exhibits/sustaining-memories/survivor-stories/?page=2&gridListView=grid`

But manually entering this url `https://local.test/exhibits/sustaining-memories/survivor-stories/?page=2&gridListView=list` works and is on page 2 with the list view

Am using your code above 

```{% do sprig.pushUrl('?' ~ {page: page, gridListView: gridListView}|url_encode) %}```

**Comment by bencroker** [comment]
Right, because you are not storing the state of the `gridListView`. State can be persisted using input fields, so this should work:

```twig
{% set page = page ?? 1 %}
{% set gridListView = gridListView ?? 'grid' %}

{{ hiddenInput('page', page }}
{{ hiddenInput('gridListView', gridListView }}
```

**Comment by CreateSean** [comment]
@bencroker Thank you, I didn't know about persistent state with input fields. Now works perfectly.
