### ISSUE TITLE
Animation example

### ISSUE THREAD

**Issue by bleepsandblops** [putyourlightson/craft-sprig#72]
### Is your feature request related to a problem? Please describe.
Would love to see a CSS animation example - i've tried adapting https://htmx.org/examples/animations/ to the search example but no success.

### Describe the solution you would like
A small concise example of animation, the search demo for example.

**Comment by bencroker** [comment]
What kind of animation are you hoping to create? Perhaps you can show me your code so far and explain what you would like to have happen?

**Comment by bleepsandblops** [comment]
@bencroker if i'm updating a search result list for example, adding a subtle fade out / fade in. Reason I ask is because my result list has images, and so the image loading is quite jarring - esp. if the result stays the same (for example there's only one result 'Craft' but the list reloads it for 'C' 'Cr' 'Cra' etc and everytime the image jumps in

**Comment by bencroker** [comment]
Assuming your results element has a class of `div`, the following CSS should fade it in:

```css
.htmx-swapping .results {
    opacity: 0;
}

.results {
    opacity: 1;
    transition: opacity 1s ease-out;
}
```

**Comment by bencroker** [comment]
You might also want to add some debounce to your input field to help prevent flickering.

```twig
<input sprig s-trigger="keyup changed delay:300ms">
```

**Comment by bleepsandblops** [comment]
@bencroker perfect thanks that worked nicely!

Adjacent question: is there a way to not replace the elements if the results are the same between two searches?

**Comment by bencroker** [comment]
No there isn't, but you could compare them in your component and if they are the same then _not_ output the classes that result in the animations.

**Comment by bleepsandblops** [comment]
@bencroker thanks - I would still get the flash on the image changing though; but if it really bothers me then I suppose I should use Vue etc

**Comment by bencroker** [comment]
If the image is the same then it should be cached by the browser, assuming you have your cache headers set up correctly.

**Comment by bleepsandblops** [comment]
indeed, I had my devtools open ! Thanks a lot @bencroker
