### ISSUE TITLE
Append Push Url to create clean urls for multifaceted searches/filters

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-sprig#73]
### Question
So I have a multi-faceted checkbox filter and I have successfully managed to get this all working and filtering correctly. 
the last piece of the puzzle I am however, stuck on. That is pushing/appending the url to reflect the options checked. Everything I try it seems to just replace the url and not append the query-string with the option checked.

So some examples are:
I have a **Geographic Location** that contains multiple checkboxes and when checked these would like so in the URL (in the address bar). `?location=europe+worldwide+asia`
The above would filter out Europe and Worldwide and Asia 

I have a **Process and Operation** that contains multiple checkboxes and when checked these would like so in the URL (in the address bar). `location=europe+worldwide+asia&amp;process=anerobic-digestion+centrifuges`

The above would filter out Anerobic Digestion and Centrifuges in  Europe and Worldwide and Asia 

There are a few more categories and filters but the above should give a good example/gist of the issue.
It would also be nice to include the entry type and limit too, but not essential.

The problem is I cannot seem to get the `s-push-url` correct to just either append the query-string if it already has options or write it new if not. So for example, if you already have a location selected.as europe. When you check Worldwide I want the url to change from `website.com/products/?location=europe` to `website.com/products/?location=europe+worldwide`
If you did not have any locations select them I would need the url to add the `?location=` part.
The same would apply for any other query-strings and append or create them.

I have tried numerous approaches, but cannot crack it. Here are some I have tried.

```
s-push-url="{{ '?' ~ {location: locationQueryString ~ '+' ~ entry.slug} }}"
s-push-url="{{ craft.app.request.queryParam('location') ? '+' ~ entry.slug : craft.app.request.absoluteUrl ~ '?location=' ~ entry.slug }}"
 s-push-url="{{ craft.app.request.queryString ? '&amp;' : '?location=' }}{{ locationQueryString|length ? '+' ~ entry.slug : entry.slug }}"
```

However, each time it just change the full Url to last selected option as an example.
If I entered `website.com/products/?location=europe` into my browser and then checked the worldwide, it would change/push the url to `website.com/products/?location=worldwide` but I want it to be `website.com/products/?location=europe+worldwide`

Whilst I appreciate I can set the `s-push-url="true"` I would like some cleaner/friendly urls.

Any ideas Ben? Or any easy way to achieve this or get clean urls from `s-push-url="true"` instead?

**Comment by bencroker** [comment]
You should probably be using the [sprig.pushUrl(url)](https://putyourlightson.com/plugins/sprig#sprig.pushurlurl) function to achieve this:

```twig
{% set params = {
    location: location,
} %}
{% do sprig.pushUrl('?' ~ params|urlencode) %}
```

See this video in which I explain this approach:
https://putyourlightson.com/sprig/videos#7.-pushing-url-updates

**Comment by terryupton** [comment]
Thanks for this Ben.  Brilliant. I did re-watch the video on CraftQuest and it made sense.
I have managed to resolve this now.
Thanks again. Sprig is awesome and you are amazing.
