### ISSUE TITLE
Trigger sprig based on query parameters

### ISSUE THREAD

**Issue by gbowne-quickbase** [putyourlightson/craft-sprig#75]
### Question
I have a page that loads in a default way, showing featured case studies at the top. I have sprig enabled category and text searches that replace the entire page with search results. If I have links from elsewhere pointing to this page, like `/case-studies?category=spreadsheets` I'd like to trigger the sprig to render the page and return those results. I've successfully set the sprig-connected dropdown and text search from the `craft.app.request.getParam()` but can't figure out how to tell sprig to "do your thing".

I did try adding a trigger, but don't think this format is really correct. The `if` condition is working, but no trigger. I'm looking at https://putyourlightson.com/plugins/sprig#sprig.triggereventsevents for details.

```
{% if craft.app.request.queryParams|length %}
    {% do sprig.triggerEvents('#searchFilters', 'change') %}
{% endif %}
```

### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
You can use Twig code as you normally would, checking if `category` exists.

```twig
{% if category is defined and category %}
    {# Output results #}
{% else %}
    {# Output default view #}
{% endif %}
```
