### ISSUE TITLE
Cookbook example with multiple trigger elements?

### ISSUE THREAD

**Issue by gbowne-quickbase** [putyourlightson/craft-sprig#77]
### Question
I've been struggling with getting sprig to fire on *both* a dropdown and a text search, seeing that only one of them seems to get a binding on the element, but not both. (I threw a few quick images in) To complicate it, I've been asked to add a reset button as well. Since I imagine I'm not the only one who might want to do something complex, an example of how to do it right would be great. I just think some good guidance on methodology would help, like "put all the triggers on the form" or "put all the triggers on the elements" or "this requires some extra javascript." 
Thanks!

### Additional context
![image](https://user-images.githubusercontent.com/39066452/103703738-1b701e80-4f76-11eb-994c-215c2946b3d6.png)
![image](https://user-images.githubusercontent.com/39066452/103703837-478b9f80-4f76-11eb-9013-2882d8a3e788.png)

**Comment by bencroker** [comment]
I have a video in the works that will explain using Sprig with forms in more detail:
https://putyourlightson.com/sprig/videos#sprigform

But if you show me a simplified version of your template code then I can try to help. I already see from your screenshot that the `input` field with `s-trigger` is missing the `sprig` attribute, which is required on any element that you want to be reactive.

To support the production of the learning material there is a sponsor program too:
https://github.com/sponsors/bencroker

**Comment by bencroker** [comment]
General advice is to be sure to add the `sprig` attribute to any element that should be reactive, which appear to be missing from the `select` and `input` fields in your code.
