### ISSUE TITLE
Interaction between different components

### ISSUE THREAD

**Issue by rauwebieten** [putyourlightson/craft-sprig#80]
First of all, nice library! It's a pleasure to work with it :)

### Question

I read in the docs: "Components can re-render themselves".
Can components re-render another sprig component?
It seems all examples in the docs & cookbook are examples with one sprig component.
I'd like to have multiple sprig components, with interaction.

My case:
I have a first component, for example filters.html.twig with content
```
<div id="filters">
<a
        sprig
        s-push-url="{{ url }}"
        s-val:myvar="somevalue"
        href="{{ url }}"
>click me</a>
</div>
```

I have a second component, for example search-results.html.twig with content
```
<div id="search-results">
    myvar : {{ myvar }}
</div>
```

Both components are included in my page like this:
```
{{ sprig('filters.html.twig') }}
{{ sprig('search-results.html.twig') }}
```

Can I make user interaction in the filters component, update the content of the search-results component?

**Comment by bencroker** [comment]
There's an example at https://putyourlightson.com/sprig/cookbook#refreshing-components and also in the last Sprigcart video at https://putyourlightson.com/sprig/videos#4.-communicating-between-sprig-components.
