### ISSUE TITLE
Can't get sprig to work on <a> tag

### ISSUE THREAD

**Issue by nealzie** [putyourlightson/craft-sprig#84]
Hi Ben,

Loving the plugin, just can't seem to figure out what's going wrong here:

I have the sprig functionality working through a dropdown, but can't get the same thing to work with an <a> element.

```
          <nav sprig class="fod-dropdown-list w-dropdown-list" name="catSelect">
          {% for cat in allCategories %}
            <a  href="" sprig s-val:catSelect="{{ cat.slug }}" s-replace="#results">{{ cat.title }}</a>
            {% endfor %}
          </nav>

```

The dropdown that does work:

```
          <select sprig name="catSelect" s-replace="#results">
		  	<option value="">Alles</option>
	            {% for cat in allCategories %}
					<option value="{{ cat.slug }}">{{ cat.title }}</option>
				{% endfor %}
		</select>

```

**Comment by bencroker** [comment]
The `s-val` attribute expects the name in `kebab-case` as per the docs:
https://putyourlightson.com/plugins/sprig#s-val

This should work:

```twig
<a  href="" sprig s-val:cat-select="{{ cat.slug }}" s-replace="#results">
```

**Comment by nealzie** [comment]
Wow, I struggled with this for so long and repeatedly checked that part of the documentation, but somehow overlooked that.. Sorry for that, and thanks for your swift reply!

btw, if you make a donate button besides the €50/pm I'd definitely make sure to hit it with every project or support case.. Just figuring out Sprig on some older projects now.. Cheers!

**Comment by bencroker** [comment]
Glad to hear it! 

The available sponsorship tiers are here, all monthly though as per GitHub's rules, but it's always possible to cancel at any time: https://github.com/sponsors/bencroker
