### ISSUE TITLE
Struggling to get pushUrl working with checkboxes.

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-sprig#85]
### Question
I've just started playing with Sprig. First impressions are great. Live search up and running in 15 mins! I'm testing out filtering now but I'm struggling to get checkboxes working with pushUrl.

Here's a very simplified version of what I'm testing where `.types` is a categories field. When I select the checkboxes, the id of the checkbox is getting replaced in the url rather than appended. 

Can't quite get my head around where I'm going wrong.

```twig

{% set q = q ?? '' %}
{% set types = types ?? '' %}

{% set entries = craft.entries()
    .section('test')
    .search(q)
    .types(types)
    .all()
%}

{% do sprig.pushUrl('?' ~ {
    q: q,
    types: types
}|url_encode) %}

<div s-replace="#results">

    <input sprig s-trigger="keyup changed" type="search" name="q" value="{{ q }}">

    {% for cat in craft.categories.group('type').all() %}
        <label >
            <input sprig type="checkbox" name="types[]" value="{{ cat.id }}"{{ cat.id in types ? ' checked' }}>
            <span>{{ cat.title }}</span>
        </label>
    {% endfor %}

    <div id="results">
        <ul>
            {% for entry in entries %}
                <li>
                    <h2><a href="{{ entry.url }}">{{ entry.title }}</a></h2>
                </li>
            {% endfor %}
        </ul>
    </div>

</div>
```

**Comment by bencroker** [comment]
I tracked this down to a bug in the current version of htmx. Fixed in https://github.com/bigskysoftware/htmx/pull/337 for the next release. You can test by manually including this version of htmx in your template:
https://raw.githubusercontent.com/bigskysoftware/htmx/dev/src/htmx.js

**Comment by bencroker** [comment]
You'll also likely have to reconstruct the `types` to be an array in the query string before using `pushUrl`.

**Comment by shornuk** [comment]
Thanks for the reply. 

> You can test by manually including this version of htmx in your template:
https://raw.githubusercontent.com/bigskysoftware/htmx/dev/src/htmx.js

How's best to do this? Is that just a case of adding it in with a script tag?

**Comment by bencroker** [comment]
Yes, instead of using the `sprig.script` tag.

**Comment by shornuk** [comment]
Thank you. Getting an error when trying to include that version.

`Refused to execute https://raw.githubusercontent.com/bigskysoftware/htmx/dev/src/htmx.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.`

**Comment by bencroker** [comment]
Well, you'll probably have to download it first.

**Comment by shornuk** [comment]
🤦‍♂️One of those days. 

Just got this tested and seems to be working. Values are getting added rather than replaced now.
