### ISSUE TITLE
Load more items inside a grid

### ISSUE THREAD

**Issue by eirabben** [putyourlightson/craft-sprig#86]
### Question
I am trying to use the Load More example from the documentation, but I want the items to be inside a grid. The code below will kind of work, but only if the limit matches the grid column count. So if I wanted to have 3 columns on a smaller breakpoint, the grid would break because another grid container is added every time you press Load more. I have tried to only load the opening and closing grid tags when `sprig.isInclude` is true, but it does not seem to work. Is there any way to load new items into the existing grid in a setup like this?

```
{% set limit = 4 %}
{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.offset(offset).limit(limit) %}
{% set entries = entryQuery.all() %}

<div class="grid grid-cols-4">
  {% for entry in entries %}
    <div class="col-span-1">{{ entry.title }}</div>
  {% endfor %}
</div>

{% if entryQuery.count() > offset + entries|length %}
    <button sprig s-val:offset="{{ offset + limit }}"
      s-target="this"
      s-swap="outerHTML">
      Load more
    </button>
{% endif %}

```

**Comment by bencroker** [comment]
The simple solution is to ignore the offset, increment the limit and always reload all entries.

```twig
{% set perPage = 4 %}
{% set limit = limit ?? perPage %}
{% set entryQuery = craft.entries.limit(limit) %}

...

<button sprig s-val:limit="{{ limit + perPage }}"
```

To append new items into the grid using your markup is possible but quite a bit more complicated.

**Comment by eirabben** [comment]
Thank you. I can probably get away with doing it this way for my current project, since the volume of entries is pretty low.

It would be awesome to see an example where items are added incrementally under a specific dom node, like in my example. I have encountered this use case in many of my projects lately, and sometimes the client can't be persuaded into using pagination instead.

**Comment by bencroker** [comment]
Will keep it in mind. Just a quick note that sponsoring is one way of supporting the creation of new learning materials:
https://github.com/sponsors/bencroker

**Comment by bencroker** [comment]
The tricky part about this is your button element. If you found a way to put it inside the grid then it would be trivial to make loading more elements work.

```twig
<div class="grid grid-cols-4">
  {% for entry in entries %}
    <div class="col-span-1">{{ entry.title }}</div>
  {% endfor %}

  {% if entryQuery.count() > offset + entries|length %}
    <button sprig s-val:offset="{{ offset + limit }}"
      s-target="this"
      s-swap="outerHTML
      class="col-span-4">
      Load more
    </button>
  {% endif %}
</div>
```

The following example would allow you to append the newly fetched entries to the grid, but then the button cannot be modified.

```twig
{% set limit = 4 %}
{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.offset(offset).limit(limit) %}
{% set entries = entryQuery.all() %}

<div id="results" class="grid grid-cols-4">
  {% for entry in entries %}
    <div class="result col-span-1">{{ entry.title }}</div>
  {% endfor %}
</div>

{% if entryQuery.count() > offset + entries|length %}
    <button sprig s-val:offset="{{ offset + limit }}"
      s-target="#results"
      s-select=".result"
      s-swap="beforeend">
      Load more
    </button>
{% endif %}
```

See https://htmx.org/attributes/hx-select/ and https://htmx.org/attributes/hx-swap/ for reference.
