### ISSUE TITLE
Sprig with Snaptcha within the Freeform module

### ISSUE THREAD

**Issue by payello** [putyourlightson/craft-sprig#87]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

We are using the Freeform module to manage our forms that are authenticated with custom JS, the site also uses Barba.js for page transitions. I have been having issues with implementing Sprig with this setup. When the form is submitted I get the following error - 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
/index.php/actions/sprig/components/render?sprig:action=b9bca585455a25bf1e5ec4d1bf65f434b1386ee13bdc51eaa17329e9b4f68092freeform/api/form. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
`
I have followed the docs and the form is as follows - 

`<form sprig 
    s-method="post"
    id="formID"
    accept-charset="UTF-8"
    class="c-form flex flex-wrap"
    data-behaviour="FormValidation"
    data-validation-rules='{{ dynamicValidationRules|json_encode() }}'
    data-successmessage="{{ form.successMessage }}"
    s-action="{{ action }}"
>
`
I've also removed the csrfinput
Is there something that I've missed here? 

### Additional context
Add any other context or screenshots about the support request here.

The decision to use sprig was due to the Barba.js - on page transition, the Snaptcha value was not populated.

**Comment by bencroker** [comment]
That error seems to indicate that your server is disallowing AJAX requests. Did you remove the URL from the error message and is it correctly entered in your site's base URL?

**Comment by payello** [comment]
I did remove the domain from the request yes. The full error message did show my full URL. It was just my local MAMP URL

Is there something that I can do to allow AJAX requests?

**Comment by bencroker** [comment]
AJAX requests to the same domain name should be allowed. Can you check whether one is `http` and the other `https`, or whether the `www` subdomain is in one but not the other?

**Comment by payello** [comment]
In my Axios header, I do have - `'Access-Control-Allow-Origin': '*'` in the JS submission. This is just locally right now. I am working with MAMP.

**Comment by payello** [comment]
I am not sure where to add this for Sprig.

**Comment by bencroker** [comment]
The `Access-Control-Allow-Origin` header is set on the server, not in JS, but that shouldn't be the issue. Did you check the URLs in the network tab when the Sprig requests are made?

**Comment by payello** [comment]
Yes - local.testsite.com/index.php/actions/sprig/components/render?sprig:action=b9bca585455a25bf1e5ec4d1bf65f434b1386ee13bdc51eaa17329e9b4f68092freeform/api/form

**Comment by payello** [comment]
It has failed so there is no HTTP request code.

**Comment by payello** [comment]
The action in the form is freeform/api/form

**Comment by bencroker** [comment]
What about the host name, look for `http` vs `https` and check the subdomains.

**Comment by payello** [comment]
The JS validation isn't being hit by the looks of things. It doesn't seem to have reached that far. 

Locally I am running HTTP

**Comment by bencroker** [comment]
In that case this must be a devops issue with your local setup.

**Comment by payello** [comment]
So not an issue with my Sprig setup? I've just got a standard MAMP setup running HTTP.

**Comment by payello** [comment]
JS validation works fine when I remove Sprig.

**Comment by payello** [comment]
The JS validation is triggered with a data-behaviour tag on the form that hooks the js function

**Comment by bencroker** [comment]
Based on the original error message I thought this was a CORS issue. The JS validation that Freeform adds will not work with out of the box with Sprig, which really only relies on back-end validation. What happens if you remove the front-end validation completely?

**Comment by payello** [comment]
Sorry I didn't realise that they were related 🤦. It was only when I noticed that the validation wasn't being hit. I can get it working without the FE validation. Is it not possible to add FE validation to a Sprig form? What is the practice there if possible?

**Comment by bencroker** [comment]
It is possible to add front-end validation to Sprig, but for that you would have to look into [validation in htmx](https://htmx.org/docs/#validation). My advice would be choosing to use either front-end validation _or_ Sprig, but not both.
