### ISSUE TITLE
Deleting wishlist entry per elementid

### ISSUE THREAD

**Issue by nealzie** [putyourlightson/craft-sprig#88]
Hi Ben,

Thought I'd post this question here as it might help others too..

I've successfully made a sprig component with a button that adds an entry to the wishlist plugin. It also refreshes another sprig component which displays the wishlist. Beautiful!

I've managed to make a 'delete' button in the wishlist component, which also updates the 'add to wishlist' button in the other component.. However here's where I'm stuck.. 
I can't get the 'delete' buttons to correspond with it's proper elementId's hidden input. So all the delete buttons have the same htmx codes and whichever one you hit, it'll delete the bottom item on the list, and so on.. 
(I've watched your shoppingcart video but as this is using such a different way to delete items I can't figure it out.) Here's my loop:

```
{% set list = craft.wishlist.lists().default(true).one() %}
{% set removedFromList = success is defined %}

{# Display list items #}
{% if list %}
{% set itemcount = list.items.count() %}

{% if itemcount > 0 %}

    <ul class="wishlist-list">
        {% for item in list.items.all() %}
        <input type="hidden" name="elementId" value="{{ item.elementId }}">
            <li>
            <a href="{{ item.element.getUrl() }}">{{ item.title }}</a>
            <button sprig s-method="post" s-action="wishlist/items/remove" class="remove-button">X</button>
            </li>
        {% endfor %}
    </ul>
 
 {% else %}
 <h2>Je wishlist is nog leeg</h2>

{% endif %}
{% endif %}
</div>
                                               
  </nav>
  <label for="cart-opener" class="CartOverlay"></label>
</aside>
	 
	 
	 <label for="cart-opener" tabindex="0" aria-haspopup="true" role="button" aria-controls="cart" class="OpenCartButton" id="opencart">
			  <div class="cart-button-wrapper">
			  <img src="{{ siteUrl }}dist/images/wishlist.png" />
			  {% if list %}
			  {% set itemcount = list.items.count() %}
			  <div class="count animate_animated animate__heartBeat">{{ itemcount }}</div>
			  {% endif %}
			  </div>
	 </label>

{% if removedFromList %}

	<script>
		htmx.trigger('#wishbutton', 'refresh');
	</script>
	{% endif %}
```

I'm sure it's one line I'm missing but for the life of me can't get it working properly

**Comment by bencroker** [comment]
You'll likely need to use the [s-val:*](https://putyourlightson.com/plugins/sprig#s-val) attribute on the delete button, rather than including the hidden input fields, all of which will be submitted on each re-render.

```twig
<button sprig s-method="post" s-action="wishlist/items/remove" s-val:element-id="{{ item.elementId }}" class="remove-button">X</button>
```
