### ISSUE TITLE
File Uploads?

### ISSUE THREAD

**Issue by bphippen** [putyourlightson/craft-sprig#9]
Does Sprig support file uploads? I wasn't able to find any mention of this in the docs, but I did try to get it working without success.

Is there something I am missing, or is it not supported yet?

Thanks so much, absolutely love this plugin!

**Comment by bencroker** [comment]
No, file uploads are out of the scope of Sprig at present.

**Comment by billmn** [comment]
@bencroker Now that htmx support file uploads (https://htmx.org/docs/#files), do you think we can reconsider this thing?

**Comment by bencroker** [comment]
Reopening for reconsideration :)

**Comment by bencroker** [comment]
Am revisiting this. What would be some valid use-cases for wanting to upload files using Sprig?

**Comment by bphippen** [comment]
My initial use-case was for a dropzone style multi-asset uploader with a progress bar.

**Comment by bencroker** [comment]
Do you perhaps have a screenshot? Would the asset volume be hard-coded or did you plan on having a selector of some sort?

**Comment by bphippen** [comment]
This is what I ended up building with vuejs but essentially the volume is hardcoded and then uploaded images show up in a list below.

<img width="974" alt="Screen Shot 2020-11-24 at 1 58 52 PM" src="https://user-images.githubusercontent.com/1563364/100144957-3884de00-2e5d-11eb-87b9-f6d711201b99.png">

**Comment by bencroker** [comment]
Thanks for sharing. Not sure how much of this Sprig would handle, most likely just the uploading and re-rendering of the component. Will make a start and see how it goes.

**Comment by bencroker** [comment]
Got file uploads working without any changes to Sprig.

```twig
<input sprig s-method="post" s-action="assets/upload" s-encoding="multipart/form-data" 
    s-val:folder-id="3" name="assets-upload" type="file">

{% if error is defined %}
    Upload error: {{ error }}
{% endif %}

{% if assetId is defined %}
    {% set asset = craft.assets.id(assetId).one() %}
    {% if asset %}
        Uploaded ({{ asset.filename }})
        <img src="{{ asset.getUrl({width: 80, height: 80}) }}">
    {% endif %}
{% endif %}
```

**Comment by bphippen** [comment]
So it's been there the whole time? That's amazing! I wonder where I went wrong initially...

I think I was trying to upload a file with the 'entries/save-entry' action with an asset field

**Comment by bencroker** [comment]
The `upload` action makes this possible when provided with a `folderId`, `fieldId` or `elementId`:
https://github.com/craftcms/cms/blob/0827fb59361d6e0a5ddefb15da68a327fa68568f/src/controllers/AssetsController.php#L283-L295

It should also be possible with an entry form, but the `upload` action seems more direct.

**Comment by bencroker** [comment]
FYI added `s-encoding` in https://github.com/putyourlightson/craft-sprig/commit/eba5fd44126b6004b5727c3d13af94fdd1a41951.

**Comment by bencroker** [comment]
Released in version 1.2.0.

**Comment by shornuk** [comment]
@bencroker any chance you could demo a version of an asset field within an entry form?

I've got a form set up with sprig, which validates on all fields nicely but my asset field always errors and returns as if it's blank/empty.

**Comment by bencroker** [comment]
If you open a new issue with a stripped down sample of code then I can take a look @shornuk.
