### ISSUE TITLE
Setting Twig variable when event triggers

### ISSUE THREAD

**Issue by fredrik-sogaard** [putyourlightson/craft-sprig#90]
I'm trying to set a simple variable in my Twig template before I make a Sprig request.

I'm submitting a form with file uploads, which can take a while, so I want to show indicators to the user. I'm aware of the built in indicators things, but I don't see how I can use that for for example changing text on a button.

I basically want to do this:
1. Click "Save"
2. Set some variable loading=true
3. Change text on button depending on the variable: `loading ? 'Saving' :  'Save'`
4. Change the variable back when the request goes through.

I can get the correct event triggered in js, but not sure how to set Twig variables here?
```
<script>
	htmx.on("htmx:beforeRequest", function(e) { 
         // I want to set a variable here to use in my Twig template
       })
</script>
```

Sorry for noob questions, I'm new to Sprig!

**Comment by bencroker** [comment]
If you're using JavaScript events then you'll need to achieve this using JavaScript code, for example:

```js
htmx.on('htmx:beforeRequest', function(e) { 
    htmx.find('#my-button').innerText = 'Saving';
})
```

**Comment by fredrik-sogaard** [comment]
Thanks! Any suggestion on how to achieve the same thing with Sprig/Twig?

________________________________
Fra: Ben Croker <notifications@github.com>
Sendt: Thursday, January 28, 2021 9:06:51 PM
Til: putyourlightson/craft-sprig <craft-sprig@noreply.github.com>
Kopi: Fredrik Søgaard <fredrik.s@feed.no>; Author <author@noreply.github.com>
Emne: Re: [putyourlightson/craft-sprig] Setting Twig variable when event triggers (#90)


If you're using JavaScript events then you'll need to achieve this using JavaScript code, for example:

htmx.on('htmx:beforeRequest', function(e) {
    htmx.find('#my-button').innerText = 'Saving';
})

**Comment by bencroker** [comment]
You can't run Twig on the front-end. I suggest you use the indicator class to show/hide a loading element as per the recipe at https://putyourlightson.com/sprig/cookbook#indicator

**Comment by fredrik-sogaard** [comment]
I see. Thanks for answer!
