### ISSUE TITLE
Minimum Craft version should be 3.5 (or tweak controller)

### ISSUE THREAD

**Issue by Mosnar** [putyourlightson/craft-sprig#91]
### Describe the bug

The "Components" controller is referencing `$this->response` here:
https://github.com/putyourlightson/craft-sprig/blob/5a551531518a1aac52413ffd2b5f721815e04f90/src/controllers/ComponentsController.php#L62-L65

The `response` property is not accessible until Yii 2.0.36, which is only available in Craft 3.5

### Versions
- Plugin version: 1.3.1
- Craft version: 3.4.30

**Comment by bencroker** [comment]
Good catch! Fixed in https://github.com/putyourlightson/craft-sprig/commit/92625cd29ab3eef80d47be5b21ecd3c74e7e36f7 and released in 1.3.2.
