### ISSUE TITLE
Doesn't load open posts when returning back - Load More

### ISSUE THREAD

**Issue by thefubon** [putyourlightson/craft-sprig#92]
https://putyourlightson.com/sprig/cookbook#load-more

Craft - 3.6.1
Sprig - 1.3.2
PHP - 7.2.34
MySQL - 5.5.5

Hello, Load More stopped working for me.
Cond I load posts in the Blog section, and then I go inside the news. And I press go back in the browser, All open pages with load through load more are reset.

In Safari, Mozilla, Chrome

![ScreenFlow](https://user-images.githubusercontent.com/43171309/106305662-02edde00-626e-11eb-8a53-81f0e4e8c71e.gif)

**Comment by bencroker** [comment]
Hitting the back button triggers a page refresh, therefore it makes sense that the page is reloaded to its initial state. Are you saying that something changed in Sprig?

**Comment by thefubon** [comment]
Stopped working after updating. Maybe something is missing in the sprig? or how can this be repaired or customized? so that when you return, all the posts that were shown are loaded. It worked earlier. And suddenly it stopped on all sites.

**Comment by bencroker** [comment]
What did you update to and from exactly?

**Comment by thefubon** [comment]
CraftCMS - Craft - 3.6.1

**Comment by thefubon** [comment]
<img width="745" alt="Снимок экрана 2021-01-29 в 21 36 49" src="https://user-images.githubusercontent.com/43171309/106313993-274fb780-627a-11eb-9f83-7790f0054563.png">

<img width="771" alt="Снимок экрана 2021-01-29 в 21 36 59" src="https://user-images.githubusercontent.com/43171309/106314002-2a4aa800-627a-11eb-803a-c95d62305d82.png">

**Comment by bencroker** [comment]
What did you update from exactly?

**Comment by thefubon** [comment]
one site through the admin panel. the second site was installed as new.

**Comment by thefubon** [comment]
plugin settings stopped working

<img width="1538" alt="Снимок экрана 2021-01-29 в 21 49 27" src="https://user-images.githubusercontent.com/43171309/106315198-f6708200-627b-11eb-982b-618af146ab28.png">

**Comment by bencroker** [comment]
I was asking what version you updated from, and what version you updated to. Can you please help me help you?

Sprig does not have plugin settings. The screenshot you posted is the Sprig playground, which I can confirm is working fine in Sprig 1.3.2.

**Comment by thefubon** [comment]
I have a completely new installation of craftcms and plugins sprig 1.3.2 Here are screenshots of the code itself. Also the site where I configure the plugin - https://fubon.uk/blog

I tried to clear the cache, it didn't help. 

<img width="404" alt="Снимок экрана 2021-01-30 в 10 48 55" src="https://user-images.githubusercontent.com/43171309/106350880-49345300-62e9-11eb-8d29-e74b54933977.png">

<img width="681" alt="Снимок экрана 2021-01-30 в 10 48 12" src="https://user-images.githubusercontent.com/43171309/106350883-4c2f4380-62e9-11eb-809f-74380a653cbd.png">

<img width="935" alt="Снимок экрана 2021-01-30 в 10 48 22" src="https://user-images.githubusercontent.com/43171309/106350889-4e919d80-62e9-11eb-97a4-1af732f6f1fc.png">

**Comment by thefubon** [comment]
I'm not sure if this is possible. It seems to me sorely missing in the browser bar in load-more as well as in normal navigation

site.name/blog/#page2

**Comment by bencroker** [comment]
If you want the history state to be saved then you must update the URL. You can see this in action in the [Sprigboard demo](https://putyourlightson.com/sprig/components/board), explained in the video at https://putyourlightson.com/sprig/videos#sprigboard

This should get you started:

```twig
{% do sprig.pushUrl('?offset=' ~ offset) %}
```

See the docs at https://putyourlightson.com/plugins/sprig#sprig.pushurlurl

**Comment by thefubon** [comment]
Unfortunately, in my loadmore, this function led to strange actions after I go to the post. and go back (

DEMO: https://fubon.uk/blog

**Comment by bencroker** [comment]
This might help, however you're likely going to run into problems with this approach too eventually. This behaviour is dictated by [htmx](https://htmx.org/), which Sprig uses. 

```twig
{% do sprig.pushUrl('/blog?offset=' ~ offset) %}
```

Also, I'm not convinced that a load more button should be saving its history state. Why not open links in a new tab if it's an issue?

**Comment by thefubon** [comment]
Apparently I'm doing something wrong

https://www.youtube.com/watch?v=h81CdJ2YObs&feature=youtu.be

**Comment by bencroker** [comment]
Yup, that is what I was referring to. I think this may be a bug in how htmx handles history state. Can you create a bug report there, linking to this issue?

**Comment by thefubon** [comment]
https://github.com/putyourlightson/craft-sprig/issues/96

I hope I did everything right?

**Comment by bencroker** [comment]
Please create the issue in the htmx repository: https://github.com/bigskysoftware/htmx

**Comment by bencroker** [comment]
This should be fixed as of Sprig 1.4.0.

**Comment by thefubon** [comment]
> This should be fixed as of Sprig 1.4.0.

I have this version. I can not understand6 how to make a template to make it all worked. From the documentation does not work

**Comment by bencroker** [comment]
If you can show me a page on which it is not working then perhaps I can help, but realistically I would think that a load more button should _not_ be tied to the page's history.

**Comment by thefubon** [comment]
https://fubon.uk/blog

<img width="1602" alt="Снимок экрана 2021-02-24 в 22 22 42" src="https://user-images.githubusercontent.com/43171309/109054374-d901cd00-76ee-11eb-813d-1bf6d21e1fc4.png">

```
{% set offset = offset ?? 0 %}
{% set entryQuery = craft.entries.offset(offset).section(section).limit(limit) %}
{% set entries = entryQuery.all() %}

{% for entry in entries %}
	<h3 class="uk-card-title uk-margin-small uk-text-bold"><a href="{{ entry.url }}">{{ entry.title }}</a></h3>
	<p class="uk-margin-small">{{ entry.leadIn|striptags|slice(0, 240) }}</p>	
{% endfor %}

{% if entryQuery.count() > offset + entries|length %}
  <button class="uk-button uk-button-default uk-button-large uk-border-rounded uk-align-center" sprig s-val:offset="{{ offset + limit }}" s-target="this" s-swap="outerHTML">{{ 'Load More'|t }}</button>
{% endif %}
```

**Comment by bencroker** [comment]
So how you have it now is exactly how I would expect the back button to work. If you really want the behaviour you are asking for then you'd need to write a `limit` parameter to the URL, using `sprig.pushUrl` and then use that to determine how many entries to show.

**Comment by thefubon** [comment]
```{{ sprig('/_components/sprig/load-more', {'limit': 2, 'section': 'blog',}) }}```
```{% do sprig.pushUrl('/blog?offset=' ~ offset) %}```
https://fubon.uk/blog?offset=3
I turned on and all wounds does not work

**Comment by bencroker** [comment]
Yeah I think you need to work a bit more on your Twig code to get this working but it is surely possible. Closing this as it is not an issue with Sprig.

**Comment by handplant** [comment]
The best is to push the page with the url and then increase the limit on initial/server load. Someting like that...

```
{% set page = page ??? craft.app.request.pageNum ??? 1 %}
{% set limit = 10 %}
{% set offset = offset ?? 0 %}

{% do sprig.pushUrl('/' ~ craft.app.config.general.pageTrigger ~ page ) %}

{% if sprig.isInclude %}
  {% set limit = limit * page %}
{% endif %}
....
<button id="load-more-oob" s-val:page="{{ page + 1 }}">
```
