### ISSUE TITLE
Redactor field in front end form

### ISSUE THREAD

**Issue by bfjare** [putyourlightson/craft-sprig#97]
Sorry if this has been answered but I have a front-end redactor form and this sucker works great but on the sprig reload the redactor js and css files no longer manipulate the field.  What would you suggest is the best way to solve this.

**Comment by bencroker** [comment]
The Redactor field will likely need to be re-initialised on each component re-render. The `htmx:afterSwap` event allows you to  run JavaScript code each time the component is re-rendered. Not sure why the CSS stops working, make sure your CSS code is _not_ inside the Sprig component though.

Put this JS code in the parent template as per the recipe at https://putyourlightson.com/sprig-cookbook#refreshing-components .

```js
<script>
htmx.on('htmx:afterSwap', function(event) {
    // Initialise Redactor
});
</script>
```

**Comment by bfjare** [comment]
That works! Thanks, Ben... solid name ;).  The plugin is really incredible!  The CSS actually is working the javascript just hadn't added the reactor class yet to the textarea field.

**Comment by bencroker** [comment]
Glad to hear it, Ben!
